TerryCavanagh/VVVVVV

- desktop_version/CONTRIBUTORS.txt
- desktop_version/src/FileSystemUtils.cpp
- desktop_version/src/FileSystemUtils.h
- desktop_version/src/main.cpp
More than two and a half years after messaging @flibitijibibo on Twitter, begging him for the source code, I'm very happy to finally be able to officially lay my eyes on this work of art (well, sort of).
Anyways, I'm also excited to share my first contribution to the game that has cost me countless hours of my life.
We should return an error code when we can't find data.zip, just letting
the program crash is a little crude.
Note: The message box did not work for me, so I just swapped it for some `puts`s. I'm obviously open for suggestions here.
> actually return an error when data.zip is missing

- desktop_version/CONTRIBUTORS.txt
- desktop_version/src/BinaryBlob.cpp
- desktop_version/src/FileSystemUtils.cpp
Some deprecated PhysFS APIs were used, which were trivial to update to the
non-deprecated versions.
The `PHYSFS_getUserDir` is still used for Linux as I could not test the change there
yet but looking at the implementation of the function it should work to replace it too
at a later point.
> Update PhysFS APIs

- desktop_version/CONTRIBUTORS.txt
- desktop_version/src/FileSystemUtils.cpp
Follow-up to #19 which did the change for macOS.
It appears to work as expected on Linux too.
Tested on a distro where XDG_DATA_HOME is undefined by default,
and `PHYSFS_getPrefDir` also resolves to `~/.local/share/VVVVVV/`.
The first organization parameter is unused on Linux and macOS.
Added myself to `CONTRIBUTORS` as requested though this patch is trivial enough not to require attribute IMO - but I'll contribute some more hopefully to make up for it.
I suggest ordering contributors alphabetically to make it easier for new ones to know where to add themselves - alternatively the instructions could be to add oneself at the bottom of the …
> FS: Use PHYSFS_getPrefDir on Linux/FreeBSD too

- desktop_version/CONTRIBUTORS.txt
- desktop_version/README.md
- desktop_version/src/Input.cpp
- desktop_version/src/titlerender.cpp
- mobile_version/src/includes/input.as
- mobile_version/src/includes/render.as
- [✔] My changes may be used in a future commercial release of VVVVVV (for
- [✔] I will be credited in a `CONTRIBUTORS` file for all of said releases, but
This one's pretty minimal, but I figured I'd contribute to this thing somehow.
The tile here's pretty self-explanatory; I corrected all instances of "seperately" to "separately." This shouldn't mess with any critical game logic since it's a single-character difference.
> Correct "seperately" to "separately"

- desktop_version/CONTRIBUTORS.txt
- desktop_version/src/BinaryBlob.cpp
- desktop_version/src/Graphics.cpp
- desktop_version/src/Graphics.h
- desktop_version/src/Music.cpp
- desktop_version/src/Script.cpp
- desktop_version/src/UtilityClass.cpp
- desktop_version/src/main.cpp
I'm not sure why you **need** debug + RTC but a good chance is that it's related to uninitialized values which are zeroed in debug but not release (had this exact mystery headache a while ago). This just sets a bunch of otherwise uninitialized member vars to 0, also getting rid of one compiler warning per variable initialized. Neat.
Also fixes a spelling error (`forground`) in the graphics class's buffers.
> zero a lot of uninitialized member vars

- desktop_version/CONTRIBUTORS.txt
- desktop_version/src/Input.cpp
- desktop_version/src/Scripts.cpp
Fixes some UI things in the menu.
- Unlock Play Modes > Return goes up one menu to Game Options, instead of up two menus to the main menu
- Game Pad Options > Return plays a menu sound instead of being silent
- When disabling Screen Effects, a menu sound is played instead of being silent (enabling Screen Effects is unchanged)
- Changing the following Graphics Options > Fullscreen, Scaling (Letterbox), Filter plays a menu sound before the change, and not both before and after the change
- as these changes are instant or near-instant, these would just overlap and make an excessively loud noise
Also fixes a typo from Victoria in the Secret Lab …
> Menu fixes and a typo

- desktop_version/CONTRIBUTORS.txt
- desktop_version/src/Script.cpp
* **Fix `hardreset()` not resetting all 50 slots in `obj.collect` and `obj.customcollect`**
This means you can actually use more than 20 trinkets/coins (slots in `obj.collect`) and 20 crewmates (slots in `obj.customcollect`) in a custom level, since the only problems with doing so previously was that they wouldn't get reset if you started the level from the beginning.
> Fix hardreset() not resetting all 50 slots in (custom)collect

- desktop_version/CMakeLists.txt
- desktop_version/src/BinaryBlob.cpp
- desktop_version/src/Graphics.cpp
- desktop_version/src/GraphicsUtil.cpp
- CMake: Add ENABLE_WARNINGS and ENABLE_WERROR build options
ENABLE_WARNINGS is enabled by default, with `-Wall` on GCC/Clang and
`/W4` on MSVC.
ENABLE_WERROR is disabled by default, treats warnings as errors.
- Fix warnings raised by GCC 8
> Enable and fix warnings

- desktop_version/CMakeLists.txt
- desktop_version/CONTRIBUTORS.txt
CMake always enabled -Werror due to an error in evaluating ENABLE_WERROR. This patch fixes this problem by fetching the value instead of using the name as a boolean.
> Fix Werror always being enabled

- desktop_version/src/Entity.cpp
- desktop_version/src/Game.cpp
- desktop_version/src/Script.cpp
Resizing the vector does the same thing that the loops did, it changes
the size for the vector and initializes it with default-constructed
elements (or 0 or its equivalent for POD types).
Where a specific value is needed, it is set with the second
parameter of resize().
> Simplify std::vector initializations

- desktop_version/CONTRIBUTORS.txt
- desktop_version/src/FileSystemUtils.cpp
- desktop_version/src/FileSystemUtils.h
- desktop_version/src/Game.cpp
- desktop_version/src/Input.cpp
- desktop_version/src/editor.cpp
On Windows, players with an account username that contains non-ASCII characters (any foreign characters, for example) will probably find that the VVVVVV directory is not created, or if it is, that no save/level files are created inside of it and any downloaded custom level cannot be loaded. This pull request fixes these issues.
The commit messages document things in more detail, but in summary: the two Windows API functions that are used to get the path to the Documents folder and to create new folders now use their "Wide" (UTF-16) variants converted to and from UTF-8, and loading and saving XML files now uses PHYSFS to load and save the …
> Handle filepaths with non-ASCII characters properly on Windows

- .gitattributes
Fix all the ActionScript in the repository being misclassified as AngelScript. I know you can't actually see it on the branch because linguist doesn't work on branches [but you can see it here](https://github.com/notviri/test1234) unless the language bar dissapears (it keeps flickering because I just committed the contents of the entire repo there), but:
> fix actionscript misclassified as angelscript

- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
- desktop_version/src/Input.cpp
- desktop_version/src/main.cpp
- desktop_version/src/titlerender.cpp
* **Add an option in the Accessibility menu to toggle the fake loading screen**
This is the variable `game.skipfakeload`, which gets saved as `<skipfakeload>` in `unlock.vvv`.
> Add an accessibility option to toggle the fake loading screen

- desktop_version/CONTRIBUTORS.txt
- desktop_version/src/Script.cpp
- mobile_version/src/scriptclass.as
Just a small spelling error that wasn't caught in #28, in the dialogue that displays when you find the Secret Lab.
> Fix a stray "seperate" in Secret Lab dialogue

- desktop_version/src/Map.cpp
* **Destroy duplicate player entities during a gotoroom**
The game makes sure that the player entity is never destroyed, but in doing so, it doesn't destroy any duplicate player entities that might have been created via strange means e.g. a custom level doing a createentity with t=0.
Duplicate player entities are, in a sense, not the "real" player entity. For one, they can take damage and die, but when they do they'll still be stuck inside the hazard, which can result in a softlock. For another, their position isn't updated when going between rooms. It's better to just destroy them when we can.
> Destroy duplicate player entities when a gotoroom happens

- desktop_version/src/Logic.cpp
* **Don't deactivate the teleport prompt when dying**
This fixes a bug where if you died after activating a teleporter prompt and then respawned in the same room as the teleporter, the teleporter prompt would go away. Which would be very annoying if you wanted to, you know, teleport.
You don't even have to R-press to make this happen. "Level Complete!" and Energize are two teleporter rooms in the main game that have hazards in them.
I see no reason to set game.activetele to false when dying. For one, it gets set to false during a gotorom anyway. For another, I couldn't get the game to activate the teleport prompt in a room without a …
> Don't deactivate the "- Press ENTER to Teleport -" prompt when dying

- desktop_version/src/main.cpp
* **Disable being able to mute the game while typing in the script editor**
This disables being able to press M to mute while editing a script in the script editor. It also disables it in the script list, too, but I'm hoping no one thinks that's an issue, because I personally don't think it is.
> Disable pressing M to mute in the script editor

- desktop_version/src/Game.cpp
* **Fix being able to lower your score for a custom level by finishing it again**
For reference, here is the list of scores for a custom level:
​    0 - not played
​    1 - finished
​    2 - all trinkets
​    3 - finished, all trinkets
Previously, you could've played a level and finished it and set a score of 3. Then you could re-play the entire level, but manage to only get a score of 1, i.e. only finished but not with all trinkets. Then your score for that level would get set back to 1, which basically nullifies the time you spent playing that level and getting all of the trinkets.
This pull request makes it so your new score will get set …
> Fix being able to lower your score for a custom level by replaying it

- desktop_version/src/Labclass.cpp
* **Fix "Exausted?" typo in roomname**
This name is the roomname of (7,17) (0-indexed) in the Lab.
> Fix "Exausted?" typo in roomname

- desktop_version/src/Map.cpp
* **Correct Warp Zone's area name from "Warpzone" to "Warp Zone"**
This is the name that gets displayed in your save file.
> Correct Warp Zone's area name from "Warpzone" to "Warp Zone"

- desktop_version/src/Script.cpp
* **Properly reset `map.roomdeaths` and `map.roomdeathsfinal` in `hardreset()`**
There are three map-related vectors that need to be reset in `hardreset()`: `map.roomdeaths`, `map.roomdeathsfinal`, and `map.explored`. All three of these vectors use the concatenated rows system, whereby each room is given a room number, calculated by doing X + Y*20, and this becomes their index in each vector.
Previously, only the first row of rooms of each vector was getting reset properly, corresponding with only the first row of rooms in both Dimension VVVVVV and Outside Dimension VVVVVV getting reset properly. This led to [strange death …
> Properly reset roomdeaths and roomdeathsfinal in hardreset

- desktop_version/src/Script.cpp
* **Fix being able to get the wrong background set in the room with `warpdir()`**
If you're in the room being targeted when a `warpdir()` command is run, and the command sets the warp direction to none (warp dir 0), and if you're in a Lab or Warp Zone room, the background will be set to the wrong one, because it will always set the background to the stars-going-left background, instead of setting it to the Lab background or the stars-going-up background.
However, this is only a visual glitch, and is a temporary one, because if you manage to trigger a `gotoroom()` on the room, it will get set to its proper background.
This PR makes it so if …
> Fix warpdir() setting the wrong background if you set the warp direction to 0 in the current room

- desktop_version/src/Entity.cpp
* **Add entity `type` checks to `getcrewman()`**
This means that the game is no longer able to target other non-crewmate entities when it looks for a crewmate.
This has actually happened in practice. A command like `position(cyan,above)` could position the text box above a horizontal warp line instead of the intended crewmate.
This is because `getcrewman()` previously only checked the `rule` of entities, and if their `rule` happened to be 6 or 7. Usually this corresponds with crewmates being unflipped or flipped, respectively.
But warp lines' `rule`s overlap with `rule`s 6 and 7. If a warp line is vertical, its `rule` is 5, and if it is …
> Prevent the game from thinking horizontal warp lines are cyan crewmates

- desktop_version/src/Graphics.cpp
* **Re-add the font outline from the Flash and mobile versions of the game**
This uncomments the code for the font outline. Now, you will see the font outline on text that had it in the Flash version, most notably "- Press ENTER to Teleport -" and the time trial overlay text.
This also fixes a problem with the commented code, where un-centered text didn't outline properly.
> Re-add the font outline from the Flash and mobile versions

- .github/pull_request_template.md
- desktop_version/CONTRIBUTORS.txt
this makes the mouse-over tooltip of PRs actually useful instead of showing the same thing for every PR like this:
Compared with this PR:
> PR template: switch position of Legal Stuff & Changes

- desktop_version/src/titlerender.cpp
* **Don't render "[Press ENTER to return to editor]" if "- Press ACTION to advance text -" is also being rendered**
This prevents a visual clash if both are being rendered on top of each other and there are no cutscene bars.
Before:
After:
> Don't render "[Press ENTER to return to editor]" if "- Press ACTION to advance text -" is also being rendered

- desktop_version/src/editor.cpp
* **Fix the off-by-one bug in the script editor that would let you type text on a nonexistent script line**
For a long time, the script editor has had a bug where it would let you put the cursor on a nonexistent script line, which would *appear* to be the last line of the script... but in reality, it *wasn't* the last line of the script, and in fact, the *actual* last line was the line *above* the "last line".
So, if you typed anything on this nonexistent line, it would appear to get erased when exiting the script and re-opening it. Thus, people have (erroneously) misdiagnosed this as the script editor somehow being trigger-happy and erasing lines when it shouldn't be, when in reality it shouldn't have let you gone onto that line in the first place!
By submitting this pull request, I …
> Fix off-by-one in script editor letting you type on a nonexistent line

- desktop_version/src/KeyPoll.cpp
- desktop_version/src/KeyPoll.h
- desktop_version/src/editor.cpp
- desktop_version/src/main.cpp
* **Fix frame-ordering bug with backspacing the last character of a line in the script editor**
There is a long-standing bug with the script editor where if you delete the last character of a line, it *immediately* deletes the line you're on, and then moves your cursor back to the previous line. This is annoying, to say the least.
The reason for this is that, in the sequence of events that happens in one frame (known as frame ordering), the code that backspaces one character from the line when you press Backspace is ran *before* the code to remove an empty line if you backspace it is ran. The former is located in `key.Poll()`, and the latter is located in `editorinput()`.
Thus, when you press Backspace, the game first runs `key.Poll()`, sees that you've pressed Backspace, and dutifully …
> Fix two script editor backspacing bugs (one related to frame ordering, the other simply being a lack of key delay)

- desktop_version/src/editor.cpp
* **Reset the Direct Mode property of each room when `editorclass::reset()` is called**
There's a long-standing issue where the Direct Mode status of the loaded custom map in memory never resets properly. So if you load a level with a certain layout of Direct Mode rooms, that same layout will be preserved if you start making a new level in the editor. This PR fixes that issue.
> Reset the Direct Mode property of each room in editorclass::reset()

- desktop_version/src/Input.cpp
* **Don't play Viridian's squeak twice when entering the menu to load a level's quicksave or start from the beginning**
This is another squeak-twice bug fixed.
> Don't play squeak twice when entering the 'quickloadlevel' menu

- desktop_version/src/Graphics.cpp
* **Fix the bug with translucent pixels being drawn incorrectly**
For a long time, VVVVVV has had an issue where if you used custom graphics with translucent pixels (i.e. pixels whose opacity was neither 0% nor 100%, but somewhere between 0% and 100%), those pixels would end up looking very ugly. They seemed to be overlaid on top of some weird blue color, instead of actually being translucent.
This bug only occurred when in-game and not in towermode. So, most of the time, basically. The translucent pixels only displayed properly inside the Tower, both minitowers, and the editor (when not playtesting).
I traced this down to the use of the magic number 0xDEADBEEF in `Graphics::drawmap()` and `Graphics::drawfinalmap()`. Looks like someone had fun finding a color. Was it you, simoroth? …
> Fix bug where translucent pixels were drawn badly

- desktop_version/src/editor.cpp
* **Fix out-of-bounds array indexing in `editorclass::findstartpoint()`**
Out-of-bounds array access is Undefined Behavior, which means Bad Things.
In this particular case, it was indexing an array by using the `testeditor` variable. Which is fine, except it was indexing that array *in a conditional that only happens if `testeditor` is -1*. So it was indexing an array at position -1, which is Out of Bounds and is Not Good.
> Fix an out-of-bounds array access in findstartpoint()

- desktop_version/src/Script.cpp
* **Reset `dwgfx.cutscenebarspos` in `scriptclass::hardreset()`**
This fixes a bug in the editor where if you had cutscene bars active while exiting playtesting, when you re-entered playtesting, the bars would do their closing animation even though they should be already gone.
> Reset the position of the cutscene bars in hardreset()

- desktop_version/src/titlerender.cpp
* **Copy `backBuffer` to `tempBuffer` when executing `towerrender()`**
This fixes a bug where bringing up the pause screen while in a tower would draw the room you entered *before* the given tower during the time it took for the pause screen to be brought up or down.
> Copy backBuffer to the tempBuffer in towerrender()

- desktop_version/src/Script.cpp
* **Reset `game.pausescript` in `scriptclass::hardreset()`**
This fixes an issue where you could softlock the game if you exited playtesting mode by pressing Esc while a "- Press ACTION to advance text -" prompt was onscreen, then re-entered playtesting and then started any script.
The "- Press ACTION to advance text -" prompt is most directly controlled by `game.advancetext`, but  when it appears, `game.pausescript` is usually set as well. However, both variables are required.
You need to have both variables on at the same time in order to press ACTION and advance past the prompt. If only `advancetext` is on, then you won't be able to flip but can still move around, but if only `pausescript` is on, then the game softlocks because the only way you can turn `pausescript` off is by pressing …
> Reset game.pausescript in scriptclass::hardreset()

- desktop_version/src/Music.cpp
* **Don't quick fade when using `musicclass::niceplay()`**
Earlier in 53950e14de65a54d9369c5183a16337782d3dc4e, I made playing a song while a song was already fading quickly fade out the current song, but then added an exception for if the fade came from the `musicfadeout()` command. This commit adds another exception for if the fade came from `musicclass::niceplay()`, since otherwise the music transitions between areas in the game would go too quick.
> Don't quick fade when using musicclass::niceplay()

- desktop_version/src/Input.cpp
* **Call `mapclass::nexttowercolour()` when exiting to the menu from the Esc screen**
This fixes a bug where you could get mismatched text and background colors on the menu screen by being in the Tower and exiting at a certain time.
The background when mismatched will always be red, which seems to have something to do with the fact that when you enter the Tower the game always sets the background to be red.
I could get a quick repro setup going by starting in the checkpoint in Teleporter Divot, then quickly entering the Tower, exiting, then re-entering, then pressing Esc and quitting - all done very quickly.
The important thing about this mismatch is that it's only temporary, and will be corrected when you press ACTION and the color of the text and background in the menu both change at …
> Call nexttowercolour() when exiting to menu from the Esc screen

- desktop_version/src/editor.cpp
* **Reset the enemy type of each room in `editorclass::reset()`**
This fixes a bug where if you loaded a level, then started making a new level in the editor, the enemy types from the previous level would persist.
While working on VVVVVV: Community Edition and adding a new room property for enemy speed, I noticed that enemy type was not getting reset at all. After some testing, I confirmed that this was the case. So this bug is fixed now.
> Reset enemy type in editorclass::reset()

- desktop_version/src/editor.cpp
* **Fix the X and Y bounds getting mixed up in `editorclass::reset()`**
When `editorclass::reset()` was resetting the contents of the level previously, it was mixing up the X and Y bounds. The Y bound was supposed to be `30*maxheight`, and the X bound was supposed to be `40*maxwidth`. Instead, it took `30*maxwidth` as its Y bound and `40*maxheight` as its X bound.
Then, when it actually indexes the contents vector to set each tile to 0, it used `30*maxwidth` instead of `40*maxwidth`.
The difference between width and height is a bit hard to spot, but one thing you can do to remember the difference is to remember the fact that X corresponds with width, and Y corresponds with height. Also, rooms are 40 by 30 tiles, and so X (and therefore width) should correspond with 40, and Y (and …
> Fix X and Y coordinates getting reversed in editorclass::reset()

- desktop_version/CONTRIBUTORS.txt
- desktop_version/src/editor.cpp
Lack of font outlines can sometimes make things difficult to read.
This pull request makes things that print directly to a room (not menus, etc)
use font outlines in the level editor.
It also adds myself to the contributor list, in case it is accepted.
> Make the level editor use font outlines

- desktop_version/src/Script.cpp
- desktop_version/src/UtilityClass.cpp
- desktop_version/src/editor.cpp
* **Raise the limit of trinkets and crewmates to 100**
The editor will now allow you to place up to 100 trinkets and crewmates.
VVVVVV 2.2 will handle 100 trinkets and crewmates in a level just fine. It has 100 slots allocated for each already, and it will read and write those 100 slots to the level quicksave file no problem. Except only the first 20 slots get reset when starting from the beginning, but that's minor and is already fixed in 2.3 anyway.
* **Make `UtilityClass::number()` less hardcoded**
It used to be a giant array of hardcoded numbers going up to Fifty. Now, it's less hardcoded to account for the new trinkets and crewmates limit of 100. For most numbers, it will find the number's tens-place, then find its one-place, and concatenate them together. Special exceptions include …
> Raise the trinket/crewmate limit and hardcode their text less

- desktop_version/CONTRIBUTORS.txt
- desktop_version/src/titlerender.cpp
Changed "controllers" to "controller's" in the game options menu.
> Added an apostrophe to 'controllers' in game options

- desktop_version/src/FileSystemUtils.cpp
- desktop_version/src/FileSystemUtils.h
The TinyXML parse() function expect a C-like string, including terminator.
When xml loading was changed, it loaded the file, but included no such thing.
Thus, we load the file, then reallocate the memory so that we can insert a
null terminator to it, before passing it to parse().
> Add a null terminator to loaded TinyXML files

- desktop_version/src/FileSystemUtils.cpp
- desktop_version/src/editor.cpp
This fixes the level editor not using LoadTiXmlDocument,
and thus retaining the null terminator issue as addressed previously.
> Fix level editor not using LoadTiXmlDocument

- desktop_version/src/Entity.cpp
- desktop_version/src/Entity.h
- desktop_version/src/Script.cpp
I ran the game through Valgrind to catch various issues.
One thing caught my attention -- map.resumedelay. This is
used by The Tower/etc to add a delay before the game is
resumed (probably for camera controls delaying it) for
spawning the player. This variable was uninitialized. Notably,
if I explicitly set it to 592851 or similar, it reproduces the
bug, even if I cannot reproduce it with my typical compilation
flags. So fixing this by initializing it to 0, alongside some
other Valgrind warnings, should fix the problem entirely.
> Fix tower quicksave bug (only appeared in some builds)

- desktop_version/src/Game.cpp
- desktop_version/src/Graphics.cpp
- desktop_version/src/Graphics.h
- desktop_version/src/Input.cpp
- desktop_version/src/editor.cpp
- desktop_version/src/main.cpp
- desktop_version/src/titlerender.cpp
This PR adds an option to be able to make the room name background translucent.
Such an option would be very useful when playing through custom levels, since certain custom levels have problems with making their visuals clear with regards to the roomname. They might put collision behind it, making it look like there's an exit and you'd go through to the room below, even though they intend for you to magically know that there's collision there and then walk on it. Or they might just be mean and decide to hide spikes there.
**With an opaque room name background:**
**With a translucent room name background:**
* **Render room name backgrounds using an `SDL_Surface` and `SDL_BlitSurface()` instead of using `SDL_FillRect`**
Unfortunately, it would be easy if we could simply change the …
> Add an accessibility option to be able to see through the room name background

- desktop_version/src/Map.cpp
When the game enter towermode, it adjusts player amd camera x/y depending
on what screen the player entered it from (The Tower) or the loadlevel
mode ("minitowers"; Panic Room and The Final Challenge). This code didn't
account for respawning to checkpoints. This is unlikely to matter in most
circumstances, but can cause problems in some corner cases, or with R abuse.
This could cause a player to die, respawn outside camera edges and then
immediately die again due to the edge spikes, repositioning the camera
properly. Invincibility would cause further issues, but that's Invincibility
Mode for you -- if this was the only problem I wouldn't bother.
I added a check that repositions the tower camera appropriately if a player
enter a tower as part of the respawn process. …
> Fix minor issue with respawning into a tower

- desktop_version/src/editor.cpp
Ingame entities are drawn backwards, probably to draw the player on top,
being entity 0 (usually, at least). Make the level editor draw entities
in the same order.
> Draw editor entities according to ingame order

- desktop_version/src/Game.h
- desktop_version/src/Map.cpp
- desktop_version/src/Script.cpp
**Don't redraw horizontal and vertical warp backgrounds if `gotoroom` is being called on the current room in custom levels**
This has two benefits:
1. The game uses less resources when it is asked to `gotoroom` to the same room from a `gotoroom` script box, because it is no longer re-drawing the warp background every single frame, which is very wasteful.
2. The warp background no longer freezes or flickers if the player is standing inside a `gotoroom` script box (which calls `gotoroom` every frame or every other frame, because every time the `gotoroom` happens the script box gets reloaded, thus doing another `gotoroom`, etc.)
To demonstrate the fix, I have attached a custom level that has `gotoroom` script boxes so you can compare before and after. Before, the game is re-drawing the warp …
> Don't re-draw horizontal and vertical warp backgrounds if gotoroom()ing to the same room in custom levels

- desktop_version/src/Game.cpp
- desktop_version/src/Graphics.cpp
- desktop_version/src/Graphics.h
- desktop_version/src/Input.cpp
- desktop_version/src/titlerender.cpp
Adds a new setting to the graphics options menu to show or hide the system mouse cursor over the game window. This is nice to have if you find the cursor distracting, particularly in fullscreen mode. The cursor initially defaults to shown because that's what players are used to, and it's helpful for the level editor.
As a bonus, this should close #105.
> Add graphics option to toggle mouse cursor

- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
- desktop_version/src/Graphics.cpp
- desktop_version/src/Graphics.h
- desktop_version/src/GraphicsResources.cpp
- desktop_version/src/GraphicsResources.h
- desktop_version/src/KeyPoll.h
- desktop_version/src/Map.h
- desktop_version/src/Music.cpp
- desktop_version/src/Music.h
- desktop_version/src/UtilityClass.h
- desktop_version/src/main.cpp
* **Allow using `help`, `graphics`, `music`, `game`, `key`, `map`, and `obj` everywhere**
This PR makes `help`, `graphics`, `music`, `game`, `key`, `map`, and `obj` essentially static global objects that can be used everywhere. This is useful in case we ever need to add a new function in the future, so we don't have to bother with passing a new argument in which means we have to pass a new argument in to the function that calls that function which means having to pass a new argument into the function that calls *that* function, etc. which is a real headache when working on fan mods of the source code.
Note that this changes *none* of the existing function signatures, it merely just makes those variables accessible everywhere in the same way `script` and `ed` are.
Also note that some …
> Allow using 'help', 'graphics', 'music', 'game', 'key', 'map', and 'obj' everywhere

- desktop_version/src/editor.cpp
- desktop_version/src/editor.h
First, two bug fixes. Room text input mode wasn't properly unset
upon pressing Esc, making the prompt get stuck, requiring you to
add roomtext again and finish it to make it go away. Secondly,
escaping script text input would remove the wrong entity.
I also tweaked the handling slightly so that instead of deleting
the entity if it already existed if escaping from text input,
it merely reverts the change in script name/roomtext to what it
was previously.
I considered refactoring the editor text input handler entirely,
but figured such a change would be a bit too extensive for the
purpose of this repository.
> Fix and improve handling of cancelling roomtext/scripttext input

- desktop_version/src/Input.cpp
- desktop_version/src/Script.cpp
- desktop_version/src/editor.cpp
- desktop_version/src/editor.h
* **Reset warp directions when exiting playtesting**
This fixes a bug where if `warpdir()` was used during in-editor playtesting, the changed warp direction would persist even when leaving playtesting.
This would be very annoying to correct back every time you playtested and `warpdir()` was used, so I've added some kludge to store the actual warp direction of each room when entering playtesting, and then set the warp directions back when leaving playtesting.
> Reset warp directions when exiting playtesting

- desktop_version/src/Entity.cpp
* **Set `customwarpmode` to true when `createentity`ing warp lines**
This fixes a bug where warp lines created through `createentity` wouldn't work without there already being a warp line present in the room as an edentity.
> Set customwarpmode to true when createentity()ing warp lines

- desktop_version/src/Script.cpp
* **Fix `text()` centering with x=-1**
The game uses magic values x=-500 and y=-500 to indicate when a text box should be centered horizontally or vertically. It does this for x=-1 too, but it's buggy because it only looks at the first line of the text box to center it. In this commit I fix it so that it will look at all of the lines of the text box to center it instead.
Here's what x=-1 centering looked like before:
Here's what x=-1 centering looks like after:
The script is:
```
text(gray,-1,-500,2)
this is
a text box with two lines
speak
endtext
```
> Fix text() centering with x=-1

- desktop_version/src/Map.cpp
- mobile_version/src/mapclass.as
* **Fix (19,8)'s hardcoded all-sides warping happening in custom levels**
(19,8) is hardcoded to warp on all-sides no matter what. This is fine, except for the fact that it was doing this in custom levels, too, even despite the fact that the warp background and color would be overridden anyway. The only workaround was to add a warp line to the room in custom levels. I've added a check for custommode so that this won't happen.
> Fix hardcoded (19,8) all-sides warp happening in custom levels

- desktop_version/src/Logic.cpp
- mobile_version/src/includes/logic.as
* **Fix the Prize for the Reckless quicksand fix kludge executing in custom levels and in way more rooms than needed**
If you died in Prize for the Reckless, which is at (11,7), and respawned in the same room, tile 59 (a solid invisible tile) would be placed at [18,9] to prevent the moving platform from going back through the quicksand.
Unfortunately, the way that this kludge was added is poor.
First, the conditional makes it so that it doesn't happen in *only* (11,7). Instead of being behind a positive conditional, the tile is placed in the else-branch of an if-conditional that checks for the normal case, i.e. if the current room is *not* (11,7), thus being a negative conditional.
In other words, the positive conditional is `game.roomx == 111 && game.roomy == 107`. To negate it, all you …
> Fix Prize for the Reckless quicksand fix kludge executing in unintended places

- desktop_version/src/FileSystemUtils.cpp
- desktop_version/src/FileSystemUtils.h
- desktop_version/src/main.cpp
This is useful for distributions, which may not want to put data.zip in the same directory as the binary. This can't be distribution-specific due to the license ("Altered source/binary versions must be plainly marked as such, and must not be misrepresented as being the original software.").
> Add -assets option to specify data.zip

- desktop_version/src/Graphics.cpp
* **Fix warping entities being the wrong color in flip mode**
In flip mode, warping entities would appear to change color for a brief moment. This is actually them defaulting to the actual color used in `flipsprites.png`, instead of first being whited-out and then re-colored using `graphics.setcol()`.
To fix this, use `BlitSurfaceColoured()` and pass `ct` along instead of using `BlitSurfaceStandard()`.
Before:
After:
> Fix discoloration when entities warp in flip mode

- desktop_version/src/Script.cpp
* **Fix `flipme()` positioning text boxes incorrectly**
The problem with `flipme()` was that it *was* properly reflecting ("reflecting" as in mirroring over a given line) the text box over the line y=120, *but* it forgot to account for the height of the text box. Thus, the text box position would be off by the length of its own height. And when the text box got taller, this offset would worsen and worsen.
Here are some screenshots to demonstrate the difference.
Not in flip mode:
In flip mode, using buggy `flipme()` positioning:
In flip mode, with fixed `flipme()` positioning:
> Account for the height of the textbox in flipme()

- desktop_version/src/Graphics.cpp
* **Fix the outline of centered text rendering upside-down in flip mode**
If you looked at the "- Press ENTER to Teleport -" text in flip mode, you might have noticed that the outline looked pretty strange and glitched-out for some reason. It's just the outline rendering upside-down. To fix this, make `PrintOff()` use `flipbfont` instead of `bfont`.
Before:
After:
> Fix centered texts' outline rendering upside-down in flip mode

- desktop_version/src/Logic.cpp
* **Fix Prize for the Reckless moving platform kludge happening in custom levels**
If you died in (11,7) and a moving platform was to the left of the line x=152, even if it was moving vertically it would get snapped to x=152, in custom levels.
Surprised nobody has ran into this before (although people have ran into the other kludge, which is placing tile 59 at [18,9] if you're in a room on either the line x=11 or y=7).
> Fix Prize for the Reckless moving platform kludge happening in custom levels

- desktop_version/src/Graphics.cpp
* **Draw entities backwards in `towermode` like non-`towermode` entities**
This fixes a bug where the player was going behind checkpoints in towers and it looked very weird and cursed.
Before:
After:
> Draw entities backwards in towers like entities outside towers

- desktop_version/src/Entity.cpp
- desktop_version/src/Map.cpp
Previously, in tower mode, being inside walls would just kill you, unlike
being inside walls outside tower mode, which was somewhat confusing.
Also, spikes behaved differently with regards to invincibility, being
unsolid in towers but solid outside them.
This does not change the behaviour of the "edge" spikes in towers.
> Make tiles in tower mode consistent with tower tileset elsewhere

- desktop_version/src/Game.cpp
* **Make the hardest room be named "Dimension VVVVVV" if it has no room name**
The only places where you can die in a room without a room name is the Overworld, and I feel that calling it Dimension VVVVVV is appropriate.
You can't naturally die in The Ship nor the Secret Lab, and you can only do it by pressing R, so I didn't feel it appropriate to add checks to make the hardest room be "The Ship" or "The Secret Lab" if you managed to get your hardest room to be a room in either of those areas.
> Make hardest room "Dimension VVVVVV" if it has no room name

- desktop_version/src/titlerender.cpp
* **Render screen shaking in towers**
It's really obvious that screen shaking is not processed in towers if you bring up the pause menu then quickly quicksave and bring it back down. The screen won't shake, but it will suddenly start shaking if you exit the tower, finishing off the stalled screenshake timer.
> Render screen shaking in towers

- desktop_version/CONTRIBUTORS.txt
- desktop_version/src/Game.cpp
- desktop_version/src/editor.cpp
In `editor.cpp`, there's a few sections of code that try and index stuff using `string.length()-1`.
This causes issues where if the string is empty, the result is -1, causing undefined behavior.
Flibit fixed a few of these cases, like on line `375` of editor.cpp:
`if((int) tstring.length() - 1 >= 0) // FIXME: This is sketchy. -flibit`
It turns out that one of these weren't caught, over at line `471`.
`tstring=tstring[tstring.length()-1];`
This causes builds compiled on Windows to segfault if you load more than one level in the editor.
I added a quick `if` around it, setting `tstring` to an empty string, which seems to fix the problem.
> Fix undefined behavior while loading scripts

- desktop_version/src/Scripts.cpp
It turns out that the line `tstring=tstring[tstring.size()-1];` also appears once in Scripts.cpp.
This causes the game to segfault after activating a terminal with an empty line at the end of it.
I added a quick `if` around this line, and set `tstring` to an empty string when needed.
(Sorry! If I knew there was more than one instance of this before making my last PR I would have fixed this too! Turns out `.size()` and `.length()` both exist...)
> Fix undefined behavior when activating scripts

- desktop_version/CONTRIBUTORS.txt
- desktop_version/src/FileSystemUtils.cpp
- desktop_version/src/FileSystemUtils.h
- desktop_version/src/Game.cpp
- desktop_version/src/main.cpp
Added a command-line argument to specify the location of the base user directory. This is useful for maintaining multiple save files or for debugging.
> Add -basedir option to specify base user directory 

- desktop_version/src/Graphics.cpp
- desktop_version/src/Graphics.h
- desktop_version/src/GraphicsUtil.cpp
- desktop_version/src/editor.cpp
- desktop_version/src/editor.h
- desktop_version/src/titlerender.cpp
This makes the `[Press ENTER to return to editor]` text in the editor fade out after a few frames, allowing screenshots of custom levels to be cleaner and to make sure nothing is obscured while the user is editing their level.
This commit also adds alpha support in BlitSurfaceColoured, where it takes into account the alpha of the pixel *and* the alpha of the color.
`graphics::getRGBA(r,g,b,a)` was added to help with this.
This is useful for future changes if anyone needs to use BlitSurfaceColoured with an alpha color, which could be something like making the translucent roomname bar use BlitSurfaceColoured instead of an entirely new surface.
> Make "[Press ENTER to return to editor]" fade out after a bit

- desktop_version/src/editor.cpp
* **Prevent removing the line if there is only one line in the script editor**
This fixes another way you could end up typing on a non-existent line in the script editor.
In a script with only 1 line, which is empty, the game would let you press backspace on it, removing the line. This results in you typing on a non-existent line.
You will keep typing on it until you either close the script or press Up. If you press Up, you will be unable to get back to the non-existent line, for it doesn't exist - but the text you typed on the non-existent line will still be there, until you close the script and re-open it.
> Prevent removing the line if there is only one line in the script editor

- desktop_version/src/titlerender.cpp
After PR #158, the "return to editor" text now fades out after a short time. The state of the fade is tracked via a variable in the editor class. If building with CUSTOM_LEVEL_SUPPORT=NO_CUSTOM_LEVELS (PR #157), the build now fails because the editor class is omitted. This PR ifdefs out the code that draws the "return to editor" text when compiling without custom level support.
> Fix NO_CUSTOM_LEVELS compile after #158

- desktop_version/src/Graphics.cpp
- desktop_version/src/Graphics.h
- desktop_version/src/editor.cpp
- desktop_version/src/editor.h
I love how active this repo seems to be! Unfortunately some of the changes are incompatible with older compilers. Fortunately, the problems are small and easy to fix.
1) Pre-C++11 compilers do not support initializing variables in class declarations.
This only occurs once, in the editor class. I've moved the initialization to the `reset()` method instead. The added benefit is that the variable gets properly reset.
2) Pre-C++11 compilers do not support `char32_t`.
Use `uint32_t` instead. Everywhere else in the code already uses either `uint32_t` or `int`.
> Support pre-C++11 compilers

- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
- desktop_version/src/Input.cpp
- desktop_version/src/titlerender.cpp
In commit 2aa4aa5, @flibitijibibo added the names of GitHub contributors to the end-of-game credits and refactored the code to use 3 lists (`superpatrons`, `patrons`, and `githubfriends`) instead of hard-coding everything. However, the names in the credits accessible from the main menu were still hard-coded as well as lacking the names of GitHub contributors.
This change refactors the main menu accessible credits to use the 3 lists and adds the names of GitHub contributors.
> Use dynamic credits lists for main menu credits screens (and add GitHub contributors)

- desktop_version/src/Music.cpp
Previously, when MMMMMM is installed but the user is using PPPPPP, niceplay would still restart the song even if it's the same. That has been fixed. In addition, Plenary and Path Complete no longer loop when MMMMMM is installed but PPPPPP is in use.
> Fixed some music bugs

- desktop_version/src/Game.cpp
* **Fix crewmate-found text boxes overlapping in flip mode**
The problem was that the code seemed to be wrongly copy-pasted from the code for generating the trinket-found text boxes (to the point where even the comment for the crewmate-found text boxes didn't get changed from `//Found a trinket!`).
For the trinket-found text boxes, they use y-positions 85 and 135 if not in flip mode, and y-positions 105 and 65 if the game *is* in flip mode. These text boxes are positioned correctly in flip mode.
However, for the crewmate-found text boxes, they use y-positions 85 and 135 if not in flip mode, as usual, but they use y-positions 105 and *135* if the game is in flip mode. Looks like someone forgot to change the second y-position when copy-pasting code around.
Which is actually a bit funny, …
> Fix crewmate-found text boxes overlapping in flip mode

- desktop_version/src/editor.cpp
This fixes the following typo: "quiting" (one T) to "quitting" (two Ts). This is in the "Save before quitting?" menu in the level editor.
> Fix typo: "quiting" (one T) to "quitting" (two Ts)

- desktop_version/src/UtilityClass.cpp
* **Initialize `x` to 0 in `ss_toi()`**
This fixes a source of undefined behavior, where the int returned by `ss_toi()` would be random garbage memory if the string passed into it would be empty. That's because if the string is empty, there are no characters to parse, so nothing simply gets put into `x`.
The easiest way a user could trigger this UB to `ss_toi()` would be to use script commands with empty arguments.
> Initialize x to 0 in ss_toi()

- desktop_version/src/editor.cpp
* **Fix left-clicking on script boxes**
This PR makes it so you can left-click on script boxes to change their script.
> Fix left-clicking on script boxes

- desktop_version/src/Map.cpp
- desktop_version/src/Map.h
- desktop_version/src/Otherlevel.cpp
- desktop_version/src/Otherlevel.h
- desktop_version/src/titlerender.cpp
* **Refactor roomtext code to not use ad-hoc objects or separate length-trackers**
This refactors the roomtext code to (1) not use ad-hoc objects and (2) not use a separate length-tracking variable to keep track of the actual amount of roomtext in a room.
What I mean by ad-hoc object is, instead of formally creating a fully-fledged struct or class and storing one vector containing that object, this game instead hacks together an object by storing each attribute of an object in different vectors.
In the case of roomtext, instead of making a Roomtext object that has attributes `x`, `y`, and `text`, the `text` attribute of each is stored in the vector `roomtext`, the `x` attribute of each is stored in the vector `roomtextx`, and the `y` attribute of each is stored in the vector `roomtexty`. …
> Refactor roomtext to not use ad-hoc objects or separate length-trackers

- desktop_version/src/Map.cpp
- desktop_version/src/editor.cpp
- desktop_version/src/editor.h
- desktop_version/src/main.cpp
* **Refactor edentities to not use separate length-trackers**
This turns the array `edentity` into a proper vector, and removes the need to use a separate length-tracking variable and manually keep track of the actual amount of edentities in the level by using the long-winded `EditorData::GetInstance().numedentities`. This manual tracking was more error-prone and much less maintainable.
`editorclass::naddedentity()` has been removed due to now functionally being the same as `editorclass::addedentity()` (there's no more `EditorData::GetInstance().numedentities` to not increment) and for also being unused in the first place.
`editorclass::copyedentity()` has been removed because it was only used to shift the rest of the edentities up manually, but now that we let C++ do all the hard work …
> Refactor edentities to not use separate length-trackers

- desktop_version/src/editor.cpp
* **Fix undefined behavior with left-click logic in editor**
There's an if-else chain that first deals with figuring out if there's an entity where your left-click happened, and to do this it uses `edentat()`, which returns a sentinel value of -1 if there is *not* an entity where your cursor is.
It's very important to check that the value returned *isn't* -1 before you start indexing the `edentity` vector, since if you *do* index it with that -1, it'll result in Undefined Behavior because you're doing an out-of-bounds array access.
Now, here's what the if-else chain looked like before:
```c++
if(tmp==-1 && ed.free(ed.tilex,ed.tiley)==0)
{
...
}
else if(edentity[tmp].t==1)
```
The bug here is very subtle but it was an easy oversight. Basically, if `ed.free` ended up not being zero, control …
> Fix undefined behavior with left-click logic in editor

- desktop_version/src/editor.cpp
* **Don't draw text outline for roomtext in the editor**
Text outline is not drawn on roomtext when you're actually playing the game, so don't draw the outline in the editor, either.
FIQ mistakenly added text outline to roomtext in ca9f577fc408d417b6bc8b35eac09b757b994964.
> Don't draw text outline for roomtext in the editor

- desktop_version/src/main.cpp
* **Write `unlock.vvv` when pressing Alt+F4**
Previously, the only way to guarantee that the game actually saved your `unlock.vvv` after changing an option, was to ensure you pressed ACTION on the "quit game" menu option.
This makes Alt+F4 graceful in that pressing it will also save `unlock.vvv`, as it should. Now truly UN-graceful ways of exiting the game, such as SIGSEGV, SIGABRT, or `pkill -9` or `pkill -15` will not save `unlock.vvv`, as should be the case.
I just realized I'm mixing Windows idioms ("Alt+F4") and Unix idioms ("SIGSEGV", "`pkill`"). Whoops.
> Write unlock.vvv when pressing Alt+F4

- desktop_version/src/KeyPoll.cpp
- desktop_version/src/main.cpp
* **Fix unfocusing the game while in fullscreen mode**
If you Alt+Tabbed while in fullscreen mode, the game would stay in fullscreen instead of switching to windowed, but there was a chance it would EITHER use the same internal resolution which would mismatch the window resolution (don't know when exactly this happens, but still) and stay being in an actual windowed mode, OR switch between fullscreen/windowed every other time you re-focused the window, which is annoying.
Now, whenever you Alt+Tab in fullscreen, the game will be in windowed mode, and then when you re-focus it will go back to fullscreen. Consistently.
> Fix unfocusing the game while in fullscreen mode

- desktop_version/CONTRIBUTORS.txt
- desktop_version/src/Game.cpp
- desktop_version/src/main.cpp
Fixes #112: Backbuffer is always 32bpp
> Fixes #112: Backbuffer is always 32bpp

- desktop_version/src/KeyPoll.cpp
* **Allow using F11 and, on macOS, RCommand+Enter/F to toggle fullscreen**
This patch allows the use of pressing F11 to toggle fullscreen, as well as allowing the use of Right Command when using the Command+Enter/F shortcut on macOS. Apparently Alt+Enter isn't the only shortcut to toggle fullscreen, Alt+F also works, which I didn't know before.
I'm adding F11 as a shortcut because it's a far more natural shortcut to toggle fullscreen than this Alt+Enter or Alt+F business, which seems to be a relic mimicking some other games and some Microsoft stuff?
I'm also adding RCommand+Enter/F because I see no reason not to. If you can use RAlt on non-macOS, why can't you use RCommand on macOS, too?
I also cleaned up the formatting relating to the shortcut code, and took the ifdef for macOS outside …
> Allow using F11 and (on macOS) RCommand+Enter/F to toggle fullscreen

- desktop_version/src/Screen.cpp
- desktop_version/src/Screen.h
- desktop_version/src/main.cpp
* **Fix console message when using a shortcut that toggles fullscreen**
Whenever you would press Alt+Enter, or Alt+F, or on macOS Command+Enter, or on macOS Command+F, or F11, the game would print this useless error message to console, every single time: "Error: failed: " and it would concatenate `SDL_GetError()` after it, but most of the time `SDL_GetError()` is blank, so it would print just that.
Instead, what the fullscreen shortcut will now do is check the result of the relevant SDL functions, BEFORE it decides to print an error message. And when it DOES print an error message, it will be less vague and will say instead "Error: toggling fullscreen failed: `<output of SDL_GetError()>`".
This means `Screen::ResizeScreen()` and `Screen::toggleFullScreen()` are now int-returning …
> Don't print useless false error message when toggling fullscreen

- desktop_version/src/Screen.cpp
- desktop_version/src/Screen.h
- desktop_version/src/main.cpp
* **Properly handle errors inside `Screen::ResizeScreen()`**
Instead of passing the error codes out of the function, just handle the errors directly as they happen, and fail gracefully if something goes wrong instead of continuing.
This should be done for every instance an SDL function is called, but this is a good start.
> Do proper error handling inside Screen::ResizeScreen()

- desktop_version/src/Game.cpp
* **Prevent custom levels from tampering with main game save data**
Someone being mean could've overwritten the telesaves of unsuspecting players, or unlocked a bunch of stuff which they shouldn't have for those players, using things like the `telesave()` command and gamestates. To prevent this, return early in `Game::savequick()`, `Game::savetele()`, and `Game::unlocknum()` if we are in custommode.
> Don't let custom levels tamper with main game save data

- mobile_version/src/mapclass.as
* **Correct Warp Zone's area name on the mobile version**
This changes the name from "Warpzone" to "Warp Zone", like it properly should be.
This is the name that gets displayed in your save file.
This PR is the same as #84, but for the mobile version.
> Correct Warp Zone's area name on the mobile version

- desktop_version/src/Script.cpp
- desktop_version/src/Script.h
- desktop_version/src/Scripts.cpp
- desktop_version/src/editor.cpp
- desktop_version/src/editor.h
* **Make `script.commands`, `ed.sb`, and `ed.hooklist` not use separate length-trackers**
This is a refactor that turns the script-related arrays `ed.sb`, and `ed.hooklist` into C++ vectors (`script.commands` was already a vector, it was just misused). The code handling these vectors now looks more like idiomatic C++ than sloppily-pasted pseudo-ActionScript. This removes the variables `script.scriptlength`, `ed.sblength`, and `ed.numhooks`, too.
This reduces the amount of code needed to e.g. simply remove something from any of these vectors. Previously the code had to manually shift the rest of the elements down one-by-one, and doing it manually is definitely error-prone and tedious.
But now we can just use fancy functions like `std::vector::erase()` and `std::remove()` to do it all in …
> Make 'script.commands', 'ed.sb', and 'ed.hooklist' no longer use separate length-trackers

- desktop_version/src/editor.cpp
* **Fix undefined behavior when pressing Backspace in the script list with 0 scripts**
The problem is that it would index out-of-bounds if you did this, but this UB hasn't caused an exception until my change to refactor script-related vectors by removing their separate length-trackers (#169).
> Fix undefined behavior when backspacing in script list with 0 scripts

- desktop_version/src/Music.cpp
- desktop_version/src/Music.h
- desktop_version/src/editor.cpp
* **Un-fix songs 0 and 7 looping and fading in if you are using PPPPPP while you have an `mmmmmm.vvv` file**
As discussed earlier in [#164](https://github.com/TerryCavanagh/VVVVVV/pull/164#issuecomment-607977519), some levels have utilized this bug to create two extra looping tracks.
This only un-fixes it in custom levels.
* **Clean up some more unused/duplicate code**
I've removed `musicclass::loopmusic()`, `musicclass::stopmusic()`, and another outdated comment.
> Un-fix songs 0 and 7 looping and fading in if using PPPPPP while mmmmmm.vvv is present

- desktop_version/src/BlockV.cpp
- desktop_version/src/BlockV.h
- desktop_version/src/Ent.cpp
- desktop_version/src/Ent.h
- desktop_version/src/Entity.cpp
- desktop_version/src/Entity.h
- desktop_version/src/Game.cpp
- desktop_version/src/Graphics.cpp
- desktop_version/src/Graphics.h
- desktop_version/src/Input.cpp
- desktop_version/src/Logic.cpp
- desktop_version/src/Map.cpp
- desktop_version/src/Script.cpp
- desktop_version/src/Script.h
- desktop_version/src/Textbox.cpp
- desktop_version/src/Textbox.h
- desktop_version/src/WarpClass.cpp
- desktop_version/src/titlerender.cpp
This is a re-do of #174 but instead of everything being in one commit, it has been split into 28.
This PR removes the variables `obj.nentity`, `obj.nblocks`, `obj.nlinecrosskludge`, `graphics.ntextbox`, `script.txtnumlines`, and `textboxclass::numlines`, in favor of using `obj.entities.size()`, `obj.blocks.size()`, `obj.linecrosskludge.size()`, `graphics.textbox.size()`, `script.txt.size()`, and `textboxclass::line::size()`, respectively. Furthermore, all entclass, blockclass, and textboxclass objects no longer have an `active` attribute, meaning that they are guaranteed to be real and you don't have to check their `active` attribute before doing any operations with them.
See #174 for more information, I don't feel like re-typing or re-copy-pasting everything here. …
> Refactor entities, blocks, and textboxes to not use the 'active' system and to not use separate length-trackers

- desktop_version/src/titlerender.cpp
- mobile_version/src/includes/render.as
* **Fix typo "Your have unlocked" to "You have unlocked"**
Looks like this was copy-pasted for every single unlock message, too. Either everyone is *that* blind, or everyone is too lazy, or both.
> Fix typo "Your have unlocked" to "You have unlocked"

- desktop_version/CMakeLists.txt
- desktop_version/src/Render.cpp
- desktop_version/src/Render.h
- desktop_version/src/main.cpp
* **Rename `titlerender.cpp` to `Render.cpp` and `titlerender.h` to `Render.h`**
All references to `titlerender.cpp` and `titlerender.h` have been updated accordingly.
Looks like `titlerender.cpp` was a misnomer, maybe in development someone started only with the `titlerender()` function in that file, but it soon included every other render function, too.
> Rename titlerender.cpp to Render.cpp and titlerender.h to Render.h

- desktop_version/src/Logic.cpp
* **Fix memory leak from warping moving platforms**
When the game warps a moving platform, it doesn't remove the moving platform's old block from the position where it warped. That means that block is abandoned and will never be removed. Over time this can pile up, causing a huge memory leak.
This would cause a crash on 2.2 and below, but in 2.3 it will simply cause the game to take up as much RAM as possible.
In extreme cases, you can cause a massive memory leak that takes up a gig by strategically placing moving platforms, like in this example level:
* [fast_platform_warping_crash.zip](https://github.com/TerryCavanagh/VVVVVV/files/4432326/fast_platform_warping_crash.zip)
* **Clean up some `gamelogic()` code**
I de-duplicated some code, condensed if-statements and "else if"-statements, …
> Fix memory leak when the game warps moving platforms

- desktop_version/src/Entity.cpp
* **Prevent `game.stat_trinkets` from being changed in in custom levels**
Whenever you collect a trinket, `game.stat_trinkets` gets updated (if applicable) to signify the greatest amount of trinkets you have ever collected in the game. However, custom levels shouldn't be able to affect this, as their trinkets are not the same trinkets as the main game.
> Don't update game.stat_trinkets in custom levels

- desktop_version/src/Input.cpp
* **Keep user in "game options" menu after toggling MMMMMM**
It's a bit rude to put the user back at the main menu after toggling something. Maybe they also wanted to do something else in the menu while they're toggling MMMMMM, there's no reason to immediately put them back there.
This is a patch that was added to VCE but not yet upstreamed, so I'm upstreaming it now.
> Don't boot user back to main menu after toggling using MMMMMM

- desktop_version/src/FileSystemUtils.cpp
- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
- desktop_version/src/main.cpp
A long-requested feature of third-party VVVVVV level editors like Ved
has been to support playtesting. However, that hasn't been possible. For
April Fools Ved included Vis, a clone of VVVVVV with jumping advertising
itself as just having physics glitches, but until recently there hasn't
been any way to *actually* playtest a level. In November, I created
libvloader, which only on Linuxenabled this functionality. It was
quickly integrated into Ved in a PR, but the difficulties of using
LD_PRELOAD from Lua, as well as only supporting Linux, this stalled.
VVVVVV-CE has replicated this functionality, but due to the lack of a
stable release as well as minor incompatibilities, Ved has been
reluctant to add playtesting support that only supports VVVVVV-CE, but
this PR ports the playtesting …
> Implement command-line playtesting

- desktop_version/src/Entity.cpp
- desktop_version/src/Entity.h
- desktop_version/src/Finalclass.cpp
- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
- desktop_version/src/Input.cpp
- desktop_version/src/Labclass.cpp
- desktop_version/src/Logic.cpp
- desktop_version/src/Map.cpp
- desktop_version/src/Map.h
- desktop_version/src/Otherlevel.cpp
- desktop_version/src/Render.cpp
- desktop_version/src/Script.cpp
- desktop_version/src/Spacestation2.cpp
- desktop_version/src/WarpClass.cpp
- desktop_version/src/editor.cpp
- desktop_version/src/editor.h
This changes the variables `game.trinkets` and `game.crewmates` to be functions which count the number of collected trinkets and crewmates automatically, so we don't have to keep track of the amount of collected trinkets and crewmates separately. It also does the same for `ed.numtrinkets` and `ed.numcrewmates` to keep track of how many trinkets and crewmates there are in the level overall. `map.customtrinkets` and `map.customcrewmates` have been removed due to simply being duplicates of `ed.numtrinkets` and `ed.numcrewmates`.
Also, I cleaned up unused or useless variables.
> Don't use separate variables for tracking number of trinkets and crewmates

- desktop_version/src/Entity.cpp
- desktop_version/src/Entity.h
- desktop_version/src/Game.cpp
- desktop_version/src/Input.cpp
- desktop_version/src/Map.cpp
- desktop_version/src/Map.h
- desktop_version/src/Render.cpp
This removes the variables `map.numteleporters` and `map.numshinytrinkets`, and removes having to give an indice when setting teleporters/trinkets (now we just `push_back` them automatically).
Also I removed `entityclass::cblocks()` because it was unused.
> Refactor map data handling a little bit

- desktop_version/src/FileSystemUtils.cpp
- desktop_version/src/UtilityClass.cpp
- desktop_version/src/UtilityClass.h
- desktop_version/src/editor.cpp
This PR optimizes loading the levels list when selecting "play a level" in the playerworlds menu.
Previously, it was *extremely* slow, because we kept parsing the *entire* XML document for every single level file, which gets pretty slow very quickly. In extreme cases, someone could have a cursed level file, like I did once, with 2<sup>18</sup> edentities inside it (don't ask<sup>note 1</sup>), making loading the levels list completely *choke* on it and temporarily take up a gigabyte of RAM. But if we no longer parse the entire XML document, bombs like these are avoided.
Instead, all we have to do is look for the metadata tags themselves, and what's contained between them. This is the same thing that Ved (an external VVVVVV level editor) does.
This optimization was added to VCE but hasn't …
> Optimize loading the levels list

- desktop_version/src/FileSystemUtils.cpp
- desktop_version/src/FileSystemUtils.h
- desktop_version/src/Game.cpp
- desktop_version/src/Input.cpp
This simply adds an "open level folder" option to the "play levels" menu, which was commented out and left unimplemented. If you press ACTION on it, it will open the level folder for you and minimize the game window. If it can't open the level folder (or the option is grayed out), it will play the sad sound effect.
Most of this code I stole from leo60228, and I kept that `#include <sys/types.h>` even though it seems to compile just fine without it because it sounds important or something.
This is yet another feature added to VCE that hasn't been upstreamed until now.
> Add an "open level folder" menu option to the "play levels" menu

- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
- desktop_version/src/KeyPoll.h
- desktop_version/src/main.cpp
This PR adds being able to press N to mute music only, and automatically pausing the audio of the game when it's unfocused and resuming when it regains focus.
Both of these are already in VCE, however they did music-only muting a bit worse (it's an option in "game options" instead of being a simple keybind, which is annoying).
Some players (myself included) would like to have their own soundtrack playing in the background when playing the game, but don't want to mute sound effects as well.
Also, some custom levels have custom music that they sync to their scripted cutscenes. However, it's always been a problem that the music would desync if players unfocused the game, leading to having to do things like put indicators that say "don't unfocus the game" during cutscenes. If the audio of the …
> Add pressing N to mute music only, and pausing audio upon lost focus

- desktop_version/src/Graphics.cpp
There's a noticeable seam in the horizontal and warp backgrounds whenever you enter a new room. Entering a new room triggers the game to re-draw the entire warp background instead of simply scrolling what it already has. This seam is the result of the initial background draw being misaligned with the rest of the scrolling.
If you get out your measuring tools, you'll see that it's misaligned by exactly 3 pixels (this applies to both horizontal and vertical warping). If you look at the part of the code where the game draws fresh warping textures after scrolling the existing ones offscreen, you'll see it starts with an offset of 317, which is exactly 320 minus 3. And for vertical, it uses 237, which is exactly 240 minus 3.
This is where the misalignment comes from. Since the incoming …
> Fix seam when entering a new room with a horizontal or vertical warp background

- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
- desktop_version/src/Input.cpp
- desktop_version/src/editor.cpp
In #201 I forgot a couple of things.
Most notably, I forgot to use `game.returnmenu()` for the editor menus. As well, I've improved the code for quitting and going back to the main menu, which now uses a new function called `game.returntomenu()`.
> Fix some menu oversights that I made

- desktop_version/src/FileSystemUtils.cpp
- desktop_version/src/FileSystemUtils.h
- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
- desktop_version/src/Input.cpp
* **Fix annoying menu flow if you have no saves but have something unlocked**
It's slightly annoying that "start game" takes you to a new game instead of the play menu just because you have no quicksave or telesave, even though you have something unlocked like Time Trials or the Secret Lab.
Now, if you have no saves but have something unlocked, "start game" will take you to the play menu. In the play menu, "continue" will be replaced with "start", and "new game" will be missing.
Speedrunners will especially notice this because they start new runs (and thus delete their saves) all the time. And speaking of deleting saves...
* **Fix deleting `saves/tsave.vvv`, `saves/qsave.vvv`, and `saves/unlock.vvv`**
Looks like deleting the telesave and quicksave has never actually properly worked, …
> Fix menuing when having no saves but having something unlocked, fix deleting saves

- desktop_version/src/Graphics.cpp
- desktop_version/src/Graphics.h
- desktop_version/src/Logic.cpp
- desktop_version/src/Logic.h
- desktop_version/src/Render.cpp
- desktop_version/src/Render.h
- desktop_version/src/main.cpp
This is a refactor that removes the copy-pasted code in tower functions. More specifically, `towerlogic()` has been merged into `gamelogic()`, `Graphics::drawtowerentities()` has been merged into `Graphics::drawentities()`, and `towerrender()` has been merged into `gamerender()`.
This is one of several refactors that will make it easier for me to eventually make an over-30-FPS patch of this game. (I plan to keep the timestep but interpolate animations, which will require me fiddling with mostly render functions, and it's a bit annoying if I have to deal with lots of copy-pasted code...)
Also there's a bugfix for a bug I encountered during testing of this PR. …
> Merge towerrender/towerlogic into gamerender/gamelogic

- desktop_version/src/Graphics.cpp
- desktop_version/src/Graphics.h
- desktop_version/src/Render.cpp
- desktop_version/src/Script.cpp
- desktop_version/src/editor.cpp
- desktop_version/src/main.cpp
- desktop_version/src/preloader.cpp
The timers of screen effects, which are simply the flash and shake effects, are now handled outside the render functions, in the framerate loop in `main.cpp`. Furthermore, the rendering code to handle flashing and shaking if the flash or shake timer is active has been de-duplicated. Additionally, these timers are now reset in `scriptclass::hardreset()`, still tick down even if screen effects are disabled, and these screen effects only apply in `TITLEMODE` and `GAMEMODE`.
> Improve and de-duplicate screen effects handling

- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
- desktop_version/src/Input.cpp
I want exiting No Death Mode to go back to the "play modes" menu, not to the "start game" menu, because it's too far back. Also do the same if you either die or complete No Death Mode.
Also I initialized `Game::wasinintermission`, probably a good thing to initialize variables.
> Fix exiting No Death Mode being one menu too far back

- desktop_version/src/editor.cpp
Previously, if you had backgrounds disabled in accessibility options, and went to the editor and opened up the editor menu, it would be drawn straight on top of what was already there in the editor instead of being drawn on top of black. So now it's drawn on top of black.
> Fix editor menu being drawn on top of editor with BGs disabled

- desktop_version/src/Graphics.cpp
- desktop_version/src/Graphics.h
- desktop_version/src/Input.cpp
- desktop_version/src/Render.cpp
- desktop_version/src/Script.cpp
- desktop_version/src/editor.cpp
When working on my over-30-FPS patch, I noticed that the descending tower background kept getting re-drawn every frame, which is kind of inefficient. Also, it'd be better for my over-30-FPS patch if the background scrolled whatever it had (at least until the color change), because that way would be much easier to interpolate than having to redraw the background every frame.
And since the background is now scrolling instead of being redrawn, when the background *does* need to be redrawn anyway, it needs to account for `map.bscroll` to be aligned with the incoming new textures. But only for the descending background.
Also, I merged `Graphics::drawtowerbackgroundsolo()` into `Graphics::drawtowerbackground()` because it'll mean I have to copy-paste less for my over-30-FPS patch.
By submitting …
> Optimize descending tower background drawing

- desktop_version/src/Render.cpp
I had forgotten that the game flashed and did screen-shaking when you pressed ACTION to quicksave.
While testing for my over-30-FPS patch I stumbled across this.
> Render screen effects in maprender()

- desktop_version/src/Graphics.cpp
- desktop_version/src/Input.cpp
- desktop_version/src/Logic.cpp
While I was working on my over-30-FPS patch, I found out that the tower background in the credits scroll was being completely re-drawn every single frame, which was a bit wasteful and expensive. It's also harder to interpolate for my over-30-FPS patch. I'm guessing this constant re-draw was done because the math to get the surface scroll properly working is a bit subtle, but I've figured the precise math out!
The first changes of this patch is just removing the unconditional `map.tdrawback = true;`, and having to set `map.scrolldir` everywhere to get the credits scrolling in the right direction but make sure the title screen doesn't start scrolling like a descending tower, too.
After that, the first problem is that it looks like the ACTION press to speed up the credits scrolling doesn't …
> Don't re-draw credits scroll background every frame

- desktop_version/src/Map.cpp
Looks like there wasn't a `custommode` check for the spawning of crewmates based on which crewmates were rescued, but now there is.
This has gone undiscovered for a long time, mostly because people don't use the `rescued()` internal command.
> Prevent spawning crewmates/activity zones in custommode

- desktop_version/src/Game.cpp
- desktop_version/src/Logic.cpp
When you complete the game, you're now redirected to the play menu. This is because your quicksave will have been deleted so you can't go back to the summary menu.
When you complete a custom level, you'll go back to the levels list, in case you started the level from a quicksave.
> Fix the menu that you land on when you complete game or custom level

- desktop_version/src/Game.cpp
Found this because when I compiled with Clang, -Wself-assign-field was
enabled.
> Fix copy-paste bug in command-line playtesting code

- desktop_version/src/Script.cpp
Otherwise, if you died after entering a room with a horizontal or vertical warp background (but not the all-sides warp background), the warp background would be the first thing you see when going to the Game Over screen, and would then start scrolling downwards with the proper tower background coming in from the top.
This oversight seems to have always been in the game.
Was No Death Mode actually tested? Like, did anyone ever play through the entire game without dying in the Warp Zone, or even *after* completing the Warp Zone, like, ever? Seems like if someone ever did do that, this oversight would've been fixed already.
section of the credits for all of said releases, but will NOT …
> Re-draw tower background when dying in No Death Mode

- desktop_version/src/Entity.cpp
The main ones to beware of here are `entityclass::updateentities()`, `entityclass::updateentitylogic()`, and `entityclass::entitymapcollision()`. They would index out-of-bounds and thus commit Undefined Behavior if the entity was removed in `entityclass::updateentities()`.
And it would've been fine enough if I only added bounds checks to those functions. However, I decided to be a bit more defensive and play it safe, and added bounds checks to *all* functions taking in not only an entity indice, but also blocks and linecrosskludge indices. Just to ensure that nothing like this happens again.
Thanks to @AllyTally for helping debug this UB.
section of the credits for all of said …
> Add bounds checks to functions taking in entity/blocks/linecrosskludge indices

- desktop_version/src/Logic.cpp
Apparently, the game just leaves minitowermode on, which can cause issues if you're in a horizontal warping room (and not any other room type, due to how frame ordering works). This would manifest itself as a wrong warp to (20,20) because the game is trying to apply the hardcoded minitower screen transitions when it shouldn't be, and the map wrapping would just put you back at (20,20).
Closes #226.
> Add towermode checks to minitowermode screen transitions

- desktop_version/src/Entity.cpp
- desktop_version/src/Entity.h
- desktop_version/src/Logic.cpp
This PR makes it so the entity update loops in `Logic.cpp` make sure to skip over an entity if it happens to be removed by `entityclass::updateentities()`.
Otherwise, this would result in the game updating an entity twice, which isn't good. This is most noticeable in the Gravitron, where many Gravitron squares are created and destroyed at a time, and it's especially noticeable during the part near the end of the Gravitron where the pattern is two Gravitron squares, one at the top and bottom, and then two Gravitron squares in the middle afterwards. The timing is just right such that the top one of the two middle ones would be misaligned with the bottom one of the two when a Gravitron square gets outside the screen.
To do this, I changed `entityclass::updateentities()` into a `bool`, and …
> Prevent updating an entity if entityclass::updateentities() removed it

- desktop_version/src/Game.cpp
> Rename "start" option to "new game"

- desktop_version/src/editor.cpp
> Fix a copy-paste error in getLevelMetaData()

- desktop_version/src/Game.cpp
- desktop_version/src/Logic.cpp
Flag 67 seems to be a general-purpose Game Complete flag. It's used to replace the CREW option with the SHIP option on the pause screen.
Unfortunately, it gets turned on too early during Game Complete. Right when Viridian starts to teleport, you can bring up the pause screen and select the SHIP option.
It will teleport you to the ship coordinates, but still keep you in finalmode, and since the ship coordinates are at 102,111 (finalmode is only around 46,54), you'll still be stuck in Outside Dimension VVVVVV, and you've interrupted the Game Complete gamestate by switching to the teleporting gamestate. Oh, and your checkpoint is set, too, so you can't even press R. Oh and since there's no teleporter, and checkpoint setting doesn't check the sentinel value, this results in Undefined …
> Fix flag 67 turning on too early

- desktop_version/src/Logic.cpp
This is to be extra safe and ensure that your hard-earned record isn't lost at all.
In 2.2, the game didn't save your Super Gravitron record at all. It only saved it if you closed the game by quitting to the title screen and pressing ACTION on "quit game". You couldn't press Alt+F4, and you couldn't press X, you had to do it that way, otherwise your record would be lost.
In 2.3 right now, the game *will* save your `unlock.vvv` when you close the game gracefully by any means, but this still means that if it doesn't otherwise close gracefully (like, say, a crash), it won't save your record. It feels like we shouldn't rely on this catch-all saving to save Super Gravitron records. …
> Call game.savestats() when setting new Super Gravitron record

- desktop_version/src/Map.cpp
It's a bit annoying how vvvvvvman status is preserved between in-game sessions if the script command `undovvvvvvman()` isn't called, and the only thing reset is the color. This is annoying because it means you have to close the game to reset vvvvvvman.
But now it'll be reset properly. I chose to put this reset code in `mapclass::resetplayer()` instead of `scriptclass::hardreset()` because it seemed like the more appropriate place. It's where all other properties of the player are reset, after all.
> Reset vvvvvvman size in mapclass::resetplayer()

- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
- desktop_version/src/Input.cpp
- desktop_version/src/Logic.cpp
This PR fixes a few issues:
- Horizontal and vertical warp backgrounds do not get reset when returning to editor, which results in background desync if you exit playtesting into a different room in the editor. This is despite `graphics.backgrounddrawn` being set to false when you exit playtesting...
- Cutscene bars start to disappear for 1 frame when you exit playtesting, if you have them up.
- Fadeout transitions suddenly disappear for 1 frame when you exit playtesting, if there is one.
This happens because editor returning is done directly in `gameinput()`, but then after that `gamerender()` and `gamelogic()` is still ran. Thus, this results in 1 more frame of the game running after things are supposed to be reset, which means the game will still render horizontal and vertical warp …
> Fix H/V warp BGs not resetting and some 1-frame glitches when returning to editor from playtesting

- desktop_version/src/Entity.cpp
- mobile_version/src/entityclass.as
We need to replace an "or" with an "and".
My best guess for this oversight happening was because of the weird ordering. The code originally did `temp < 30` first and `temp > -30` second instead of the other way around. With the weird ordering, it becomes more natural to insert an "or" instead of an "and". So I swapped around the ordering just for good measure.
This is also fixed in the mobile version, too.
Closes #237.
> Fix 1x1 quicksand collision optimization not working

- desktop_version/src/Render.cpp
Since this is at the start of `maprender()`, the text boxes drawn by this function will get hidden behind everything else being drawn on top of it. Thus, it'll only result in a glitchy rendering where the text boxes at the very top of the screen will be rendered in the roomname space of the map screen.
To fix this rendering glitch, just remove the `drawgui()`. It's useless anyway since it's being drawn behind everything else, so no need to have it here.
> Remove graphics.drawgui() from maprender()

- desktop_version/src/Input.cpp
This change makes it so that in in-editor playtesting, the code to handle pressing ENTER on activity zones is the same code to handle pressing ENTER on activity zones in `custommodeforreal`.
This removes the need to copy-paste code and adapt it to in-editor playtesting. And thus, this fixes an editor artifact where you can press ENTER on activity zones while doing the death animation, even though you can't do that when you're playing custom levels normally.
> Don't duplicate activity zone handling code in playtesting

- desktop_version/src/FileSystemUtils.cpp
Previously:
- Linux: `xdg-open`
- Everything else: `open`
Now:
- macOS and Haiku: `open`
- Everything else: `xdg-open`
This is all according to [a comment](/TerryCavanagh/VVVVVV/pull/203#issuecomment-616222350) by @leo60228 in PR #203.
> Fix FILESYSTEM_openDirectory command used on Haiku and *BSD

- desktop_version/src/FileSystemUtils.cpp
Whenever I compile with `-O2`, GCC gives me a warning that the return value of `fread()` is being ignored. Which is a fair point, it means that we're not doing proper error handling if something goes wrong. But I'm also going to check the return value of `fwrite()` for good measure.
I believe that checking that this number is not equal to length is the way to catch all errors and output an error message accordingly. I didn't use `ferror()` or `feof()` mostly because I think it takes up too much code. Also an error from `fwrite()` only says "Warning" because I don't think there's much we can do if we don't fully write all bytes to the intended file.
Also some indentation fixes. …
> Handle return values from fread() and fwrite() in PLATFORM_copyFile()

- desktop_version/src/Game.cpp
For some reason (probably a copy-paste error), this XML tag gets `atoi()` called on it before being assigned to `Game::hardestroom`. And only when loading a quicksave, at that.
This would result in `Game::hardestroom` being set to an empty string, which if you kept until Game Complete, would end up rendering as a single null byte (if you even have a font face for said null byte).
I'm not sure how this error compiles in the first place, but whatever.
> Fix <hardestroom> having atoi() called on it when loading quicksave

- desktop_version/src/Game.cpp
This fixes a bug where if you had the play menu in a state where the first option was "new game", then kept playing up until a quicksave or telesave was created, then quit to the menu, the menu wouldn't update. Thanks to KSSBrawl for reporting this bug to me: https://cdn.discordapp.com/attachments/708567577978470410/712060797924147240/untitled.webm
> Re-create menu if returntomenu() is given current menu

- desktop_version/src/Input.cpp
Just fixing things that were a bit inconsistent.
- **Make all gamemode starts play a Viridan squeak**
It's always personally irked me that the only time you get a Viridian squeak when pressing ACTION to start fading out and going in-game is when you start playing a custom level. And that's only if you don't have a quicksave.
To make things more consistent (and to add more polish to the game), I made sure there was a `music.playef(11)` every time `game.mainmenu` gets set. I also made sure that this doesn't result in double-squeaking, i.e. `music.playef(11)` being called twice, which can be very loud and ear-hurting.
- **When toggling Flip Mode, only flash and shake screen when enabling it**
It's a bit inconsistent how every time you toggle flip mode, it does this flashing and shaking (and …
> Fix a few menu inconsistencies

- desktop_version/src/Entity.cpp
- desktop_version/src/Map.cpp
- desktop_version/src/Script.cpp
Instead of using somewhat-obtuse for-loops to initialize or reset these vectors, it takes up less lines of code and is clearer if we use `std::vector::resize()` and `std::vector::clear()` instead.
> Simplify inits/resets in entityclass/mapclass

- desktop_version/src/Game.cpp
This fixes being able to trigger Undefined Behavior by pressing R when not in-bounds in the Outside Dimension VVVVVV map, usually when you're falling upwards towards Game Complete.
I also put bounds checks on normal `roomdeaths` for good measure. You'll never know when you need it.
> Add bounds checks to roomdeaths and roomdeathsfinal

- desktop_version/src/main.cpp
Blackout mode doesn't work properly, because the game doesn't actually black out the screen, it merely stops drawing things. Oh and only some things at that, some other things are still drawn. This results in a freeze-frame effect, which is apparently fixed in the Switch version. Custom levels utilize this freeze-frame effect, so it's a bit annoying that the "Game paused" screen draws on top of it and makes it so that the freeze-frame freezes on "Game paused" until blackout is turned off.
So I'm making it so that "Game paused" doesn't get drawn in blackout mode. However it will still do `graphics.render()` because otherwise it'll just result in a black screen. …
> Don't draw "Game paused" when in blackout mode

- desktop_version/src/editor.cpp
For some reason, the only way to get a cyan crewmate is by cycling through an already-existing crewmate by keeping left-clicking on it. This is because when you cycle through crewmate colors, the allowed colors are 0-5, but when you place down a crewmate, it picks a random color from 1-5, which seems to be a bit consistent.
So placing and cycling a crewmate now use the same color ranges.
> Allow crewmate to be cyan when initially placing it down

- desktop_version/src/Script.cpp
Resetting `game.activeactivity` fixes triggering Undefined Behavior if you quit to the menu while standing inside an activity zone, and then re-entered the game. Resetting `game.act_fade` also fixes the activity zone prompt fadeout that happens once the above segfault is fixed.
Don't worry, other activity-zone like variables such as teleporter prompts and trophy text are already covered. `obj.trophytext` is reset in `scriptclass::hardreset()`, too, and `game.readytotele` is reset every time `mapclass::gotoroom()` is called, and `mapclass::gotoroom()` is called every time a gamemode is started.
for these …
> Reset game.activeactivity and game.act_fade in scriptclass::hardreset()

- desktop_version/src/Game.cpp
It's a bit bad for the compiler if you have lots of function calls with hardcoded strings in them, because every time the compiler encounters one, it has to go out of its way to find a dedicated storage location for the string, which is really inefficient. And it does this inefficient thing every single time.
There's not much of an impact compiling these lists, but I at least want to encourage this sort of code style, instead of the `push_back(string)` style, in case we ever need a hardcoded array of things later.
> Refactor superpatrons/patrons/githubfriends to not push_back(string)

- desktop_version/src/Map.cpp
- desktop_version/src/editor.cpp
- desktop_version/src/editor.h
When the game loads a room in a custom level, previously it would load the tilemap of that room into `ed.swapmap`, and then `mapclass::loadlevel()` would manually go through each element in `ed.swapmap` to set each tile in `contents`. Why do that, when you can just return the vector from `editorclass::loadlevel()` and set it directly? `ed.swapmap` is really unnecessary.
> Remove unnecessary middleman ed.swapmap

- desktop_version/src/Script.cpp
Otherwise, it would end up indexing a vector out-of-bounds, which is UB and causes a segfault, too. This is used in some constructs like
say(-1)
<internal command>
where the text contents don't matter, only that a text box shows up.
>  Fix using `speak`/`speak_active` without a `text` beforehand

- desktop_version/src/Scripts.cpp
- desktop_version/src/TerminalScripts.cpp
Although it's not an issue, this should minimize the stack footprint of calling `scriptclass::load()`, especially if it goes down to calling `scriptclass::loadcustom()` or `scriptclass::loadother()`.
> Statically allocate built-in scripts as well

- desktop_version/src/Game.cpp
Very small change. `Game.cpp` relied on other headers importing `script.h`, which is not the case when building with `CUSTOM_LEVEL_SUPPORT=DISABLED`
> Fix build with CUSTOM_LEVEL_SUPPORT=DISABLED

- desktop_version/src/Script.cpp
This PR adds bounds checks to those commands in case `say()`/`reply()` asks for more lines than there are left in the all-script-lines buffer (not just the current script, so in order for it to segfault your script has to be last in the all-script-lines vector), and in case `text()` asks for more lines than there are in the rest of the rest of the parsed internal script.
Also some small refactors.
> Fix vector indexing out-of-bounds if say()/reply()/text() asks for more lines than there are

- desktop_version/CMakeLists.txt
- desktop_version/src/Network.c
I think it's a bit silly to always include the Steam and GOG APIs whenever we build VVVVVV, since the only time they'll ever be used is in a live build and not a dev build.
So now Steam and GOG are disabled by default. If you want them, you'll need to add `-DSTEAM=ON` or `-DGOG=ON` respectively at CMake time.
> Allow for conditional building of Steam and GOG APIs

- desktop_version/src/editor.cpp
- desktop_version/src/editor.h
Previously, the editor would always say it saved or loaded a level, even if it was not successful. For example, because a file to load does not exist, a file to save has illegal characters in its name or the
name is too long to be stored. Now failure is reported. Also, when quitting the editor and saving before quitting is unsuccessful, the editor will abort quitting.
> Add editor saving/loading error messages

- desktop_version/src/Graphics.cpp
- desktop_version/src/Script.cpp
- desktop_version/src/editor.cpp
- desktop_version/src/editor.h
- desktop_version/src/main.cpp
Previously, loading a level with assets and then loading the main game would retain the assets; this has been fixed. Additionally, custom font files are now loaded properly. Finally, you can now load a level as a .zip file, with the .vvvvvv and `graphics/` (etc) folders at the root of the archive.
> Fixed some custom asset bugs, added .zip level loading

- desktop_version/src/Game.cpp
- desktop_version/src/Script.cpp
This resulted in two bugs:
1. Custom assets would not be unmounted when quitting to the menu.
2. Custom assets would be unmounted when playtesting a level.
The solution is to unmount assets in Game::quittomenu() instead.
> Fix custom assets being unmounted in scriptclass::hardreset()

- desktop_version/src/Music.cpp
- desktop_version/src/SoundSystem.cpp
- desktop_version/src/SoundSystem.h
This merges the commits missed by @Fussmatte necessary for music to be properly reloaded. Partially fixes #271.
> Fix music reloading

- desktop_version/CMakeLists.txt
This enforces the C++03 standard for people making pull requests who may not realize their fancy features are too new and shouldn't be used (_\*cough*_, _\*cough*_, @leo60228).
I did some internet searching and this is what I got from this page: https://crascit.com/2015/03/28/enabling-cxx11-in-cmake/
CI will fail because of #273 (i.e. it's Leo's fault).
> Add C++98/C++03 standards declaration to CMakeFiles.txt

- desktop_version/src/Graphics.cpp
- desktop_version/src/Graphics.h
- desktop_version/src/Script.cpp
- desktop_version/src/Script.h
- desktop_version/src/Scripts.cpp
- desktop_version/src/TerminalScripts.cpp
- desktop_version/src/editor.cpp
- desktop_version/src/editor.h
This PR refactors custom level scripts to no longer be stored in one giant vector containing not only every single script name, but every single script's contents as well. More specifically, `scriptclass::customscript` has been converted to an `std::vector<Script> scriptclass::customscripts` (note the extra S), and a `Script` is just a struct with an `std::string name` and `std::vector<std::string> contents`.
This is an improvement in both performance and maintainability. The game no longer has to look through script contents in case they're actually script names, and then manually extract the script contents from there. Instead, all it has to do is look for script names only. And the contents are provided for free. This results in a performance gain.
Also, the old system resulted in lots …
> Refactor custom scripts to not be stored in one giant vector containing every single script's lines

- desktop_version/src/editor.cpp
2.2 and earlier had this god-awful thing where it put the closing tag of an edentity onto the next line, and then kept the indentation the same. This requires parsing the XML in an extremely specific way (i.e. ignoring the whitespace) so the newline and indentation isn't taken as part of the actual contents of the tag.
2.3 removed this awful whitespace entirely to make it easier on parsers. When I tested #270, I tested against a 2.3 re-save of Dimension Open and diffed the two, because I thought testing against the original version of the level would result in a bunch of noise I didn't want due to the whitespace change. Well, I did exactly what I intended, and ended up ignoring the whitespace change so much that levels saved in this stupid format ended up getting broken.
Luckily, we can …
> Fix loading levels saved with 2.2 or earlier

- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
- desktop_version/src/Graphics.h
- desktop_version/src/Render.cpp
- desktop_version/src/Script.cpp
- desktop_version/src/editor.cpp
- desktop_version/src/editor.h
- desktop_version/src/main.cpp
A few months ago, I added ghosts to the VVVVVV: Community Edition editor. I was told recently I should think about upstreaming it, and with Terry saying go ahead I finally ported them into VVVVVV. There's one slight difference however--you can choose whether you have them or not in the editor's settings menu. They're off by default, and this is saved to the save file.
Anyway, when you're playtesting, the game saves the players position, color, room coordinates and sprite every 3 frames. The max is 100, where if it tries to add more, the oldest one gets removed.
When you exit playtesting, the saved positions appear one at a time, and you can use the Z key to speed it up.
[Here's a video of them in action.](https://o.lol-sa.me/4H21zCv.mp4) …
> Add editor ghosts

- desktop_version/src/Entity.cpp
- desktop_version/src/Game.cpp
- desktop_version/src/Input.cpp
- desktop_version/src/Logic.cpp
- desktop_version/src/Map.cpp
- desktop_version/src/Render.cpp
- desktop_version/src/Script.cpp
There are three functions that return a sentinel value of -1 if the entity it is looking for doesn't exist: `obj.getteleporter()`, `obj.getplayer()`, and `obj.getcompanion()`. There are many places in the code that blindly use the return values from those functions without checking that it isn't -1 first, and could thus end up indexing out-of-bounds, which is bad bad Undefined Behavior.
So to fix the potential for UB, this PR adds if-guards to all of those cases.
> Put if-guards around usages of entity-getting functions whose return values can be out-of-bounds

- desktop_version/src/Music.cpp
- desktop_version/src/Script.cpp
Continuing from #280, another potential source of out-of-bounds indexing (and thus, Undefined Behavior badness) comes from script commands. A majority of them don't do any input validation at all, which means the potential for out-of-bounds indexing and segfaulting in custom levels. So it's always good to add bounds checks to them.
Interesting note, the only existing command that has bounds checks is the `flag()` command. That means you can't turn out-of-bounds flags on or off. But there's no bounds checks for `ifflag()`, or `customifflag()`, which means you *can* index out-of-bounds with those commands! That's a bit bad to do, so.
Also, I decided to add the bounds checks for `playef()` at the `musicclass::playef()` level, instead of just the level of the `playef()` command. I don't know …
> Add bounds checks to script commands that didn't have them

- desktop_version/src/UtilityClass.cpp
So there were two problems with using `std::isdigit()`:
- It needs to be properly included with `#include <cctype>`. This has only been reported as an issue by one person, but after looking it up, all the relevant authorities *do* say you have to `#include <cctype>`. Which is puzzling, because today is the first time I've ever heard of this being an issue, and no one else has ever had a problem with it.
(A small hint I noticed: it looks like `tinyxml2.h` has `#include <cctype>`. So I guess the game was relying on TinyXML-2 having that include. However this doesn't fully explain the mystery, because where was the game getting that include from before TinyXML-2?)
- Undefined Behavior could happen if the argument passed to it can't be parsed as an `unsigned char`. This means that not all …
> Fix usage of std::isdigit() in UtilityClass.cpp

- desktop_version/src/KeyPoll.cpp
- desktop_version/src/KeyPoll.h
- desktop_version/src/Screen.cpp
- desktop_version/src/Screen.h
- desktop_version/src/main.cpp
Just wanted to put to a stop a somewhat huge code smell that existed in 2.2, before it starts again.
`gameScreen` is now `extern`ed and moved off the stack. The constructor has been moved to a delayed `init()` function now.
> Remove having to pass around gameScreen in function arguments

- desktop_version/src/Entity.cpp
- desktop_version/src/Entity.h
Removing the player entity has all sorts of nasty effects, such as softlocking the game because many inputs require there to be a player present, such as opening the quit menu.
The most infamous glitch to remove the player entity is the Gravitron Fling, where the game doesn't see a gravity line at a specific y-position in the current room, and when it moves the bottom gravity line it moves the player instead. When the gravity line gets outside the room, it gets destroyed, so if the player gets dragged outside the room, they get destroyed, too. (Don't misinterpret this as saying anytime the player gets dragged outside the room, they get destroyed - it's only the Gravitron logic that destroys them.)
Also, there are many places in the code that use entity-getting functions that have a …
> Prevent removing the player entity

- desktop_version/src/Entity.cpp
- desktop_version/src/Graphics.cpp
- desktop_version/src/UtilityClass.h
- desktop_version/src/editor.cpp
This PR prevents an indexing out-of-bounds segfault/UB if an entity has an out-of-bounds `drawframe`, if tile numbers are out-of-bounds, if an out-of-bounds image or teleporter is requested to be drawn, or if an out-of-bounds font index is requested to be drawn.
Also I cleaned up some more duplicated Flip Mode code. And added a convenient `INBOUNDS` macro.
> Prevent attempts to index things out-of-bounds when drawing various things

- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
This prevents the game from being saved if you manage to trigger a `Game::savetele()` during a "special" gamemode (like if you use the Gravitron out-of-bounds glitch when replaying Intermission 2, then go to Game Complete that way).
> Add special gamemode checks to Game::savetele() and Game::savequick()

- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
- desktop_version/src/Graphics.cpp
- desktop_version/src/Graphics.h
- desktop_version/src/Map.cpp
- desktop_version/src/Map.h
- desktop_version/src/Otherlevel.h
- desktop_version/src/Tower.h
The only class that actually needs its i/j/k kept is scriptclass, because some custom levels rely on it for creating custom activity zones. So I haven't touched that.
Other than that, there's no chance that anything important relies on i/j/k in any other class. For that to be the case, it would have to use i/j/k without initializing it beforehand, and that can simply be detected by removing the attribute from the header file and seeing where the compiler complains. And the compiler complains only about cases where it's initialized first. (Note that due to this check, I *haven't* removed Graphics's `m` as it precisely does exactly this, using it without initializing it first.)
Interestingly enough, otherlevelclass and towerclass have unused i/k variables for whatever reason.
By submitting …
> Remove i/j/k attributes from classes that don't need them

- desktop_version/src/Game.cpp
If your time was exactly 60 seconds, it would display 00:60 instead of 01:00.
> Fix time trial result displaying 00:60 instead of 01:00

- desktop_version/src/UtilityClass.cpp
- desktop_version/src/UtilityClass.h
- desktop_version/src/editor.cpp
This adds support for hex entities in level metadata.
> Support hex entities in metadata

- desktop_version/src/Graphics.cpp
The flashy color of the elephant can be hard on people's eyes, especially if they're the type who want screen effects disabled because they might have epilepsy. The elephant takes up a good 3/4ths of the screen, you know. If screen effects are disabled, the elephant will use color 22, which is a neutral gray.
I'm only adding this because the VVVVVV speedrun mods (@tzann, @mohoc) invalidate all runs that have the elephant texture removed, even though many people would be looking at a potentially epilepsy-inducing image many times a day grinding 100% speedruns. (Imo, their justification for this is flimsy at best.) …
> Make elephant not be flashy if screen effects are disabled

- desktop_version/src/Entity.cpp
If a trinket or crewmate ID is out-of-bounds, it will not be created. This is not only because the `collect`/`customcollect` check in `entityclass::createentity()` would then be out-of-bounds, but also touching it would also be out-of-bounds, too.
Display trinkets will always be created if the ID is out-of-bounds. Apparently some people (@AllyTally) have been creating display trinkets with IDs of -1 in order to get a display trinket that always shows up, which is rather horrifying. But it makes sense, there's a lot more nonzero int values than there are the amount of int values that are zero, so it's fairly likely that the `collect` check will always come up to be true (nonzero). Also, it's more useful to be able to have a display trinket that always shows up without having to collect a …
> Prevent out-of-bounds indexing with trinket/crewmate IDs

- desktop_version/src/Map.cpp
- desktop_version/src/Script.cpp
Looks like duplicate player entities persisting across rooms is a semi-useful feature used by some levels. Still, though, it's a bit of a nuisance to have duplicate player entities persisting across game sessions. And levels can't rely on this persistence anyway, anyone could just close the game and re-open it to get rid of the duplicate entities regardless.
> Only remove duplicate player entities in scriptclass::hardreset()

- desktop_version/src/editor.cpp
This is really awful, but there's not much we can do.
TinyXML-2 no matter what will never stop on newlines, so without changing the XML parser, this is the best we can do - just remove the `"\n            "` (that's a linefeed plus exactly 12 spaces) if it appears at the end of the contents of an edentity tag.
Also a giant comment for good measure.
> Revert old fix, hardcode fix for next-line </edentity>

- desktop_version/src/Game.cpp
- desktop_version/src/Logic.cpp
- desktop_version/src/editor.cpp
This fully fixes #271.
The cause of the first issue (menu music silence) was wrong frame ordering, the cause of the second issue was a missing `FILESYSTEM_unmountassets()` in two places. (Also, I made sure to avoid the first issue and checked my frame ordering carefully, as well as tested it.)
> Fix assets unmounting causing main menu music silence, and assets not being unmounted when returning from editor or credits screen

- desktop_version/src/editor.cpp
This was added by Info Teddy in VCE, but their message in #267 says it should be upstreamed, so here we are.
This adds support to switch to the gray variant of the Warp Zone tileset in the editor. This was already possible by editing the level file, but now it should just be easier to do.
> Allow using Warp Zone gray tileset in editor

- desktop_version/src/editor.cpp
- desktop_version/src/editor.h
Adds the 7x7, 9x9, horizontal and vertical subtools from VED/VVVVVV: Community Edition to vanilla.
These are just like the default vanilla subtools for placing/removing walls/background, except larger.
There's a few gifs on [this page](https://vsix.dev/vce/#new_tool_sizes), which explains what they are and why they were added to VVVVVV: Community Edition.
This was requested in #267.
> Add 7x7, 9x9, full horizontal and vertical brush sizes

- desktop_version/src/editor.cpp
`__STDC_FORMAT_MACROS` is needed in order for the `SCNx32`/`SCNu32` in `find_tag()` to be compiled correctly on older `glibc`s, and `_POSIX_SOURCE` is needed in order for them to work on MinGW (when compiling C++98), apparently. I put ifndef guards around both just to be sure, because I got a warning about redefining `_POSIX_SOURCE` from my compiler.
Fixes #300.
> Add define __STDC_FORMAT_MACROS, _POSIX_SOURCE

- desktop_version/src/Game.cpp
This prevents being able to "roll over" the amount of minutes to 0 (by simply waiting for the timer to tick past one hour) and being able to get a result of 00:13 when your result is really 01:00:13 or 03:00:13.
By looking only at the minutes, the game would read 01:00:13 as 00:13 instead. So simply add the amount of hours to the time trial result.
> Account for hours when calculating time trial result time

- desktop_version/src/Ent.cpp
- desktop_version/src/Ent.h
- desktop_version/src/Entity.cpp
- desktop_version/src/Entity.h
- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
- desktop_version/src/Graphics.cpp
- desktop_version/src/Graphics.h
- desktop_version/src/GraphicsUtil.cpp
- desktop_version/src/GraphicsUtil.h
- desktop_version/src/Input.cpp
- desktop_version/src/Logic.cpp
- desktop_version/src/Map.cpp
- desktop_version/src/Map.h
- desktop_version/src/Render.cpp
- desktop_version/src/Textbox.cpp
- desktop_version/src/Textbox.h
- desktop_version/src/editor.cpp
- desktop_version/src/editor.h
- desktop_version/src/main.cpp
- desktop_version/src/preloader.cpp
- desktop_version/src/preloader.h
VVVVVV is a game that runs at 1000/34 frames per second, which is approximately 29.4 frames a second, which is close to, but not quite, 30 frames a second. This odd number comes from the fact that the amount of times it takes for each frame is coded to be 34 milliseconds, and not 33.333333333... milliseconds.
This pull request unlocks VVVVVV's framecap of 1000/34 FPS. It does this in such a way that the underlying engine still runs at an actual framerate of 1000/34 FPS (which we should be calling tickrate now), and in between each actual frame we just draw what the frames in between each frame *should* be, using something called "linear interpolation". So now the game will visually run at the same rate as your monitor (my monitor is 60hz, I'm not a true gamer :( &#x200b; &#x200b; &#x200b; …
> Make the game (visually) run at framerates above ~30 FPS

- desktop_version/src/Graphics.cpp
- desktop_version/src/KeyPoll.cpp
- desktop_version/src/Screen.cpp
- desktop_version/src/Screen.h
- desktop_version/src/main.cpp
Ugh, this is terrible and stupid and I hate myself for it.
Anyway, since the SDL2 VSync hint only applies when the renderer is created, we have to re-create the renderer whenever VSync is toggled. However, this also means we need to re-create `m_screenTexture` as well, *and* call `ResizeScreen()` after that or else the letterbox/integer modes won't be applied.
Unfortunately, this means that in `main()`, `gameScreen.init()` will create a renderer only to be destroyed later by `graphics.processVsync()`. There's not much we can do about this. Fixing this would require putting `graphics.processVsync()` before `gameScreen.init()`. However, in order to know whether the user has VSync set, we would have to call `game.loadstats()` first, but wait, we can't, because `game.loadstats()` mutates …
> Work around stupid and annoying SDL2 VSync hint bug, and don't extern gameScreen (use *graphics.screenbuffer instead)

- desktop_version/src/editor.cpp
- desktop_version/src/editor.h
- desktop_version/src/main.cpp
These functions aren't needed in a `NO_EDITOR` build, so it's useful to reduce the binary size this way.
> Add '#if !defined(NO_EDITOR)' guards around editorinput/render/logic

- desktop_version/src/FileSystemUtils.cpp
- desktop_version/src/FileSystemUtils.h
- desktop_version/src/Game.h
- desktop_version/src/UtilityClass.cpp
- desktop_version/src/UtilityClass.h
- desktop_version/src/editor.cpp
- desktop_version/src/main.cpp
If the game was loading a level file from STDIN, and that level file had custom assets, they wouldn't be loaded in. This is because of the fundamental problem where if the game loads a level file from STDIN, it doesn't know the actual filename of the level. To fix this, it needs to be able to be provided the name of the actual filename, so it can load the assets.
After this is merged, a trivial amount of work (compared to this patch) just needs to be done on Ved's end.
Also cleaned up and fixed some filesystem/CLI code (read the commits).
Anyone who wants to test this, but doesn't know how to or want to modify Ved to make it use `-playassets`, but knows how to use the command-line... don't abuse `cat`! I went out of my way to figure out how to avoid abusing `cat`. The command I used was: …
> Add `-playassets` command-line option, and clean up and fix filesystem and command-line arguments code

- desktop_version/src/Input.cpp
It's always been a bit annoying that if you're in the teleporter menu, you can't press Escape to go to the "Do you want to quit?" menu.
> Add being able to press Esc to go to quit menu from teleporter menu

- desktop_version/src/Graphics.cpp
- desktop_version/src/Graphics.h
- desktop_version/src/Render.cpp
`maprender()` has lots of copy-pasted code, so I thought I'd start to de-duplicate at least some of it.
> De-duplicate menu tab name printing and custom level CREW page printing

- desktop_version/README.md
Only the 2.2 version has these problems, so you don't need to worry about this section when compiling 2.3.
> Add note to README about "compiler quirks" only applying to 2.2

- desktop_version/src/main.cpp
In my previous PR, I wrongly assumed that I could just replace the `i` handling code of those options with an `i++;` at the beginning, and thus I could put all blocks' `i++;` into `ARG_INNER()`. Well I was wrong, because the code was written the original way for a reason, namely that we still need `i` to point to the -playx/y/rx/ry/gc/music argv so we can re-compare which argument led us into this code block.
> [HOTFIX] Fix -playx/y/rx/ry/gc/music looking at wrong argument

- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
- desktop_version/src/Graphics.cpp
- desktop_version/src/Graphics.h
- desktop_version/src/Input.cpp
- desktop_version/src/Logic.cpp
- desktop_version/src/Logic.h
- desktop_version/src/Map.h
- desktop_version/src/Render.cpp
The Esc menu is now overhauled. There are four options: "return to game", "quit to menu", "graphic options", and "game options". It's always been a bit annoying how you had to actually exit the game in order to change some options, which necessitated having to quicksave beforehand, and then you have to back into the level, etc.
"return to game" just closes the menu. You can also press Esc again to close it (you couldn't do this before). "quit to menu" takes you to the old quit menu, where it gives you the option of either "no, keep playing" or "yes, quit to menu", and you can also press Esc to return back to the new menu.
"graphic options" and "game options" take you to the graphic options and game options menus respectively. I made sure you couldn't toggle invincibility or slowdown when …
> Overhaul the menu brought up by pressing Escape

- desktop_version/src/Input.cpp
This fixes a corner case where using gamestate 82 from the editor would put you in a softlock because it would return to the editor settings menu, which only functions in EDITORMODE and results in a softlock in TITLEMODE.
> Use game.returntomenu(Menu::timetrials) instead of game.returnmenu() in Menu::timetrialcomplete3

- desktop_version/src/Script.cpp
It's unnecessary to re-draw the background if you're modifying the warp direction of some other room.
> Make warpdir only re-draw background if targeted room is current room

- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
- desktop_version/src/KeyPoll.cpp
- desktop_version/src/KeyPoll.h
- desktop_version/src/Music.cpp
- desktop_version/src/Music.h
- desktop_version/src/Script.cpp
- desktop_version/src/main.cpp
This patch makes it so that resumemusic and musicfadein actually work properly. Namely, if you use stopmusic or musicfadeout, the position where the song ended will be remembered, and using resumemusic or musicfadein will start the song from that position again. Also there's some miscellaneous cleanups I did along the way.
> Fix resumemusic and musicfadein not working

- desktop_version/src/Game.cpp
> Fix Game::anything_unlocked() always evaluating to true

- desktop_version/src/Graphics.cpp
The tilesheets in question are `font.png`, `tiles.png`, `tiles2.png`, `tiles3.png`, `entcolours.png`, `teleporter.png`, `sprites.png`, and `flipsprites.png`.
This patch removes the hardcoded dimensions when scanning the tilesheets, because it's simpler that way. It also de-duplicates it so it isn't a bunch of copy-paste, by using macros. (I had to use macros because it was the easiest way to optionally pass in some extra code in the innermost for-loop.)
Also, if the dimensions of a scanned tilesheet aren't exactly multiples of the dimensions of the tile unit for that given tilesheet (e.g. if the dimensions of a scanned tiles.png are not exact multiples of 8), then an `SDL_SimpleMessageBox` will show up with the error message, a `puts()` of the error message will be called, and the program …
> Refactor, de-duplicate, and clean up tilesheet processing

- desktop_version/src/Graphics.cpp
It seems to be a bit bad to blindly use `m` without checking it. In fact, this has caused a few segfaults already, actually.
> Add bounds check to textbox functions that use `m`

- desktop_version/src/Entity.cpp
- desktop_version/src/Game.cpp
- desktop_version/src/Logic.cpp
- desktop_version/src/Map.cpp
- desktop_version/src/Map.h
- desktop_version/src/Script.cpp
- desktop_version/src/Script.h
- desktop_version/src/main.cpp
This patch is very kludge-y, but at least it fixes a semi-noticeable visual issue in custom levels that use internal scripts to spawn entities when loading a room.
Basically, the problem here is that when the game checks for script boxes and sets `newscript`, `newscript` has already been processed for that frame, and when the game does load a script, `script.run()` has already been processed for that frame.
That issue can be fixed, but it turns out that due to my over-30-FPS game loop changes, there's now *another* visible frame of delay between room load and entity creation, because the render function gets called in between the script being loaded at the end of `gamelogic()` and the script actually getting run.
So... I have to temporary move `script.run()` to the end of `gamelogic()` …
> Fix the two-frame-delay when entering a room with an "init" script

- desktop_version/src/Entity.cpp
- desktop_version/src/Graphics.cpp
- desktop_version/src/GraphicsUtil.cpp
- desktop_version/src/GraphicsUtil.h
The only reason why gray Warp Zone entities were green originally was because there is a giant concatenated list of tileset+tilecol combinations, and by using tileset 3 tilecol 6 you're using the entry of tileset 4 tilecol 0, which is the green Ship tileset.
So without interfering with the green Ship tileset's entry, I've decided that the best thing to do is to just add special cases. The enemy color was easy enough to fix. The platform color was also easy to fix. However, there exist no existing textures for gray conveyors, so at that point I decided to just tint the existing green one gray, and then I did the same for platforms.
section of the credits for all of said releases, but …
> Fix enemies, platforms, and conveyors in Warp Zone gray tileset not being colored gray

- desktop_version/src/Map.cpp
The two-frame delay can be utilized to trigger a glitch that spawns entities in the wrong room.
The width of the player can be changed by using the Gravitron OoB glitch. It will not be reset if the game is in glitchrunner mode.
> Disable two-frame delay fix in glitchrunner mode, and reset width of player if not in glitchrunner mode

- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
- desktop_version/src/Render.cpp
Centiseconds won't be saved to any save file or anything. This is just to make speedrunning a bit more competitive, being able to know the precise time of a time trial or full game run.
The time trial par time on the result screen always has ".99" after it. This is basically due to the game comparing the number of seconds to the par number of seconds using less-than-or-equal-to instead of simply less-than.
> Display centiseconds on time trial result and Game Complete

- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
- desktop_version/src/Graphics.cpp
- desktop_version/src/Graphics.h
- desktop_version/src/Render.cpp
- desktop_version/src/editor.cpp
All menus had a hardcoded X position (offset to an arbitrary starting point of 110) and a hardcoded horizontal spacing for the "staircasing" (mostly 30 pixels, but for some specific menus hardcoded to 15, 20 or something else). Not all menus were centered, and seem to have been manually made narrower (with lower horizontal spacing) whenever text ran offscreen during development.
This system may already be hard to work with in an English-only menu system, since you may need to adjust horizontal spacing or positioning when adding an option. The main reason I made this change is that it's even less optimal when menu options have to be translated, since maximum string lengths are hard to determine, and it's easy to have menu options running offscreen, especially when not all menus are checked …
> Make menus automatically centered and narrowed

- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
There were a few problems with the old way of doing things:
1. Level stats were an ad-hoc object. Basically, it's an object whose attributes are stored in separate arrays, instead of being an actual object with its attributes stored in one array.
2. Level filenames with pipes in them could cause trouble. This is because the filename attribute array was stored in the XML by being separated by pipes.
3. There was an arbitrary limit of only having 200 level stats, for whatever reason.
To remedy this issue, I've made a new struct named `CustomLevelStat` that is a proper object. The separate attribute arrays have been replaced with a proper vector, which also doesn't have a size limit.
For compatibility with versions 2.2 and below, I've kept being able to read the old format. This only happens …
> Refactor how custom level stats are stored, read, and written

- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
- desktop_version/src/Input.cpp
- desktop_version/src/KeyPoll.cpp
- desktop_version/src/Render.cpp
It's sometimes unwanted by people, and it's unwanted enough that there exist [instructions to hexedit the binary to remove it](
https://distractionware.com/forum/index.php?topic=3247.0).
Fun fact, the unfocus pause didn't exist in 2.0.
> Add being able to disable unfocus pause

- desktop_version/src/main.cpp
The Alt+Enter Glitch is a funny glitch where if you press any toggle fullscreen keybind during a cutscene, Viridian will stop moving (if they're being moved by a `walk()`) and ACTION will start being held down for them. Meaning in most cases you can interrupt a walk and flip at the same time.
This can obviously break cutscenes if a casual just wants to toggle fullscreen, so I'm fixing it. But it will be unfixed in glitchrunner mode in case you want to glitch out custom levels (I know I do).
More information on the Alt+Enter Glitch is available here: https://gitgud.io/infoteddy/vvvvvv-knowledge/blob/master/bugs/bugs.md#the-altenter-glitch
(The page is a bit outdated, some bugs have been fixed in 2.3 already.)
example, a 2.3 update on Steam …
> Fix Alt+Enter Glitch if not in glitchrunner mode

- desktop_version/src/Game.cpp
- desktop_version/src/Input.cpp
- desktop_version/src/Render.cpp
- desktop_version/src/Screen.cpp
- desktop_version/src/Screen.h
If you want your game window to simply be exactly 320x240, or 640x480, or 960x720 etc. then it's really annoying that there's no easy way to do this (to clarify, this is different from integer mode, which controls the size of the game *inside* the window). The easiest way would be having to close the game, go into `unlock.vvv`, and edit the window size manually. VCE has a 1x/2x/3x/4x graphics option to solve this, although it does not account for actual monitor size (those 1x/2x/3x/4x modes are all you get, whether or not you have a monitor too small for some of them or too big for any of them to be what you want).
I discussed this with flibit, and he said that VCE's approach (if it accounted for monitor size) wouldn't work on high-retina displays or high DPIs, because getting the actual …
> Add "resize to nearest" graphics option

- desktop_version/src/Game.cpp
- desktop_version/src/Input.cpp
- desktop_version/src/Render.cpp
Flip Mode will now be in the game options menu if either:
1. You're playing the M&P version.
2. You have it unlocked and you came here from the in-game pause screen.
This is because if you're playing M&P, you'd have to close the game, edit `unlock.vvv`, and re-launch the game to toggle Flip Mode, since there's no other way to do so. And if you're playing the full version, you'd have to save and exit your session in order to toggle Flip Mode.
> Add Flip Mode to game options if in M&P or in-game menu and unlocked

- desktop_version/src/Graphics.cpp
- desktop_version/src/Graphics.h
- desktop_version/src/Render.cpp
The game for some reason had this thing where it would not draw the diagonal background tiles if you had animated backgrounds turned off. Which is weird, because spikes with that background are still drawn as spikes with that background. And also, it doesn't do this for any of the tower hallway rooms, which is inconsistent.
Better to simplify the logic in `Render.cpp` anyways by removing `graphics.drawtower_nobackground()` and making it really clear what exactly we'll do if backgrounds are turned off. ("Aren't we already not drawing the background? What's this `_nobackground()` function for?")
for these …
> Don't selectively undraw tiles in towers if backgrounds are off

- desktop_version/src/Game.cpp
- desktop_version/src/Map.cpp
- desktop_version/src/Map.h
- desktop_version/src/Render.cpp
- desktop_version/src/Script.cpp
This patch makes the `showtrinkets()` command work in player levels, as in trinkets will now show up on the minimap if you run that command. Some work has to be done, notably getting all the trinkets into the `shinytrinkets` vector, as well as drawing them on the minimap and accounting for different minimap sizes. But it works now.
> Make showtrinkets() command work in levels

- desktop_version/src/Script.cpp
For whatever reason, not all arguments of createentity() are exposed in the command.
We have to keep in mind that (1) unspecified arguments default to 0 (instead of the 320 and 240 for argument 8 and 9 that `createentity()` usually defaults to), and that (2) arguments persist across commands. (Why not get rid of argument persistence, you say? Unfortunately, some levels rely on argument persistence to call `gotoposition()` without specifying the third argument, even though you're supposed to specify all three arguments.)
To add these arguments without breaking levels, I re-added the `createentity()` defaults of 320 and 240 for args 8 and 9, and then I reset the new arguments afterwards when I'm done. Technically this could be bad if other commands used those higher arguments, but none of …
> Expose all 9 arguments of createentity()

- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
- desktop_version/src/Input.cpp
- desktop_version/src/Render.cpp
VVVVVV's menus are kind of packed to the brim, so I thought it was time to recategorize the menus a little bit. There's now a new "advanced options" menu which holds the following options which were moved out of graphic options, game options and especially accessibility options:
- toggle mouse
- unfocus pause
- fake load screen
- room name background
- glitchrunner mode
I also moved the "resize to nearest" option to be grouped more logically and changed "toggle letterbox" to "scaling mode" (further explained in the commit messages).
> Move some options to a new menu, "advanced options"

- desktop_version/src/editor.cpp
Ved has this useful feature where you can "lock" a gravity line or warp line in place, meaning it'll no longer extend its length until it touches a tile. A line is locked if the p4 of the edentity is 1.
VVVVVV doesn't support this, but now it does. The horrifying thing is that it stretches the lines out *while rendering the line*, so it looks like logic and rendering aren't that separate after all (although, I already learned that when I did my over-30-FPS patch).
Describe your patch here!
> Adhere to "locked" gravity/warp lines

- desktop_version/src/FileSystemUtils.cpp
- desktop_version/src/FileSystemUtils.h
- desktop_version/src/Graphics.cpp
- desktop_version/src/UtilityClass.h
- desktop_version/src/editor.cpp
- desktop_version/src/editor.h
One-ways have always had this problem where they're always yellow. That means unless you specifically use yellow, it'll never match the tileset.
The best way to fix this without requiring new graphics or changing existing ones is to simply re-tint the one-way with the given color of the room. That way, the black part of the tile is still black, but the yellow is now some other color.
But existing custom levels already re-texture the one-way tiles and some of them probably don't want the re-color. So if custom assets are mounted, then don't re-color the one-ways.
But new custom levels might want to take advantage of the re-color anyway, so there's now an override switch if a certain tag is present in the XML to use the re-color anyway even if assets are mounted. …
> Re-color one-way tiles to match the tileset

- desktop_version/src/editor.cpp
This doesn't make the editor completely accessible on controller, but it's a good start at least. VCE already let you move between rooms with the D-Pad, though.
> Allow D-Pad to act as arrow keys in the editor

- desktop_version/src/BinaryBlob.cpp
- desktop_version/src/BinaryBlob.h
- desktop_version/src/Music.cpp
- desktop_version/src/Music.h
- desktop_version/src/SoundSystem.cpp
Previously, the game didn't parse all headers from a given binary blob. It would look for headers with very specific names and only parse those.
This patch makes it so that all headers will be parsed and loaded. Headers with said specific names will still get priority and be loaded first, though, in case there happen to be binary blobs where the index of one of those headers isn't in the range 0..16. Then the extra headers are parsed in order according to their index.
`musicclass::play()` has been adjusted accordingly to accomodate for the new tracks, and the `music(-1)` trick still works (it plays the last MMMMMM track if you have MMMMMM and you're on PPPPPP). …
> Parse all headers from binary blobs

- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
This is basically just bolting on the "frames" part of a time trial score. There's not enough space to properly show it on the time trial select screen, maybe we can figure something out later. But I at least want to implement the functionality now.
> Read and write best time trial frames

- desktop_version/src/editor.cpp
This was already possible by editing the XML or using Ved, yet for some reason the in-game editor interface just wouldn't allow you to do it. Namely, the songs Pause, Plenary, ecroF evitsoP, and Predestined Fate Remix were missing from the track list.
I see no good reason to not allow these songs, so I'm enabling them again.
I kept the old track numbers (e.g. Piercing the Sky is track 11 instead of 14) because otherwise they wouldn't correlate with the track numbers you use for the `music()` simplified command.
> Allow using tracks 0..15 in the editor

- desktop_version/src/Script.cpp
- desktop_version/src/main.cpp
Ok, this'll be my last PR before the feature freeze. For real this time.
* **Make `text()` colors consistent with `blockclass::setblockcolour()`**
It seems a bit strange to have two separate color indexes that are mostly the same, don'tcha think?
* **Don't adhere to slowdown in MAPMODE/TELEPORTERMODE**
Now that you have a mini menu in MAPMODE, it's a bit annoying to have to deal with the slowed-down timestep when pressing left/right/ACTION inside it. Especially since going to an options menu restores the timestep back to normal (because it's in TITLEMODE). Also removed it from TELEPORTERMODE for consistency. …
> Make text() have the same colors as blockclass::setblockcolour(), and ignore slowdown on the map screen

- desktop_version/src/Entity.cpp
Their drawframe needs to be incremented by 2 instead of 1, because they're double-sized.
Animation type 3 is used by the cloud emitter in The Solution is Dilution, animation type 6 is used by the radar dish in Comms Relay. Animation type 4 is used by the maverick bus in B-B-B-Busted, but it's not noticeable since it spawns offscreen. This bug would cause all of those entities to appear incorrectly for the deltaframes between the tick the room got loaded and the next tick after that.
This is noticeable in flibit's tweet showing off my over-30-FPS patch: https://twitter.com/flibitijibibo/status/1273983014930993153 …
> Fix deltaframe render glitch when spawning animated double-size entities

- desktop_version/src/Map.cpp
- desktop_version/src/editor.cpp
- desktop_version/src/editor.h
Yet another three-in-one pull request.
I've refactored entity text input the same way VCE did it, which is basically just de-duplicating all the text input starting and finishing code. I've also added the G keybind to go to a room given its coordinates from VCE, which VCE got from Ved. Also, edentity terminals are now allowed to use any sprite they want to.
Unfortunately, this pull request will conflict with #342.
> Refactor entity text input, add G keybind to go to room in editor, and allow terminals to use any sprite they want

- desktop_version/src/Graphics.cpp
It should be `setcolreal()`, and not `setcol()`.
Fixes #347.
> Fix wrong function being used to set color of coins

- desktop_version/src/Game.cpp
- desktop_version/src/Script.cpp
This was caused by the fact that not all unlocks were done through the `Game::unlocknum()` function. Some just set the unlock number directly. But it's fixed now.
> Fix still being able to unlock things in custommode

- desktop_version/src/Input.cpp
This infinite loop would occur because once you pressed left or right, the game keeps searching through all the list of teleporters until it finds one that is unlocked. But if there's none that are unlocked, then the game goes into an infinite loop, which brings up the Not Responding dialog on Windows so you can kill it.
Normally, you're not supposed to have no teleporters unlocked while being able to access a teleporter, but you can achieve this by going to Class Dismissed from a custom level (while making sure you don't start in 0,0, because there's a teleporter there that you would unlock).
The solution is to make sure at least one teleporter is unlocked before doing any searching.
example, a 2.3 update on Steam for …
> Fix infinite loop if left or right is pressed in the teleporter screen while no teleporters are unlocked

- desktop_version/src/Map.cpp
This would mean that NO_CUSTOM_LEVEL builds wouldn't compile.
> Fix Map.cpp relying on editor.h to include Script.h

- desktop_version/src/Game.cpp
So there's this really annoying softlock that can happen if you put script boxes next to a trinket or a crewmate. You would collect the trinket or crewmate, and there would be the "You have found a shiny trinket!" or "You have found a lost crewmate!" text box, along with the first text box of the script, and then after you pressed ACTION the rest of the script would play out. This is because the trinket/crewmate collection sequences use `game.completestop` to stop everything when their sequence runs, but that variable doesn't end up getting reset for whatever reason.
For a while it was just common wisdom that you shouldn't overlap script boxes with trinkets or crewmates or else Bad Things Will Happen.
Well, it's only a problem with script boxes that create text boxes. If a script box does …
> Fix being able to softlock the game if you touch a script box on the same frame you touch a trinket or crewmate, and that script has a text box in it

- desktop_version/src/Spacestation2.cpp
The spikes are removed if the game is in no death or time trial mode,
however the removal is accomplished by modifying a static array. So if
the player switches to no death or time trial mode and switches back to
regular play, the spikes will no longer be present until the game is
restarted (since the static initialization only happens once).
This simple fix writes the spikes back to the static array if the game
is not in no death or time trial mode. Another option is to maintain 2
static arrays - one with the spikes and one without - but that is
needlessly wasteful and prone to mistakes (one array updated but not the
other).
section of the credits for all of said releases, but will …
> Fix 'Prize for the Reckless' spikes when switching game modes

- desktop_version/src/Scripts.cpp
There's a bug in the cutscene that plays if your companion is Vitellary in the room "Now Stay Close To Me...". The relevant gamestate is gamestate 43, which for Vitellary calls the script `int1yellow_4`.
When Vitellary says the text box "That big... C thing! I wonder what it does?", Terry intended for Vitellary to change his facing direction to the left, as you can see with the command `changedir(yellow,0)` in the original scripting. `changedir()` just changes the `dir` attribute of an entity, and a `dir` of 0 means face left and a `dir` of 1 means face right.
Then when Vitellary says "Maybe we should take it back to the ship to study it?", Terry intended for him to face rightwards once again, as indicated by the `changedir(yellow,1)` command.
Unfortunately, what happens instead is that …
> Fix Vitellary looking left for only one frame in the cutscene in "Now Stay Close To Me..."

- desktop_version/src/Game.cpp
Gamestates 300..336 are used to start scripts in custom levels. However, it looks like instead of having the cases have common code, each individual case was copy-pasted numerous times, which is pretty wasteful.
> De-duplicate gamestates 300..336

- desktop_version/src/Input.cpp
The music for the Tower is supposed to be ecroF evitisoP in Flip Mode, and Positive Force when not in Flip Mode. However, if you go to the options from the pause menu and toggle Flip Mode, the music isn't changed.
Fixing this is pretty simple, just check the current area if not in a custom level and play the correct track accordingly when toggling Flip Mode from in-game.
> Fix wrong Tower music when toggling Flip Mode from in-game options

- desktop_version/src/Game.cpp
- desktop_version/src/Input.cpp
- desktop_version/src/Script.cpp
So you get a trophy and achievement for completing the game in Flip Mode. Which begs the question, how does the game know that you've played through the game in Flip Mode the entire way, and haven't switched it off at any point? It looks like if you play normally all the way up until the checkpoint in V, and then turn on Flip Mode, the game won't give you the trophy. What gives?
Well, actually, what happens is that every time you press Enter on a teleporter, the game will set flag 73 to true if you're *not* in Flip Mode. Then when Game Complete runs, the game will check if flag 73 is off, and then give you the achievement and trophy accordingly.
However, what this means is that you could just save your game before pressing Enter on a teleporter, then quit and go into options, turn on Flip …
> Fix being able to circumvent not-in-Flip-Mode detection

- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
- desktop_version/src/main.cpp
There's a bug where playtesting from Ved doesn't properly play the music of the level, due to no fault with Ved.
This was because the music was being faded out by `scriptclass::startgamemode()` case 23 after `main()` called `music.play()`. To fix this, just call `music.play()` when all the other variables are being set in `Game::customloadquick()`.
> Fix -playmusic command line option not working

- desktop_version/src/Script.cpp
When I moved duplicate player entity removal to `scriptclass::hardreset()`, I also inadvertently made it so all non-player entities got removed as well, even though this wasn't my intent. And thus, pressing Enter to restart a time trial removes every entity except the player, since it calls `script.hardreset()`.
The time trial `script.hardreset()` is bad for other reasons (see #367), however it's still a good idea to reset only what's needed in `script.hardreset()`.
> Don't remove non-player entities in scriptclass::hardreset()

- desktop_version/src/Game.cpp
A missing newline in a `printf()` is annoying, it means the next line of output is concatenated to the previous one.
> Fix missing newline on printf() for Game::customsavequick() failure

- desktop_version/src/main.cpp
This patch optimizes the loop used to limit the framerate in 30-FPS-only mode so that it uses `SDL_Delay()` instead of an accumulator. This means that the game will take up less CPU power in 30-FPS-only mode. This also means that the game loop code has been simplified, so there's only two while-loops, and only two places where `game.over30mode` is checked, thus leading to easier-to-understand logic.
Using an accumulator here would essentially mean busywaiting until the 34 millisecond timer was up. (The following is just what @leo60228 told me.) Busywaiting is bad because it's inefficient. The operating system assumes that if you're busywaiting, you're performing a complex calculation and handles your process accordingly. And this is why sleeping was invented, so you could busywait without …
> Optimize 30-mode FPS loop to use SDL_Delay()

- desktop_version/src/Entity.cpp
- desktop_version/src/Entity.h
- desktop_version/src/Map.cpp
Previously, whenever a script box was created in a custom level, the game would set the script box's script in `game.customscript` (an array of `std::string`s) and set the gamestate that the script box will execute to be one that will read from that array (gamestates 300..336). This seems to be a really unnecessary middleman, so I've made it so that the primary way a script box gets executed is by the game setting the `script` attribute of the block, and then directly reading that attribute if the player collides with it.
However, for backwards compatibility, I've left gamestates 300..336 and `game.customscript` alone, as some custom levels use those gamestates in order to enter a script box loop.
Furthermore, I've made sure that the quirks of script boxes were preserved:
- Script boxes …
> Refactor script boxes in custom levels to not use gamestates

- desktop_version/src/main.cpp
Whoops.
Noticed this earlier when I was merging upstream back into VCE, and interestingly enough, it doesn't look like cppcheck warns about undeffing a non-existent define.
> Fix undeffing ARG_IS instead of ARG

- desktop_version/src/Input.cpp
The game would softlock if you brought up the map screen or quit screen after exiting the Super Gravitron to the Secret Lab. This softlock would only happen if you were in glitchrunner mode.
This is because glitchrunner mode set `game.fadetolabdelay` when it shouldn't have, and also checked `game.fadetolabdelay` when it shouldn't have.
So I made it so that the game will only set `game.fadetolabdelay` when not in glitchrunner mode (I already had a check for `game.fadetomenudelay`, too!) and the game will only check for `game.fadetomenudelay` and `game.fadetolabdelay` when not in glitchrunner mode, as well.
I originally made the game check `game.fadetomenudelay` and `game.fadetolabdelay` to prevent being able to re-press ACTION to re-start the fadeout if the game was already fading out. And …
> Fix softlock if exiting Super Grav and bringing up map in glitchrunner

- desktop_version/src/editor.cpp
Whoops. Forgot to do this earlier when adding the Shift+F3 hotkey. Otherwise the enemy type would become invalid and just turn into the default square.
> Wrap around enemy type when switching enemy types

- desktop_version/src/Game.cpp
- desktop_version/src/Script.cpp
This fixes the bug where Viridian would appear to "zip" when they would be teleported to the position of the teleporter before being flung out of it.
As discussed in #393, I've also set the `oldxp`/`oldyp` when Viridian is temporarily positioned in the center of the room, even though at this point they should already be invisible. This is just to be safe.
Fixes #393.
> Set oldxp/oldyp when being teleported around during teleport

- desktop_version/src/Map.cpp
This fixes the bug where it would appear as if they "zipped" to the destination from the warp token.
Fixes #384.
> Set oldxp/oldyp when player teleports through warp token

- desktop_version/src/Logic.cpp
Otherwise, this would cause immense slowdown during the New Record animation that plays when you die, as the game would be writing `unlock.vvv` every frame.
To fix this, I just put it under the same if-guard as the `music.playef()`, since the sound effect also only plays once. But I have to watch out for frame ordering and make sure the record is actually set before I call `game.savestats()`, and then of course I have to move `game.swnmessage = 1` over because that's the variable being checked in the conditional.
> Don't savestats() every frame of New Record animation

- desktop_version/src/Render.cpp
Added checks to fix singular cases in the No Death Mode game over screen.
Closes #374 
> Add check for singular trinkets and crewmates in NDM game over screen

- desktop_version/CONTRIBUTORS.txt
- desktop_version/src/Credits.h
- desktop_version/src/Entity.cpp
- desktop_version/src/Otherlevel.cpp
The 'Game Complete' Trophy stand hovers above the ground. This change fixes that. Also, I changed the comments in Otherlevel.cpp so they say trophy instead of terminal, since that's what's actually being created.
Here is what it used to look like:
Note that the trophy position (line 8953 in Otherlevel.cpp) was altered by 3 pixels originally. This has been removed and instead the position is only altered if the trophy is shown.
> Fix the 'Game Complete' trophy stand so it no longer hovers above the ground

- desktop_version/src/Graphics.cpp
Fix Graphics::drawentities() screen wrapping logic to allow for simultaneous horizontal and vertical wrapping of sprites. Closes #404.
> Wrap entities

- desktop_version/src/editor.cpp
This makes starting from a checkpoint in the editor put you in the same position as when respawning from it after a death. Closes #378.
> Fix checkpoint starts in editor

- desktop_version/src/editor.cpp
When releasing Ctrl to let the tile selection drawer disappear, the tile indicator for the selected tile would stay in place, the drawer would move away underneath it, and it would abruptly disappear. This makes the selected tile indicator move along with the drawer when it moves up.
Closes TerryCavanagh#386.
> Fix Direct Mode selection square not moving with tile selection drawer

- desktop_version/src/Game.cpp
What this simply does is make it so that in the event that `game.hascontrol` is somehow set to false when there isn't a cutscene
running (i.e. when `game.state` is 0 and `script.running` is false), it gets set back to true again.
There's many ways to interrupt a gamestate and/or a running script, most notably telejumping and doing a screen transition in the middle of the animation, interrupting it.
This implements the first part of my idea in [this comment](https://github.com/TerryCavanagh/VVVVVV/issues/391#issuecomment-659757071).
> Add catch-all softlock protection

- desktop_version/src/Render.cpp
Fixes #376.
Since trinket counts in the "game saved" box can now go above Twenty in custom levels, some numbers can run out of the box:
Now the trinket count is positioned automatically based on its length. The trinket icon is now also displayed at the far right (instead of to the left of the count) for better symmetry, and so that switching between the menu options for tele save and quick save doesn't make the trinket icon move if the trinket counts have different lengths. Lastly, I've repositioned the time and trinket count a bit and made the box a little wider to account for future localizations of the game (I mean, I could have done the minimum necessary to fix the overflow in English in this branch and do the rest in the localization branch, but why not get it out of the way while …
> Reposition game time and trinket count in game save box

- desktop_version/src/Render.cpp
This fixes a possible graphical issue where the "Press ENTER to activate terminal" prompt gets drawn on top of the "- Press ACTION to advance text -" prompt, which looks bad. Trophy text gets drawn on top, too, so there's a check there as well.
I've also made it so the activity prompt doesn't get drawn if the player doesn't have control. After all, what use is it to say "press ENTER" if the player isn't allowed to?
Here are some example screenshots with Dimension Open, in the cutscene that plays after rescuing Voon from the Space Station.
Before:
After:
> Don't draw activity zone or trophy text when cutscene is running

- desktop_version/src/GOGNetwork.c
- desktop_version/src/Network.c
- desktop_version/src/SteamNetwork.c
M&P contains network code despite M&P not being a Steam/GOG release (as Steam/GOG releases are full releases of the game, not custom-levels-only releases).
While unlocking achievements is already ifdef'd out in M&P, let's remove the network code entirely to make sure people can't do other shenanigans with M&P builds, and also to have a smaller binary size.
> Ifdef out network code for Make & Play edition

- desktop_version/src/Map.cpp
Four variables are now initialized upon declaration, because GCC warns that they may be used uninitialized whenever I compile in release mode (even though I can't find out how this could happen...).
And I fixed a bug where enemies in custom levels would have the same bounds as platforms.
> Initialize bx1/by1/bx2/by2 and fix enemies in custom levels taking on the same bounds as platforms

- desktop_version/src/Entity.cpp
- desktop_version/src/Logic.cpp
- desktop_version/src/Render.cpp
This moves the teleporter, activity prompt, and trophy text "don't draw" conditionals to the part where the game checks collision with them, instead of whenever the game draws them.
This makes it so that the game smoothly does the fade-in/fade-out animation instead of suddenly stopping rendering them whenever their "don't draw" conditions apply. Now, the "Press ENTER to activate terminal" prompt will no longer suddenly disappear whenever you activate one, and the "- Press ENTER to Teleport -" prompt will smoothly fade back in after teleporting, instead of suddenly popping in on screen.
> Move tele/activity/trophytext conds to collision detection

- desktop_version/src/main.cpp
This is helpful to know if the user either spelled an argument wrong, or spelled it right but nothing is happening.
> Print an error message and return if the game is given an invalid command-line argument

- desktop_version/src/Game.cpp
The `samemenu` argument to `createmenu()` just has to be set to true so another stack frame doesn't get added.
Fixes #415.
> Fix dupe stack frame when creating unlock notif menu

- desktop_version/src/Input.cpp
The half-second delay comes from the fact that the game uses `graphics.resumegamemode` to go back to GAMEMODE. This system waits for `graphics.menuoffset` to reach a certain threshold before actually going back (this is the animation of the map screen being brought down). To speed it up, I'll just set `graphics.menuoffset` directly.
I could've directly set `game.gamestate` to GAMEMODE, but I wanted to be safe and use the existing system instead.
> Remove half-second delay when exiting to menu in glitchrunner mode

- desktop_version/src/Graphics.cpp
The function was not actually checking the number that would end up being used to index the `tiles3` vector, and as a result there could potentially be out-of-bounds indexing. But this is fixed now.
(Conflicts with #428.)
> Fix INBOUNDS() check for Graphics::drawtile3()

- desktop_version/src/Graphics.cpp
- desktop_version/src/Graphics.h
If you have the translucent room name option enabled, you'd always be seeing the spikes at the bottom of the screen hidden behind the room name. This patch makes it so that the spikes get carefully cropped so they only appear above the room name when the player gets close to the bottom of the screen.
> Crop bottom tower spikes so they don't get drawn behind room name

- desktop_version/src/Graphics.cpp
- desktop_version/src/GraphicsUtil.cpp
- desktop_version/src/GraphicsUtil.h
* The superfluous `intersectRect()` function has been axed in favor of the already-existing and much better `UtilityClass::intersects()`.
* The return logic of the function has been cleaned up a bit.
* `SDL_max()` and `SDL_min()` are used instead of `std::max()` and `std::min()`.
> Clean up Graphics::Hitest() a little bit

- desktop_version/src/main.cpp
For some reason, the cursor would be either disabled and re-enabled if you switched to windowed mode, or it would be always enabled if you switched to fullscreen mode. This only happened when you toggled fullscreen using the Alt+Enter, Alt+F, or F11 keybinds, and the fullscreen option in graphic options doesn't have this problem.
This cursor toggling business seems like an arcane incantation back in the days of SDL1.2, now since no longer necessary with SDL2. However, after some testing, it seems like removing these indecipherable runes don't cause any harm, so I'm going to remove them.
Fixes #371.
for these …
> Remove unnecessary cursor toggling when toggling fullscreen

- desktop_version/src/Graphics.cpp
- desktop_version/src/GraphicsUtil.cpp
- desktop_version/src/GraphicsUtil.h
- desktop_version/src/main.cpp
So, earlier in the development of 2.0, Simon Roth (I presume) encountered a problem: Oh no, all my backgrounds aren't appearing! And this is because my `foregroundBuffer`, which contains all the drawn tiles, is drawing complete black over it!
So he had a solution that seems ingenius, but is actually really really hacky and super 100% *not* the proper solution. Just, take the `foregroundBuffer`, iterate over each pixel, and *don't* draw any pixel that's `0xDEADBEEF`. `0xDEADBEEF` is a special signal meaning "don't draw this pixel". It is called a 'key'.
Unfortunately, this causes a bug where translucent pixels on tiles (pixels between 0% and 100% opacity) didn't get drawn correctly. They would be drawn against this weird blue color.
Now, in #103, I came across this weird constant and …
> Actually finally fix rendering of translucent pixels on tiles (remove OverlaySurfaceKeyed() and set proper foregroundBuffer blend mode)

- desktop_version/src/Graphics.cpp
- desktop_version/src/GraphicsUtil.cpp
- desktop_version/src/GraphicsUtil.h
So, `ScaleSurfaceSlow()` does a slower `DrawPixel()`-based method of scaling the given surface, unlike `ScaleSurface()`, which uses a much more efficient `SDL_FillRect()`.
So, why use `ScaleSurfaceSlow()` over `ScaleSurface()`? It turns out it's because `ScaleSurface()` has this weird 1-pixel offset for no reason, causing not only the result to be offset by one pixel, but also completely dropping scaled pixels, too. So I removed that offset as well, and Big Viridian no longer looks like they're floating on the ground when they're standing on the floor.
> Remove ScaleSurfaceSlow() in favor of ScaleSurface() and fix the offset in ScaleSurface()

- desktop_version/src/Game.cpp
This PR fixes a bug that's existed since MMMMMM was added (so, 2.2), where if you quicksaved in a custom level while no music was playing, then quit and loaded that quicksave, and you were using PPPPPP while having MMMMMM available, it would play MMMMMM track 15, even though the game intends for the music to simply be silent.
This is due to the same bug that lets you play MMMMMM tracks if you're on PPPPPP - `musicclass::play()` does a modulo, but C++ modulo is not guaranteed to be positive given negative inputs, so the 16-track offset is added to a negative number, resulting in targeting the MMMMMM soundtrack instead of PPPPPP.
That exploit doesn't harm anyone and shouldn't be fixed, *except* it causes a problem in this specific case. But this bug can be fixed without removing that …
> Fix silent music saves playing MMMMMM track 15 if you're using PPPPPP while having MMMMMM available

- desktop_version/src/Game.cpp
- desktop_version/src/Graphics.cpp
- desktop_version/src/Graphics.h
- desktop_version/src/Textbox.cpp
- desktop_version/src/Textbox.h
When I added the over-30-FPS mode, I kept running into this problem where the special images of text boxes would render during the deltaframes of fade-in/fade-out animations, even though they shouldn't be. So I simply added a flag to the text box that enables drawing these special images.
However, this doesn't solve the problem fully, and there's still a small chance that a special-image text box could draw another special image during its deltaframes. It's really rare and you have to have your deltaframe luck juuuuuust right (or you could use libTAS, probably), but it helps to be in 40% slowmode and have a high refresh rate (which, if it isn't a multiple of 30, you should disable VSync, too, in order to not have a low framerate).
So instead, special images will only be drawn if the text …
> Remove allowspecial, replace with opaqueness check

- desktop_version/src/Game.cpp
- desktop_version/src/Script.cpp
- desktop_version/src/UtilityClass.cpp
- desktop_version/src/UtilityClass.h
- desktop_version/src/editor.cpp
- desktop_version/src/main.cpp
If an invalid integer is passed into `atoi()`, whether or not the behavior is undefined seems to depend on which libc you're using. So, it's best to have a wrapper function that performs the check for you, to avoid any problems from invalid input.
Additionally, this is an opportunity to replace `atoi()` with `SDL_atoi()`. If libc has `atoi()`, then `SDL_atoi()` will still call that function, so we still need to check the input, but if that function isn't available `SDL_atoi()` will call `SDL_strtol()`, which doesn't have this problem.
> Fix potential Undefined Behavior from not checking input passed into atoi()

- desktop_version/src/FileSystemUtils.cpp
As the title says, this cleans up some string-related code in `FileSystemUtils.cpp`. Mostly the `strcat()`s and `strcpy()`s, but mwpenny's basedir code gets an honorable mention for a Rube Goldberg-like if-statement that I cleaned up to be less unnecessarily complicated.
I decided not to clean up `PLATFORM_migrateSaveData()` because it's going to be axed in 2.4 anyway. That function is most likely susceptible to a million different buffer overrun attacks, but I really don't want to touch it.
> Clean up FileSystemUtils string operations, EXCEPT for PLATFORM_migrateSaveData()

- desktop_version/src/FileSystemUtils.cpp
> Fix array decay in PLATFORM_getOSDirectory()

- desktop_version/src/Input.cpp
While working on updating my homebrew port on the Switch I noticed the Map and Menu screens couldn't be navigated using the up and down buttons using a controller. Seeing as up and down is allowed for keyboard it seemed controllers should be the same.
> Fixed controllers not being able to navigate the map and menu with up and down buttons.

- desktop_version/src/Input.cpp
All that pressing R does in No Death Mode is end your run. As a result, it'll only be pressed by accident, so it's better to just disable it instead.
It's not even useful to quick-restart, because it's faster to quit and go through the menu again than it is to wait through the Game Over screen.
Additionally, I removed the `game.deathseq<=0` conditional because it's unnecessary due to the if-statement already being inside a `game.deathseq == -1` conditional.
> Disable pressing R in No Death Mode

- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
- desktop_version/src/Input.cpp
- desktop_version/src/Render.cpp
Saw pull request #440 and noticed that you could only restart to a checkpoint with a keyboard. So I added another a key binding for controllers to allow people to be able to restart to a checkpoint. I'm not sure if "Restart" is a good name for it, but it was the best I could think of. Also wasn't sure if right shoulder was the best default for it either.
> Added ability to bind restart to a controller.

- desktop_version/CONTRIBUTORS.txt
- desktop_version/src/Credits.h
- desktop_version/src/KeyPoll.cpp
- desktop_version/src/editor.cpp
- desktop_version/src/main.cpp
Fixes #366
- The fullscreen issue was solved by checking to see if any modifier buttons (Ctrl, Alt, or Super) were being held down on the key down event, and if so then we ignore the input on the text input event. This allows for future hotkeys to not cause an issue.
- The sound muting issue was because the `getlin` method in editor wasn't properly setting `ed.textentry` to true. The reason why this started happening was because the inEditor check in main.cpp:620 was changed to use just `ed.textentry` whereas before it used to also check `key.textentrymode`.
- I also went ahead and added myself as a contributor. (Hopefully that is okay.)
section of the credits for all of said …
> Hotkey text input fix

- desktop_version/.gitignore
- desktop_version/src/main.cpp
Fixes #450 
Sets `menustart` to true when using the playtesting argument. This prevents the title screen from showing up when going to the Graphics Options while playtesting. Also added `.DS_Store` to the gitignore file for macOS. 🙄 
> Fixed the title screen showing up when going to graphics options while playtesting.

- desktop_version/src/Input.cpp
If Presenting VVVVVV is playing when you exit to the menu, the song will fade out, and then Presenting VVVVVV won't fade (back) in. This fixes that by avoiding fading the music out if it's already playing Presenting VVVVVV for a smooth transition between the level and the menu. The alternative would have been making it fade out and then back in, which wouldn't really be ideal.
Fixes #452.
> Don't fade music out when returning to the menu if it's Presenting VVVVVV

- desktop_version/src/KeyPoll.cpp
- desktop_version/src/KeyPoll.h
- desktop_version/src/editor.cpp
- desktop_version/src/editor.h
- desktop_version/src/main.cpp
After looking at pull request #446, I got a bit annoyed that we have *two* variables, `key.textentrymode` and `ed.textentry`, that we rolled ourselves to track the state of something SDL already provides us a function to easily query: `SDL_IsTextInputActive()`. We don't need to have either of these two variables, and we shouldn't.
So that's what I do in this patch. Both variables have been axed in favor of using this function, and I just made a wrapper out of it, named `key.textentry()`.
For bonus points, this gets rid of the ugly `NO_CUSTOM_LEVELS` and `NO_EDITOR` ifdef in main.cpp, since text entry is enabled when entering the script list and disabled when exiting it. This makes the code there easier to read, too.
Furthermore, apparently `key.textentrymode` was initialized to *true* …
> Axe manual state trackers and use SDL_IsTextInputActive()

- desktop_version/src/Input.cpp
This fixes the bug where in glitchrunner mode, quitting to the menu would always put you back at the play menu on the first option, instead of the menu you entered the game from.
The problem is the `script.hardreset()` that gets called before the game actually quits to the menu, so when `Game::quittomenu()` gets called to quit to the menu, all the variables that keep track of whether you're in a certain gamemode, such as `game.insecretlab` and `map.custommode`, all get prematurely reset before that function can read them and put you back to the correct menu.
The solution here is to simply reset only what's needed when quitting to the menu. Specifically, in order for credits warp to work, `script.running` needs to be set to false and all the text boxes need to be removed. Text boxes need …
> Fix aggressive glitchrunner hardreset causing issues quitting to menu

- desktop_version/src/BinaryBlob.cpp
- desktop_version/src/BinaryBlob.h
- desktop_version/src/Music.cpp
So I sat down and added some more security to the binary blob code.
This particular round of fuzzing came after I attempted to TAS Unshackled 1.4, only to find that loading the level segfaulted my game. Why? Well, the root cause is a bogus `invalid` value in all headers in `vvvvvvmusic.vvv`, and the secondary cause is that the game kind of doesn't just ignore all those invalid headers and still attempts to parse them. So I decided that it really should ignore them!
By the way, @AllisonFleischer (level creator of Unshackled), you should check Unshackled 1.4's `vvvvvvmusic.vvv`. For whatever reason, all the headers' `valid` attributes are `0x01` `0x01` `0x01` `0x01`, even though the only value that will be accepted as valid is `0x01` `0x00` `0x00` `0x00`. Even stranger, `mmmmmm.vvv` loads …
> Prevent more fuzzing of binary blob (check bounds and indices, actually mark invalid headers as invalid)

- desktop_version/src/Input.cpp
There's not really any need for it to be there. It gets called when the Time Trial restarts, as restarting the Time Trial calls `script.startgamemode()`, which calls `script.hardreset()` anyway.
Furthermore, since `script.hardreset()` is removed, we can also remove two lines that are meant to work around the fact that everything gets reset, which is now no longer the case.
Fixes #367.
> Remove script.hardreset() when restarting Time Trial

- desktop_version/src/Entity.cpp
- desktop_version/src/Map.cpp
* **Fix compatibility with levels that rely on gamestate-based script boxes**
Some levels rely specifically on the fact that certain script boxes are loaded using gamestates, instead of directly loading the script and bypassing the gamestate system. Then weird things could happen. This restores compatibility with those levels.
`mapclass::twoframedelayfix()` doesn't need to be updated because the point of that function is to bypass the gamestate system entirely anyways.
* **Add custommode check to `mapclass::twoframedelayfix()`**
This is to ensure that this function only has an effect inside custom levels. It might do something weird or bad in the main game.
section of the credits for …
> Fix compatibility with levels that rely on gamestate-based script boxes, and add custommode check to mapclass::twoframedelayfix()

- desktop_version/src/editor.cpp
This fixes a bug where opening a script, then closing the script but not exiting the script list, then opening a script again (it can be the same script as before) would result in you being unable to type in the script. You would have to close the script, then close the script list, then re-open the script list in order to be able to type properly.
This was caused by the fact that `key.enabletextentry()` was being called when the script list was opened, but `key.disabletextentry()` was being called when closing a script. So the fix for this is to simply move the `key.enabletextentry()` to its proper place, which is when the script is being opened, and not when the script list is. …
> Move text entry start to script open instead of script list open

- desktop_version/src/Render.cpp
This is a follow-up to #421.
The game would draw the activity zone if there was one active at all, and would ignore `game.act_fade`. Normally this wouldn't be a problem, but since #421, it's possible that there could be an active activity zone but `game.act_fade` would still be 5. This would happen if you entered a new activity zone while a cutscene was running.
To fix this, just make it so that the prompt gets drawn on its own and only depends on the state of `game.act_fade` (or `game.prev_act_fade`), and won't be unconditionally drawn if there's an active activity zone. As a bonus, this de-duplicates the drawing of the activity prompt, so it's no longer copy-pasted.
section of the …
> De-duplicate activity zone rendering, don't ignore game.act_fade

- desktop_version/src/Script.cpp
Fixes #402 (Violet appearing 1 frame after the Ship teleporter room appears).
The root cause of this bug is due to the game loop order changes made with the over-30-FPS patch. 2.2's game loop order was `gameinput()`, `gamerender()`, then `gamelogic()`. In 2.3, `gamerender()` was moved to the end as it required special code to render more than 30 frames a second. So 2.3's game loop order is `gameinput()`, `gamelogic()`, then `gamerender()`.
In hindsight, I could have preserved the game loop order, but this would require some more complex code in the game loop than what is there currently. Fixing it now would fix rendering glitches such as this one (along with being able to remove script.dontrunnextframe with the two-frame-delay fix), but it could also introduce new rendering glitches we …
> Fix 1-frame render glitch with running teleport scripts

- desktop_version/src/Entity.cpp
If the player is stuck in a wall (which shouldn't happen in the first place), their sprite would always default to being flipped, even if they were unflipped.
Being stuck in a wall is characterized by having both positive `onfloor` and `onground`.
> Fix sprite of player if they are stuck in a wall

- desktop_version/src/editor.cpp
It's perfectly acceptable to have both warp lines and a warping background in the same room. Many levels do this exact thing, I would say at least 30 or so levels, many of them popular and played by many, and this has never caused any issues at all.
All that having both warp lines and warp BG does is make it so the warping of the warping background gets overriden by the warp lines, but make it so the background is still a warp background. So in effect, you can have a warp background without any warping. This is perfectly defined behavior. Except, for whatever reason, it's unintentional, and the editor tries to prevent you from doing it.
Key word being "tries". The code to prevent having both warp types is bugged (at least when you change the warp BG. The check when you place warp lines …
> Remove checks to prevent having both warp lines/BGs in editor

- desktop_version/src/Entity.cpp
- desktop_version/src/Map.cpp
This makes it so the fix for crewmates' drawframes being wrong for 1-frame is fixed for all crewmates regardless of when they get created. Sure, crewmates created in `mapclass::loadlevel()` have their drawframes fixed there, but for crewmates that get created from scripting (such as Violet when gotorooming to the Ship teleporter room after Space Station 1), this fix doesn't apply to them. But now it does, and Violet will no longer be facing the wrong way for 1 frame when teleporting to the Ship teleporter room in the Space Station 1 Level Complete cutscene.
> Move crewmate drawframe fix to entityclass::createentity() instead of mapclass::loadlevel()

- desktop_version/src/Input.cpp
These changes serve to make it less likely that winding up in a situation where you don't have control like #391 would actually softlock the game. With these new changes, you will always be able to press Esc and quit to the menu, or press Enter and quicksave and then quit, regardless of whether `game.hascontrol` is true or not. As a bonus, these inputs also still work even if there's no player entity that currently exists, whereas otherwise the lack of a player entity would mean you wouldn't be able to quit or quicksave either.
> Allow certain inputs even if player entity doesn't exist or player doesn't have control

- desktop_version/src/Entity.cpp
I noticed that if I have a large amount of entities in the room, the game starts to freeze and one frame would take a very long time. I identified an obvious cause of this, which is that the entity collision checking in `entityclass::entitycollisioncheck()` is O(n²), n being the number of entities in the room.
But it doesn't need to be O(n²). The only entities you need to check against all other entities are the player and the supercrewmate. You don't need to "test entity to entity" if 99% of the pairs of entities you're checking don't involve the player or supercrewmate.
How do we make it O(n)? Well, just hoist the rule 0 and type 14 checks out of the inner for-loop. That way, the inner for-loop won't be unconditionally ran, meaning that in most cases it will always be O(n). However, if …
> Optimize entity collision checking to O(n)

- desktop_version/src/Script.cpp
It's trivially easy to send the scripting system into an infinite loop on the same frame (i.e. without any script delay in between, i.e. within the same execution of `script.run()`). Just take a look at these two scripts:
a:
iftrinkets(0,b)
#
b:
iftrinkets(0,a)
#
The hashes are to prevent the scripting system from parsing `iftrinkets()` using the internal version instead of the simplified version, because after doing a simplified `iftrinkets()`, the parser will (to oversimplify) execute the last line of the script as internal.
Anyway, sending the game into an infinite loop like this will cause the Not Responding dialog on Windows.
So to prevent this from happening, I've added an execution counter to `scriptclass::run()`. If it gets too high, we're in an infinite loop and so we stop …
> Prevent same-frame infinite loops in scripts

- desktop_version/src/Graphics.cpp
For some reason, there's some color-clamping code in this function directly after already-existing color-clamping code. This code dates back to 2.2. And also, there's a smaller lower-bound of -1 for the red channel, despite the fact that this smaller value doesn't matter because the red would get clamped to 0 by the first code anyway.
So even if this was put here for some strange reason, it doesn't matter because it doesn't do anything anyway.
Also, all other graphics functions use the `clamp()` macro instead of writing out the clamping manually, so this one should, too.
> Clean up color-clamping code in Graphics::bigrprint()

- desktop_version/src/GraphicsUtil.cpp
- desktop_version/src/GraphicsUtil.h
So, there was both an `endian_swap()` function and `endian_swap()` template(!), which were both unused. SDL provides endian swap macros anyway, not sure why either of those were in here. But that template was the only instance of a template being used in the game, so the game *technically* wasn't templateless until now.
I've also axed the `SDL_BYTEORDER` checks, because (1) the game basically only runs on little-endian, anyway, (2) even if it didn't, the game doesn't check it everywhere it should (so big-endian has definitely never been tested), and (3) the endianness checks shouldn't be written anyways, the code should be endian-agnostic already.
I've also cleaned up two suspicious `SDL_CreateRGBSurfaceFrom()`s that used their own hardcoded arguments for bits-per-pixel and color masks …
> Clean up endianness and surface mess

- desktop_version/src/Entity.cpp
- desktop_version/src/Logic.cpp
So, I was staring at VVVVVV code one day, as I usually do, and I noticed that warp lines had this curious code in `entityclass::updateentities()` that set their `statedelay` to 2, and I thought, hm, maybe the pre-2.1 warp line bypass is caused by this `statedelay`. And, it doesn't seem like this is the primary code used to detect if the player collides with warp lines, the actual code is commented with "Rewritten system for mobile update" and bolted-on in `gamelogic()` instead of properly being in `entityclass::entitycollisioncheck()`.
So, after getting tripped up on the misleading indentation of that "Rewritten system" block, I removed the rewritten system, re-added collision detection for rule 7 (horizontal warp lines), and after checking the resulting behavior, it appears to be nearly …
> Restore pre-2.1 warp line bypass glitch in glitchrunner mode

- desktop_version/src/Game.cpp
This is a regression from 25779606b499819de50151cd20aab406256315f5 (PR #74).
On the one hand, I should've thought this through carefully when implementing the fix for the lower-score overwrite bug. On the other hand, flibit didn't seem to notice either. And on the third hand, no one else seems to have noticed, when they have had over 8 months to do so. Not even the person who originally reported the lower-score overwrite bug and also reported other bugs I hadn't noticed (e.g. the "You have rescued a crewmate!" in Flip Mode) noticed, which I believe was weee50. But to be fair, he does seem to be less active nowadays.
On the fourth hand, I only realized the cause of the duplicate bug after stepping through it in GDB, instead of just looking at it and going "hey wait a minute" earlier. I'm …
> Fix duplicate levels in levelstats if you don't have a higher score

- desktop_version/CONTRIBUTORS.txt
- desktop_version/src/Credits.h
- desktop_version/src/editor.cpp
This is a small fix that partially addresses #379 by inserting a space after a colon followed by a new line when a script is saved.
> Add space after lines terminated by a colon in scripts

- desktop_version/src/Graphics.cpp
This patch fixes a regression caused by commit 6b1a7ebce6fa77ec54c881bec95081b1a2826646.
When you spawn a crewmate with an invalid color, by doing something like `createentity(100,100,18,-1,0)` (here the color is -1, which is invalid), a white crewmate with the color of solid white (255, 255, 255) would appear.
That is, until @AllyTally came along and committed commit 6b1a7ebce6fa77ec54c881bec95081b1a2826646 (Make "[Press ENTER to return to editor]" fade out after a bit) (PR #158). Then after that commit, it would seem like the crewmate didn't appear, but in reality they were just invisible, because they had an invisible color.
As part of Ally's changes, to properly support drawing text with a certain amount of alpha, she made `BlitSurfaceColoured()` account for the alpha of the color …
> Fix default Graphics::setcol() value having no alpha

- desktop_version/src/Script.cpp
This is a followup to b7cf6855b0ad1e30ac33bc9a53ef4268fdf686cf and 10ed0058fd760f764cc7b849e6f0e22f1e4dc6bb.
In 2.2, if you had a duplicate player entity, there'd be no way to get rid of it. Except for the recently-discovered Arbitrary Entity
Manipulation glitch, where you set `i` to the indice of the entity and call `flipgravity()` on it, turning its rule to 7 and making it no longer a player entity.
However, I patched this useful mechanic out when I made it so that you'd no longer be able to convert entities with rule 0 to rule 6 (10ed0058fd760f764cc7b849e6f0e22f1e4dc6bb, upheld in b7cf6855b0ad1e30ac33bc9a53ef4268fdf686cf), because doing so would mean being able to softlock the game by not having any player entity.
So, in this patch, I'm making it so that you *can* convert duplicate …
> Allow calling flipgravity() on duplicate player entities

- desktop_version/src/Script.cpp
In 2.0, 2.1, and 2.2, calling `flipgravity()` on an entity that wasn't rule 6 would change it to rule 7. In 2.3 currently, doing this will only change it to rule 7 if it's already rule 6, starting with the introduction of the change where if an entity was rule 7 it would be changed to rule 6.
The crewmate conversion trick has been restored, but converting an entity to a crewmate will change its rule to 6, not 7 like in pre-2.3. If you want it to be changed to rule 7 instead of 6, you'd have to call `flipgravity()` twice in 2.3 and only once in pre-2.3, which would make maintaining compatibility between versions a bit harder.
So to fix this, I'm inverting it so that if you call `flipgravity()` on an entity that isn't rule 7, it will be converted to rule 7, and only if it's rule 7 will it …
> Fix flipgravity() rule conversion being inverted

- desktop_version/src/Graphics.cpp
Due to #464, standing inside a gravity line during a gotoroom that occurs every frame will end up with the gravity line being gray instead of being white. To temporarily fix this (until #464 is properly fixed), I decided to add some kludge that colors it white if its onentity is 1. I tested this patch with gravity lines in both constant-gotoroom and normal environments, and it seems to be fine for both.
Attached is a level where you can test this for yourself.
* [gravity_lines_gotoroom_test.zip](https://github.com/TerryCavanagh/VVVVVV/files/5284326/gravity_lines_gotoroom_test.zip)
> Add kludge to fix rendering of gravity lines in a gotoroom

- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
The game has four different functions for the same XML schema: `Game::loadtele()`, `Game::savetele()`, `Game::loadquick()`, and
`Game::savequick()`. This essentially means one XML schema has been copy-pasted three different times.
I can at least trim that number down to being copy-pasted only one time by de-duplicating the reading and writing part. So both `Game::loadtele()` and `Game::loadquick()` now use `Game::readmaingamesave()`, and `Game::savetele()` and `Game::savequick()` now use `Game::writemaingamesave()`.
This will make it take less work to add XML forwards compatibility (#373).
> De-duplicate reading and writing main game telesaves and quicksaves

- desktop_version/CONTRIBUTORS.txt
- desktop_version/src/Credits.h
- desktop_version/src/editor.cpp
In-level, they were made to be gray in #323. The editor does not reflect this however; they're still shown as
green. For the same reasons in #323, this adds special cases to draw the entities as gray.
Closes #372.
Also, I changed my name in `contributors.txt` to be my username as I didn't feel comfortable with it being my name.
> Fix entities in the Warp Zone's gray tileset not being gray in the editor

- desktop_version/src/Entity.cpp
- desktop_version/src/Entity.h
- desktop_version/src/Logic.cpp
This is a PR to primarily improve code maintainability.
Supercrewmate collision detection has been copy-pasted from player collision detection and tweaked slightly, instead of abstracting the collision detection routines to proper generalized functions. This copy-pasting makes the codebase less maintainable, because if you fix a problem in one routine, you'd have to remember to fix it in the other routine, or otherwise the other routine could have the same issue.
So that's what I do here. Supercrewmate and player collision detection functions are now more-or-less the same thing.
> Consolidate player and supercrewmate collision detection

- desktop_version/src/Entity.cpp
- desktop_version/src/Game.cpp
- desktop_version/src/Graphics.cpp
- desktop_version/src/Input.cpp
- desktop_version/src/Logic.cpp
- desktop_version/src/Map.cpp
- desktop_version/src/Music.cpp
- desktop_version/src/Otherlevel.cpp
- desktop_version/src/Render.cpp
- desktop_version/src/Script.cpp
- desktop_version/src/Script.h
- desktop_version/src/UtilityClass.h
- desktop_version/src/editor.cpp
The game currently has these problems with its bounds checks, all of which this PR fixes:
- It was sometimes using manually-typed bounds checks instead of the macros, which is inconsistent. Also, some of these manually-typed bounds checks are wrong!
- It was falsely assuming it would be sufficient to check `i > -1` and not the other end, *especially* in script commands, where the lack of checking of the other end could lead to potential out-of-bounds indexing given a fuzzer!
- In the same vein, it was also falsely assuming entity getters that returned a default value of 0 would also be fine to not check, leading to the same situation with certain script commands as above.
- And sometimes it just plain flat-out didn't bounds-check certain things.
By submitting this pull request, I confirm …
> Fix up bounds checks

- desktop_version/src/Graphics.cpp
This fixes a bug where `font_positions` wouldn't get cleared after exiting a custom level that had a `font.txt` if it didn't exist in the default graphics, leading to messed-up-looking font rendering.
This is what the bug looks like:
And here's a test level so you can see for yourself:
* [charmap_test_level.zip](https://github.com/TerryCavanagh/VVVVVV/files/5285069/charmap_test_level.zip)
This bug was originally discovered by @AllyTally.
> Clear font_positions if there is no font.txt

- desktop_version/src/Entity.cpp
For some reason, the variable `k` is on `entityclass` and gets mutated in `createentity()` and `createblock()`. Then `updateentities()` uses it without checking if it's valid, because either `k` or the size of `entities` could have changed in the meantime. To fix any potential undefined behavior, these bounds checks should be added.
> Add bounds checks to indexing of global "temporary" variable `k`

- desktop_version/src/Entity.cpp
`checktrigger()` returns a gamestate number, not the index of an entity.
Whoops.
> Don't use bounds check for result of checktrigger(), it's a gamestate

- desktop_version/src/Map.cpp
This is like the previous patch, but for `twoframedelayfix()`, because I forgot to read the comment that talked about `twoframedelayfix()`.
> Don't use bounds check for checktrigger() in twoframedelayfix()

- desktop_version/src/Scripts.cpp
Instead of copying to a temporary string, just use `SDL_strncmp()`. Also, I checked the blame, and apparently I committed the line that used `strcmp()` instead of `SDL_strcmp()`, for whatever reason. But that's fixed now.
> Make 'custom_' check more readable

- desktop_version/src/UtilityClass.cpp
It's possible that `SDL_atoi()` could call the libc `atoi()`, and if a string is provided that's too large to fit into an integer, then that would result in undefined behavior. To avoid this, use `SDL_strtol()` instead.
> Prevent potential undefined behavior with integer underflow/overflow with help.Int()

- desktop_version/src/editor.cpp
This prevents users from being confused whenever they type a pipe in the script editor, then save the level and load it again and see their script lines unexpectedly splitting in two. Now if you attempt to type a pipe, it simply won't happen at all.
Fixes #379.
> Prevent typing pipes in the script editor

- desktop_version/src/Entity.cpp
- desktop_version/src/Entity.h
- desktop_version/src/Logic.cpp
- desktop_version/src/Map.cpp
This is a refactor that simply moves all temporary variables off of `entityclass`, and makes it so they are no longer global variables. This makes the resulting code easier to understand as it is less entangled with global state.
These attributes were:
- `colpoint1`
- `colpoint2`
- `tempx`
- `tempy`
- `tempw`
- `temph`
- `temp`
- `temp2`
- `tpx1`
- `tpy1`
- `tpx2`
- `tpy2`
- `temprect`
- `temprect2`
- `x` (actually unused)
- `dx`
- `dy`
- `dr`
- `px`
- `py`
- `linetemp`
- `activetrigger`
- `skipblocks`
- `skipdirblocks`
Most of these attributes were assigned before any of the times they were used, so it's easy to prove that ungloballing them won't change any behaviors. However, `dx`, `dy`, `dr`, and `skipblocks` are a bit more tricky to analyze. They relate to blocks, with `dx`, `dy`, and …
> Move all temporary variables off of entityclass

- desktop_version/src/Entity.cpp
- desktop_version/src/Entity.h
- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
- desktop_version/src/Graphics.cpp
- desktop_version/src/Graphics.h
- desktop_version/src/KeyPoll.cpp
- desktop_version/src/KeyPoll.h
- desktop_version/src/Map.cpp
- desktop_version/src/Map.h
- desktop_version/src/Music.cpp
- desktop_version/src/Music.h
- desktop_version/src/Script.cpp
- desktop_version/src/Script.h
- desktop_version/src/UtilityClass.cpp
- desktop_version/src/UtilityClass.h
- desktop_version/src/editor.cpp
- desktop_version/src/editor.h
By "unnecessary qualifiers to self", I mean something like using the `game.` qualifier for a variable on the `Game` class when you're inside a function on the `Game` class itself. This patch is to enforce consistency as most of the code doesn't have these unnecessary qualifiers.
To prevent further unnecessary qualifiers to self, I made it so the extern in each header file can be omitted by using a define. That way, if someone writes something referring to `game.` on a `Game` function, there will be a compile error.
However, if you really need to have a reference to the global name, and you're within the same `.cpp` file as the implementation of that object, you can just do the extern at the function-level. A good example of this is `editorinput()`/`editorrender()`/`editorlogic()` in …
> Clean up and prevent unnecessary qualifiers to self

- desktop_version/src/Ent.cpp
- desktop_version/src/Ent.h
- desktop_version/src/Entity.cpp
These attributes were `jumping` and `jumpframe`. Removal of unused attributes makes reading the code easier.
> Remove unused attributes from entclass

- desktop_version/src/Entity.cpp
The `onroof`/`onground` attributes are used to determine if the player is standing on a surface and is eligible to flip. Most notably, it is an integer and not a boolean, and it starts at 2, giving the player 2 frames to edge-flip, i.e. they can still flip 2 frames after walking off an edge.
However, these attributes are unnecessarily reassigned in `movingplatformfix()` (which is the function that deals exclusively with vertically-moving platforms; horizontal moving platforms get their own `hormovingplatformfix()`). Whoever wrote this misunderstood what `onroof`/`onground` meant; they thought that they were booleans, and so set them to true, instead of the proper value of 2. This ends up setting `onroof`/`onground` to 1 instead of 2, causing a discrepancy with vertical moving platforms …
> Remove duplicate onroof and onground assignments for vertically-moving platforms

- desktop_version/src/Entity.cpp
So, 77a636509bf3b2a429f18bcae0615b898aa7321b fixed the fact that you only got 1 frame of onground/onroof when standing on a vertical moving platform, but removing those lines entirely means that it takes 1 frame before the onground/onroof of 2 actually takes effect. This desyncs my Nova TAS, so it seems important to fix.
> Fix onground/onroof taking 1 frame to apply after landing on a vertical moving platform

- desktop_version/src/Entity.cpp
- desktop_version/src/editor.cpp
* **Fix spawning from an exotic checkpoint setting invalid gravitycontrol**
An exotic checkpoint is a checkpoint with a sprite that is neither the flipped checkpoint nor unflipped checkpoint. More specifically, it's a checkpoint whose edentity p1 attribute is something other than 0 or 1.
Normally, whenever you touch an exotic checkpoint in-game, your savepoint's y-position and gravitycontrol don't get touched. However, in the editor, spawning from an exotic checkpoint means that your gravitycontrol gets set to a value that is neither 0 nor 1. In this invalid gravitycontrol state, Viridian is treated like they're flipped, but they cannot unflip.
This is an inconsistency between the editor and in-game, so I'm fixing it. Now, spawning from an exotic checkpoint in the editor will just set …
> Fix inconsistencies with checkpoints, spawn points, and start points

- desktop_version/src/Music.cpp
- desktop_version/src/main.cpp
Previously, setting the actual volume of the music was all over the place. Which isn't bad, but when I added being able to press N to mute the music specifically, I should've made it so that there would be a volume variable somewhere that the game looks at if the music is unmuted, and otherwise sets the actual volume to 0 if the game is muted.
This resulted in things like #400 and #505 and having to add a bunch of special-cased checks like `game.musicmuted` and `game.completestop`. But instead of adding a bunch of special-case code, just make it so there's a central place where `Mix_VolumeMusic()` actually gets called, and if some piece of code wants to set the music volume, they can set `music.musicVolume`. But the music handling logic in `main.cpp` gets the final say on whether to …
> Clean up music handling and put it in one place

- desktop_version/src/Entity.cpp
- desktop_version/src/Entity.h
- desktop_version/src/Logic.cpp
This patchset restores the evaluation order of moving platforms and conveyors to be what it was in 2.2. The evaluation order changed in 2.3 after the patchset to improve the handling of the `obj.entities` and `obj.blocks` vectors (#191).
By evaluation order, I'm talking about the order in which platforms and conveyors will be evaluated (and thus will take priority) if Viridian stands on both a conveyor or platform at once, and they either have different speeds or are pointing in different directions. Nowhere in the main game is there a place where you can stand on two different conveyors/platforms at once, so this is solely within the territory of custom levels, which is my specialty.
So what caused this evaluation order to change? Well, every moving platform and conveyor in the game is …
> Restore moving platform and conveyor evaluation order to what it was in 2.2

- desktop_version/src/Ent.cpp
- desktop_version/src/Ent.h
- desktop_version/src/Entity.cpp
- desktop_version/src/Game.cpp
- desktop_version/src/Graphics.cpp
- desktop_version/src/Logic.cpp
- desktop_version/src/Map.cpp
- desktop_version/src/Script.cpp
- desktop_version/src/main.cpp
I was investigating a desync in my Nova TAS, and it turns out that the gravity line collision functions check for the `oldxp` and `oldyp` of the player, i.e. their position on the previous frame, along with their position on the current frame. So, if the player either collided with the gravity line last frame or this frame, then the player collided with the gravity line this frame.
Except, that's not actually true. It turns out that `oldxp` and `oldyp` don't necessarily always correspond to the `xp` and `yp` of the player on the previous frame. It turns out that your `oldyp` will be updated if you stand on a vertically moving platform, before the gravity line collision function gets ran. So, if you were colliding with a gravity line on the previous frame, but you got moved out of there by …
> Restore previous oldxp and oldyp variables in favor of lerpoldxp and lerpoldyp

- desktop_version/src/editor.cpp
I got this warning when compiling VVVVVV again after a while:
```
/home/david/g/github_vvvvvv/dav999fork/VVVVVV/desktop_version/src/editor.cpp: In function ‘void editorrender()’:
/home/david/g/github_vvvvvv/dav999fork/VVVVVV/desktop_version/src/editor.cpp:2697:29: warning: name lookup of ‘i’ changed
if(edentity[i].p1<=4)
^
/home/david/g/github_vvvvvv/dav999fork/VVVVVV/desktop_version/src/editor.cpp:2656:14: warning:   matches this ‘i’ under ISO standard rules
for (int i = edentity.size() - 1; i >= 0; i--)
^
/home/david/g/github_vvvvvv/dav999fork/VVVVVV/desktop_version/src/editor.cpp:2691:26: warning:   matches this ‘i’ under old rules
for (int i = 0; i < 4; i++) {
^
```
It points out there are two nested for loops both defining `i` in what looks to be the code that draws entities in the …
> Fix "name lookup of ‘i’ changed" warning in editor.cpp

- desktop_version/src/Entity.cpp
- desktop_version/src/Logic.cpp
There is this issue with conveyors where if you collide with them, your intended next y-position doesn't get updated to the position of the conveyor, and then your y-position gets set to your intended next y-position. This also applies to horizontally moving platforms.
This bug used to not produce any problems, if at all, until #502 got merged. Since then, respawning from checkpoints that are on conveyors would sometimes not update your y-position at all, making it possible to get stuck inside a death loop that would require you to exit the game and re-enter it.
But you can always reliably create this bug simply by going into the editor and placing down a conveyor and checkpoint on top of each other. Then enter and exit playtesting a bunch of times, and you'll notice the glitchy …
> Fix conveyor/platform collisions with newyp, and getting stuck inside certain conveyors

- desktop_version/src/Map.cpp
The intent of #504 was to make it so `oldxp`/`oldyp` would never be messed with for over-30-FPS stuff, but I forgot that I changed these assignments in my over-30-FPS patch when I was doing #504. So these assignments have been restored to the way they were in 2.2, and is fixed now.
> Re-add original oldxp/oldyp assignments of player in mapclass::gotoroom()

- desktop_version/src/Graphics.cpp
- desktop_version/src/Screen.cpp
- desktop_version/src/Screen.h
The window icon is simply another asset that can be customized by level makers. And in fact, one of my levels changes the window icon. It's simply named `VVVVVV.png`, but it doesn't sit in the `graphics` folder, rather it sits in the root VVVVVV directory.
I noticed that this asset was missed when per-level assets loading was added, so I decided to add it in.
> Reload window icon when mounting and unmounting assets

- desktop_version/src/Entity.cpp
Scripting crewmates apparently have a specific hardcoded rule in their follow-player code that makes it so if they're in (10,5) and are to the left of the line x=155, they will refuse to continue following the player. This was clearly done to make it so Vitellary in the main game wouldn't overlap the teleporter, and that was clearly done to make it so it wouldn't look like he would go behind the teleporter, which would look weird (I also noticed this in #513).
I stumbled across this code and thought that just like other weird main-game code that shouldn't apply in custom levels (#136, #137, #144), this should be fixed, too.
section of the credits for all of said releases, but will …
> Disable hardcoded (10,5) no-follow rule of scripting crewmates in custom levels

- desktop_version/src/Script.cpp
These commands now use the `INBOUNDS_ARR()` macro to convey intent, and to make sure that if the size of the array changes in the future, that the bounds check wouldn't end up being wrong. Also fixed some code style for the `flag()` and `ifcrewlost()` commands.
> Clean up bounds checks and style for customifflag/flag/ifflag/ifcrewlost

- desktop_version/src/Graphics.cpp
- desktop_version/src/Graphics.h
On the deltaframes of the tower background, there would be "pixel bleed" if the tower background would be scrolling from the top. This is because there wouldn't be any more pixels from above the screen to grab, because the background rendering functions didn't draw any pixels above the screen. But they couldn't draw any pixels above the screen, because that was simply the end of the buffer. So this PR expands the buffer, and then draws above the screen to fix this glitchy interpolation rendering.
> Fix the interpolation of the tower background when it scrolls from the top

- desktop_version/src/Map.cpp
- desktop_version/src/Map.h
I was working on fixing #369, when I noticed these attributes and wondered what they were for, because I had never really seen them before. It turns out that they aren't used for anything, so they can be safely removed and I don't have to worry about analyzing them.
> Removed unused attributes towercol and RGB() from mapclass

- desktop_version/src/Graphics.cpp
- desktop_version/src/Graphics.h
`Graphics::tl` is unused. `Graphics::bcol` and `Graphics::bcol2` are temporary variables that shouldn't be on a global class.
> Remove unused Graphics::tl and move bcol and bcol2 temporary variables off of Graphics

- desktop_version/src/main.cpp
Whoops. But I'm not sure if not explicitly setting the blend mode of `towerbuffer_lerp` actually did anything bad or not.
> Fix copy-paste error with SetSurfaceBlendMode of towerbuffer_lerp

- desktop_version/src/Map.cpp
- desktop_version/src/Map.h
Yet another set of temporary variables is on a global class when they shouldn't be. These two are only used in tower background functions and are never used anywhere else, so they're clearly temporaries.
> Move check/cmode temporary variables off of mapclass

- desktop_version/src/editor.h
The author, description, and title of the level are actually stored on the `EditorData` instance. These attributes do nothing and should be removed.
> Remove unused attributes author/description/title from editorclass

- desktop_version/src/Game.cpp
- desktop_version/src/Graphics.cpp
- desktop_version/src/Graphics.h
- desktop_version/src/Input.cpp
- desktop_version/src/Logic.cpp
- desktop_version/src/Map.cpp
- desktop_version/src/Map.h
- desktop_version/src/Render.cpp
- desktop_version/src/Script.cpp
- desktop_version/src/TowerBG.h
- desktop_version/src/editor.cpp
- desktop_version/src/main.cpp
This PR fixes #369 by doing what I suggested - splitting the three usages of one buffer into three separate buffers. Well, technically, it was one buffer plus its lerp buffer, and there needs to be a lerp buffer for each buffer; so now we have six buffers, three of which are the "main" ones, plus three lerp ones. I just threw out a bunch of numbers. Oh, also, the tower and title screen backgrounds have a bunch of other variables associated with them, so I put them in an object, but you can always just read the diffs for details like that.
> Separate the tower background, title screen background, and horizontal and vertical warp backgrounds into separate buffers

- desktop_version/CMakeLists.txt
- desktop_version/src/Game.cpp
- desktop_version/src/XMLUtils.cpp
- desktop_version/src/XMLUtils.h
- desktop_version/src/editor.cpp
- desktop_version/src/editor.h
This PR adds XML forwards compatibility, meaning extra XML data will be preserved if the game encounters it while writing an XML file. It assumes that the XML data is from some future version of the game and tries very hard not to throw it away. It does this by loading in the current XML when it saves it, and instead of creating a new XML document from scratch, it takes the existing document and updates it in place.
There are exceptions, of course. The most notable ones are that unknown attributes of `<edLevelClass>` and `<edEntity>` are *not* preserved. This is because they would take extra work to support (you can't just blindly keep the attributes for the same indice between reading and writing, in the meantime the user could have changed the order around or deleted edentities, so then …
> Add XML forwards compatibility

- desktop_version/src/Ent.cpp
- desktop_version/src/Ent.h
- desktop_version/src/Graphics.cpp
- desktop_version/src/Graphics.h
This fixes the draw order by drawing all other entities first, before then drawing all humanoids[1] after, including the player afterwards.
This is actually a regression fix from #191. When I was testing this, I was thinking about where get a crewmate in front of another entity in the main game, other than the checkpoints in Intermission 1. And then I thought about the teleporters, because I remember the pre-Deep Space cutscene in Dimension Open looking funny because Vita ended up being behind the teleporter. (Actually, a lot of the cutscenes of Dimension Open look funny because of crewmates standing behind terminals.)
So then I tried to get crewmates in front of teleporters. It actually turns out that you can't do it for most of them... except for Verdigris. And then that's what I …
> Fix crewmates being drawn behind other entities

- desktop_version/src/Graphics.cpp
This commit fixes a bug that also sometimes occurred in 2.2, where the teleporter sprite would randomly turn into a solid color and just be a solid circle with no detail.
Why did this happen? The short answer is an incorrect lower bound when clamping the teleporter sprite index in `Graphics::drawtele()`. The long answer is bad RNG with the teleporter animation code. This commit fixes the short answer, because I do not want to mess with the long answer.
So, here is what would happen: the teleporter's `tile` would be 6. The teleporter code decrements its `framedelay` each frame. Then when it reached a `framedelay` of 0, it would call `fRandom()` and essentially ask for a random number between 0 and 6. If the RNG ended up being greater than or equal to 4, then it would set its `walkingframe` …
> Fix teleporter sprites sometimes being solid colors

- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
- desktop_version/src/Input.cpp
- desktop_version/src/Render.cpp
- desktop_version/src/Script.cpp
When touching a teleporter or quicksaving the game, the game would always explicitly say saving was successful, even if the save actually failed. Now both telesaving and quicksaving can alternatively show an error message:
This partially covers #377.
> Add error messages for game save failure

- desktop_version/src/Game.cpp
Whenever you delete all your save data, your settings aren't changed at all, and you could resave them if you fiddled with a setting somewhere. But the full game doesn't count Flip Mode as a setting, instead it counts it as an unlock. This means deleting your save data would unset Flip Mode in M&P, which would seem weird because in M&P it's just a simple setting.
For consistency, Flip Mode shouldn't be unset when deleting save data in M&P.
> Don't unset Flip Mode when deleting all data in M&P

- desktop_version/src/Graphics.cpp
- desktop_version/src/Music.cpp
- desktop_version/src/Render.cpp
- desktop_version/src/editor.cpp
In C++, when you have two variables in different scopes with the same name, the inner scope wins. Except you have to be really careful because sometimes they're not (#507). So it's better to just always have unique variable names and make sure to never clash a name with a variable in an outer scope - after all, the C++ compiler and standard might be fine with it, but that doesn't mean humans can't make mistakes reading or writing it.
Usually I just renamed the inner variables, but for `tx`/`ty` in `editor.cpp`, I just got rid of the ridiculous overcomplicated modulo calculations and replaced them with actual simple modulo calculations, because the existing ones were just ridiculous. Actually, somebody ought to find every instance of the overcomplicated modulos and replace them with the …
> Fix variables shadowing other variables

- desktop_version/src/Entity.cpp
`cppcheck` said: "Logical disjunction always evaluates to true".
Yes. Yes it does. Whoops. I learned how to specify ranges like this in high school math and still screw it up...
> Fix conveyor check in entityclass::collisioncheck() always being true

- desktop_version/src/Map.cpp
This fixes a deltaframe glitch where the "- Press ENTER to Teleport -" prompt would show up for a split second if you exited the game while the prompt was fully faded in, and then re-entered it.
> Fix game.oldreadytotele not being reset in mapclass::gotoroom()

- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
- desktop_version/src/Input.cpp
- desktop_version/src/XMLUtils.cpp
- desktop_version/src/XMLUtils.h
- desktop_version/src/main.cpp
The game previously did this dumb thing where it lumped in all its settings with its file that tracked your records and unlocks, `unlock.vvv`. It wasn't really an issue, until 2.3 came along and added a few settings, suddenly making a problem where 2.3 settings would be reset by chance if you decided to touch 2.2.
The solution to this is to move all settings to a new file, `settings.vvv`. However, for compatibility with 2.2, settings will still be written to `unlock.vvv`.
The game will prioritize reading from `settings.vvv` instead of `unlock.vvv`, so if there's a setting that's missing from `unlock.vvv`, no worries there. But if `settings.vvv` is missing, then it'll read settings from `unlock.vvv`. As well, if `unlock.vvv` is missing, then `settings.vvv` will be read from instead (I …
> Move all settings to settings.vvv

- desktop_version/src/Input.cpp
Here's what causes #401: After the fade to menu delay ticks down to 0, the game calls `game.quittomenu()`, but the rest of `mapinput()` still executes. This means that the block that detects your ACTION press gets executed, because there's a check that `fadetomenudelay` is less than or equal to 0, and, well, it is.
So if you've pressed ACTION on the exact frame that it counts down to 0, then the game detects your ACTION press, then processes it accordingly, and then sets the `fadetomenudelay`, which means it'll get reactivated the next time you open the map screen. But at this point, you get sent to TITLEMODE, because `game.quittomenu()` set `game.gamestate` accordingly. (This is why resetting `game.fadetomenu` or `game.fadetomenudelay` in `game.quittomenu()` or `script.hardreset()` won't …
> Fix ACTION press processing on the same frame as the fade to the title screen ticks to 0

- desktop_version/src/Game.cpp
- desktop_version/src/Music.cpp
- desktop_version/src/Music.h
- desktop_version/src/Script.cpp
The cause of #390 is the `music.fadeoutqueuesong` system stepping on the toes of the `music.nicechange` system, when they both do basically the same thing. So `music.fadeoutqueuesong` has been removed in favor of using `music.nicechange`, which fixes #390.
Also, I fixed some code that didn't properly account for being able to have a number of MMMMMM tracks that *wasn't* 16 (yet again, sigh...). And fixed some style.
Fixes #390.
> Merge music.fadeoutqueuesong system into music.nicechange system, fix more music code not accounting for dynamic number of MMMMMM tracks

- desktop_version/src/Entity.cpp
This check is clearly meant for destroying the factory clouds in the room "Level Complete!" in the main game, but it covers all rooms on row 8, instead of only (13,8). Adding an x-room check restricts this behavior to only (13,8).
Trinket9 reported that this weird behavior of destroying specifically above y-position 60 was undesirable, since they were creating an enemy with this `behave` in a room on row 8 and it kept disappearing instantly.
> Add x-room = 13 check to entity 1 `behave` 13

- desktop_version/src/main.cpp
Just a small thing I noticed when working on fixing #464. It's always good to use the SDL stdlib where possible.
> Use SDL_fmodf() instead of libc fmodf()

- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
- desktop_version/src/Logic.cpp
In #522 itself, I removed some of the kludge that existed before the tower, title, and warp buffers each got separated, but I forgot to remove all of them in that PR. So this PR cleans up some of the stragglers.
> Remove in-game menu kludge that was rendered unnecessary by #522

- desktop_version/src/Input.cpp
These were needed when the title and tower background shared the same buffer, but since #522 got merged, these are no longer necessary.
> Remove unneeded graphics.titlebg assignments when going to in-game settings

- desktop_version/src/Logic.cpp
Originally this function was made because it needed to be exported to `gameinput()`, but this piece of code is actually also used in `gamecompletelogic()`. So it's good to de-duplicate it here, too.
> De-duplicate titleupdatetextcol() in gamecompletelogic()

- desktop_version/src/GraphicsUtil.cpp
I can't really make the filter update only every timestep, because it's per-pixel and operates on deltaframes too, so it *technically* runs faster in over-30-FPS mode than not. That said, it's not really noticeable, the filter doesn't look bad for updating more often or anything. However, I can at least interpolate the scrolling, so it's smooth in over-30-FPS mode.
> Interpolate scrolling in Analogue Mode filter

- desktop_version/src/editor.cpp
What's the difference between a slash sign and a percent sign? Well, a percent sign is just a slash sign with two extra oranges in between, but those two oranges make a huuuuge difference...
> Fix edentities not rendering at all in the editor

- desktop_version/src/Logic.cpp
This bug would happen if you die and the platform isn't completely clear of the space of its adjacent disappearing platform.
The block needs to be updated accordingly with calls to `obj.nocollisionat()` and `obj.moveblockto()`, else the block will simply be left behind and the platform will no longer have any collision. This is in contrast to 2.2 behavior, where the platform would simply unconditionally create a new block, which would actually end up with a duplicate block since the previous block didn't get cleaned up, but this didn't cause any problems because the room was carefully designed so you would never be able to touch that previous block after you died and respawned at the checkpoint. But it's still there.
I also added comments to document what this kludge code did, because …
> Fix Prize for the Reckless moving platform losing its block when you die and the platform's x-coordinate is to the left of x=152

- desktop_version/src/Music.cpp
- desktop_version/src/Music.h
This PR fixes a couple of annoying bugs I found just now that screw with the status of having MMMMMM selected in Game Options (which are tracked by *two different variables*(!!!) `game.usingmmmmmm` and `music.usingmmmmmm`) whenever you load a custom level that has assets. It would call `graphics.reloadresources()`, which would call `music.init()`, which would reset way more variables than necessary.
That duplicate variable thing should probably be fixed. In fact there's more duplicate state tracking than just this `game.usingmmmmmm` and `music.usingmmmmmm` example. But fixing those will be a separate patch... …
> Fix bugs with the status of having MMMMMM selected whenever a custom level with assets is entered or exited

- desktop_version/src/Render.cpp
Apparently, the amount of digits in a commit hash that git will output varies depending on how many objects are in the repository that the hash gets pulled from. The more objects, the more digits needed to avoid a hash collision.
Sources:
- https://stackoverflow.com/q/18134627/#comment26560283_18134919
- https://stackoverflow.com/a/21015031/
So that means we'll have to dynamically account for the length of the commit hash in order to get it properly right-aligned with the rest of the text.
> Don't hardcode offset of interim commit print

- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
- desktop_version/src/Input.cpp
- desktop_version/src/KeyPoll.cpp
- desktop_version/src/KeyPoll.h
- desktop_version/src/Render.cpp
- desktop_version/src/Screen.cpp
- desktop_version/src/Screen.h
- desktop_version/src/ScreenSettings.h
- desktop_version/src/editor.cpp
- desktop_version/src/main.cpp
There were a bunch of duplicate configuration variables in the game, e.g. having MMMMMM selected was tracked by both `game.usingmmmmmm` and `music.usingmmmmmm`. My guess is this was probably because argument passing in 2.2 would have gotten in the way of directly accessing variables (it seems like that's the reason why `invincibility` is on Game instead of mapclass), but either way, these duplicate variables can lead to a bunch of headache as they could get desynced, and one part of the code operates on one variable and another part uses the other one.
- `game.fullScreenEffect_badSignal` is a duplicate of `graphics.screenbuffer->badSignalEffect`
- `game.fullscreen` is a duplicate of `!graphics.screenbuffer->isWindowed`
- `game.stretchMode` is a duplicate of …
> Clean up duplicate settings-related variables 

- desktop_version/src/Input.cpp
- desktop_version/src/Render.cpp
PR #468 made it so you can use the menus while in a cutscene, in order to counteract softlocks. However, this has resulted in more unintentional behavior:
- `gamemode(teleporter)` breaks when opening the ENTER menu (Misa mentioned this)
- The player can now interrupt shakes and walks, and have their timers run out before resuming the cutscene
- After completing the game, the player can warp to the ship while a dialogue is active, and prevent themselves from advancing text (plus it's always rude to just teleport away while someone's talking)
- The player can peek at the map before hidecoordinates is run, and can also peek at what the game does with missing/rescued crewmates during cutscenes
This PR fixes the latter two issues. While a script is running, only the SAVE tab is now available. …
> Restrict the ENTER menu to saving while in a cutscene

- desktop_version/src/Logic.cpp
Today, I saw a video posted by Chelito on the VVVVVV speedrunning Discord where he died inside a gravitron square over and over after the Gravitron in Intermission 2 ended.
https://cdn.discordapp.com/attachments/234787368522088448/779074864660480020/What.mp4
This is caused by the fact that after the Gravitron ends, the game no longer considers you to be inside swnmode, so it won't move the enemies offscreen when you die.
To fix this, after the Gravitron ends, the game will switch to swngame 8, where it will keep you inside swnmode until all gravitron squares are offscreen. This means that gravitron squares that are onscreen after the Gravitron ends will be moved offscreen if you die, preventing the above death loop from happening. …
> Maintain game.swnmode until all gravitron squares are offscreen

- desktop_version/CMakeLists.txt
- desktop_version/src/Input.cpp
- desktop_version/src/Logic.cpp
- desktop_version/src/Logic.h
- desktop_version/src/RenderFixed.cpp
- desktop_version/src/RenderFixed.h
- desktop_version/src/editor.cpp
- desktop_version/src/editor.h
- desktop_version/src/main.cpp
- desktop_version/src/preloader.cpp
- desktop_version/src/preloader.h
As part of fixing #464, I'll need to move these pieces of code around easily. In #220 I just kind of shoved them awkwardly in whatever fixed function would be last called in the gamestate loop, which I shouldn't have done as I've now had to make formal fixed-render functions anyway. Because these fixed functions need to be called directly before a render function, and I'm fixing the order to put render functions in their proper place, so I need to be able to move these around easily, and making them function calls instead of inlined makes them easier to manipulate.
> Move all fixed-timestep render updates to new file RenderFixed.cpp

- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
- desktop_version/src/Input.cpp
- desktop_version/src/Render.cpp
Changing settings would most of the time attempt to save `unlock.vvv` and now also `settings.vvv`, but there would be no feedback whether the files have been saved successfully or not. Now, if saving fails when changing settings in the menu, a warning message will be shown. The setting will still be applied of course, but the user will be informed it couldn't be saved. This message can be silenced until the game is restarted, because I can imagine this could get very annoying when someone already knows their settings aren't writeable.
Note that the message shows up if either `unlock.vvv` or `settings.vvv` fails to be saved, even if one of them succeeds and the user wouldn't notice it in principle. Both files will still be attempted individually, but I have no idea how the user could …
> Add error messages for failed writes to disk of settings

- desktop_version/src/main.cpp
- desktop_version/src/preloader.cpp
- desktop_version/src/preloader.h
While there already exists an option to skip the fake loading screen entirely (without requiring an ACTION press), there are several reasons for including this option as well:
* So people upgrading from 2.2 won't have to sit through the fake loading screen the first time they open 2.3.
* So if people are too lazy to use the existing option, they can use this one instead.
* So tool-assisted speedruns (TASes) of this game can skip the fake loading screen without requiring an existing `settings.vvv` beforehand.
This last one is the biggest reason for me, since I'm not sure what TASVideos.org rules are regarding existing save files, but with this change nobody has to worry about their rules and can safely just press ACTION to skip the fake loading screen automatically.
Currently, when you …
> Allow pressing ACTION to skip the fake loading screen

- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
- desktop_version/src/Input.cpp
- desktop_version/src/Logic.cpp
- desktop_version/src/Script.cpp
- desktop_version/src/main.cpp
In order to be able to fix the bug #556, I'm planning on adding `ScreenSettings*` to the `settings.vvv` write function. However, that entails adding another argument to `Game::savesettings()`, which is going to be really messy given the default argument of `Game::savestats()`. That, combined with the fact that the code comment at the site of the implementation of `Game::savestats()` being wrong (!!!), leads me to believe that using default function arguments here isn't worth it.
Instead, what I've done is made it so callers are explicit about whether or not they're calling `savestats()`, `savesettings()`, or both at the same time. If they are calling both at the same time, then they will be using a new function named `savestatsandsettings()`.
In short, these are the interface changes:
* …
> Refactor Game::savestats() to not use a default argument

- desktop_version/src/Game.cpp
- desktop_version/src/Game.h
- desktop_version/src/Screen.cpp
- desktop_version/src/Screen.h
Another step to fix the bug #556 is to allow `Game::savestats()` to accept a pointer to an existing `ScreenSettings` struct. This entails refactoring `Game::savesettings()` and `Game::serializesettings()` to accept the function as well, along with adding `Screen::GetSettings()` so the settings of the current `Screen` can be easily grabbed.
> Allow Game::savestats() to accept a pointer to ScreenSettings

- desktop_version/src/Game.cpp
To fix this bug, all we have to do is just pass the existing `ScreenSettings*` that we have in `loadstats()` to `savestats()`, and in `loadsettings()` to `savesettings()`.
Fixes #556. Depends on #558.
> Fix segfault when settings.vvv or unlock.vvv is missing

- desktop_version/src/Map.cpp
- desktop_version/src/Script.cpp
- desktop_version/src/main.cpp
While I was working on #535, I noticed that all the call sites of `script.run()` have the exact same code, namely:
```c++
if (script.running)
{
script.run();
}
```
I figured, why not move the `script.running` check into the function itself? That way, we won't have to duplicate the check every single time, and we don't risk forgetting to add the check and causing a bug because of that.
The check was already duplicated once since 2.0 (it's used in both GAMEMODE and TELEPORTERMODE), and with the fix of the two-frame delay in 2.3, it's now duplicated twice, leading to *three* instances of this check in the code, when there should be only one.
section of the credits for all of said …
> De-duplicate script.running checks

- desktop_version/src/Input.cpp
While working on #535, I noticed this bug.
When going to Graphic Options or Game Options from the pause menu, `kludge_ingametemp` was intended to save the current menu stack frame *before* either of those menus got created. However, it was actually assigned afterwards, meaning `kludge_ingametemp` would always be either `Menu::graphicoptions` or `Menu::options`.
This meant that the `returntomenu()` in `returntopausemenu()` would always attempt to return to the current in-game menu, and seeing as it's the same menu, would re-create the menu, instead of returning to the previous menu before it.
This patch also fixes a potential source of a trivial memory leak, if someone were to keep entering and exiting Graphic Options or Game Options from the pause menu. It would keep piling up duplicate …
> Fix kludge_ingametemp being assigned after menu creation

- desktop_version/.gitignore
- desktop_version/CMakeLists.txt
- desktop_version/src/Render.cpp
- desktop_version/src/Version.h
- desktop_version/src/Version.h.in
The previous implementation of showing the commit hash on the title screen used a preprocessor definition added at CMake time to pass the hash and date. This was passed for every file compiled, so if the date or hash changed, then every file would be recompiled. This is especially annoying if you're working on the game and switching branches all the time - the game has at least 50 source files to recompile!
To fix this, we'll switch to using a generated file, named `Version.h.out`, that only gets included by the necessary files (which there is only one of - `Render.cpp`). It will be autogenerated by CMake (by using `CONFIGURE_FILE()`, which takes a templated file and does a find-and-replace on it, not unlike C macros), and since there's only one file that includes it, only one file will …
> Don't recompile all files when the commit hash is changed
