desktop_version/CONTRIBUTORS.txt, desktop_version/src/FileSystemUtils.cpp, desktop_version/src/SteamNetwork.c
Thanks for making a pull request! Before making a pull request, we have some
things for you to read through first:
- We generally do not accept patches for formatting fixes, unless the formatting
fixes are part of a functional patch (for example, when fixing a bug in a
function you can fix up the lines surrounding it if needed).
- Patches that break compatibility with the original game data or save data will
not be accepted.
- New features and user interface changes will most likely not be accepted
unless they are for improving user accessibility.
- New platforms are acceptable if they use SDL + PhysicsFS and don't mess with
the game source too much.
- (No homebrew console targets, sorry! Maybe do the work in SDL instead?)
- Pull requests that do not fill out the Legal Stuff will be …
=> Freebsd fix

desktop_version/CONTRIBUTORS.txt, desktop_version/src/SoundSystem.cpp
=> Avoid segfault with bad, missing, or corrupted audio

desktop_version/src/main.cpp
It serves no purpose and clutters up the visual field.
=> Hide mouse cursor in game window

desktop_version/.gitignore
Prevents contributors from adding them by mistake to the Git repo.
=> Add .gitignore with build artifacts and data.zip

desktop_version/CONTRIBUTORS.txt, desktop_version/src/FileSystemUtils.cpp, desktop_version/src/SteamNetwork.c
Thanks for making a pull request! Before making a pull request, we have some
things for you to read through first:
- We generally do not accept patches for formatting fixes, unless the formatting
fixes are part of a functional patch (for example, when fixing a bug in a
function you can fix up the lines surrounding it if needed).
- Patches that break compatibility with the original game data or save data will
not be accepted.
- New features and user interface changes will most likely not be accepted
unless they are for improving user accessibility.
- New platforms are acceptable if they use SDL + PhysicsFS and don't mess with
the game source too much.
- (No homebrew console targets, sorry! Maybe do the work in SDL instead?)
- Pull requests that do not fill out the Legal Stuff will be …
=> Add OpenBSD support

desktop_version/CONTRIBUTORS.txt, desktop_version/src/UtilityClass.cpp
- [X ] My changes may be used in a future commercial release of VVVVVV (for
- [X ] I will be credited in a `CONTRIBUTORS` file for all of said releases, but
Cleans up the implementation of `UtilityClass::number`, should do a lot for code readability / making it more approachable :)
=> Clean up UtilityClass::number implementation

desktop_version/CONTRIBUTORS.txt, desktop_version/src/FileSystemUtils.cpp
Adds support for symbolic links.
=> Support symbolic links

desktop_version/src/UtilityClass.cpp
Use `SDL_HasIntersection` instead of custom intersection detection in `UtilityClass::intersects`.
=> Use SDL_HasIntersection for UtilityClass::intersects

desktop_version/src/Graphics.cpp
This is similar to what was reverted in 3011911 but this time should use
syntax available even before C++11, tested on Clang with
`-std=c++98 -Wall -pedantic`.
=> Simplify initializations

desktop_version/src/main.cpp
* **Fix mute button not working at all**
Whoops, looks like I forgot to test that I didn't break the mute button completely in #72.
=> Fix mute button not working at all

desktop_version/src/Script.cpp
* **Fix the `flipgravity()` internal command**
There are two main problems with `flipgravity()`:
​ ​ 1. It doesn't work for an already-flipped crewmate.
​ ​ 2. It doesn't work on the player.
This PR addresses both of those issues.
=> Fix the flipgravity() internal command

desktop_version/src/Entity.cpp, desktop_version/src/TerminalScripts.cpp, desktop_version/src/editor.cpp, mobile_version/src/entityclass.as, mobile_version/src/includes/terminalscripts.as
* **Correct capitalization of song names**
This corrects things like "Passion for exploring" and "Passion For Exploring" to be "Passion for Exploring".
=> Correct capitalization of song names

mobile_version/levels/labclass.as, mobile_version/src/includes/scripts.as
* **Fix "Exausted?" and "scentists" typos in mobile version**
=> Fix "Exausted?" and "scentists" typos in mobile version

desktop_version/src/Entity.h
Looks like in my original pull request I forgot to make `obj` accessible from everywhere. Oh well.
=> Make obj accessible from everywhere

desktop_version/src/MakeAndPlay.h
* **Re-comment out `#define MAKEANDPLAY`**
Silly me forgot to remove it after testing the MAKEANDPLAY define.
=> Re-comment out #define MAKEANDPLAY

third_party/lodepng/LICENSE.txt, third_party/lodepng/lodepng.c, third_party/lodepng/lodepng.h, third_party/utfcpp/source/utf8/core.h, third_party/utfcpp/source/utf8/unchecked.h
Updated `lodepng` and `utfcpp`
=> Update lodepng and utfcpp

desktop_version/CONTRIBUTORS.txt, desktop_version/src/FileSystemUtils.cpp, desktop_version/src/SteamNetwork.c
More or less the same as what had to be done for FreeBSD (#11) / OpenBSD (#34), just fix the build for DragonFlyBSD.
=> Fix build on DragonFlyBSD

desktop_version/CONTRIBUTORS.txt, desktop_version/src/Game.cpp
Just a tiny change to replace my old name with my new one. Name is rendered as "Fussmatte" in-game, but should be updated to "Fußmatte" when the Unicode font is added to the game.
=> Update Stelpjo's name to Fußmatte

desktop_version/src/Logic.cpp
=> Change a '||' to a '=='

desktop_version/src/editor.cpp
=> [HOTFIX] Fix pressing Enter moving you leftwards in the editor

desktop_version/src/BinaryBlob.cpp, desktop_version/src/BlockV.cpp, desktop_version/src/Entity.cpp, desktop_version/src/FileSystemUtils.cpp, desktop_version/src/Finalclass.cpp, desktop_version/src/Finalclass.h, desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/Graphics.cpp, desktop_version/src/Graphics.h, desktop_version/src/GraphicsResources.cpp, desktop_version/src/KeyPoll.cpp, desktop_version/src/KeyPoll.h, desktop_version/src/Labclass.cpp, desktop_version/src/Labclass.h, desktop_version/src/Map.cpp, desktop_version/src/Map.h, desktop_version/src/Music.cpp, desktop_version/src/Otherlevel.cpp, desktop_version/src/Otherlevel.h, desktop_version/src/Textbox.cpp, desktop_version/src/WarpClass.cpp, desktop_version/src/WarpClass.h, desktop_version/src/editor.cpp
This is a re-do of #354, but without adding constructors.
=> Ensure that member attributes of most classes are initialized

desktop_version/src/Game.cpp
Missed adding probably the most important part. :woman_facepalming: 
=> Missed adding the option to the createmenu method.

desktop_version/src/FileSystemUtils.cpp
=> Fix other array decay too

desktop_version/src/Game.cpp, desktop_version/src/Scripts.cpp
You're intended to rescue Violet first, and not second, third, or fourth, and especially not last.
If you rescue her second, third, or fourth, your crewmate progress will be reset, but you won't be able to re-rescue them again. This is because Vitellary, Verdigris, Victoria, and Vermilion will be temporarily marked as rescued during the `bigopenworld` cutscene, so duplicate versions of them don't spawn during the cutscene, and then will be marked as missing later to undo it.
This first issue can be trivially fixed by simply toggling flags to prevent duplicates of them from spawning during the cutscene instead of fiddling with their rescue statuses.
However, there is still another issue. If you rescue Violet last, then you won't be warped to the Final Level, meaning you can't properly …
=> Fix unwinnable save from rescuing Violet out of order

desktop_version/src/Ent.cpp
I forgot to fix these when I was doing #504.
=> Fix lerpoldxp/lerpoldyp not being updated in entclass::setenemy() and entclass::setenemyroom()

desktop_version/src/Entity.cpp, desktop_version/src/Graphics.cpp
Ever since 2.0, the colors of some of the Time Trial trophies in the Secret Lab don't correspond to the crewmate of the given level. The trophy for the Tower uses Victoria's color, and the Lab trophy uses Vermilion's color. The Space Station 2 trophy uses Viridian's color, and the Final Level trophy uses Vitellary's color.
This doesn't appear to be intentional, and it would be odd if it was, since this game matches the colors everywhere else (each zone on the map is colored with their respective crewmate in mind, for instance). Also, the Lab trophy has the sad expression, which is Victoria's trait - it would be weird if this was intended for Vermilion instead.
But the biggest piece of evidence that this was unintentional is the corresponding comment for each color in `Graphics::setcol()`. …
=> Fix Secret Lab Time Trial trophies having wrong colors

desktop_version/src/Game.cpp, desktop_version/src/UtilityClass.cpp, desktop_version/src/UtilityClass.h, desktop_version/src/editor.cpp
This is just a general grab-bag of cleanups I did after refactoring `ss_toi()` to not use stringstreams.
=> Miscellaneous cleanups with UtilityClass.cpp and some of editor.cpp

desktop_version/src/Graphics.cpp, desktop_version/src/GraphicsUtil.cpp, desktop_version/src/GraphicsUtil.h, desktop_version/src/Input.cpp, desktop_version/src/Render.cpp, desktop_version/src/Screen.cpp, desktop_version/src/editor.cpp, desktop_version/src/main.cpp, desktop_version/src/preloader.cpp
I've replaced all `FillRect()`s that clear a surface with a new function named `ClearSurface()` to better convey the intent of the code. I've also done some other cleanups as well; view the commits for details, as always.
=> Clean up some graphics code, mostly including ClearSurface()

desktop_version/README.md
This is the same thing as #626, but without all the other changes that were lumped in with that PR.
Closes #626.
=> Add SDL2 version number to desktop_version/ README

desktop_version/src/Graphics.cpp, desktop_version/src/Render.cpp
=> De-duplicate Flip Mode textbox printing and Gravitron initial message

desktop_version/src/Graphics.cpp
So #434 didn't end up solving the deltaframe flashing fully, only reduced the chances that it could happen.
I've had the Level Complete image flash a few times when the Game Saved text box pops up. This seems to be because the Level Complete image is based off of the text box being at y-position 12, and the Game Saved text box is also at y-position 12. Level Complete only gets drawn if the text box additionally has a red channel value of 165, and the Game Saved text box has a red channel value of 174. However, there is a check that the text box be fully opaque first before drawing special images. So what went wrong?
Well, after thinking about it for a while, I realized that even though there is indeed an opaqueness check, the alpha of the text box updates *before* it gets drawn. And …
=> Fix text box deltaframe flashing on deltaframes after fully opaque

desktop_version/src/Render.cpp
=> Add period to text outline description and capitalize "OFF" in invincibility description

desktop_version/src/Render.cpp
This is to be consistent with the other options in the Advanced Options menu.
=> Add period to glitchrunner mode description text

desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/KeyPoll.cpp, desktop_version/src/KeyPoll.h, desktop_version/src/Music.cpp, desktop_version/src/Music.h, desktop_version/src/Script.cpp, desktop_version/src/main.cpp
So it looks like facb079b3597b380f876537523cd351a0e637b62 (PR #316) had a few issues.
The SDL performance counter doesn't really work that well. Testing reveals that unfocusing and focusing the game again results in the `resumemusic()` script command resuming the track at the wrong time. Even when not unfocusing the game at all, stopping a track and resuming it resumes it at the wrong time. (Only disabling the unfocus pause fixes this.)
Furthermore, there's also the fact that the SDL performance counter keeps incrementing when the game is paused under GDB. So... yeah.
Instead of dealing with the SDL performance counter, I'm just going to pause and resume the music directly (so the `stopmusic()` script command just pauses the music instead). As a result, we no longer can keep constantly …
=>  Re-fix resumemusic/musicfadein once again

desktop_version/CONTRIBUTORS.txt
Hi, I did a small patch a bit ago and saw 2.3 is getting in beta now, and I realize I put my old domain that I'll probably be letting expire so I changed it. That's all. Thanks!
=> CONTRIBUTORS.txt: Update contact info

desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/Input.cpp, desktop_version/src/Render.cpp
It turns out, despite the game attempting to prevent you from using invincibility or slowdown in the Super Gravitron by simply preventing you from entering the Secret Lab from the menu, it's still possible to enter the Super Gravitron with it anyways. Just have invincibility or slowdown (or both!) enabled, enter the game normally, and talk to Victoria when you have 20 trinkets, to start the epilogue cutscene.
Yeah, that's a pretty big gaping hole right there...
It's also possible to do a trick that speedrunners use called telejumping to the Secret Lab to bypass the invincibility/slowdown check, too.
So rather than single-case patch both of these, I'm going to fix it as generally as possible, by moving the invincibility/slowdown check to the gamestate that starts the Super Gravitron, …
=> Move Secret Lab invincibility/slowdown check to Super Gravitron

desktop_version/src/Input.cpp
=> Play Viridian squeak when returning to Secret Lab

desktop_version/src/Input.cpp
=> Play Viridian squeak when returning to Super Gravitron

desktop_version/src/Input.cpp
Well, I accidentally deleted #796. Let's try this again.
=> Play Viridian squeak when exiting to menu

desktop_version/src/FileSystemUtils.cpp, desktop_version/src/FileSystemUtils.h, desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/Graphics.cpp, desktop_version/src/Graphics.h, desktop_version/src/Input.cpp, desktop_version/src/Render.cpp, desktop_version/src/Script.cpp, desktop_version/src/UtilityClass.h, desktop_version/src/editor.cpp, desktop_version/src/main.cpp
#808 
This is the second time I've accidentally deleted an open PR branch, let's try this again...
=>  Be more user-friendly if levels have asset/zip issues

desktop_version/src/editor.cpp
=> Editor: Play Viridan squeak when entering a script

desktop_version/CONTRIBUTORS.txt, desktop_version/src/Credits.h
Update own name to "Reese Rivers" in credits.
=> Update own name for credits

desktop_version/src/FileSystemUtils.cpp
The chances of someone using 2.0, then directly jumping to 2.4, are pretty low - 2.0 is almost a decade old at this point.
=> Axe save file migration

desktop_version/src/FileSystemUtils.cpp
These tweaks allow VVVVVV to be compiled for a new Unix-like platform with no source changes.
=> Improve FileSystemUtils.cpp portability

desktop_version/src/Input.cpp
Fixes #839 (and https://github.com/TerryCavanagh/VVVVVV/issues/839#issuecomment-911137578).
=> Fix flipping regressions

desktop_version/CMakeLists.txt, desktop_version/src/KeyPoll.cpp, desktop_version/src/main.cpp
A couple small Emscripten fixes. See individual commits for details.
=> Miscellaneous Emscripten fixes

.github/workflows/ci.yml
As I requested in #864, this changes the workflow to build out-of-tree.
=> Build out-of-tree in workflows

desktop_version/src/Music.cpp
=> Fix semi random volume jumps

desktop_version/lang/eo/strings.xml, desktop_version/lang/eo/strings_plural.xml
Some small updates to the Esperanto translation, namely `strings.xml` and `strings_plural.xml` (more concise wording, fixing some minor mistakes).
=> Update Esperanto translation

desktop_version/src/Font.cpp
An example is Maximally Misleading Miserable Misadventure, which has a font.txt which includes all ASCII characters starting with a 0x00 byte. This would accidentally null-terminate the string too early.
Instead, we now use the total length of the file again, and keep getting the next UTF-8 codepoint until the file ends. We still need to null-terminate it - it protects against incomplete sequences getting the UTF-8 decoder to read out of bounds.
=> Fix loading font .txt files that contain null bytes

desktop_version/CMakeLists.txt
The CI has always been fairly slow on Windows, so I decided to look into it a little bit to see where the bottlenecks are. Nowadays it seems to be faster than I remember it being - Windows CI runs nowadays seem to be around 3-4 minutes. Still, the faster CI finishes, the more comfortable it is (since we get faster feedback). If every CI could finish after a minute like the Linux one, that'd be even nicer.
The biggest bottleneck on Windows seems to be the initial CMake configure step - on Linux and macOS, this step is near-instant or a couple of seconds at most. On Windows, it can take a lot longer, sometimes more than a minute, most of the time at least 40 seconds, but it varies a lot. It's always slower than on Linux and macOS by a serious amount, though (see the table below).
As for why …
=> Add /MP to CMakeLists for Windows for (slightly) faster CI

desktop_version/src/BlockV.cpp, desktop_version/src/CustomLevels.cpp, desktop_version/src/CustomLevels.h, desktop_version/src/Game.cpp, desktop_version/src/Graphics.cpp, desktop_version/src/Graphics.h, desktop_version/src/RoomnameTranslator.cpp, desktop_version/src/Script.cpp, desktop_version/src/Script.h
Since we now have a custom textbox colors system, it doesn't make sense to keep the built-in colors hardcoded. This PR moves them to the new system, and also unhardcodes some colors which were manually passed into functions.
=> Unhardcode text colors

desktop_version/lang/README-programmers.txt, desktop_version/lang/ca/strings.xml, desktop_version/lang/de/strings.xml, desktop_version/lang/en/strings.xml, desktop_version/lang/eo/cutscenes.xml, desktop_version/lang/eo/meta.xml, desktop_version/lang/eo/strings.xml, desktop_version/lang/es/strings.xml, desktop_version/lang/fr/strings.xml, desktop_version/lang/it/cutscenes.xml, desktop_version/lang/it/meta.xml, desktop_version/lang/it/roomnames.xml, desktop_version/lang/it/strings.xml, desktop_version/lang/it/strings_plural.xml, desktop_version/lang/nl/strings.xml, desktop_version/lang/pt_BR/cutscenes.xml, desktop_version/lang/pt_BR/meta.xml, desktop_version/lang/pt_BR/strings.xml, desktop_version/lang/pt_BR/strings_plural.xml, desktop_version/lang/pt_PT/strings.xml, desktop_version/lang/ru/strings.xml, desktop_version/lang/tr/strings.xml, desktop_version/src/Render.cpp
- Portuguese (BR) and Italian have been updated to the latest delivered versions
- Dutch and Esperanto are 100% translated again (new strings)
- Added section on editing existing strings to README-programmers.txt
Leaving this a draft for a few days to include possible further updates.
=> Language updates

desktop_version/src/CustomLevels.cpp, desktop_version/src/Graphics.cpp, desktop_version/src/Graphics.h, desktop_version/src/Render.cpp, desktop_version/src/RoomnameTranslator.cpp
Simple cleanup of `Graphics.cpp`.
- Adds more draw functions (and overloads) for future usage
- Replaces lines/pixels drawn with rectangles with functions which actually draw lines and pixels
- Speeds up custom minimap generation by batching pixel draws together (and again, not drawing pixels with 1x1 rectangles)
- Some unused background code stripped out
- Some missing casts fixed
- General formatting cleanup
=> Graphics cleanup

desktop_version/src/LocalizationStorage.cpp
I kinda forgot about these, but they should be checked.
=> Add limits check to roomnames and roomnames_special

desktop_version/lang/ja/strings.xml
Applying a fix from the Japanese translator.
=> Language patch - Fix inconsistency in "FINAL LEVEL MASTERED" in Japanese

desktop_version/lang/ca/strings.xml, desktop_version/lang/eo/strings.xml, desktop_version/lang/nl/strings.xml
- Bring Catalan, Dutch and Esperanto language files 100% up-to-date with upstream again
- Improve some Dutch menu strings
=> Language patches: Catalan, Dutch and Esperanto

desktop_version/lang/tr/cutscenes.xml, desktop_version/lang/tr/meta.xml, desktop_version/lang/tr/strings.xml
This fixes some translations that were too long for the newly translated strings.
=> Language patch - Apply latest fixes to some Turkish strings

desktop_version/lang/pl/cutscenes.xml, desktop_version/lang/pl/strings.xml, desktop_version/lang/szl/cutscenes.xml, desktop_version/lang/szl/strings.xml, desktop_version/lang/szl/strings_plural.xml
Updates to Polish and Silesian were delivered a couple hours ago.
=> Language patches - Polish and Silesian

desktop_version/lang/eo/strings.xml
The localization credits are now also translated.
This PR is set to merge into `final_string_updates`.
=> Language patch - Final strings for Esperanto (credits part)

desktop_version/lang/ca/cutscenes.xml, desktop_version/lang/cy/cutscenes.xml, desktop_version/lang/de/cutscenes.xml, desktop_version/lang/en/cutscenes.xml, desktop_version/lang/eo/cutscenes.xml, desktop_version/lang/es/cutscenes.xml, desktop_version/lang/fr/cutscenes.xml, desktop_version/lang/ga/cutscenes.xml, desktop_version/lang/it/cutscenes.xml, desktop_version/lang/ja/cutscenes.xml, desktop_version/lang/ko/cutscenes.xml, desktop_version/lang/nl/cutscenes.xml, desktop_version/lang/pl/cutscenes.xml, desktop_version/lang/pt_BR/cutscenes.xml, desktop_version/lang/pt_PT/cutscenes.xml, desktop_version/lang/ru/cutscenes.xml, desktop_version/lang/szl/cutscenes.xml, desktop_version/lang/tr/cutscenes.xml, desktop_version/lang/uk/cutscenes.xml, desktop_version/lang/zh/cutscenes.xml, desktop_version/lang/zh_TW/cutscenes.xml, desktop_version/src/Scripts.cpp
Now that the language files are fairly stable, we should be able to do this without any accidental reverts taking place (if any do happen, it should be easy to see and prevent)
Before:
=> Fix "he'd be a a big help" typo

desktop_version/lang/nl/cutscenes.xml, desktop_version/lang/nl/strings.xml
I put a main focus on the first cutscenes in the game, changing the first "Uh oh..." from something like "Oh dear..." to "Oh no..." to make sure it always sounds right. (The real translation of "Uh oh" is "O-o", but that seemed too easy to read wrong for the first line in the game that I wanted to avoid it altogether.)
=> Make some minor refinements to Dutch translation

desktop_version/src/Font.cpp
VVVVVV 2.2 only supported displaying characters 00-7F with its font system. VVVVVV 2.3 added support for unicode, by supplying a font.txt with all the characters that are in the font image. But 2.3 made another change that I didn't immediately realize, even after reading the code: if font.txt is not present, then the font is not assumed to have _only_ 00-7F, but _all_ of unicode, as far as the image dimensions allow.
However, an inconsistency I _did_ notice is how unknown characters would be rendered in 2.3. If a font had a font.txt, then any unknown characters would be shown as a '?'. If a font had no font.txt however, then suddenly any unknown characters would just come out as a space. I fixed this behavior with the new font system; but what was actually happening for characters to come …
=> Load plain font.png beyond U+007F

desktop_version/src/Graphics.cpp
This is quite a last-minute thing that was almost getting called off by me discovering a critical segfault just now in testing this (whew) but this shouldn't hurt.
=> Move author face to the right for RTL languages

.github/pull_request_template.md
Translators have been getting compensated for localization. Sometimes they submit pull requests for their changes, but just because they do doesn't mean that they won't get compensated.
The intent of this line was to make sure that any random contributor wouldn't expect any compensation for their changes, so adding another clause here still keeps that expectation while making it clear that it's not like @TerryCavanagh _never_ compensates people. Even if, as a Swedish man once sung, "Terry is a monster, I think we all know that".
^^^ This is the updated line!
=> PR template: Clarify compensation

desktop_version/lang/ar/cutscenes.xml, desktop_version/lang/ar/meta.xml, desktop_version/lang/ar/numbers.xml, desktop_version/lang/ar/strings.xml
This update was delivered earlier today!
=> Apply updates to Arabic language files

desktop_version/src/Screen.cpp
This fixes the possibility of the "resize to nearest" graphics option resizing the game window to be bigger than the resolution of the user's desktop monitor.
To fix this, just subtract multiples of 320x240 until the chosen multiple is smaller than the dimensions of the desktop.
Discord user Dzhake discovered this issue.
=> Fix "resize to nearest" potentially resizing to a resolution larger than the user's desktop resolution

.github/workflows/android.yml, desktop_version/VVVVVV-android/README.md, desktop_version/VVVVVV-android/app/build.gradle
=> Update Android SDL2 to 2.30.8

desktop_version/src/Ent.cpp, desktop_version/src/Ent.h, desktop_version/src/Entity.cpp, desktop_version/src/LevelDebugger.cpp, desktop_version/src/Logic.cpp, desktop_version/src/Map.cpp, desktop_version/src/Script.cpp
In an effort to remove magic numbers, I've given every entity type a name. Hopefully I didn't miss anywhere.
=> Convert entity `type`s to an enum
