TerryCavanagh/VVVVVV

desktop_version/CMakeLists.txt, desktop_version/version.cmake
The commit hash is now properly updated every time it gets changed, and not just when CMake gets re-ran.
For this to work, we need to use a few CMake tricks. We add a custom target with `ADD_CUSTOM_TARGET()`, which is apparently always considered out-of-date (but I had to add a `BYPRODUCTS` line to get it to actually work), and we use the target to run a `.cmake` file every time we build. Also, VVVVVV needs to depend on this custom target, to ensure that the game gets built *after* the version gets generated - otherwise there'll be an error. So we do an `ADD_DEPENDENCIES()` after the `ADD_EXECUTABLE()` for VVVVVV.
This file, `version.cmake`, is just the `Version.h.out` generation that I added previously, but the important thing about all of this is that if the contents of `Version.h.out` …
=> Update commit hash every time it changes, not just when CMake is re-ran

desktop_version/src/Render.cpp
Since `INTERIM_COMMIT` is a char array whose size we know for sure at compile time, and which we also know is an array (instead of being a pointer), we can take the `SDL_arraysize()` of it. However, `SDL_arraysize()` doesn't account for the null terminator unlike `SDL_strlen()`, so we'll have to do it ourselves. But at least we are guaranteed to get a constant value at compile time, unlike if we use `SDL_strlen()`, which would be repeatedly evaluating a constant value at runtime.
To my knowledge, there's no equivalent `SDL_arraysize()` for constant strings, and a quick `rg` (ripgrep) for `sizeof` in the SDL `include/` folder doesn't show anything like that. So we'll just have to use the `SDL_arraysize() - 1` and deal with it.
example, a …
=> Use SDL_arraysize() - 1 to take length of INTERIM_COMMIT

.github/workflows/ci.yml, desktop_version/CMakeLists.txt
CI builds were added to this repository on the first day it was released, and haven't really been touched since then. And since then, 2.3 has added `NO_CUSTOM_LEVELS`, `NO_EDITOR`, and `OFFICIAL_BUILD` builds to the CMake file.
On top of the `MAKEANDPLAY` define already existing, this means CI coverage is a bit sparse - covering compile failures for changes made to most of the codebase, except for Steam and GOG, and not covering compile failures if certain parts of the code get stripped out. And people do forget to check for those configurations as well.
These mess of configurations is kind of a wake-up call to refactor and generalize the code a bit, because we would probably be able to get rid of at least two of these (Make & Play, and no-custom-levels) by making it so custom levels …
=> Add official, M&P, no custom levels, and no editor builds to CI

desktop_version/src/Script.cpp
There's a small inconsistency where the first time you load in to the game, `game.lifeseq` is at 0, but when you exit to the menu and load in again, `game.lifeseq` becomes 10. This is visible as Viridian blinking when loading in only after the first time you load in, and this also means that after the first time you load in, you also have to wait 5 frames before being able to move Viridian.
The reason for this inconsistency is because on the first time you load in to the game, there are no entities loaded in `obj.entities` yet, so the game creates a player entity, and doesn't mess with `game.lifeseq`. When you exit and then load in for the second time, `obj.entities` contains at least one entity (all the entities from the room you just exited out of - `map.gotoroom()` hasn't even been …
=> Consistently set game.lifeseq to 0 when script.startgamemode() is called

desktop_version/src/Music.cpp
When exiting a level, `music.init()` gets called again, and every time it gets called after the first time it gets called, it will free all music tracks.
To do so, it calls `Mix_FreeMusic()`. Unfortunately, if there is music fading, `Mix_FreeMusic()` will call `SDL_Delay()`, which will result in annoying no-draw frames. Meaning, the screen freezes and doesn't draw anything, and has to wait a bit before continuing.
Here's the relevant piece of code from SDL2_mixer's `music.c`:
```c
if (music == music_playing) {
/* Wait for any fade out to finish */
while (music->fading == MIX_FADING_OUT) {
Mix_UnlockAudio();
SDL_Delay(100);
Mix_LockAudio();
}
if (music == music_playing) {
music_internal_halt();
}
}
```
This is especially annoying if you're a TASer, because no-draw frames in a libTAS movie …
=> Fix no-draw frames when exiting a level with custom assets

desktop_version/src/Logic.cpp, desktop_version/src/Map.cpp, desktop_version/src/Map.h, desktop_version/src/Script.cpp
When I did #567, I didn't test it. And I should have tested it, because it made the player invisible. This is because `map.resetplayer()` also sets the `invis` attribute of the player to true as well, and I only undid it setting `game.lifeseq` to 10.
So instead, I'll just add a flag to `map.resetplayer()` that by default doesn't set `game.lifeseq` or the player's `invis` attribute. And I tested it this time, and it works fine. I tested both respawning after death and exiting to the menu and loading in the game again.
=> Fix player being invisible upon loading into game again

desktop_version/src/Map.cpp
When I did #569, I forgot that taking out the code path that set the player's `invis` to false meant that the player would still be invisible upon loading back in to the game if they exited the game while invisible. Taking out that code path also meant that if `game.lifeseq` was nonzero, it wouldn't be reset properly, either. So this fixes those things.
=> Reset player invis attribute to false in mapclass::resetplayer()

desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/Input.cpp, desktop_version/src/Script.cpp
When bringing up the map screen, the game does a small menu animation where the menu comes in from the bottom. The code to calculate the menu offset is copy-pasted everywhere, so I thought I'd de-duplicate it to make my life easier when working with it. I also included the `game.gamestate` assignment in the de-duplicated function, so it would be easier for a future bugfix.
At the same time, I'm also removing all the `BlitSurfaceStandard()`s that copied `menubuffer` to `backBuffer`. The red flag is that this blit happened for every single entry point to `MAPMODE` and `TELEPORTERMODE`, except for the script command `gamemode(teleporter)`. Pressing Enter to bring up the map screen, pressing Enter to quit the Super Gravitron, pressing Esc to bring up the pause screen, and pressing Enter to …
=> De-duplicate menu animation code when bringing up map screen

desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/Input.cpp, desktop_version/src/RenderFixed.cpp, desktop_version/src/Script.cpp
When `gamemode(teleporter)` gets run in a script, it brings up a read-only version of the teleporter screen, intended only for displaying rooms on the minimap.
However, ever since 2.3 allowed bringing up the map screen during cutscenes (in order to prevent softlocks), bringing up the map screen during this mode would (1) do an unnecessary animation of suddenly switching back to the game and bringing up the menu screen again (even though the menu screen has already been brought up), and (2) would let you close the menu entirely and go back to `GAMEMODE`, thus unintentionally closing the teleporter screen and kind of ruining the cutscene.
To fix this, when you bring up the map screen, it will instead instantly transition to the map screen. And when you bring it down, it will also instantly …
=> Fix bringing up map menu during gamemode(teleporter)

desktop_version/src/Entity.cpp, desktop_version/src/Input.cpp
This prevents issues when calling std::abs with a float on some older compilers. While it would normally be promoted to an int, std::abs is special due to being overloaded despite being a C function. This can cause errors due to the compiler being unable to find a float overload. SDL_abs doesn't have this problem, since it's a normal C function.
From some testing, this issue occurs in g++ 6.4, but not 7.1. In addition, there does not appear to be a difference caused by `-std` flags (I tried the default, `-std=c++03`, `-std=c++11`, `-std=gnu++03`, and `-std=gnu++11`).
See discussion in #574.
=> Use SDL_abs instead of std::abs

desktop_version/src/Entity.cpp, desktop_version/src/Input.cpp
Despite @InfoTeddy having written [a short essay](https://github.com/TerryCavanagh/VVVVVV/pull/574#discussion_r550822082) about how I should've used `SDL_abs` in #575, it turns out that [this isn't actually true](https://godbolt.org/z/Pnh3Gj).
=> Use SDL_fabsf where std::abs was previously used 

desktop_version/src/Entity.cpp, desktop_version/src/Entity.h, desktop_version/src/Graphics.cpp, desktop_version/src/Graphics.h, desktop_version/src/GraphicsUtil.cpp, desktop_version/src/GraphicsUtil.h, desktop_version/src/KeyPoll.cpp, desktop_version/src/KeyPoll.h, desktop_version/src/SoundSystem.cpp, desktop_version/src/SoundSystem.h, desktop_version/src/editor.cpp, desktop_version/src/editor.h
Unused code is code that can't be tested for correctness, and so is code that will slowly rot from lack of maintenance. I ran `cppcheck --std=c++03 --enable=unusedFunction *.cpp` and identified all functions that are unused everywhere in the codebase. In case we need them back in the future, we can always refer to the Git history.
Here's the list of removed functions:
- `FlipSurfaceHorizontal()`
- `Graphics::PrintOff()`
- `Graphics::RPrint()`
- `Graphics::drawentcolours()`
- `edentclear()`
- `entityclass::fixfriction()`
- `KeyPoll::isUp()`
- `editorclass::placetile()`
- `SoundSystem::playMusic()`
- `Graphics::textboxcenter()`
- `Graphics::textboxmove()`
- `editorclass::warpzoneedgetile()`
- `editorclass::warpzonematch()`
example, a 2.3 …
=> Remove functions marked as unused by cppcheck

desktop_version/src/Music.cpp
While working on #580, I noticed that `musicclass::play()` had some inconsistent whitespace, as well as having control flow that meant nesting the rest of the function in two unnecessary levels of indentation. And that other PR would be much more readable if this function was improved. So I thought I'd fix it up first.
=> Clean up whitespace and control flow of musicclass::play()

desktop_version/src/Input.cpp, desktop_version/src/Music.cpp
With commit 48313169b68f8ef8e6f83f29830b789061219ffd (PR #453), @AllyTally added a single-case patch for a regression, instead of fixing it at its root cause.
In fact, that commit only fixes the music if Presenting VVVVVV is playing while exiting to the menu, not if you enter a level that plays Presenting VVVVVV - so it only fixes it going one way, and not going the other way around; neither fixing also all the other cases this could happen.
It doesn't, say, fix the case where you are exited to the menu automatically after collecting the last crewmate in the level (or if the level calls gamestate 1013 itself), which is what happens in my MIRA-VIU TAS video at the end, and which I noted in the description of that video ([link](https://www.youtube.com/watch?v=OYQO4ePbYW4&t=111)).
So, the …
=> Fix regression with playing the same track after it fades out

desktop_version/src/Input.cpp, desktop_version/src/main.cpp
This fixes a bug where if you completed a custom level during command-line playtesting, when returning to the title screen, the background would be red and the text would be white.
This is because playtesting skips over the code path of pressing ACTION to start the game and advance to the title screen, and the code path of that ACTION press specifically initializes the title screen colors to cyan.
This is also caused by the fact that completing a custom level doesn't call `map.nexttowercolour()`, but my guess is that the intent there was that the player would select a custom level, complete it, and return to the title screen on the same screen with the same colors, so I decided not to add a `map.nexttowercolour()` there.
Instead, I've moved the cyan color initialization to `main()`, so …
=> Move title screen color initialization to main()

desktop_version/src/Map.cpp, desktop_version/src/Map.h, desktop_version/src/RenderFixed.cpp, desktop_version/src/TowerBG.h, desktop_version/src/editor.cpp
This fixes a bug where if you entered a tower before watching the credits sequence, the credits sequence would have mismatched text and background colors.
This bug happened because entering a tower modified the `r`/`g`/`b` attributes of mapclass, and updated `graphics.towerbg`, without updating `graphics.titlebg` too. Then `gamecompleterender()` uses the `r`/`g`/`b` attributes of mapclass, which were meant to work with `graphics.towerbg`, but draws `graphics.titlebg` instead.
The solution is to put the `r`/`g`/`b` attributes on TowerBG instead. That way, entering a tower will only modify the `r`/`g`/`b` attributes used to render towers, and won't affect the `r`/`g`/`b` attributes used to render the credits sequence.
Additionally, I also de-duplicated the case-switch that updated the …
=> Move mapclass r/g/b variables off onto TowerBG

desktop_version/src/editor.cpp
So... it looks like being able to switch through tilesets backwards has been in 2.3 for a while, guess no one just uses 2.3 or the level editor that much. It seems like it's always been broken, too.
If you were on the Space Station tileset (tileset 0), pressing Shift+F1 would keep you on the Space Station tileset instead of switching to the Ship (tileset 4).
It looks like the problem here was mixing `size_t` and `int` together - so the modulus operation promoted the left-hand side to `size_t`, which is unsigned, so the -1 turned into `SIZE_MAX`, which is 18446744073709551615 on my system. You'll note that that ends in a 5, so the number is divisible by 5, meaning taking it modulo 5 leads to 0. So the tileset would be kept at 0.
At least unsigned integer underflow/overflow is properly …
=> Fix Shift+F1 from Space Station tileset not switching to Ship

desktop_version/src/editor.cpp
There is a certain ordering of which corners you click on to place enemy and platform boundaries, and script boxes. You must first click on the top-left corner, then click on the bottom-right corner. The visual box that is drawn after you've first clicked on the top-left corner clearly shows this intended way of doing things.
However, it seems like despite the visuals, the game didn't properly prevent you from clicking on the corners in the wrong way. If you placed it from top-right to bottom-left, or bottom-left to top-right, then the game would place the boxes accordingly, and they would have a weird shape where two of its opposite sides would just be missing. But, placing them from bottom-right to top-left is prevented accordingly.
The bug comes down to a simple use of "or", instead of …
=> Fix attempts to place enemy and platform bounds and script boxes with bad corner order (top-right to bottom-left, bottom-left to top-right)

desktop_version/src/main.cpp
Line clipping and second-frame edge-flipping have been broken since #539 was merged (d910c5118dc47ed0847485e15e7b315fe0420ff6). The cause of this is moving the `onground`/`onroof` code around.
A proper loop order fix is going to come once #535 gets finalized and merged, so this is a stopgap measure just to make sure people don't report that line clipping or second-frame edge-flipping are broken in current builds of 2.3.
=> Move gamerenderfixed() in between gameinput() and gamelogic()

desktop_version/src/FileSystemUtils.cpp, desktop_version/src/Game.cpp, desktop_version/src/GraphicsResources.cpp, desktop_version/src/GraphicsUtil.cpp, desktop_version/src/GraphicsUtil.h, desktop_version/src/Input.cpp, desktop_version/src/Music.cpp, desktop_version/src/Render.cpp, desktop_version/src/UtilityClass.cpp, desktop_version/src/editor.cpp, desktop_version/src/editor.h, desktop_version/src/main.cpp, desktop_version/src/preloader.cpp
This patch cleans up unnecessary exports from header files (there were only a few), as well as adds the `static` keyword to all symbols that aren't exported and are specific to a file. This helps the linker out in not doing any unnecessary work, speeding it up and avoiding silent symbol conflicts (otherwise two symbols with the same name (and type/signature in C++) would quietly resolve as okay by the linker).
=> Clean up unnecessary exports and add static keywords

desktop_version/src/editor.cpp
2.3's per-level assets feature also added a hotkey to reload the custom assets of the level you're currently editing in the editor, so you wouldn't have to re-load the level yourself. This hotkey is F9, but however, it hasn't been documented in the hotkey list brought up by pressing Shift, until now.
=> Add F9 "reload resources" hotkey to list of hotkeys in Shift menu

desktop_version/src/Game.cpp, desktop_version/src/Map.cpp, desktop_version/src/Map.h, desktop_version/src/Script.cpp
These variables basically serve no purpose. `map.customx` and `map.customy` are clearly never used. `map.finalx` and `map.finaly`, on the other hand, are basically always `game.roomx` and `game.roomy` respectively if `map.finalmode` is on, and if it's off, then they don't matter.
Also, there are some weird and redundant variable assignments going on with these; most notably in `map.gotoroom()`, where `rx`/`ry` (local variables) get assigned to `finalx`/`finaly`, then `finalx`/`finaly` get assigned to `game.roomx`/`game.roomy`, then `finalx`/`finaly` get assigned to `rx`/`ry`. If `finalx`/`finaly` made a difference, then there'd be no need to assign `finalx`/`finaly` back to `rx`/`ry`. So it makes the code clearer to remove these weird bits of code.
By submitting this pull request, I …
=> Remove map.finalx/map.finaly and map.customx/map.customy

desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/Input.cpp, desktop_version/src/main.cpp
This variable seems to have been intended to make sure `game.savestatsandsettings()` was called at the end of the frame, or make sure that it didn't get called more than once per frame. I don't see any frame ordering-related reason why it needs to be called specifically at the end of the frame (the function doesn't modify any state), so it's more plausible that it was added to make sure it didn't get called more than one per frame.
However, upon further analysis, none of the code paths where `game.savemystats` is used ever calls or sets `game.savemystats` more than once, and a majority of the code directly calls `game.savestatsandsettings()` anyway, so there's no reason for this variable to exist. If we ever need to make sure it doesn't get called more than once, and there's no way to …
=> Remove game.savemystats

desktop_version/src/editor.cpp
This patch de-duplicates the tool drawing code a bit in the menu that gets brought up when you press Space in the level editor, as well as fixes several bugs related to the fact that the original author(s) of the code decided to copy-paste everything. (It was most likely Terry, judging by the distinct lack of whitespace between tokens in the code.)
There are two "pages" of tools that get shown when you open the tool menu, according to your currently-selected tool.
1. On the first page, your currently-selected tool gets a brighter outline. However, on the second page, the code to draw the outline over your currently-selected tool is missing. So I've fixed that.
2. On the first page, the glyph indicator next to the tool icon also gets brighter when you have that tool selected. However, on …
=> Fix editor tool menu inconsistencies

desktop_version/CMakeLists.txt, desktop_version/src/FileSystemUtils.cpp, desktop_version/src/Game.cpp, desktop_version/src/Graphics.cpp, desktop_version/src/GraphicsResources.cpp, desktop_version/src/GraphicsUtil.cpp, desktop_version/src/KeyPoll.cpp, desktop_version/src/Map.cpp, desktop_version/src/Maths.h, desktop_version/src/Render.cpp, desktop_version/src/Screen.cpp, desktop_version/src/ThirdPartyDeps.c, desktop_version/src/UtilityClass.cpp, desktop_version/src/editor.cpp, desktop_version/src/main.cpp
During 2.3 development, there's been a gradual shift to using SDL stdlib functions instead of libc functions, but there are still some libc functions (or the same libc function but from the STL) in the code.
Well, this patch replaces all the rest of them in one fell swoop.
SDL's stdlib can replace most of these, but its `SDL_min()` and `SDL_max()` are inadequate - they aren't really functions, they're more like macros with a nasty penchant for double-evaluation. So I just made my own `VVV_min()` and `VVV_max()` functions and placed them in `Maths.h` instead, then replaced all the previous usages of `min()`, `max()`, `std::min()`, `std::max()`, `SDL_min()`, and `SDL_max()` with `VVV_min()` and `VVV_max()`.
Additionally, there's no `SDL_isxdigit()`, so I just implemented my own …
=> Reduce dependency on libc functions

desktop_version/src/Graphics.cpp
While compiling in release mode, GCC warns about these two potentially being used uninitialized further down. The only way this could happen is if the case-switches below didn't match up with a case, which would require the game to be in an invalid state (and have invalid values for `rcol` and `spcol`), but it's better to be safe than sorry.
=> Initialize bcol and bcol2 in Graphics::drawbackground()

desktop_version/src/Music.cpp
=> Fix wrong function being used for musicclass::play() check

desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/Input.cpp, desktop_version/src/Logic.cpp, desktop_version/src/Render.cpp, desktop_version/src/Script.cpp, desktop_version/src/editor.cpp
There are multiple different exit paths to the main menu. In 2.2, they all had a bunch of copy-pasted code. In 2.3 currently, most of them use `game.quittomenu()`, but there are some stragglers that still use hand-copied code.
This is a bit of a problem, because all exit paths should consistently have `FILESYSTEM_unmountassets(),` as part of the 2.3 feature of per-level custom assets. Furthermore, most (but not all) of the paths call `script.hardreset()` too, and some of the stragglers don't. So there could be something persisting through to the title screen (like a really long flash/shake timer) that could only persist if exiting to the title screen through those paths.
But, actually, it seems like there's a good reason for some of those to not call `script.hardreset()` - namely, dying …
=> Clean up all exit paths to the menu to use common code

desktop_version/src/GraphicsResources.cpp
Otherwise, if `SDL_CreateRGBSurfaceFrom()` returned NULL, then this memory would be leaked.
(Anyone testing this at the moment should cherry-pick #602 until that gets merged.)
=> Free data upon failure in LoadImage()

desktop_version/src/main.cpp
This call to `Makebfont()` always existed, but ever since 2.3's per-level custom assets were added, `graphics.reloadresources()` also calls `graphics.Makebfont()`, meaning this call is unnecessary. Calling it twice results in `graphics.bfont` and `graphics.flipbfont` having twice the number of elements, until custom assets get mounted (or unmounted, technically).
(Anyone testing this at the moment should cherry-pick #602 until that gets merged.)
=> Remove duplicate graphics.Makebfont() in main()

desktop_version/src/editor.cpp
Retextured checkpoints have always been in the game, but clicking on them in the editor would lead to them losing their retextured-ness. So, checkpoints should be left alone if their `p1` isn't either 0 or 1. Also, they don't show up properly in the editor, so that's fixed, too.
Retextured and flipped terminals were added in 2.3, and show up properly in-game, but don't properly show up in the editor, either. So now they show up in the editor. Additionally, clicking on them will flip the terminal as well, but only if its `p1` is 0 or 1, just like checkpoints now do.
=> Improve support for retextured checkpoints and terminals in the editor

desktop_version/src/UtilityClass.cpp
This fixes a bug where `"12"` gets properly evaluated as 12, but `"148"` gets evaluated as 1408. It's because `place` gets multiplied by `radix` again, so `retval` gets multipled by 100 instead of 10.
There's no reason to have a `place` variable, so I've removed it entirely. This simplifies the function a little bit.
Additionally, `radix` also now has static storage duration, because it's a constant integer literal.
=> Don't mutate the decimal place in ss_toi()

desktop_version/src/editor.cpp
`find_tag()` would commit out-of-bounds indexing if someone made a level file with malformed XML entity encodings in the metadata tags.
This would happen if the end of the string followed immediately after an ampersand and hash, or if there wasn't a semicolon ending an XML entity.
Valgrind complains about these, so I've fixed it.
=> Fix out-of-bounds indexing with malformed XML entities in find_tag()

desktop_version/src/Map.cpp, desktop_version/src/editor.cpp
MSVC complains about these, doesn't seem like GCC does. These can be safely removed because they're unreachable, and they always follow a case-switch or similar that has a default case which this code is a duplicate of anyway. (Unless it isn't, in which case all the better to remove it, becausee otherwise it looks misleading or confusing to casual glances at the code.)
=> Fix unreachable code warnings

desktop_version/src/BinaryBlob.cpp, desktop_version/src/BinaryBlob.h, desktop_version/src/Exit.h, desktop_version/src/FileSystemUtils.cpp, desktop_version/src/Game.cpp, desktop_version/src/Graphics.cpp, desktop_version/src/Graphics.h, desktop_version/src/Music.cpp, desktop_version/src/Music.h, desktop_version/src/Screen.cpp, desktop_version/src/Screen.h, desktop_version/src/Script.cpp, desktop_version/src/SoundSystem.cpp, desktop_version/src/editor.cpp, desktop_version/src/main.cpp
The other day, I ran this game under Valgrind and it reported a ton of stuff. Some of it was memory that wasn't really leaked but which we should clean up on program exit anyway just so Valgrind is useful, and most of the rest of it is 2.3 regressions that didn't exist in 2.2.
Here are all the resources which weren't technically being leaked (because they can't get leaked more than once), but which Valgrind reports, and is now properly cleaned up by the time of the game exiting:
- All `Screen` resources
- All `GraphicsResources` resources
- All `Graphics` resources (tile vectors and buffers)
- All `musicclass` resources
- The `musicWriteBlob` that writes a `BinaryMusic.vvv` to disk (if `VVV_COMPILEMUSIC` is defined)
Here are all the memory leaks that are fixed:
- Leaking memory if an …
=> Fix all memory errors reported by Valgrind (including some 2.3 regressions)

desktop_version/src/Game.cpp, desktop_version/src/Script.cpp, desktop_version/src/UtilityClass.cpp, desktop_version/src/UtilityClass.h, desktop_version/src/editor.cpp
The current way "arrays" from XML files are loaded (before this PR is applied) goes something like this:
1. Read the buffer of the contents of the tag using TinyXML-2.
2. Allocate a buffer on the heap of the same size, and copy the existing buffer to it. (This is what the statement `std::string TextString = pText;` does.)
3. For each delimiter in the heap-allocated buffer...
a. Allocate another buffer on the heap, and copy the characters from the previous delimiter to the delimiter you just hit.
b. Then allocate the buffer *again*, to copy it into an std::vector.
4. Then re-allocate every single buffer *yet again*, because you need to make a copy of the `std::vector` in `split()` to return it to the caller.
As you can see, the existing way uses a lot of memory allocations and data …
=> Refactor loading arrays from XML to not use the STL

desktop_version/src/UtilityClass.cpp, desktop_version/src/UtilityClass.h, desktop_version/src/editor.cpp
While working on an unrelated patchset, I noticed that these two functions could use some work. Then I worked on that other patchset further and it turned out that it didn't need to depend on any of the changes I was planning to make to these functions. So I've split these changes off into their own PR, which is this PR.
`is_positive_num()` no longer uses an `std::string` and instead uses a `const char*`, along with its `hex` argument becoming const. Code style of both `is_positive_num()` and `is_number()` has also been cleaned up.
But the biggest thing is probably the bug fixes; `is_positive_num()` and `is_number()` no longer accept empty strings as numbers, and `is_number()` no longer accepts the string `"-"` as a number, either. `VVV_isxdigit()` no longer accepts the entire alphabet as …
=> Clean up is_number(), is_positive_num(), and VVV_isxdigit(), and fix some of their bugs

desktop_version/src/editor.cpp
Otherwise this results in an infinite loop. Whoops.
=> Fix using ii instead of i in script serialization

desktop_version/src/BlockV.cpp, desktop_version/src/BlockV.h, desktop_version/src/Ent.cpp, desktop_version/src/Ent.h, desktop_version/src/Entity.cpp, desktop_version/src/Entity.h, desktop_version/src/Game.cpp, desktop_version/src/Input.cpp, desktop_version/src/Logic.cpp, desktop_version/src/Map.cpp, desktop_version/src/Script.cpp
This patch restores some 2.2 behavior, fixing a regression caused by the refactor of properly using `std::vector`s.
In 2.2, the game allocated 200 items in `obj.entities`, but used a system where each entity had an `active` attribute to signify if the entity actually existed or not. When dealing with entities, you would have to check this `active` flag, or else you'd be dealing with an entity that didn't actually exist. (By the way, what I'm saying applies to blocks and `obj.blocks` as well, except for some small differing details like the game allocating 500 block slots versus `obj.entities`'s 200.)
As a consequence, the game had to use a separate tracking variable, `obj.nentity`, because `obj.entities.size()` would just report 200, instead of the actual amount of entities. Needless to …
=> Fix entity and block indices after destroying them

desktop_version/CMakeLists.txt
If you configure the build with `-DBUNDLE_DEPENDENCIES=OFF`, then VVVVVV will dynamically link with TinyXML-2 and PhysicsFS instead of using the bundled source code in `third_party/` and statically linking with them.
Unfortunately, it doesn't seem like distros package LodePNG, and LodePNG isn't intended to be packaged, so we can't dynamically link with it, nor can we use some system LodePNG header files somewhere else because those don't exist.
UTF8-CPP is a special case, because no matter what, it's going to be statically linked with the binary (it doesn't come as a shared object file in any way). So with `-DBUNDLE_DEPENDENCIES=OFF`, we will use the system UTF8-CPP header files instead of the bundled ones, but it will still be statically linked in with the binary.
The main motivation for …
=> Add option to not use bundled TinyXML-2, PhysicsFS, and UTF8-CPP

desktop_version/src/BinaryBlob.cpp, desktop_version/src/BinaryBlob.h, desktop_version/src/Music.cpp
Just like I refactored text splitting to no longer use `std::vector`s, `std::string`s, or temporary heap allocations, decreasing memory usage and improving performance; there's no reason to use a temporary heap-allocated `std::vector` to grab all extra binary blob indices, when instead the iteration can just be more immediate.
Instead, what I've done is replaced `binaryBlob::getExtra()` with `binaryBlob::nextExtra()`, which takes in a pointer to an index variable, and will increment the index variable until it reaches an extra track. After the caller processes the extra track, it is the caller's responsibility to increment the variable again before passing it back to `getExtra()`.
This avoids all heap allocations and brings down the memory usage of processing extra tracks.
By submitting …
=> Refactor extra binary blob tracks to not use STL data marshalling

desktop_version/src/FileSystemUtils.cpp, desktop_version/src/FileSystemUtils.h, desktop_version/src/editor.cpp, desktop_version/src/editor.h, desktop_version/src/main.cpp
Note that level dir listing still uses plenty of STL (including the end product - the `LevelMetaData` struct - which, for the purposes of 2.3, is okay enough (2.4 should remove STL usage entirely)); it's just that the initial act of iterating over the levels directory no longer takes four or *six*(!!!) heap allocations (not counting reallocations and other heap allocations this patch does not remove), and no longer does any data marshalling.
Like text splitting, and binary blob extra indice grabbing, the current approach that `FILESYSTEM_getLevelDirFileNames()` uses is a temporary `std::vector` of `std::string`s as a middleman to store all the filenames, and the game iterates over that `std::vector` to grab each level metadata. Except, it's even worse in this case, because …
=> Refactor level dir listing to not use STL data marshalling

desktop_version/src/UtilityClass.cpp
`next_split_s()` could potentially commit out-of-bounds indexing if the amount of source data was bigger than the destination data.
This is because the size of the source data passed in includes the null terminator, so if 1 byte is not subtracted from it, then after it passes through the `VVV_min()`, it will index 1 past the end of the passed buffer when null-terminating it.
In contrast, the other argument of the `VVV_min()` does not need 1 subtracted from it, because that length does not include a null terminator (`next_split()` returns the length of the substring, after all; not the length of the substring plus 1).
(The `VVV_min()` here also shortens the range of values to the size of an `int`, but we'll probably make `size_t` versions anyway; plus who really cares about supporting …
=> Fix potential out-of-bounds in next_split_s() with regards to buffer length

desktop_version/src/Entity.cpp
This fixes a regression where moving platforms had no collision. Because their width and height would be maintained, but their type would be -1. (Also because I didn't test enough.)
In #565, I decided to set blocks' types to -1 when disabling them, to be a bit safer in case there was some code that used block types but not their width and heights. However, this means that when blocks get disabled and re-created in the platform update loops, their types get set to -1, which effectively also disables their collision.
In the end, I'll just have to compromise and remove setting blocks to type -1. Because in a better world, we shouldn't be destroying and creating blocks constantly just to move some platforms - however, fixing such a fundamental problem is beyond the scope of at least 2.3 …
=> Remove assigning block type to -1 when disabling them

desktop_version/src/FileSystemUtils.cpp
The recently released SDL 2.0.14 adds a native function for opening URIs from the host system, superseding the OS-specific implementations of FILESYSTEM_openDirectory.
This has only been tested on Linux. It should be tested on other platforms too.
=> Use SDL_OpenURL in FILESYSTEM_openDirectory

desktop_version/src/FileSystemUtils.cpp, desktop_version/src/Graphics.h, desktop_version/src/editor.cpp
One of these days, I need to get around to running Include What You Use on this codebase. Until then, while I was working on #624, I noticed these; I'm removing them now.
=> Remove unneeded <algorithm> includes

desktop_version/src/FileSystemUtils.cpp
PhysFS by default just uses system `malloc()`, `realloc()`, and `free()`; it provides a way to change them, with a struct named `PHYSFS_Allocator` and a function named `PHYSFS_setAllocator()`.
According to PhysFS docs, this function should be called before `PHYSFS_init()`, which is why this allocator stuff is handled in `FileSystemUtils.cpp`.
Also, I've had to make two "bridge" functions, because `PHYSFS_Allocator` wants pointers to functions taking in `PHYSFS_uint64`s, not `size_t`s.
=> Use SDL allocators for PhysFS

desktop_version/src/Music.cpp, desktop_version/src/SoundSystem.cpp
Since we're not going to be writing to any of these RWops, we might as well just ensure that we don't by using `SDL_RWFromConstMem()`.
=> Replace all SDL_RWFromMem() with SDL_RWFromConstMem()

desktop_version/src/FileSystemUtils.cpp, desktop_version/src/FileSystemUtils.h, desktop_version/src/UtilityClass.cpp, desktop_version/src/UtilityClass.h, desktop_version/src/editor.cpp
`FILESYSTEM_mountassets()`, `FILESYSTEM_assets()`, and `endsWith()` no longer use `std::string`s, since they don't need to. Along the way, I also cleaned up some other code that interacted with them, because they needed it too.
As always, look at the commits for more info.
=> Refactor assets mounting to not use the STL, and clean up some code as well

desktop_version/src/Screen.cpp
`Screen.cpp` wasn't explicitly including `SDL.h`, instead relying on `Screen.h` to include it.
It was also relying on `SDL.h` to include `stdio.h` on Linux, which breaks because `SDL.h` doesn't include `stdio.h` on Windows. So `stdio.h` is now explicitly included as well.
`stdlib.h` is not used in this file.
=> Fix transitive includes in Screen.cpp

desktop_version/src/BlockV.cpp, desktop_version/src/BlockV.h, desktop_version/src/Entity.cpp
These float attributes are assigned to, and then never read again. The coordinate systems of blocks are a bit of a mess - some use `xp`/`yp`, some use `xp`/`yp` and `rect.x`/`rect.y` - but I can confidently say that these are never used, because it compiles fine if I remove the attributes from the class, plus remove all assignments to it.
=> Remove unused x and y attributes of blockclass

desktop_version/src/editor.cpp
I had misread this line in #629 and thought that it was just clearing the entire surface, when really it was filling the surface with opaque black. `ClearSurface()` would instead make it transparent, which would mean when it got drawn, it would get drawn against blue, and not black. Whoops.
=> Fix regression with background of level minimaps not being black

desktop_version/src/FileSystemUtils.cpp
Three simple fixes: we no longer throw away 32 bits of information when grabbing the length of the file, if PhysFS gives us -1 for length we set it to 0, and the type of the return value of `PHYSFS_readBytes()` now matches the type of the value we store it in.
=> Fix handling of file sizes in FILESYSTEM_loadFileToMemory()

desktop_version/src/FileSystemUtils.cpp, desktop_version/src/FileSystemUtils.h, desktop_version/src/editor.cpp
`editor.cpp` no longer calls PhysFS functions directly; its `physfs.h` include can now be dropped.
=> Abstract zip loading to FileSystemUtils

desktop_version/src/FileSystemUtils.cpp, desktop_version/src/FileSystemUtils.h, desktop_version/src/editor.cpp
I have a bunch of directories in my levels folder. I also have a zip file in there.
Currently, whenever I load the levels folder, I get this mess printed to the terminal:
```
Level levels/graphics not found :(
Level levels/backlog not found :(
Level levels/archives not found :(
Level levels/temp not found :(
Level levels/default_levels not found :(
Level levels/concepts not found :(
Level levels/files not found :(
Level levels/wip not found :(
Level levels/hidden_levels not found :(
Level levels/open2v2_r245 not found :(
Couldn't load metadata for levels/open2v2_r246.zip
Level levels/saves_test_level_1 not found :(
Level levels/open2v2_r246 not found :(
Level levels/more_levels not found :(
Level levels/tas not found :(
Level levels/graphics not found :(
```
All of these are basically …
=> Fix false positive warning messages when loading levels directory (or at least fix most of them)

desktop_version/src/Game.cpp, desktop_version/src/editor.cpp
This is just a small quality-of-life feature - it's annoying to have to press ACTION 15 times in order to cycle back through to the previous song.
=> Add previous song option to editor music screen

desktop_version/src/Game.cpp, desktop_version/src/Input.cpp
If we're recreating the same menu, then we no longer need to reassign `game.currentmenuoption` ourselves; this simplifies the code a bit. Also, there was an errant `music.niceplay(6)` in the `credits6` menu, as well as a missing `map.nexttowercolour()` when returning from the game pad rebind screen.
=> Clean up menu option reassignments and fix two menu inconsistencies

desktop_version/src/Input.cpp
Since you're now allowed to bring up the map screen during cutscenes, you've also been able to activate activity zones and teleporter prompts during cutscenes. This only really affects custom levels; nowhere in the main game can you overlap with an activity zone while in a cutscene.
To fix this, I've just added a `script.running` check to Enter keybind processing.
=> Fix regression being able to activate activity zones during cutscenes

desktop_version/src/Logic.cpp, desktop_version/src/Render.cpp
If you stood in two activity zones at once, you'll automatically select the one that got created first. And when you activated it, the activity zone prompt would switch to fading out the prompt of the *other* activity zone, the one you didn't activate.
This wasn't a problem in 2.2 and previous, because the fading animation was simply bugged and defaulted to being solid black. However, in 2.3, the fading animation is fixed, so this is possible.
Also, this really only happens in the main game. Since there's only one type of useful activity zone in custom levels - namely the terminal activity zone - if two activity zones did happen to overlap, activating one of them wouldn't result in visibly fading out a different activity zone (because they both look the same); furthermore custom level …
=> Fix prompt fade out when activating overlapping activity zones

desktop_version/src/Graphics.cpp
In normal mode, the room name is at the bottom of the screen. When you bring up the map screen, it appears as if the room name is moving up from the bottom of the screen, and the map screen is "pushing" it up. The effect is pretty seamless, and when I first played the game (back in 2014), I thought it was pretty cool.
However, in Flip Mode, the room name is at the top of the screen. So one would expect the menu animation to come from above the screen. Well, no, it still goes from the bottom of screen; ruining the effect because it seems like there are two room names on the screen, when there ought to be only one.
To be fair, I only noticed this while fixing another bug now, but it's one of those things you can't unsee (I have cursed you with knowledge!); not to mention that I probably …
=> Reverse menu animation direction in Flip Mode

desktop_version/src/Input.cpp
This bug is technically *not* a regression - the code responsible for it has been around since the source release.
However, it hasn't been a problem until Graphic Options and Game Options were added to the pause screen. Since then, if you opened the pause menu in Flip Mode, pressing up would move to the menu option below, and pressing down would move to the menu option above. Notably, left and right still remain the same.
This is because the map screen input code assumes that the menu options will be flipped around - however, this has never been the case. What happens instead is that the menu options get flipped around time when in Flip Mode - flipping what's already flipped - so it ends up the same again.
(Incidentally enough, the up/down reversing code is present on the title screen, …
=> Fix up/down controls being reversed in in-game menu in Flip Mode

desktop_version/src/GraphicsUtil.cpp
This fixes a "root cause" bug (that's existed since 2.2 and below) where recreated surfaces wouldn't preserve the blend mode of their original surface.
The surface-level (pun genuinely unintended) bug that this root bug fixes is the one where there's no background to the room name during the map menu animation in Flip Mode.
This is because the room name background relies on `graphics.backBuffer` being filled with complete black. This is achieved by a call to `ClearSurface()` - however, `ClearSurface()` actually fills it with transparent black (this is not a regression; in 2.2 and previous, this was an "inlined" `FillRect(backBuffer, 0x00000000)`). This would be okay, and indeed the room name background renders fine in unflipped mode - but it suddenly breaks in Flip Mode.
Why? Because …
=> Copy blend mode to recreated surfaces, fixing room name background during menu animation in Flip Mode

desktop_version/src/Game.cpp, desktop_version/src/editor.cpp
There's no need to create an `std::string` for every single element just to see if it's a key name.
At least in libstdc++, there's an optimization where `std::string`s that are 16 characters or less don't allocate on the heap, and instead use the internal 16-char buffer directly in the control structure of the `std::string`. However, it's not guaranteed that all the element names we'll get will always be 16 chars or less, and in case the `std::string` does end up allocating on the heap, we have no reason for it to allocate on the heap; so we should just convert these string comparisons to C strings instead. …
=> Don't use std::strings when comparing key names

desktop_version/src/FileSystemUtils.cpp, desktop_version/src/FileSystemUtils.h, desktop_version/src/Graphics.cpp, desktop_version/src/Graphics.h
So, 2.3 added recoloring one-way tiles to no longer make them be always yellow. However, custom levels that retexture the one-way tiles might not want them to be recolored. So, if there are *any* custom assets mounted, then the one-ways will not be recolored. However, if the XML has a `<onewaycol_override>1</onewaycol_override>` tag, then the one-way will be recolored again anyways.
When I added one-way recoloring, I didn't intend for any custom asset to disable the recoloring; I only did it because I couldn't find a way to check if a specific file was customized by the custom level or not.
However, I have figured out how to do so, and so now `tiles.png` one-way recolors will only be disabled if there's a custom `tiles.png`, and `tiles2.png` one-way recolors will only be disabled if …
=> Make the one-way recolor conditional check for specific files instead of any mounted asset

desktop_version/src/GraphicsUtil.cpp
While I was working on fixing Flip Mode bugs, I ran Include What You Use on `GraphicsUtil.cpp` and fixed the evil transitive includes that the file relied upon. Include What You Use also told me to include `<math.h>` because of `floor()`; I've swapped out the `floor()` for `SDL_floor()` instead.
=> Fix transitive includes and use SDL_floor() in GraphicsUtil

desktop_version/src/Input.cpp
If there was absolutely no music playing, and you went to the in-game options to switch between MMMMMM and PPPPPP, the behavior would be a bit glitchy.
If you started with PPPPPP, switching once to MMMMMM wouldn't play anything, but then switching back to PPPPPP would play MMMMMM track 15. Then switching back to MMMMMM wouldn't do anything, but then switching back to PPPPPP again would play PPPPPP track 15 - and from there, the behavior is stable.
If you started with MMMMMM, switching once to PPPPPP would play MMMMMM track 15. Then switching back to MMMMMM wouldn't do anything, but then switching back to PPPPPP would play PPPPPP track 15 - and as above, the behavior is stable after that.
Anyways, the point is, -1 shouldn't be passed to `musicclass::play()` unless you want glitchy things. …
=> Fix glitchy behavior switching soundtracks on silence

desktop_version/src/Input.cpp
Flip Mode toggling is now no longer copy-pasted.
=> De-duplicate toggling flip mode in Input.cpp

desktop_version/src/Input.cpp
In #553, when @Dav999-v added error messages to settings menus if the game was unable to successfully save the changed settings, he seemed to have forgotten the PPPPPP/MMMMMM toggle option.
However, I can fully blame him for only that miss. The Flip Mode options were using `game.savemystats` (which was removed in #591), so if he searched for all instances of `game.savestats()` (`game.savestatsandsettings()` was only added in #557), he would've missed the `game.savemystats`.
Later, when I did #591, I didn't realize that I should've replaced the ones in the Flip Mode options with `game.savestatsandsettings_menu()`, so part of the blame does fall on me.
Anyways, this is fixed now. …
=> Fix MMMMMM and Flip Mode options ignoring save failure

desktop_version/src/Game.cpp, desktop_version/src/Game.h
Since it only ever gets assigned from `FILESYSTEM_getUserSaveDirectory()`, and that function returns a C string, and the variable is only ever read from again, this doesn't need to be an `std::string`.
=> Make saveFilePath not an std::string

desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/Graphics.cpp
I've moved this to a define that gets declared in `Game.h`. I could've made it a const int, but that's only legal in C++ mode.
=> De-duplicate number of menu text bytes

desktop_version/src/editor.cpp
When I did #220, I forgot about these things. So now they are no longer dependent on framerate.
Additionally, the Direct Mode drawer closing animation is now interpolated. Room name hiding isn't interpolated because it only changes by 1 pixel per frame, and you can't draw a fractional pixel.
=> Move gravity line, Direct Mode drawer, and room name hiding updates to editorrenderfixed, and interpolate Direct Mode drawer

desktop_version/src/editor.cpp
It's always been a bit weird how moving to a non-Direct Mode after having the tile picker drawer open, and then moving back, will result in the drawer popping up only to close again. Same goes for the room name hiding animation activating again if your cursor moved after you moved out of an unnamed room and then back.
So I fixed both of those.
=> Fix Direct Mode/room name timers being paused when switching to non-Direct Mode/unnamed rooms

desktop_version/src/KeyPoll.cpp, desktop_version/src/KeyPoll.h, desktop_version/src/main.cpp
This moves the responsibility of toggling fullscreen when any of the three toggle fullscreen keybinds are pressed (F11, Alt+Enter, Alt+F) directly into `key.Poll()` itself, and not its caller (which is `main()` - more specifically, `fixedloop()`). Furthermore, the fullscreen toggle itself has been moved to a separate function that `key.Poll()` just calls, to prevent cluttering `key.Poll()` with more business logic (the function is already quite big enough as it is).
As part of my work in re-removing the 1-frame input delay in #535, I'm moving the callsite of `key.Poll()` around, and I don't want to have to lug this block of code around with it. I'd rather refactor it upfront than touch any more lines than necessary in that PR.
example, a …
=> Directly toggle fullscreen if keybind pressed in key.Poll()

desktop_version/src/RenderFixed.cpp, desktop_version/src/RenderFixed.h, desktop_version/src/main.cpp
As part of my work in #535, I've noticed that 2.3 currently with 2.2 loop order doesn't have interpolated cutscene bars. This is because cutscene bars in 2.3 get updated at the start of the frame, which interpolates them correctly until the render functions are put in their proper place.
There is, however, a somewhat bigger issue, outside the scope of #535, where cutscene bars always get updated regardless of which gamemode you are in. Previously in 2.2 and previous, cutscene bars only got updated in GAMEMODE and TELEPORTERMODE; sometime during 2.3, the cutscene bars timer got pulled out of all the individual game modes and moved to the very start of the loop. (I was probably the one who did this change; I've been caught in a trap of my own devising.)
Thus, going to MAPMODE during the …
=> Inline cutscene bars timer for gamemodes that used it in 2.2

desktop_version/src/Graphics.cpp
This is because it directly uses the xp and yp of the player instead of the interpolated xp and yp. Whoops.
=> Fix VVVVVV-Man not being interpolated

desktop_version/src/Input.cpp, desktop_version/src/editor.cpp
This is a small quality-of-life thing that makes it so you don't have to move your menu selection all the way over to the "return" button in order to return to the previous menu. You can just press Escape instead to return to the previous menu. The previous behavior of pressing Escape was to bring up the 'confirm quit' menu, or if you were in an options menu in-game, return to the pause menu.
If you're on the main menu (and thus don't have any previous menu) and press Escape, the game will instead bring up the 'confirm quit' menu. For consistency, the "quit game" option on the main menu will also bring up the 'confirm quit' menu as well, instead of immediately closing the game.
Pressing the controller button mapped to Escape will also work as well.
The only menus that don't have return …
=> Add being able to press Esc to return to previous menu

desktop_version/src/Game.cpp, desktop_version/src/Graphics.cpp, desktop_version/src/Render.cpp, desktop_version/src/editor.cpp
While working on #535, I noticed that `editormenuactionpress()` still didn't do the explicit void declaration. Then I ran `rg 'void.*\(\)'` and found three other functions that I somehow missed in #628. Whoops. Well, now they no longer are missed.
=> Fix a few missing implicit void arg declarations

desktop_version/src/Game.cpp, desktop_version/src/Graphics.cpp, desktop_version/src/Graphics.h, desktop_version/src/Logic.cpp, desktop_version/src/Script.cpp
This fixes over-30-FPS rendering glitches caused `graphics.oldfadeamount` not being assigned at the same times that `graphics.fadeamount` gets assigned. The same thing could happen with cutscene bars, but it doesn't seem like there are any glitches - still better to be safe than sorry, and make sure `graphics.oldcutscenebarspos` gets assigned at the same times that `graphics.cutscenebarspos` do.
=> Ensure oldcutscenebars and cutscenebars get set at the same time, and that oldfadeamount and fadeamount get set at the same time

desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/Graphics.cpp, desktop_version/src/Graphics.h, desktop_version/src/Script.cpp, desktop_version/src/Script.h, desktop_version/src/Textbox.cpp, desktop_version/src/Textbox.h
2.3 added being able to go to the options menus from the pause menu. It also added Flip Mode to Game Options in the in-game options menu, if you have it unlocked or are using an M&P build. It also added being able to go to these options during cutscenes.
So if you toggle Flip Mode when certain text boxes are onscreen...
<sup>Everything seems ok.</sup>
...then this happens:
<sup>Uh oh.</sup>
So what went wrong here? Well, these text boxes only check for Flip Mode when they get created, and assume that that Flip Mode-ness will continue until after the text boxes go away. In contrast, the rescued crewmate sprite (Violet in these screenshots) and the Level Complete image always check for Flip Mode and don't assume that Flip Mode status will persist until the end of their lifetime.
What's the …
=> Fix misplaced text boxes when toggling Flip Mode while Flip Mode-aware text boxes are active

desktop_version/CMakeLists.txt, desktop_version/src/DeferCallbacks.c, desktop_version/src/DeferCallbacks.h, desktop_version/src/Ent.cpp, desktop_version/src/Ent.h, desktop_version/src/Entity.cpp, desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/Graphics.cpp, desktop_version/src/Graphics.h, desktop_version/src/Input.cpp, desktop_version/src/Logic.cpp, desktop_version/src/Map.cpp, desktop_version/src/RenderFixed.cpp, desktop_version/src/RenderFixed.h, desktop_version/src/Script.cpp, desktop_version/src/Script.h, desktop_version/src/editor.cpp, desktop_version/src/main.cpp
Okay, so the reason why all render functions were moved to the end of the frame in #220 is because it's simpler to call two fixed functions and then a delta function instead of one fixed function, then a delta function, and then another fixed function.
This is because fixed functions need special handling inside `deltaloop()`, and you can't simply duplicate this handling after calling a delta function. Oh, and to make matters worse, it's not always fixed-delta-fixed, sometimes (like in MAPMODE and TELEPORTERMODE) it's delta-fixed-fixed, so we'd need to handle that somehow too.
The solution here is to generalize the game loop and factor out each function, instead of hardcoding it. Instead of having hardcoded case-switches directly in the loop, I made a function that returns an array of …
=> Fix game loop order to what it was in 2.2

desktop_version/src/main.cpp
Clang warns on this. This doesn't fix anything but it does ensure that whoever's reading it won't be focused as to whether or not omitting the second set of braces is legal or not.
=> Add braces around sub-object in unfocused_func_list

desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/RenderFixed.cpp, desktop_version/src/main.cpp
PR #279 added `game.gametimer` solely for the editor ghosts feature. It seems that whoever originally wrote it (Leo for the now-dead VVVVVV: Community Edition, I believe) forgot that the game already had its own timer, that they could use.
The game timer does increment on unfocus pause (whereas this doesn't), but that's a separate issue, and it ought to not do that.
=> Remove game.gametimer in favor of game.frames

desktop_version/src/Game.cpp, desktop_version/src/editor.cpp
XML loading is pretty safe due to the use of TinyXML-2 handles. However, that doesn't mean there aren't a few holes - namely, not re-assigning `pText` when it is `NULL`, and not initializing the temporary edentity created when loading custom levels; all of which I have fixed.
=> Fix undefined behavior when loading XML

desktop_version/src/Graphics.cpp
The existing bounds checks were correct sometimes but other times were not.
The bounds check for 2x2 and 2x1 sprites only covered the top-left sprite drawn; the other sprites could still be out of bounds. But if the top-left sprite was out of bounds, then none of the other sprites wouldn't be drawn - although it ought to be that the other sprites still get attempted to be drawn. So I've updated the bounds checks accordingly, and now an out of bounds top-left sprite won't prevent the drawing of the rest of the sprites.
Similarly, if the sprite of a Gravitron square was out of bounds, that would prevent its indicators from being drawn. But the indicators weren't being bounds-checked either (2.3 lets you have less than 1200 tiles in a given tilesheet). So the bounds check has been moved to …
=> Fix bounds checks in drawentity()

desktop_version/src/Entity.cpp, desktop_version/src/Graphics.cpp, desktop_version/src/Input.cpp, desktop_version/src/Map.cpp, desktop_version/src/Map.h, desktop_version/src/Render.cpp, desktop_version/src/Script.cpp, desktop_version/src/editor.cpp, desktop_version/src/editor.h
This adds bounds checks so levels bigger than 20x20 don't run into undefined behavior.
Most of the work done is creating setter and getter funcs and replacing all existing raw accesses with those functions. Then the rest is just adding bounds checks to those functions.
Anyways, with this PR, it should no longer be possible to cause undefined behavior by going past the size limit. I tested it with Valgrind, to be sure.
=> Add bounds checks to fix undefined behavior with levels bigger than the size limit

.github/pull_request_template.md
Mentioning 2.3 here is going to be anachronistic when 2.4 exists. And there's not really any point in bumping this version number every time the game's version number is bumped as well. So it's best to just remove it.
=> Remove 2.3 example from pull request template

desktop_version/src/Entity.cpp
I just spotted this one - if `vy` isn't bounds-checked, this causes bogus input from the `createentity()` script command to commit Undefined Behavior. Should've spotted this one when I was adding bounds checks to the rest of `createentity()` earlier, but at least it's fixed now.
=> Add bounds check for color of createentity number 55

desktop_version/src/Entity.cpp
Custom levels can have warp lines. If you have a warp line and a warping background in the same room, the warp line takes precedence over the warp background.
However, whenever you enter a room with a warp line and warp background, any entities on the warping edges will be drawn with screenwrapping for one frame, even though they never wrapped at all.
This is due to frame ordering: when the warp line gets created, `obj.customwarpmode` gets set to true. Then when the screen edges and warping logic gets ran, the very first thing that gets checked is this exact variable, and `map.warpx`/`map.warpy` get set appropriately - so there's no way the entity could legitimately screenwrap.
However, that happens in `gamelogic()`. `gamelogic()` is also the one responsible for creating entities upon …
=> Fix 1-frame flicker when entering a room with warp lines that also has an entity on a warping screen edge

desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/Graphics.cpp, desktop_version/src/Graphics.h, desktop_version/src/Input.cpp, desktop_version/src/main.cpp
If you have glitchrunner mode off, and open the pause menu while fully faded out, then go to the in-game options, the game would call `startgamemode()` immediately, basically replaying the option you chose on the title screen, whether that be going to the start of the level or the start of the new game or reloading your save file or whatever you chose.
This fixes that by making the title screen no longer rely on `graphics.fademode` to call `startgamemode()`, and temporarily storing `graphics.fademode` to a different variable when going to the in-game options so the screen isn't black when you do so.
(Opening the map or pause screen while faded out and having glitchrunner mode on results in immediately returning to the title screen - this is intentional glitchrunner behavior.)
By …
=> Fix calling startgamemode when going to in-game options while faded out and not in glitchrunner mode

desktop_version/src/Input.cpp
Followup to #664: Pressing "quit game" instead of using Esc changes the background, but pressing Esc doesn't. Whoops.
=> Fix background not changing when pressing Esc on main menu

desktop_version/src/Render.cpp
Followup to #635: I had misread the original `==0` comparisons as being truthy comparisons instead of being falsy comparisons. Whoops.
=> Fix targets (question marks) not showing up on minimap

desktop_version/src/KeyPoll.cpp
According to [SDL documentation](https://wiki.libsdl.org/SDL_GetClipboardText), the returned pointer needs to be freed. A glance at the source code confirms that the function allocates, and also Valgrind complains about it.
Also if it couldn't allocate, the game no longer segfaults (`std::string`s do not check if the pointer is non-`NULL` for `operator+=`).
=> Fix memory leak when pasting text

desktop_version/src/FileSystemUtils.cpp
Ethan, you forgot this other one.
I do have to rejiggle the control flow of the function a bit, so it doesn't leak memory upon failure. (Although the SDL message box leaks memory anyway because of X11 so... whatever.) Also, there's a `NULL` check for if `SDL_GetBasePath()` fails now.
=> Replace other usage of PHYSFS_getBaseDir() with SDL_GetBasePath()

desktop_version/src/main.cpp
Flip Mode flips all the unfocus pause screen text upside-down, to make it read in reverse order. This looks kind of strange to me, and I don't think it was intended. So I'm flipping the text again so it's the right way up in Flip Mode.
=> Fix oversight with unfocus pause screen in Flip Mode

desktop_version/src/Graphics.cpp, desktop_version/src/Graphics.h, desktop_version/src/Render.cpp
This PR adds text outlines (if enabled) to textboxless textboxes - these are text boxes with RGB values of 0,0,0, which just get rendered as text without any text box behind it - and all gravitron text. I've refactored some of the text printing a bit, but also copy-pasted some of the text printing calculations, because of how the text printing functions work - and I'm beginning to think these text printing functions are a bit awful to work with... but that's a refactor for later.
These text outlines should be added in case they get placed against hard-to-contrast backgrounds, which could happen in custom levels (since you can start the Gravitron or Super Gravitron in custom levels), or if someone manages to glitch themselves out in the main game.
(Depends on #670). …
=> Add text outlines to textboxless textboxes and gravitron text

desktop_version/src/Entity.cpp, desktop_version/src/Logic.cpp
During the final stretch, after Viridian turns off the Dimensional Stability Generator, the map goes all psychedelic and changes colors every 40 frames. Entities change their colors too, including conveyors, moving platforms, and disappearing platforms.
But play around with the disappearing platforms for a bit and you'll notice they seem a bit glitchy. If you run on them at the right time, the tile they use while disappearing seems to abruptly change whenever the color of the room changes. If there's a color change while they're reappearing (when you die and respawn in the same room as them), they'll have the wrong tile and look like a conveyor. And even if you've never interacted with them at all, dying and respawning in the same room as them will change their tile to something wrong and …
=> Fix tile of disappearing platforms during final stretch

desktop_version/src/KeyPoll.cpp, desktop_version/src/KeyPoll.h, desktop_version/src/main.cpp
This fixes a regression introduced by #535 where a quit signal (e.g. Ctrl-C) sent to the window while the game was in unfocus pause wouldn't close the game.
One problem was that `key.quitProgram` would only be checked when control flow switched back to the outer loop in `main()`, which would only happen when the loop order state machine switched to a delta function. As the unfocused func table didn't have any delta functions, this means `key.quitProgram` would never be checked.
So a naïve solution to this would just be to add a no-op delta func entry to the unfocused func table. However, we then run into a separate issue where a delta function at the end of a func list never reassigns the active funcs, causing the game to be stuck in the unfocus pause forever. Active func reassignment …
=> Call VVV_exit() when SDL_QUIT is received

desktop_version/src/main.cpp
One of the solutions to the quit signal unfocus pause regression is to add a no-op delta func to the unfocused func table. However, this results in the game being stuck in unfocus pause forever, because when it reaches the end of a list on a delta func, it won't reassign the active functions - only when the end of a list is a fixed func will it do so. A workaround is to then add a no-op fixed func afterwards, but that's inelegant.
The solution in the end to the quit signal regression is to not bother with adding a delta func, so the game as of right now actually never has a delta func at the end of a list, and probably never will - but this is one piece of technical debt I don't want to leave laying around. In case we're ever going to put a delta function at the end of a list, I've made …
=> Fix funcs not being reassigned if delta func is last func in list

desktop_version/src/Logic.cpp
This fixes being unable to use teleporters while the "- Press ACTION to advance text -" prompt is up, which is used to perform credits warp.
In 2.2 and 2.0, this advancetext check was only in `gamerender()` for rendering the "- Press ENTER to Teleport -" prompt and didn't affect any logic. In 2.3, I moved the check (and the rest of the conditional it was in) to `gamelogic()` - same as the activity zone prompt conditionals - so if you gained control while being in a prompt zone, the prompt wouldn't suddenly appear<sup>[1]</sup>.
As a side effect, this ended up aligning rendering and logic together, so if you couldn't see the teleporter prompt, you weren't able to teleport - whereas in 2.2 and 2.0, you could still use the teleporter even though the prompt wasn't up.
So by removing the …
=> Remove advancetext check from teleporter prompt logic

desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/Input.cpp, desktop_version/src/Render.cpp, desktop_version/src/main.cpp
This is an option for speedrunners whose muscle memory is precisely trained and used to the 1-frame input delay that existed in 2.2 and below. It is located in Game Options -> Advanced Options, and is off by default.
To re-add the 1-frame input delay, we simply move the `key.Poll()` to the start of the frame, instead of before an input function gets ran - undoing what #535 did.
There is a frame ordering-sensitive issue here, where toggling `game.inputdelay` at the wrong time could cause double-polling. However, we only toggle it in an input function, which regardless is always guaranteed to be ran after `key.Poll()` (it either happened at the start of the frame or just before the input function got ran), so this is not an issue. But, in case we ever need to toggle this variable in the …
=> Add option to re-enable 1-frame input delay

desktop_version/src/FileSystemUtils.cpp, desktop_version/src/FileSystemUtils.h, desktop_version/src/Game.cpp, desktop_version/src/Graphics.cpp, desktop_version/src/GraphicsResources.cpp, desktop_version/src/Screen.cpp, desktop_version/src/SoundSystem.cpp, desktop_version/src/editor.cpp, desktop_version/src/main.cpp
This fixes an issue where you would be able to mount things other than custom assets in per-level custom asset directories and zips.
To be fair, the effects of this issue were fairly limited - about the only thing I could do with it was to override a user-made quicksave of a custom level with one of my own. However, since the quicksave check happens before assets are mounted, if the user didn't have an existing quicksave then they wouldn't be able load my quicksave. Furthermore, mounting things like `settings.vvv` simply doesn't work because assets only get mounted when the level gets loaded, but the game only reads from `settings.vvv` on startup.
Still, this is an issue, and just because it only has one effect doesn't mean we should single-case patch that one effect only. So what can we …
=> Switch assets mounting to dedicated directory

desktop_version/src/editor.cpp
While the game does support playing levels with filenames that don't have the `.vvvvvv` extension, it doesn't do it well.
Namely, those files can't be loaded or saved into the editor (because a `.vvvvvv` always gets tacked on to your input when saving or loading). In 2.3, this gets worse because you can't load a level without a `.vvvvvv` extension from command-line playtesting (because a `.vvvvvv` automatically gets added) and you can't load per-level custom assets.
The only place where extensionless level files are supported is when loading level metadata. But this makes it so they no longer work. This is technically an API break, but it's easily fixed (just add the `.vvvvvv`), plus there's nothing to be gained from not having an extension, plus basically no one ever actually did this in …
=> Blacklist non-.vvvvvv files in level metadata

desktop_version/src/Game.cpp
So some people reported the levels list crashing when they loaded it. But this wasn't reproducible every time. They didn't provide any debugging information, so I had to use my backup plan: doing a full audit of the code path taken for loading the levels list.
And then I found this. It turns out this was because I used a `LOAD_ARRAY_RENAME()` macro on an `std::vector`. You can't do that because you need to use `push_back()` to resize a vector, so the macro will end up indexing into nothing, causing a segfault. However, this code path would only be taken if you have an old `levelstats.vvv`, from 2.2 and previous - which explains why it wasn't 100% reproducible. But now that I know you need an old `levelstats.vvv`, this bug happens 100% of the time.
Anyways, to fix this, just ditch the …
=> Fix level list segfault when upgrading old levelstats.vvv

desktop_version/src/Game.h, desktop_version/src/Graphics.cpp, desktop_version/src/editor.cpp
Fix some compilation warnings due to redundant semicolons or empty macro arguments under `-Wpedantic`.
Feel free to not credit me for these small changes. 
=> Fix '-Wpedantic' warnings under gcc 10.x

desktop_version/src/Game.cpp, desktop_version/src/Script.cpp
Two softlocks, two bug fixes. One of them is getting stuck in `completestop` and the other is getting stuck with `pausescript` on but `advancetext` off.
=> Fix softlocks from mistimed trinket text skip and turning advancetext off at the wrong time

desktop_version/src/Input.cpp
This fixes returning from the confirm quit menu placing you on the options button instead of the quit to menu button, using the return button in gameplay or graphic options putting you back at the pause menu instead of the options menu, and pressing Esc in graphic options putting you back at the pause menu instead of the options menu.
Fixes #711.
=> Fix pause menu inconsistencies from Terry's menu cleanup

desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/Graphics.cpp, desktop_version/src/Input.cpp, desktop_version/src/Music.cpp, desktop_version/src/Music.h, desktop_version/src/Render.cpp, desktop_version/src/UtilityClass.cpp, desktop_version/src/UtilityClass.h, desktop_version/src/main.cpp
There is now a new audio category in options, which includes the new volume sliders for the music and sound effects, along with the MMMMMM/PPPPPP soundtrack switching option.
The audio sliders are quite simple: Once you navigate one of them, pressing ACTION on it will transfer your control to the slider itself - this is indicated by your selection brackets switching to surround the slider instead of the menu option.
Once you have a slider selected, you press left or right to change the volume. After that, you can either press ACTION to confirm that this is the volume you want, or press Esc to cancel the volume change and go back to the previous volume. Either way, your settings will be written to disk when you do so.
Closes #706.
section …
=> Add in-game music and sound volume sliders and a new audio category to options

desktop_version/src/FileSystemUtils.cpp
In #52 I fixed VVVVVV not being able to handle filepaths with non-ASCII characters on Windows. 2f0a0bce4c663b7df2ed229ef897dcf3fd878ec6 and aa5c2d9dc260386c1b99fb9867b2a8ef7c82252f reintroduce this problem, however, by reverting the definition of mkdir to how it was before the fix and using the non-Unicode version of CreateDirectory. And I can confirm that VVVVVV indeed doesn't make its folder anymore with a Windows username of "тест". This PR fixes that issue.
=> Re-fix handling filepaths with non-ASCII characters on Windows

desktop_version/src/Music.cpp, desktop_version/src/Script.cpp, desktop_version/src/Scripts.cpp
As usual, I aimed to fix one bug, and then one thing led to another, and then ~~I'm now gay~~ I ended up fixing all the music regressions on the tracker. Oh and other things that weren't even reported yet.
Anyways: This fixes the music stopping after collecting the trinket that Victoria or Vitellary gives you, fixes the inconsistencies between the trinket cutscenes and trinkets found in the wild (trinket cutscenes now silence music instead of halting, and fade the music back in instead of restarting it), fixes some fade-ins not starting from zero (which I ran into when fixing the trinket cutscenes thing), fixes the 2.2-and-below music blocking workaround not working in 2.3, and fixes the level music not playing when starting playtesting in the editor.
Fixes #701, fixes #710, and fixes …
=> Fix a bunch of music regressions and inconsistencies

desktop_version/src/BinaryBlob.cpp, desktop_version/src/BinaryBlob.h, desktop_version/src/FileSystemUtils.cpp, desktop_version/src/FileSystemUtils.h
There were two other types of asset paths that I forgot to account for when implementing the virtual mount path system. So one-way recolors would always recolor because it didn't use the virtual mount path, and music files were unable to be mounted because they wouldn't use the virtual mount path. But both of those bugs are fixed now.
=> Fix one-way recolors and music files not accounting for virtual mount path

desktop_version/src/Input.cpp
It turns out this entire chunk of code is simply unneeded (and is actively harmful) since when we're done with the time trial, `quittomenu()` gets called, and that removes the previous stack frame anyway.
I'm guessing that I added this code, then added `quittomenu()`, then didn't consider how this code and `quittomenu()` would mix. But anyways, this bug is fixed.
Fixes #714.
=> Remove time trial replay menu stack popping

desktop_version/src/Game.cpp, desktop_version/src/Logic.cpp, desktop_version/src/Render.cpp, desktop_version/src/Script.cpp, desktop_version/src/main.cpp
I fixed #699, fixed music fades, fade bars, and the game clock ticking during unfocus pause, fixed another instance of logic code being entangled with rendering code, and fixed the frames portion of level saves always being discarded when loaded (I don't know why that ever happened, but whatever).
Fixes #699.
=> Fix some unfocus pause and timer bugs

desktop_version/src/Graphics.cpp
When an entity warps vertically, it teleports 232 pixels up or down - however, the rendering code uses an offset of 230 pixels, which is off by 2 pixels, and draws the wrapped entity at the wrong position. In the same vein, entities that just teleported through the bottom 8 pixels of the screen to the top weren't being drawn at the bottom of the screen (possibly because the code was originally written for rooms with room names), so I've increased the threshold for drawing entities near the top of the screen at the bottom of the screen.
Wrong render offset - before:
Correct render offset - after:
Entity not drawn on bottom 8 pixels - before:
Entity drawn on bottom 8 pixels - after:
section of the credits for all of said releases, but will …
=> Fix vertical entity wrapping render inconsistencies

desktop_version/src/Entity.cpp
I was working on another PR, and spotted this. This is a *giant* whoops moment right here!
=> Fix wrong variable being bounds-checked when collecting trinket

desktop_version/src/Game.cpp, desktop_version/src/editor.cpp
This fixes a bug where quitting to the menu from command-line playtesting with `-playassets` specified would always use those assets when loading back in to any custom level. This also fixes loading in to a custom level quicksave always using the command-line playtesting arguments instead of using the actual quicksave.
=> Reset cliplaytest when exiting to menu and check it when loading

desktop_version/src/Logic.cpp
`edteleportent` is a global variable that gets assigned whenever the player collides with a warp token, and gets read from later down the line in `gamelogic()`. While I don't know of any way to cause anything bad with this (and I did try), storing a temporary indexing variable like this is only bound to be a liability in the future - so we might as well prevent badness now by adding a bounds check here.
=> Add bounds check to use of edteleportent

desktop_version/CONTRIBUTORS.txt, desktop_version/src/Credits.h, desktop_version/src/Input.cpp, desktop_version/src/Script.cpp
This fixes the current bug where quick restarting a time trial will completely stop the music until you go back to the main menu.
I also cleaned up the code around it a bit by merging several nearly identical switch cases into one.
=> Fix music stopping when restarting a time trial

desktop_version/src/Input.cpp, desktop_version/src/Music.cpp, desktop_version/src/Script.cpp
This reverts only a part of f196fcd896defc0b24690851c701b8273ba8074b - as the original commit author did not do their changes atomically, they also squashed in a de-duplication within the same commit. So I'm only reverting the part of the commit that wasn't the de-duplication, which is simply the changes to the `music.fadeout()` calls.
#727 is being (partially) reverted for several reasons:
1. It's not the correct behavior. What this does instead is persist the track through after you restart the time trial, instead of fading it out, then restarting it again. This is in contrast to behavior in 2.2, and I see no reason to not keep the same behavior.
2. It's a single-case patch. The time trials are not the only time in the game a music track could fade out and then be restarted with the …
=> Revert part of #727, and fix EVERY case where a track could restart after fading out, and not just only one single case

desktop_version/src/Game.cpp, desktop_version/src/Graphics.cpp, desktop_version/src/Graphics.h, desktop_version/src/Input.cpp, desktop_version/src/KeyPoll.cpp, desktop_version/src/Render.cpp
Instead of having a one-size-fits-all config option, just make it so we hide the mouse when the user uses their keyboard or controller, and show it again when they move their mouse.
=> Axe mouse cursor config option in favor of automatically toggling mouse

desktop_version/src/Map.h
So... I did see that `map.ypos` was a float when I added over-30-FPS mode, because `map.oldypos` wasn't there before... I'm guessing that I kind of just ignored it at the time. But, c'mon, `map.ypos` and `map.oldypos` are always treated as ints, so there's literally no reason for them to be actually floats in reality. I didn't even know they were anything other than ints until I checked `Map.h`.
=> Make map.ypos and map.oldypos ints instead of floats

desktop_version/src/Game.cpp, desktop_version/src/Game.h
This boolean is assigned, and it is checked... but it's never assigned to true, thus making it useless. I also checked 2.2 source and the same thing happens there; to prevent any confusion, I'm removing this.
=> Remove customlevelstatsloaded from Game

desktop_version/src/Entity.cpp, desktop_version/src/Entity.h
This fixes up `entityclass::createentity()` to no longer use floats for its parameters, to no longer use default arguments (well, as much as is possible for it to), and to not have misleading `vx`/`vy` parameter names (they are *not* x-velocity or y-velocity).
=> Clean up entityclass::createentity() parameters

desktop_version/src/Input.cpp
Pressing Esc to cancel the confirm quit menu didn't play the squeak, in contrast to pressing ACTION to cancel it, so now it does; pressing Esc to close the pause menu or pressing ACTION will also now play the Viridian squeak too.
=> Consistently play Viridian squeak for pause menu inputs

desktop_version/src/editor.cpp
All other instances of "Enter script name:" have a colon except for this one.
=> Fix missing colon in prompt when placing terminal

desktop_version/src/editor.cpp
This fixes a bug where after loading in to the level editor, pressing Esc and then switching your option to something other than the first option, then pressing Esc again to close the menu, then pressing Esc once more would not keep your menu option.
This is because the code that checks if `Menu::ed_settings` is already in the stack doesn't account for if `ed_settings` is the current menu - the current menu doesn't get put in to the stack.
In hindsight, maybe I could have designed the new menu system better so the current menu *is* on the stack, and/or should have used a statically-allocated linked list for each menu name for the stack frames (instead of an `std::vector`) and asserted if a menu that already existed in the stack was created instead... that'll have to be done later, though. …
=> Fix duplicating ed_settings when opening editor menu second time

desktop_version/src/Graphics.cpp, desktop_version/src/GraphicsUtil.cpp
These casts are sprinkled all throughout the graphics code when creating and initializing an `SDL_Rect` on the same line. Unfortunately, most of these are unnecessary, and at worst are wasteful because they result in narrowing a 4-byte integer into a 2-byte one when they don't need to (`SDL_Rect`s are made up of 4-byte integers).
Now, removing them reveals why they were placed there in the first place - a warning is raised (`-Wnarrowing`) that implicit narrowing conversions are prohibited in initializer lists in C++11. (Notably, if the conversion wasn't narrowing, or implicit, or done in an initializer list, it would be fine. This is a really specific prohibition that doesn't apply if any of its sub-cases are true.)
We don't use C++11, but this warning can be easily vanquished by a simple …
=> Remove unnecessary Sint16 casts

desktop_version/src/FileSystemUtils.cpp, desktop_version/src/Graphics.cpp, desktop_version/src/GraphicsResources.cpp, desktop_version/src/Screen.cpp, desktop_version/src/SoundSystem.cpp, desktop_version/src/editor.cpp
It's simple: The game committed undefined behavior if it had no assets. But now it doesn't.
To test this, I created a zip file with nothing inside (`touch nothing`, then `zip nothing.zip nothing`), then did `./VVVVVV -assets nothing.zip` and fixed every segfault until it worked properly.
=> Fix undefined behavior if assets are missing and asserts if some of them are missing

desktop_version/src/FileSystemUtils.cpp
Previously, if the game couldn't set the write dir to the base directory, or couldn't make the base directory, or couldn't calculate the base directory, it would probably dereference `NULL` or read from uninitialized memory or murder your family or something. But now, I've eliminated the potential Undefined Behavior from the code dealing with the base path.
=> Add error checking to base path setup 

desktop_version/src/Graphics.cpp, desktop_version/src/Graphics.h, desktop_version/src/Render.cpp
This is a simple change - we draw `minimap.png`, instead of the generated custom map, if it is a per-level mounted custom asset.
Custom levels have already been able to utilize `minimap.png`, but it was limited - they could do `gamemode(teleporter)` in a script, and that would show their customized `minimap.png`, but it's not like the player could look at it during gameplay.
I would have done this earlier if I had figured out how to check if a specific asset was mounted or not.
=> Draw minimap.png if it is mounted

desktop_version/CMakeLists.txt
Otherwise this would result in multiple input arguments to the regex instead of just one. Similar to shell scripting.
=> Quote CMAKE_CXX_FLAGS

desktop_version/src/editor.cpp
If there were two scripts with the same name, removing one of them would only remove the other script from the script name list, and not also remove the contents of said script - leading to a desync in state, which is probably bad.
Fixing this isn't as simple as removing the `break` statement - I either also have to decrement the loop variable when removing the script, or iterate backwards. I chose to iterate backwards here because it relocates less memory than iterating forwards.
Also I removed the `<algorithm>` include from `editor.cpp`.
=> Fix only removing duplicate script names from script name list

desktop_version/src/Input.cpp, desktop_version/src/Render.cpp, desktop_version/src/Screen.cpp
Title says it all. I also added a `NULL` pointer check when pressing ACTION in or rendering the graphic options menu, just to be safe.
=> Fix using fullscreen toggle keybind in graphic options not updating grayness of 'resize to nearest'

desktop_version/src/Logic.cpp
The game excludes warp lines and gravitron squares from warping; unfortunately it over-blacklists too much and VVVVVV-Man and rescuable crewmates can't warp at all. This fixes it and makes them able to warp.
I've been in the custom level community for 7 years, and I don't know of any levels that warp rescuable crewmates or even use VVVVVV-Man in the first place. Furthermore, this in fact is more likely to fix things rather than break them, because entities falling out of the room are basically irretrievable. So this should be okay to do.
=> Fix VVVVVV-Man not warping horizontally and rescuable crewmates not warping at all

desktop_version/src/Music.cpp, desktop_version/src/Music.h
This PR fixes three music regressions.
1. The fade durations ended up being longer than intended due to loss of precision in calculations.
2. Playing track 0 or 7 after music already faded out would end up immediately fading out those tracks, due to the fade booleans not being reset.
3. The first frame of track 0 or 7 would be silent, leading a lack of musical attack.
=> Fix three music regressions - incorrect fade durations, un-reset fade bools, 1-frame silence when playing track 0 or 7

desktop_version/src/Logic.cpp, desktop_version/src/Map.cpp, desktop_version/src/Map.h, desktop_version/src/Script.cpp, desktop_version/src/main.cpp
If you have invincibility enabled and push the camera, the background would smear. This is because the game doesn't calculate the proper `bscroll` and `bypos` of the tower background, and also doesn't end up redrawing it.
We do both these things now, so this is fixed.
Additionally, all `bscroll` and `bypos` calculations have been consolidated, to fix any other potential issues with the background.
=> Fix tower background smearing when pushing camera in invincibility mode

desktop_version/src/Game.cpp, desktop_version/src/Logic.cpp
Custom levels shouldn't affect main game save data, and Super Gravitron records and best game deaths are no exception.
I also added `MAKEANDPLAY` ifdefs just to be safe.
=> Don't allow setting Super Gravitron records or best game deaths in custom levels

desktop_version/src/Input.cpp
When you enter the Super Gravitron, you have to wait until the Super Gravitron actually starts before being able to press Enter to return to the Secret Lab. This is annoying if you just want to get back to the Secret Lab. So, I've made it so the press-Enter-to-return functionality is enabled from the moment that the Super Gravitron starts.
=> Enable returning to Secret Lab immediately from Super Gravitron

desktop_version/src/Game.cpp
If you had Flip Mode enabled when exiting from in-game options, the game would flash the in-game options menu as flipped for 1 frame before returning to the pause menu.
To fix this, just defer the Flip Mode variable assignment to be done at the end of the frame.
=> Fix 1-frame glitch returning from in-game options with Flip Mode on

desktop_version/src/Input.cpp
This is a small quality-of-life fix in the same vein as allowing the player to press Esc in the teleporter menu (which they weren't able to do in 2.2, either).
=> Allow using Esc in Super Gravitron quit menu

desktop_version/src/Entity.cpp
If you have completed No Death Mode, and entered the Master of the Universe trophy room in the Secret Lab in over-30-FPS mode, it would appear to start at one position before quickly zipping to another during the deltaframes.
This is because it updates its position after the initial assignments of `lerpoldxp`/`lerpoldyp` in `entityclass::createentity()`.
Other entities do this too, and what's been done for them is to copy-paste the `lerpoldxp`/`lerpoldyp` updates alongside the `xp`/`yp` updates. However, instead of single-case patching this deltaframe glitch, I've opted to fix *all* cases by simply moving the `lerpoldxp`/`lerpoldyp` assignments to the end of the function, guaranteeing that all entities that update their position after the initial assignment in the function will not have …
=> Fix deltaframe glitch when spawning No Death Mode trophy

desktop_version/src/Game.cpp, desktop_version/src/TerminalScripts.cpp
After the dimension destabilizes, the song that plays is Positive Force. Which has already been played twice in the game at that point (first in Tower, then in the Gravitron). Since Piercing the Sky is unused, why not play a song that the player hasn't heard before? It would also be musically fitting for the scenario.
The song gets played in two places - one for if you have cutscenes enabled, and one for if you don't - so we just need to change both of them.
I asked Terry in Discord DMs if he wanted this change and he approved of it.
=> Change final stretch song to Piercing the Sky

desktop_version/src/Map.cpp
There's a bit of inconsistency with how long each color lasts for during final stretch. Initially, each color lasts for 40 frames, but when you enter either of the minitowers, the color switches to lasting for 15 frames only. This is because a `final_colorframe` of 1 makes it go for 40 frames, but a `final_colorframe` of 2 makes it go for 15 frames - and `final_colorframe` gets set to 2 whenever you enter a minitower.
This seems like an oversight because (1) `final_colorframe` doesn't affect anything inside the minitower, (2) `final_colorframe` doesn't get saved to the save file and always gets set to 1 if your save file has `finalstretch` set to true, so saving and reloading will set the colors back to 40 frames each, and (3) `final_colorframe` doesn't get set back to 1 when leaving the …
=> Remove final_colorframe assignments when entering minitowers

desktop_version/src/Render.cpp
This fixes the finalstretch tile shifting persisting if you return to the main dimension and `final_colormode` isn't reset properly.
It's possible to do so in the main game by using a teleporter in finalmode while having the Intermission 1 or 2 companion active.
For custom levels, level makers can make a setup that automatically turns on finalstretch, goes to finalmode, and then returns to the main dimension. The only thing being... as a level maker myself, this tile shifting *really* doesn't seem useful (and no one has ever used it because the setup to do so hadn't really been found or documented until this year). For one, the exact shift is randomized every time (there's an `fRandom()` call to cycle the colors). For two, it goes away after the player saves and reloads the level. And for …
=> Add finalmode check to drawfinalmap call

desktop_version/src/Graphics.cpp, desktop_version/src/Textbox.cpp, desktop_version/src/Textbox.h
Colors in over-30-FPS mode shouldn't be updating every deltaframe; mostly to ensure determinism between switching 30-mode and over-30 mode. I'm going to overhaul RNG in 2.4 anyway, but right now I'm going to fix this because I missed it.
The RNG of each special text box is stored in a temporary variable on the text box itself, and only updated if the color uses it (hence the big if-statement). Lots of code duplication, but this is acceptable for now.
=> Don't update crewmate colors in text boxes every deltaframe

desktop_version/src/Entity.cpp, desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/Input.cpp, desktop_version/src/KeyPoll.h, desktop_version/src/Render.cpp, desktop_version/src/editor.cpp
This is a lot of copy-pasted code, but a little bit of copy-pasting never hurt anyone...
The keybind to interact with activity zones and teleporters is now separate from the keybind to open the map, or return to the editor from in-editor playtesting, or restart a time trial. The keybind is now E, and the default controller bind is X. No controller button prompts, but the game didn't have controller button prompts anyways, so whatever.
Doing this now because if people's muscle memory are going to be broken by not being able to spam the map keybind anymore, at least we can help a bit by changing the keybind so they can keep spamming it - their muscle memory is going to be broken anyways.
This option has to be enabled by going to the speedrunner menu options and selecting "interact button". …
=> Separate pressing Enter to open map from pressing Enter to interact

desktop_version/src/Game.cpp
This fixes an oversight that could lead to confusion by the player.
`showtargets` is the variable that shows all unexplored teleporters on the map as a question mark, so players know where to head to to make progress. However, it previously was not directly saved to the main game file. Instead, it would be set to true if flag 12 was turned on in the save file.
How well does flag 12 correlate with `showtargets`?
Well, the script that turns on `showtargets` (`bigopenworld` and `bigopenworldskip`) doesn't turn it on. Neither does completing Space Station 1.
This flag is only turned on when the player activates Violet's activity zone for the first time.
Therefore, it's entirely possible that a new player could complete Space Station 1, then save their game, and come back to resume playing …
=> Save showtargets to main game save files

desktop_version/src/Entity.cpp
There is a pattern in the Super Gravitron that is meant to "staircase", similar to the Gravitron in Intermission 2. It looks like this:
<sup>How the pattern was intended - four descending squares, with two offscreen, and one more yet to spawn.</sup>
Unfortunately, due to an oversight, this pattern can only ever produce 1 square or 4 squares, which look out of place. So instead it currently looks like:
<sup>There is only one square on the left, then it immediately goes to a different pattern (two sets of two squares vertically opposite each other).</sup>
Both gravitrons are state machines (of course). States 20 and 21 in the Super Gravitron are this staircase pattern (state 20 spawns the squares on the left, state 21 spawns the squares on the right).
The only way states 20 and 21 can be …
=> Fix Super Gravitron pattern oversight

desktop_version/src/Entity.cpp
This fixes a bug where the player's y-position would be incorrect if they loaded a save that was on a conveyor and it was their first time loading in since the game was opened.
This is because on the first load, the game creates a new player entity, but on subsequent loads, the game re-uses the player entity. Subsequent loads use `mapclass::resetplayer()`, which already has the `newxp`/`newyp` fix, but as for the first time, the game does not set `newxp`/`newyp`.
So just set `newxp`/`newyp`, like in `mapclass::resetplayer()`.
=> Set newxp/newyp when creating player

desktop_version/src/Logic.cpp
If you have invincibility enabled, the tower camera behavior is inconsistent.
In ascending towers, you can "push" the camera upwards; however you cannot push it downwards; at least it stays still when it comes up to you if you stay still. In descending towers, the camera moves quicker when you're at the bottom of the screen, but it's slower than your falling speed and quickly loses sight of you; the camera can be pushed upwards; unfortunately it also does a "bumping" motion if you're standing still when the camera reaches you, which gets real annoying and isn't particularly pleasant to look at.
There are two problems, so this PR does two fixes:
1. Pushing the camera now applies the appropriate counter-offset depending on the direction of the tower. You can now push the camera downwards in …
=> Fix tower camera invincibility inconsistencies

desktop_version/src/FileSystemUtils.cpp, desktop_version/src/Network.c, desktop_version/src/Unused.h, desktop_version/src/UtilityClass.cpp, desktop_version/src/UtilityClass.h
If a level zip is named `LEVELNAME.zip`, the level file inside it must also be named `LEVELNAME.vvvvvv`, else custom assets won't work.
This is because when we mount the zip file, we simply add `LEVELNAME.vvvvvv` to the levels directory. Then whenever we load `LEVELNAME.vvvvvv`, we look at the filename, remove the extension, and look for the assets inside the zip of the same name, `LEVELNAME.zip`.
As a result, if someone were to make a level zip with assets but mismatch the filename, the assets wouldn't load. Furthermore, if someone were to add extra levels in the same zip, they wouldn't have any assets load for them as well, which could be confusing.
To make things crystal-clear to the user, we now filter out any zips that have incorrect structures like that, and print a message to the …
=> Add zip structure checks for user friendliness

desktop_version/src/editor.cpp
For consistency, the Viridian squeak will now play whenever you start editing a level description field, or finish editing it (either by pressing Esc or Enter).
=> Play Viridian squeak when editing level desc fields

desktop_version/src/Input.cpp
Settings are now saved after updating controller keybinds, and Viridian squeaks are played when using the controller keybind options.
=> Fix inconsistencies with controller keybind options

desktop_version/src/Render.cpp
The text box drawn at the bottom of the map screen isn't wide enough, so it's possible to see the corners on the right side of the text box if you have custom graphics like I do.
The solution is to increase the width of the text box by one tile.
=> Fix being able to see box corners on map screen with custom graphics

desktop_version/src/Script.cpp
When `rollcredits` is ran during in-editor playtesting, all unsaved data is lost. To prevent this, just return to the editor if `rollcredits` is ran, with a note saying "Rolled credits".
=> Prevent losing level data with rollcredits

desktop_version/src/Script.cpp
If you enter the Secret Lab from the title screen, all rooms will be explored. However, if you enter the Secret Lab via the Secret Lab
entrance cutscene (epilogue), not all rooms will be explored, which is inconsistent.
To do this, just do an `SDL_memset()` for the `entersecretlab` script command.
=> Explore all rooms when entering Secret Lab 

desktop_version/src/Graphics.cpp
This is more future-proofing than anything else. The position of the indicators is just the x-position of the gravitron square divided by 10, but the gravitron squares will always only ever move at 7 pixels per frame - so the distance an indicator travels on each frame will only ever be at most 1 pixel. But just in case in the future gravitron squares become faster than 10 pixels per frame, their indicators will be interpolated as well.
=> Interpolate gravitron square indicators

desktop_version/src/Render.cpp
This makes the text much more readable against certain backgrounds (if you have text outline enabled), especially against the Warp Zone background (when you start in "This is how it is").
Without outline:
Bad contrast, especially when the text glow turns blue.
With outline:
Excellent contrast.
=> Outline time trial countdown

desktop_version/src/Input.cpp
This fixes a regression where you're able to start flipped by restarting and then holding ACTION.
This happens because when the game resets all variables, it turns `hascontrol` back on (because of `hardreset()`). However, this is handled in the input function, and it's handled before player input is handled, so the player is able to get 1 frame of being able to flip after a time trial resets.
Why didn't this happen in 2.2? Because `resetplayer()` in 2.2 would set `lifeseq` to 10, as if the player had died. However, this is inconsistent, because loading in to the game for the first time would not result in a `lifeseq` of 10. So, in 2.2, restarting the time trial would remove that 1 frame of being able to flip because of `lifeseq`, while 2.3 doesn't set `lifeseq` because the player hasn't …
=> Fix being able to start flipped in time trials

desktop_version/src/Input.cpp
For some reason this button was missing the Viridian squeak.
=> Play Viridian squeak when using return button in audio options

desktop_version/src/Render.cpp
In order to help players spot the difference between outlined text and non-outlined text, we now outline the text outline text itself (if text outline is enabled, of course). But drawing the outline alone doesn't stand out enough, so we have to draw a solid backing against the text as well, in order to properly show the contrast.
Outline enabled:
Outline disabled:
=> Outline text outline text and draw backing

desktop_version/CONTRIBUTORS.txt, desktop_version/src/FileSystemUtils.cpp, third_party/tinyxml2/tinyxml2.cpp
- use fseeko and ftello like FreeBSD in tinyxml2
- use current directory as basePath if NULL (OpenBSD doesn't actually support this feature it is disabled via a patch in their ports)
=> Support for OpenBSD

desktop_version/src/Game.cpp
In earlier 2.3, if the roomname was empty, Dimension VVVVVV was used instead. However, instead of doing that, it's better to just use the hiddenname instead. Both because it's less hardcoded, and some rooms have hidden names that aren't Dimension VVVVVV.
=> Use hiddenname for hardestroom if roomname is empty

desktop_version/src/Entity.cpp
This fixes one of two desyncs in my Nova TAS.
The problem is that by adding two frames of edge-flipping to vertically moving platforms, Viridian's framedelay is updated for one extra frame after they step off of a vertically-moving platform. This then messes up Viridian's drawframe for the rest of the TAS until they die in a drawframe-sensitive trick.
The solution here is to only set the visual `onroof`/`onground` to 1 instead. The logical `onroof`/`onground` is still 2, so players still have two frames of edge-flipping off of vertically-moving platforms - it just won't really look like it (not that you could easily tell anyway).
=> Set visualonroof/visualonground to 1 on vertically-moving platforms

desktop_version/src/Input.cpp
This fixes a regression where you're unable to activate activity zones in in-editor playtesting if your interact button is not separate from the map button.
When I originally did #743, I didn't have an option to set the bind to be non-separate, so I removed this logic without adding a `game.separate_interact` check. But when I added the option, I overlooked this code, and so this regression happened. Whoops.
=> Re-add playtesting passthrough code block for non-separate interact

desktop_version/src/editor.cpp
In the past, people have reported having glitched levels where they can't get the trinket star or can't complete the level because the number of trinkets or crewmates is one higher than what can be obtained in the level.
How did this happen? Well, it turns out that if you place an entity, and then resize the level to be smaller, that entity still exists. This is inconsequential for most entities, but if the entity is a trinket or crewmate, that entity is still counted towards the number of trinkets or crewmates in the level.
One fix would be to just remove entities whenever the level is downsized, but then if someone accidentally downsizes the level and wants to go back, that entity will be gone. Plus, it would be inconsistent with tiles, because tiles don't get removed when you downsize …
=> Custom levels: only count inbounds trinkets and crewmates

desktop_version/src/Logic.cpp
=> Fix wrong bounds check when colliding with activity zones

desktop_version/README.md
Update the desktop project generation code snippet currently, as it still references SDL2 2.0.10 even though building now requires 2.0.14.
Just a minor nitpick on my part.
=> Update project generation snippet to reference SDL2 2.0.14

desktop_version/src/Ent.cpp, desktop_version/src/Ent.h, desktop_version/src/Entity.cpp, desktop_version/src/Entity.h, desktop_version/src/Logic.cpp
This fixes a regression that desyncs my Nova TAS after re-removing the 1-frame input delay.
Quick stopping is simply holding left/right but for less than 5 frames. Viridian doesn't decelerate when you let go and they immediately stop in place. (The code calls this tapping, but "quick stopping" is a better name because you can immediately counter-strafe to stop yourself from decelrating in the first place, and that works because of this same code.)
So, the sequence of events in 2.2 and previous looks like this:
- `gameinput()`
- If quick stopping, set `vx` to 0
- `gamerender()`
- Change `drawframe` depending on `vx`
- `gamelogic()`
- Use `drawframe` for collision (whyyyyyyyyyyyyyyyyyyyyyyyyyyy)
And now (ignoring the intermediate period where the whole loop order was wrong), the sequence of …
=> Fix regression with quick stopping changing drawframe

desktop_version/src/FileSystemUtils.cpp
It was checking for `.vvv-mnt-temp-XXXXXX/LEVELNAME.vvvvvv` instead of `LEVELNAME.vvvvvv`. When PhysFS enumerates the folder, it only gives us `LEVELNAME.vvvvvv`, and not `.vvv-mnt-temp-XXXXXX/LEVELNAME.vvvvvv`.
=> Fix zip structure checks checking for wrong filename

desktop_version/src/FileSystemUtils.cpp
Two problems: the `fRandom()` range was from 0..36, but that's 37 characters, not 36. And the check to sort the lower 26 values into the Latin alphabet used a 'lesser-than-or-equal-to 26' check, even though that checks for the range of values of 0..26, which is 27 letters, even though the alphabet only has 26 letters. So just drop the equals sign from that check.
=> Fix generateBase36 generating more than base 36

desktop_version/src/Input.cpp
For consistency, this should be done to match pressing Esc on the map screen.
=> Play Viridian squeak when pressing Esc in teleporter menu

desktop_version/CMakeLists.txt, desktop_version/src/Entity.cpp, desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/GlitchrunnerMode.c, desktop_version/src/GlitchrunnerMode.h, desktop_version/src/Input.cpp, desktop_version/src/KeyPoll.cpp, desktop_version/src/Logic.cpp, desktop_version/src/Map.cpp, desktop_version/src/Render.cpp, desktop_version/src/Script.cpp
Previously, turning glitchrunner mode on essentially locked you to emulating 2.0, and turning it off just meant normal 2.3 behavior. But what if you wanted 2.2 behavior instead? Well, that's what I had to ask when a TAS of mine would desync in 2.3 because of the two-frame delay fix (glitchrunner off), but would also desync because of 2.0 warp lines (glitchrunner on).
What I've done is made it so there are three states to glitchrunner mode now: 2.0 (previously just the "on" state), 2.2 (previously a state you couldn't use), and "off". Furthermore, I made it an enum, so in case future versions of the game patch out more glitches, we can add them to the enum (and the only other thing we have to update is a lookup table in `GlitchrunnerMode.c`). Also, 2.2 glitches exist in 2.0, so you'll want …
=> Split glitchrunner mode into multiple versions

desktop_version/src/Graphics.cpp
There's nothing to interpolate. It moves at one pixel per frame. And interpolating sometimes results in the box being short by 1 pixel to cover the whole screen on deltaframes, so if you stand on the right edge of the screen and have a translucent sprite, it will quickly draw over itself many times, and it looks glitchy. This commit fixes that bug.
=> Don't lerp when drawing all-sides warp background

desktop_version/src/editor.cpp
This fixes being able to re-trigger the fadeout while a fadeout is already happening. It also fixes being able to enter playtesting during the fadeout, which means the level now has a fadeout you normally can't do in actual gameplay.
=> Don't take editor input when fading out

desktop_version/src/Entity.cpp
This ensures that if the game crashes afterwards, the new `stat_trinkets` value won't be lost.
=> Save stats when setting stat_trinkets

desktop_version/src/Script.cpp
This fixes a bug where the player would always be facing right if they were loading in for the first time. This essentially made them always ignore the facing direction set in the save file if the facing direction was leftwards.
The problem is facing direction only gets set in `map.resetplayer()`, but if loading in for the first time, that path is never taken (unless you are loading a main game quicksave that's inside a tower). The solution is to always reset the player, even after creating them for the first time.
=> Always reset player when starting gamemode

desktop_version/CONTRIBUTORS.txt, desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/Input.cpp, desktop_version/src/Render.cpp
Since the game's speedruns are timed based on the IGT it would be useful to display it during gameplay.
How it looks:
It displays behind textboxes and the cutscene screen border effect, doesn't display on super gravitron and the game complete screen
=> Add in-game timer option

desktop_version/src/Input.cpp, desktop_version/src/Render.cpp
This is because the fade delay did not last long enough.
I was under the mistaken impression that the fade animation lasts for 15 frames. However, this does not account for the fact that the offset of each fade bar is dependent on RNG, and the worst case scenario is that they have an offset of 96 pixels (in the opposite direction of the fade).
The actual fade animation timer accounts for the worst case scenario, so the fade animation actually lasts for (320 pixels plus 96 pixels is 416 pixels, 416 pixels divided by 24 pixels per frame equals 17.333... frames, but since the actual timer keeps adding/subtracting 24 pixels per frame until it passes the 416-pixel threshold, that gets rounded up to...) 18 frames.
And an extra frame to make it so deltaframe interpolation doesn't suddenly stop …
=> General bug fixes

desktop_version/src/Map.cpp, desktop_version/src/Map.h, desktop_version/src/main.cpp
This can happen if you select an option in a menu that (A) returns to the previous menu and (B) saves settings. If the settings save fails, this will create another menu on the same frame that cycles the tower BG after it's already been cycled for that frame. Examples are the slowdown and glitchrunner menus.
I could fix this by creating a new function that copy-pastes all of `Game::savestatsandsettings_menu()` except for the `map.nexttowercolour()` at the end. But that's copy-pasting code.
Instead what I've done is added a variable to signal if the color has already been cycled this frame, so we don't cycle it again. This also covers cases of possible double-cycling in the future as well.
section of the credits for all of said releases, …
=> Fix cycling title BG more than once per frame

desktop_version/src/Graphics.cpp
Since colors going into `FillRect()` need to be in BGR format, we need to use `getBGR` instead. (Well, actually, it gets passed in RGB, but then at some point the order gets switched around, and, really, this game's masks are all over the place, I'm going to fix that in 2.4.)
=> Fix regression with chunky pixels being the wrong color

desktop_version/src/FileSystemUtils.cpp
Let's say you have a zip named `LEVELNAME.zip`, but the only `.vvvvvv` file it contains is `NOTLEVELNAME.vvvvvv`. This zip would end up printing both the '`LEVELNAME.vvvvvv` is missing' and 'It has `.vvvvvv` file(s) other than `LEVELNAME.vvvvvv`' messages, even though we already know there's something wrong with the zip, and the 'other level files' message is redundant, since in this case the problem here is simply just the `.vvvvvv` file being named the wrong way.
The 'other level files' message is only intended to be printed when `LEVELNAME.vvvvvv` *does* exist, but there's additional `.vvvvvv` files in the zip on top of that, so don't print this message if `LEVELNAME.vvvvvv` exists.
section of the credits for all of said releases, but …
=> Don't print redundant zip structure failure message if .vvvvvv file not found

desktop_version/src/Graphics.cpp, desktop_version/src/UtilityClass.h
It's quite rude to close the game. Especially if the user does not use the console. They won't know why the game closed.
Instead, just return -1. All usages of `font_idx()` should be and are bounds checked anyways. This will result in missing characters, but, it's not like the characters had a font image in the first place, otherwise we wouldn't be here. And if the user sees a bunch of
characters missing in their font, they'll probably work out what the problem is even without having a console. And it's still far better than abruptly closing the game.
And use `WHINE_ONCE` to prevent spamming the console.
=> Do not close game if fallback character is missing

desktop_version/src/Map.cpp
Similar to disabling the elephant flashiness, at least one photosensitive person has told me the flashy color animation makes their
eyes kind of hurt a little bit. Also it screws up the compression really badly when they record (especially the green noisy tiles!).
The colors will still cycle, but the individual animations within each color will be completely static.
=> Disable final color animations if screen effects off

desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/Input.cpp, desktop_version/src/KeyPoll.cpp, desktop_version/src/Render.cpp
Some people prefer the 2.2 behavior where unfocusing pauses the game, but the music still plays. One such person is Trinket9 on the VVVVVV Discord server, who wanted it that way.
The reason audio pausing was added in the first place was to prevent desyncing music in levels with cutscenes that synced to music. Rather than reverting it, let's add this option instead.
=> Add unfocus audio pause option

desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/KeyPoll.cpp, desktop_version/src/Script.cpp
If you have unfocus pause off, and unfocus audio pause off, then this command will go into effect. When it's set to on, the audio will pause when you unfocus the game. When it's set to off, the audio will not. This is different from the setting, and gets saved to the save file.
This was created in response to #799 being merged.
=> Add audiopause(on/off) command

desktop_version/src/Game.cpp
Since custom levels have gained the functionality to show trinkets on the minimap, it's nice to just save the `showtrinkets` variable directly to the save file, without having to make level makers handle it themselves.
=> Save showtrinkets to custom level quicksaves

desktop_version/src/Game.cpp
Previously, you would only get the trinket completion star if you got the exact same amount of trinkets as there are custom entity trinkets in the level file. But if you got more (say, if the level spawned extra "bonus trinkets"), you wouldn't be able to get the star.
This is true of the custom crewmate case as well, but I've decided to not change that case, because there are still downsides to the resulting behavior and it's better to just leave it alone because it's rare for it to happen anyways.
=> Allow getting star if more trinkets than level trinkets

desktop_version/src/Game.cpp, desktop_version/src/Input.cpp, desktop_version/src/Render.cpp
It's possible to get one page of levels by removing all the built-ins, either by removing them directly from `data.zip` or by putting files with the same filenames as them in your level folder that don't contain nothing.
And hey, there's already a check for if no levels exist at all, so why not check for this too?
=> Don't show next/previous page options if only one page

desktop_version/src/Script.cpp
=> Cycle tower color if loading level has error

desktop_version/src/Script.cpp, desktop_version/src/Script.h
Since `createentity()` started accepting `p1`/`p2`/`p3`/`p4` arguments, it now unconditionally passes in whatever arguments were present there previously, when there weren't any before.
This can lead to unexpected behavior when selectively using and then omitting `p1`/`p2`/`p3`/`p4` arguments.
Also, plenty of existing levels already only use the 5-argument version of `createentity()`. And `createcrewman()` can take up to 6 arguments at once. It's not far-fetched that an existing level could `createentity()` right after doing a 6-argument `createcrewman()`, which would lead to a different behavior than in 2.2 and previous.
So instead, instead of checking if `words[index]` is an empty string (it only sets the string to be empty if there are enough argument separators on the line), …
=> Actually have p1/p2/p3/p4 defaults for createentity() command

desktop_version/src/Script.cpp
63a487d20df72e5ed64d1625217fb4257a3cc668 only checked for the last argument, not for all arguments.
Fixes #822.
=> tokenize(): Check all arguments

desktop_version/CONTRIBUTORS.txt, desktop_version/src/Credits.h, desktop_version/src/Game.cpp, desktop_version/src/Render.cpp
This pull request standardizes punctuation and style for the categories and options of the new menu!
- All category and menu option descriptions have been given punctuation! In the old 2.2 menu, some pages consistently had punctuation and some didn't (ex. everything in "Graphic Options" had punctuation while everything in "Game Options" didn't), so now all descriptions do.
- Some options/titles have been changed slightly for clarity or consistency.
- Options which did not have a description and only indicated their status have been given one (ex. the fake loading screen).
- Spacing between descriptions and status indicators has been standardized to one line of space (some options had their indicator two lines away from the description, such as with slowdown or vsync, while others had it …
=> Standardize punctuation and style for the new options menu

desktop_version/src/Map.cpp, desktop_version/src/Otherlevel.cpp, desktop_version/src/Otherlevel.h
It seems appropriate that these rooms should have their names shown on the map screen.
=> Set Secret Lab/Super Gravitron hidden names

desktop_version/src/Entity.cpp, desktop_version/src/Entity.h, desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/Logic.cpp, desktop_version/src/Map.cpp, desktop_version/src/Script.cpp
The three temporary variables were `game.roomchangedir`, `obj.linecrosskludge`, and `game.roomchange`. Moving them off makes it easier to reason about what happens in `mapclass::gotoroom()`.
Also, the `screen_transition` variable in `gamelogic()` got axed in favor of using the already-existing `roomchange` instead.
=> Move temporary variables in mapclass::gotoroom() off of their classes

desktop_version/src/Script.cpp
`destroy(platforms)` has been bugged since 2.0. The problem with it is that it removes the platform entity, but doesn't remove its block. This results in essentially turning the platorm invisible and stopping it from moving.
This error should be fixed, but some levels (including my own) rely on the invisible platform trick. So instead, the fixed version will be implemented under a different name, `destroy(moving)`.
There's also another problem with `destroy(platforms)`, which is that the name is misleading and it doesn't additionally destroy disappearing platforms. I would also fix this, but in order to not run the risk of breakage, it will have to be implemented under a different name, too. So this will be `destroy(disappear)`. As an added benefit, it's also more granular to have …
=> Fix destroy(platforms), implement under different names

desktop_version/src/Entity.cpp, desktop_version/src/Entity.h, desktop_version/src/Script.cpp
This PR adds two new internal commands to the game, being `setactivitycolour` and `setactivitytext`.
`setactivitycolour(colour)` sets the colour of the next activity zone spawned to the colour you pass as an argument, and `setactivitytext` changes the text of the net activity zone spawned to the text on the next line.
These changes were made this way to keep forwards compatibility; levels that use these commands will not break on earlier versions, only have the default orange `Press ENTER to activate terminal` text which would be shown anyway.
Additionally, activity zones spawned with ID 35 (custom level terminal) which are spawned through `createactivityzone` have had their default text changed to `Press ENTER to interact` (from `Press ENTER to activate terminal`). This change was done …
=> Custom activity zone text and colours

desktop_version/src/Entity.cpp, desktop_version/src/Entity.h, desktop_version/src/Game.cpp, desktop_version/src/Graphics.cpp, desktop_version/src/Map.cpp, desktop_version/src/Otherlevel.cpp, desktop_version/src/Script.cpp
Originally this started as a "deduplicate a bunch of duplicated code in script commands" PR, but as I was working on that, I discovered there's a lot more that needs to be done than just deduplication. Anything which needs a crewmate entity now calls `getcrewmanfromname(name)`, and anything which just needs the crewmate's color calls `getcolorfromname(name)`. This was done to make sure that everything works consistently and no copy/pasting is required. Next is the fallback; instead of giving up and doing various things when it can't find a specific color, it now attempts to treat the color name as an ID, and if it can't then it returns -1, where each individual command handles that return value. This means we can keep around AEM -- a bug used in custom levels -- by not doing anything with …
=> Refactor colors in internal commands

desktop_version/CMakeLists.txt, desktop_version/src/BinaryBlob.cpp, desktop_version/src/BinaryBlob.h, desktop_version/src/FileSystemUtils.cpp, desktop_version/src/Music.cpp, third_party/physfs/physfsrwops.c, third_party/physfs/physfsrwops.h
Files are loaded from paths like `/home/leo60228/.local/share/VVVVVV/music/6presentingvvvvvv.ogg`. This allows the game to have less than 20MB of peak heap usage (though still ~100MB of non-heap RAM usage, which I'm investigating).
=> Fallback to loading music from loose files if vvvvvvmusic.vvv is invalid or missing

desktop_version/src/Input.cpp
(this is a replacement for #485 since GitHub doesn't allow editing the repo of an existing PR)
Closes #484
Flipping only applies momentum to the player entity currently being processed. This normally wouldn't be a problem. However, flipping involves global state, and only one flip can occur per frame. This means that additional player entities don't get this boost of momentum, which feels somewhat unnatural during gameplay.
This commit fixes this by splitting flip logic out of the loop over player entities, and applying the flip momentum to all player entities.
=> Split flip logic from player input logic

desktop_version/CMakeLists.txt, desktop_version/src/BinaryBlob.cpp, desktop_version/src/Entity.cpp, desktop_version/src/FileSystemUtils.cpp, desktop_version/src/Game.cpp, desktop_version/src/Graphics.cpp, desktop_version/src/GraphicsResources.cpp, desktop_version/src/Input.cpp, desktop_version/src/KeyPoll.cpp, desktop_version/src/Music.cpp, desktop_version/src/Screen.cpp, desktop_version/src/Script.cpp, desktop_version/src/SoundSystem.cpp, desktop_version/src/SteamNetwork.c, desktop_version/src/UtilityClass.h, desktop_version/src/Vlogging.c, desktop_version/src/Vlogging.h, desktop_version/src/editor.cpp, desktop_version/src/main.cpp
In the spirit of naming things after Vs, I have named the log system "V-Log", so the function prefix is named `vlog`. I insist that everyone pronounce it as "VEE-log" and not "vuh-LOG"; defection from this norm will result in a fine of 500 V-Bucks (inflation adjusted).
Anyways, this introduces `vlog_info()`, `vlog_warn()`, `vlog_error()`, and `vlog_debug()`, which you should all start using instead of `printf()`, `puts()`, or `fprintf()`.
Everything except debug logs are enabled by default. To disable all output, pass in `-nooutput` on the command-line. To disable info, do `-noinfo`; to disable warnings, do `-nowarn`; to disable errors, do `-noerror`. To enable debug logs, do `-debug`.
There are also colors, which are enabled if the game thinks it's outputting to a TTY. Else, it's …
=> Overhaul logging

desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/editor.cpp
All XML functions now check the return value of `tinyxml2::XMLDocument::Error()` after each document gets loaded in to TinyXML-2. If there's an error, then all functions return. This isn't strictly necessary, but printing the error message that TinyXML-2 is the bare minimum we could do to be useful.
Additionally, I've standardized the error messages of missing or corrupted XML files.
Also, the way the game went about making the XML handles was... a bit roundabout. There were two XML handles, one for the document and one for the root element - although only one XML handle suffices. So I've cleaned that up too.
I could've gone further and added error checking for a whole bunch of things (e.g. missing elements, missing attributes), but this is good enough.
Also, if `unlock.vvv` or …
=> Simplify and print XML errors from TinyXML-2

desktop_version/src/FileSystemUtils.cpp, desktop_version/src/FileSystemUtils.h, desktop_version/src/Game.cpp, desktop_version/src/Game.h
While thinking about #835, I realized that I can sidestep asyncify entirely by directly calling the relevant functions via inline JS.
=> Call FS.syncfs on Emscripten

desktop_version/src/Script.cpp, desktop_version/src/main.cpp
`SDL_GetTicks64()` is a function that got added in SDL 2.0.18, which is just an `SDL_GetTicks()` without a value that wraps every ~49 days, instead wrapping after the sun explodes and kills us all. Oh sorry, didn't mean to get existential.
For now, put this behind an `SDL_VERSION_ATLEAST` guard, which will be removed when SDL 2.0.18 officially releases and we can update to it.
Don't merge this until libsdl-org/SDL#4872 is merged into SDL 2.0.18.
=> Switch over to using `SDL_GetTicks64()`

desktop_version/src/FileSystemUtils.cpp, desktop_version/src/Graphics.cpp
In two places, `vlog_error` is fed a string, even though it takes a format string. This causes warnings for me:
```
FileSystemUtils.cpp:309:16: warning: format not a string literal and no format arguments [-Wformat-security]
309 |     vlog_error(levelDirError);
|                ^~~~~~~~~~~~~
```
And this one is repeated several times:
```
Graphics.cpp:324:20: warning: format not a string literal and no format arguments [-Wformat-security]
324 |         vlog_error(error); \
|                    ^~~~~
```
The fix is to change these into `vlog_error("%s", levelDirError)` and `vlog_error("%s", error)`.
=> Fix -Wformat-security warnings

desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/Render.cpp, desktop_version/src/UtilityClass.cpp, desktop_version/src/UtilityClass.h
(The commit message says it all:)
Here's my notes on all the existing functions and what kind of time
formats they output:
- Game::giventimestring(int hrs, int min, int sec)
H:MM:SS
MM:SS
- Game::timestring()
// uses game.hours/minutes/seconds
H:MM:SS
MM:SS
- Game::partimestring()
// uses game.timetrialpar (seconds)
MM:SS
- Game::resulttimestring()
// uses game.timetrialresulttime (sec) + timetrialresultframes (1/30s)
MM:SS.CC
- Game::timetstring(int t)
// t = seconds
MM:SS
- Game::timestringcenti(char* buffer, const size_t buffer_size)
// uses game.hours/minutes/seconds/frames
H:MM:SS.CC
MM:SS.CC
- UtilityClass::timestring(int t)
// t = frames, 30 frames = 1 second
S:CC
M:SS:CC
This is kind of a mess, and there's a lot of functions that do the same
thing except using different variables. …
=> Simplify time formatting functions

.github/workflows/ci.yml
Required for Actions workflow due to windows-latest Version Change
(Alternatively, pin Windows to 2019)
I was having build issues on my fork, turns out the Github Actions [windows-latest version change](https://github.com/actions/virtual-environments/issues/4856) breaks the CMake Generator used atm.
Update it to keep compatibility with windows-latest.
=> Update VS2019 to VS2022

desktop_version/CMakeLists.txt
So, it turns out we weren't quite done fighting CMake yet...
To accommodate #869 (and actually also #272), the C standard was raised from C90 to C99. This turned out to require a bit of a fight with the CentOS CI's CMake version to get it to set the flags we wanted (and to not overwrite them later). Eventually the fix was to move the block that sets the standards to later in the file, which was done in 24353a54bb40665b64a93faebfb2ebd96cd0f6b5.
However, in [this comment](https://github.com/TerryCavanagh/VVVVVV/pull/869#pullrequestreview-917605059), I saw this screenshot:
> ![2022-03-22_10-21-52](https://user-images.githubusercontent.com/59748578/159538971-19a0e6ca-5a02-49d3-8854-6eb03ddd4218.png)
Where's the `--std=c++98` now?
As it apparently turns out, if your CMake is at least 3.1.3 and …
=> Fix C/C++ standards being unset for VVVVVV target if CMake is >= 3.1.3

.github/workflows/ci.yml, .gitmodules, desktop_version/CMakeLists.txt, desktop_version/Dockerfile, desktop_version/README.md, desktop_version/src/Music.cpp
I was browsing the repo and saw #829, with the note that porting to FAudio should be "really easy" for someone else to do.
Answer is no it wasn't (tbf I never touched any audio stuff ever), but I tried nonetheless.
This should be functional, but buggy. I'm opening the PR to see if I should continue or just stop.
~~Thanks for looking at my awful code~~
CI is failing because I used a submodule for FAudio. I can either make CI clone recursive or just copy folder contents, will wait for feedback on that.
Had to increase C Standard Version due to stb_vorbis (90 -> 99). If someone has suggestions on how to avoid that please share.
Most Bugs revolve around tabbing in and out of the game. Sometimes there is no `Resume()` generated for some reason I think. For example, tabbing out during the intro …
=> Port to FAudio

desktop_version/src/Music.cpp
Missed a Bug in #869.
When changing Areas, [this](https://github.com/TerryCavanagh/VVVVVV/blob/master/desktop_version/src/Music.cpp#L1010) line checks if Music is halted before playing the next track. However, it was never being halted, just paused.
Changing `haltdasmusik` to actually halt `MusicTrack` fixes it, but given the comment placed I wonder if this is the right approach. Could also check if Music is paused at the original location.
=> Fix music changes between areas

.github/workflows/ci.yml, desktop_version/Dockerfile, desktop_version/README.md
2.0.22 just released 40 minutes ago.
This also updates the `Dockerfile` to use the URL from the GitHub releases page, instead of SDL's servers.
I've also pushed a new Docker container to `ghcr.io/infoteddy/vvvvvv-build`.
=> Update SDL version to 2.0.22

desktop_version/CMakeLists.txt, desktop_version/src/CWrappers.cpp, desktop_version/src/CWrappers.h, desktop_version/src/Editor.cpp, desktop_version/src/VFormat.c, desktop_version/src/VFormat.h
=> Implement new string formatting system (VFormat)

desktop_version/src/CustomLevels.cpp, desktop_version/src/CustomLevels.h, desktop_version/src/main.cpp
As already described in cc61194bed324e9fbf51847915357d613a94ff47, as well as Ved's commits from the last almost two weeks, starting VVVVVV from Ved for playtesting could be made a lot faster by "preloading" the game - letting it do all its asset loading in the background without creating a window - and then waiting until the level is passed in via stdin. There's only one problem left with this approach: VVVVVV currently expects the starting position to be passed via command line arguments, which isn't known yet at the time we'd like to start VVVVVV. Therefore, this commit allows passing the starting position via the level XML, instead of via arguments.
The extra XML looks like this, and is added next to the `<Data>` tag:
```xml
<Playtest>
<playx>214</playx>
<playy>112</playy> …
```
=> Add support for start position via level XML for CLI playtesting

desktop_version/README.md
VVVVVV uses submodules now, so you need to know how to initialize them.
I'm explicitly not including `git clone --recurse-submodules`. Usage of submodules in git projects is kinda rare in my experience, so people are used to doing simple clones, and that instruction would just result in people being annoyed thinking they have to delete the repo they already cloned, and clone it again except slightly differently.
It also doesn't help you if you need submodules that aren't in the master branch (for example, if you clone my fork recursively and then checkout the localization branch, you won't have C-HashMap and you'll need the update command anyway). And you also need it whenever VVVVVV updates its submodules. So teaching people just the update command is better. …
=> Clarify submodules in desktop_version/README.md

desktop_version/src/Input.cpp
In editor playtesting, If you die while in a teleporter activity zone and you press ENTER, you open the map screen. This can lead to a crash viewing the CREW tab due to data not being initialized. This PR simply makes sure you can't open the map in the editor.
This does NOT fix the glitchy map when using a teleporter in the editor, that'll be fixed in #898 shortly.
Fixes #892.
=> Don't open the map in the editor

desktop_version/src/Render.cpp, desktop_version/src/Script.cpp
This PR deduplicates a lot of map rendering code, as it's cloned a few times for the following reasons:
- Main game map
- Teleporter screen map
- Custom level map
This splits a lot of map rendering features into smaller functions, instead of a bunch of slightly different copy-pasted huge functions. This also allows the teleporter screen to work properly in custom levels with smaller map sizes, and with showing the legend (trinkets, teleporters, targets) in those as well.
This also cleans up some bad code such as fog rendering, so it uses a small for loop instead of 30+ lines of code...
**NOTE:** One of these changes means the teleporter screen in custom levels no longer always shows `minimap.png` -- it shows the map that custom levels are supposed to show. This is a _fix_, but I thought …
=> Deduplicate map rendering code

desktop_version/src/Entity.cpp, desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/Input.cpp, desktop_version/src/Map.cpp, desktop_version/src/Script.cpp
This PR adds a few new functions to manage changing the gamestate (`game.state`). While you're teleporting to the ship, it prevents the game from setting a new state until the initial teleport animation is finished. This is done using `lockstate()`, `unlockstate()`, and the generic teleport animation setting the state _manually_.
Fixes #448.
=> Add state locking

desktop_version/CONTRIBUTORS.txt, desktop_version/src/Credits.h, desktop_version/src/CustomLevels.cpp, desktop_version/src/Editor.cpp, desktop_version/src/Entity.cpp, desktop_version/src/Graphics.cpp, desktop_version/src/Graphics.h, desktop_version/src/GraphicsResources.cpp, desktop_version/src/GraphicsResources.h, desktop_version/src/GraphicsUtil.cpp, desktop_version/src/GraphicsUtil.h, desktop_version/src/Input.cpp, desktop_version/src/KeyPoll.cpp, desktop_version/src/Logic.cpp, desktop_version/src/Map.cpp, desktop_version/src/Render.cpp, desktop_version/src/RoomnameTranslator.cpp, desktop_version/src/Screen.cpp, desktop_version/src/Screen.h, desktop_version/src/Script.cpp, desktop_version/src/TowerBG.h, desktop_version/src/UtilityClass.h, desktop_version/src/main.cpp, desktop_version/src/preloader.cpp
This is quite a big PR.
Ever since VVVVVV was initially ported to C++ in 2.0, it has used surfaces from SDL. The downside is, that's all software rendering. This PR moves most things off of surfaces, and all into GPU, by using textures and SDL_Renderer.
Pixel-perfect collision has been kept by keeping a copy of sprites as surfaces. There's plans for pixel-perfect collision to use masks instead of reading pixel data directly, but that's out of scope for this PR.
Everything has been ported over, and from a bit of playtesting, I see no visual differences between the old system and the new one. This PR should help make the code more understandable and easier to mess with, while also providing a fair framerate boost, cutting down on CPU, and it maybe even cuts down on memory a bit.
Also as a …
=> Move the game off of surfaces, and use the render system instead

desktop_version/src/Graphics.cpp
The renderer branch had a last-minute fix for screenshaking, and I didn't fully think out the interactions between screenshaking and other features (or, well, the other feature) like `blackout()`. This fixes screenshaking not clearing the gameplay texture, which `blackout()` relies on for some weird reason.
=> Fix screenshake not clearing the gameplay cache

desktop_version/src/Graphics.cpp, desktop_version/src/Graphics.h, desktop_version/src/Script.cpp, desktop_version/src/Script.h, desktop_version/src/Textbox.cpp, desktop_version/src/Textbox.h
For some reason, textboxes can only have 11 lines added before the line list gets cleared. This changes that behavior, allowing a total of 26 lines before *ignoring* extra lines added. 26 is the maximum amount of lines that the screen can display vertically without the textbox going off-screen. As far as I can tell, this is only visual, and doesn't affect any used glitches.
=> Allow 26 textbox lines

desktop_version/src/Graphics.cpp
This fixes a regression introduced by #923 where flip mode no longer flips the screen while the screen is shaking.
=> Fix screen shake during flip mode not flipping the screen

desktop_version/src/BlockV.cpp, desktop_version/src/CustomLevels.cpp, desktop_version/src/CustomLevels.h, desktop_version/src/Script.cpp
Textbox colors are also hardcoded, this loads them from XML, this is a visual change.
```xml
<TextboxColours>
<colour r="170" g="47" b="88" name="test"></colour>
</TextboxColours>
```
=> Custom textbox colors

desktop_version/lang/ca/strings.xml, desktop_version/lang/en/strings.xml, desktop_version/lang/eo/strings.xml, desktop_version/lang/es/strings.xml, desktop_version/lang/nl/strings.xml, desktop_version/src/Render.cpp
Activity zone prompts have always been limited to a single line, because the text box had a hardcoded size. A translator requested for the possibility to add a subtitle under music names for the jukebox, and the easiest solution is to make it possible to translate a prompt with multiple lines. This is possible now, and the textbox even wordwraps automatically (using the normal `font::print_wrap`).
(I wouldn't really like to see translations using multiple lines for stuff like "Press ENTER to talk to Vitellary", especially if it wraps with one name and not with another, but if a string is too long, wordwrapping will look better than text running out of the box.) …
=> Allow multiple lines and wordwrapping in activity zone prompts

desktop_version/src/Game.cpp, desktop_version/src/Game.h
The `-addresses` command-line option added in 64be99d4 helps autosplitters on platforms where VVVVVV is not built as a position-independent executable. macOS has made it increasingly difficult, or impossible, to build binaries without PIE.
Adding an obvious string to search for will help tools that need to deal with versions of VVVVVV built with PIE. The bytestring to search for is `[vVvVvV]game`, followed by four null bytes (to avoid finding it in the program code section). This identifies the beginning of the game object; addresses to other objects can be figured out by relative offsets printed by `-addresses`, since ASLR can only change where the globals begin.
Partially f i x e s #928; it may still be advisable to figure out how to explicitly disable PIE on Windows/Linux.
By …
=> Add magic string to the start of the `game` global

desktop_version/src/Graphics.cpp
Operator precedence meant that `sc == 2 ? PR_2X : PR_1X | PR_CEN` didn't work how I expected it to.
So I added some parentheses.
=> Fix centering of translated "Level Complete!" and "Game Complete!"

.gitmodules, desktop_version/CMakeLists.txt, desktop_version/src/CustomLevels.cpp, desktop_version/src/Editor.cpp, desktop_version/src/Font.cpp, desktop_version/src/Graphics.cpp, desktop_version/src/KeyPoll.cpp, desktop_version/src/Localization.cpp, desktop_version/src/Textbox.cpp, desktop_version/src/UTF8.c, desktop_version/src/UTF8.h, desktop_version/src/VFormat.c
This adds a small library I wrote to handle UTF-8.
Usage is meant to be as simple as possible - see for example decoding a UTF-8 string:
```c
const char* str = "asdf";
uint32_t codepoint;
while ((codepoint = UTF8_next(&str)))
{
// you have a codepoint congrats
}
```
Or encoding a single codepoint to add it to a string:
```cpp
std::string result;
result.append(UTF8_encode(0x1234).bytes);
```
There are some other functions (`UTF8_total_codepoints()` to get the total number of codepoints in a string, `UTF8_backspace()` to get the length of a string after backspacing one character, and `UTF8_peek_next()` as a slightly less fancy version of `UTF8_next()`), but more functions could always be added if we need them.
This allows us to replace utfcpp (utf8::unchecked) - which is also done in this …
=> Add new UTF-8 library, remove utfcpp submodule, fix UTF-8 fixme in next_wrap()

desktop_version/src/CustomLevels.cpp, desktop_version/src/Finalclass.cpp, desktop_version/src/Game.cpp, desktop_version/src/Map.cpp, desktop_version/src/Map.h, desktop_version/src/Render.cpp, desktop_version/src/RenderFixed.cpp, desktop_version/src/RoomnameTranslator.cpp, desktop_version/src/Script.cpp
Roomname animations ("glitchy" and "changing" ones, used in the final level) are very hardcoded. Roomnames are solely visual, and some fun could be had with making them look cool.
Sample:
```xml
<SpecialRoomnames>
<static x="0" y="0" flag="2">This shows if flag 2 is on!</static>
<glitch x="0" y="0" flag="1">
<text>On the Waterfront</text>
<text>On the Vaterfront</text>
</glitch>
<transform x="1" y="0" loop="0" flag="1">
<text>Television Newsveel</text>
<text>Television Newsvel</text>
<text>TelevisvonvNewsvel</text>
<text>TvlvvvsvonvNevsvel</text>
<text>vvvvvvsvovvNe svel</text>
<text>vhv vvv'vvovv vevl</text>
<text>vhv V v'Cvovv vewv</text>
<text>vhe 9 v'Cvovv vewv</text>
<text>vhe 9 v'Cvovv Newv</text>
<text>The 9 O'Cvovk Newv</text>
<text>The 9 O'Clock News</text>
</transform> …
```
=> Unhardcoded glitchy and changing roomnames

desktop_version/src/Font.cpp
The hashmap would get populated with the name of each font, as each font was being added. Unfortunately, adding a font would also realloc the storage for fonts, in which the names are also stored... Possibly invalidating the pointers to the names. This is now fixed by populating the hashmap after all the fonts are added.
=> Fix possible dangling pointers in FontContainer.map_name_idx

desktop_version/src/Graphics.cpp, desktop_version/src/Graphics.h
Drawing a texture onto itself seems to produce issues on Metal.
To fix this, use a temporary texture instead, that then gets drawn onto the original texture.
Fixes #927.
=> Don't draw texture onto itself for scrolling

desktop_version/src/Editor.cpp, desktop_version/src/Font.cpp, desktop_version/src/Font.h, desktop_version/src/Graphics.cpp, desktop_version/src/Render.cpp, desktop_version/src/RoomnameTranslator.cpp, desktop_version/src/Textbox.cpp
Taking `const char*` instead of `const std::string&` means two things:
- If you already had a `const char*` (which is very common especially because `loc::gettext` gives them, and also string literals), your string is no longer converted into a `std::string` when calling `font::len`, `font::print` or `font::print_wrap`.
- If you had a `std::string` (for example due to string concatenation), you now need to call these functions with `.c_str()` (doesn't apply to `font::print` specifically).
In the case of `font::len` and `font::print_wrap`, they were pretty easy to change to taking only `const char*`. Any code that calls these functions needs to add `.c_str()` to any `std::string`s passed, and I didn't need to add them enough times to feel really worried about that (just 4 times for …
=> Change `font::len`, `font::print` and `font::print_wrap` text argument from `std::string` to `const char*`

desktop_version/src/Game.cpp
`hardestroom` currently stores the current roomname, but it was missing a call to get the translated string. This has been added, fixing the hardest room appearing as untranslated. This bug appeared in 5beaf973cefa0aa5a19655575d89b52febf21149.
=> Fix hardestroom not being translated

desktop_version/src/Font.cpp, desktop_version/src/Localization.cpp, desktop_version/src/LocalizationMaint.cpp, desktop_version/src/LocalizationStorage.cpp
- Hashmap keys are now const everywhere except in callbacks, meaning we don't need (char*) and (void*) casts whenever passing a const pointer anymore - so I cleaned up all these casts. (Guess C is a lot less strict with const than C++ is, and string literals aren't even const-qualified in C, but the reason hashmap keys aren't just const everywhere is because you may want to free a key based on a hashmap iteration).
- "no newline at end of file" warnings on macOS are fixed (for some reason, specifically macOS complained about that)
- "'return': conversion from 'uint64_t' to 'uint32_t', possible loss of data" warning on Windows is fixed (though Windows gives lots of these warnings, I guess /W4 is a bit too much...) …
=> Update c-hashmap submodule

desktop_version/src/FileSystemUtils.cpp, desktop_version/src/Font.cpp
This was an oversight when we migrated to the new UTF-8 system - it expects a null-terminated string, but the utfcpp implementation worked with a pointer to the end of the file instead.
I also added an assert in FILESYSTEM_loadFileToMemory() so this is less likely to happen again - because there should be no valid reason to have a NULL pointer for the total file size, as well as not wanting a null terminator to be added at the end of the file.
=> Fix font .txt files not being null-terminated

desktop_version/src/Graphics.cpp
Because of how `blackout` works, screen shaking must clear the gameplay buffer. `blackout` simply pauses rendering, so if the gameplay buffer gets cleared, then the screen will just be black, otherwise it'll look like the game is "frozen". VVVVVV only uses `blackout` during screen shaking, so it works as intended. However, when reimplementing this behavior in the move to using the SDL_Renderer system, I failed to notice that since my implementation always clears the gameplay buffer when shaking, if you open the menu during a shake, instead of seeing gameplay during the transition animation, you only see black. This has been fixed with a simple `game.blackout` check before clearing the gameplay buffer.
section of the credits for all of …
=> Fix the game texture clearing during menu shaking

desktop_version/src/Render.cpp
When `blackout` is active, the screen (to simplify) stops getting drawn to. The excecption is textboxes, which draw anyway. But since the screen isn't being cleared, removed textboxes stay on screen, since that texture isn't being cleared. In the SDL_Renderer PR, I accidentally broke this behavior, so this commit fixes it.
Fixes #951.
=> Fix textboxes fully fading out during blackout

desktop_version/lang/en/strings.xml, desktop_version/src/CustomLevels.cpp, desktop_version/src/Editor.cpp, desktop_version/src/Editor.h, desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/Graphics.cpp, desktop_version/src/Graphics.h, desktop_version/src/Render.cpp, desktop_version/src/RenderFixed.cpp, desktop_version/src/Script.cpp, desktop_version/src/main.cpp
The editor's code is all over the place, spread across dozens of `else if` chains, filled with repeating logic and math, useless code and broken code which somehow works. This PR is an attempt to clean it up, and while it's not perfect, it's a huge improvement.
Tools now get registered using `register_tool`, so everything about a tool is in one place instead of hardcoded. Instead of magic numbers denoting tools, an enum has been created, and logic has been extracted into simple switch/cases, with shared
logic being deduplicated.
A state system has been created, allowing the editor's input, logic and render functions to be cleaned up and organized quite a bit. This also means that the entire editor is no longer drawn over the settings UI, which might help with performance.
While warp lines …
=> Editor cleanup & refactor

desktop_version/lang/ca/cutscenes.xml, desktop_version/lang/de/cutscenes.xml, desktop_version/lang/en/cutscenes.xml, desktop_version/lang/eo/cutscenes.xml, desktop_version/lang/es/cutscenes.xml, desktop_version/lang/fr/cutscenes.xml, desktop_version/lang/it/cutscenes.xml, desktop_version/lang/nl/cutscenes.xml, desktop_version/lang/pt_BR/cutscenes.xml, desktop_version/lang/pt_PT/cutscenes.xml, desktop_version/lang/ru/cutscenes.xml, desktop_version/lang/tr/cutscenes.xml, desktop_version/src/LocalizationMaint.cpp, desktop_version/src/Script.cpp, desktop_version/src/Script.h
This was easier than I expected - just add an optional buttons="1" attribute to cutscenes.xml. It's treated like the speaker attribute - it's only there as context for the translator, and for the cutscene test.
Before:
After:
=> Make Violet's button dialogue work in cutscene test

desktop_version/src/Editor.cpp
Boxes could be placed by just holding down the left button. This PR adds a missing `!key.leftbutton` check, fixing this behavior.
=> Fix box placement in editor

.github/workflows/ci.yml
Apart from the CI seemingly liking to randomly twiddle its fingers for dozens of seconds or even minutes (are Windows shared runners overloaded or something?) and CMake (and probably also Visual Studio) still spending a lot of time rebuilding things no matter what I try, I've made some more changes to improve the Windows CI:
- The SDL cache action is now upgraded from `cache@v2` to `cache@v3` (removing a Node.js 12 deprecation warning)
- It now caches the correct SDL folder (it was caching 30 bytes before, I don't know what those 30 bytes were)
- The "Download SDL" step is now fully skipped (with the cache hit return value) instead of using `Test-Path` to check for the folder
- The build folder is now cached, to avoid the initial `cmake -G -A -D -D ..` which often takes really long. It …
=> Attempt to make the Windows CI again a bit faster

desktop_version/lang/ca/meta.xml, desktop_version/lang/de/meta.xml, desktop_version/lang/en/meta.xml, desktop_version/lang/eo/meta.xml, desktop_version/lang/es/meta.xml, desktop_version/lang/fr/meta.xml, desktop_version/lang/it/meta.xml, desktop_version/lang/nl/meta.xml, desktop_version/lang/pt_BR/meta.xml, desktop_version/lang/pt_PT/meta.xml, desktop_version/lang/ru/meta.xml, desktop_version/lang/tr/meta.xml, desktop_version/src/Localization.h, desktop_version/src/LocalizationMaint.cpp, desktop_version/src/LocalizationStorage.cpp, desktop_version/src/Render.cpp
The language screen has a "Press Space, Z, or V to select" hint, which I forgot to update for supporting button glyphs in #943, so this commit does.
```xml
<action_hint>Press Space, Z, or V to select</action_hint>
<gamepad_hint>Press {button} to select</gamepad_hint>
```
=> Add button glyphs support to selection hint on language screen

desktop_version/src/ButtonGlyphs.cpp, desktop_version/src/Game.cpp, desktop_version/src/Input.cpp, desktop_version/src/Render.cpp
I thought 2.2 already had separate map and interact gamepad bindings, and they simply got neglected and broken with 2.3's split Enter/E key option. But actually, the new split Enter/E option also applied to gamepad buttons, and a separate interact binding was added, without really indicating anything if Enter and E are not split. And I guess using the same button for map and interact by default also makes sense for simplicity...
This commit makes sure the button glyph displayed in-game is at least the correct button. The gamepad bindings menu is also slightly modified to darken the interact option - the button glyphs code now automatically causes them to show equal buttons anyway, so it wasn't too big of a change to also darken the line and disable the binding option. To me this says: …
=> Show correct button glyph for interact if Enter/E are not split

desktop_version/src/Graphics.cpp, desktop_version/src/Graphics.h
Misa asked me if this should only work for non-transparent textboxes, and it shouldn't - that was kind of an oversight.
To make it work for transparent textboxes as well, I made a little restructuring to avoid duplicating the code - fill_buttons() is now called textbox_line(), and it replaces the direct accessing of the textbox lines in the printing loops. The code that checks the width of the textbox does not need to be copied, since the text box is naturally not drawn for transparent text boxes.
=> Make textbuttons() work for transparent text boxes

desktop_version/src/Ent.cpp, desktop_version/src/Entity.cpp, desktop_version/src/Game.cpp, desktop_version/src/Graphics.cpp, desktop_version/src/Graphics.h, desktop_version/src/Render.cpp
For some reason, the accessibility option that was meant to disable flashes doesn't disable ALL flashes, only screen flashes and screen shaking. This commit disables a lot more, most importantly randomness in colors, the player flashing on death/respawn, and teleporters flashing.
=> Disable more flashing elements if a11y is on

desktop_version/src/Input.cpp
Ever since 2.3, if you bind a controller button to the "menu" action (i.e. back/escape) you won't be able to change that button to any other action, because pressing it anywhere in the binding menu will exit to the previous menu, without applying the binding.
I know action sets will overhaul everything, but 2.4 may (probably "should") come out before we have action sets. This part is very broken, and the fix is very easy: just move the bind-assigning code to above the menu-return-on-esc code, and add a return.
=> Fix rebinding "menu" (esc) bindings to different actions

desktop_version/src/Script.cpp
This command was changed from setactivityposition(x,y) to setactivityposition(y) in acca4747f73f066e002a74db5dd2edaacc8ea8d2, but there's a small problem here:
```diff
else if (words[0] == "setactivityposition")
{
-                obj.customactivitypositionx = ss_toi(words[1]);
obj.customactivitypositiony = ss_toi(words[2]);
}
```
This meant that the function still took two arguments, the first of which was unused and the second of which was the Y position of the activity zone. This is now fixed.
=> Fix setactivityposition still taking two arguments

desktop_version/src/Editor.cpp, desktop_version/src/Editor.h
Autotiling was a mess of functions and if chains and switch statements. This commit makes autotiling better by assigning each direction to one bit in a byte, giving each different combination its own value. This value is then fed into a lookup table to give fine control on which tiles get placed where.
The lab tileset can now use the single tiles which were before unused in the autotiler, and the warp zone's background tool now places the fill used in the main game.
=> Rewrite autotiling completely

desktop_version/src/Graphics.cpp
I broke this, so now I'm fixing it. Also fix style around it.
=> Make gravity lines render when screen effects are off

desktop_version/src/ButtonGlyphs.cpp, desktop_version/src/ButtonGlyphs.h, desktop_version/src/KeyPoll.cpp
The only weird-ish thing here is that we're using the Valve vendor ID to assign the Deck layout, but that technically applies to _all_ virtual gamepads. This will eventually fix itself when we migrate to a system that uses Steam Input directly and we can get the hardware information again.
Fixes #945
=> Controller layout detection

desktop_version/src/Editor.cpp, desktop_version/src/Game.cpp, desktop_version/src/Screen.cpp
This PR fixes an issue where resizing the window can cause textures to not properly recache, rendering invisible.
Fixes #988, fixes #977.
=> Fix texture cache missing in certain situations after resizing the window

desktop_version/src/GraphicsResources.cpp
Looks like I forgot to set `data` to `NULL`, and uh, there's a double free somewhere. Not anymore.
=> Fix UB where image loading fails in certain cases

desktop_version/src/Map.cpp
If `p2` is >= 1, the spawned terminal will be entity 21 instead of 20. If the entered script does not exist, don't bother spawning the activity zone.
=> Terminal edentity tweaks

.github/workflows/ci.yml, desktop_version/CMakeLists.txt, desktop_version/lang/en/strings.xml, desktop_version/src/ButtonGlyphs.cpp, desktop_version/src/CustomLevels.cpp, desktop_version/src/CustomLevels.h, desktop_version/src/Editor.cpp, desktop_version/src/Editor.h, desktop_version/src/Entity.cpp, desktop_version/src/Font.cpp, desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/Graphics.cpp, desktop_version/src/Graphics.h, desktop_version/src/Input.cpp, desktop_version/src/LocalizationStorage.cpp, desktop_version/src/Map.cpp, desktop_version/src/Render.cpp, desktop_version/src/RenderFixed.cpp, desktop_version/src/Script.cpp, desktop_version/src/main.cpp
This PR removes the `NO_EDITOR` and `NO_CUSTOM_LEVELS` defines, which cleans up the code a lot, and they weren't really needed anyways.
This commit also disables the editor on the Steam Deck, ~~and adds a program argument to re-enable the editor, `-enable-editor`.~~ This has been removed in favor of detecting if a keyboard is available when you enter the menu.
When the editor is disabled, this is the screen which gets shown:
Closes #992.
=> Remove NO_EDITOR/NO_CUSTOM_LEVELS, disable editor on Steam Deck

desktop_version/src/Render.cpp
Showing the option on the "play a level" option feels to me as though inexperienced players would think they're not supposed to open the player levels, because the message says editor levels are unsupported, right? But the message is only referring to the level editor, so in my opinion, it's clearer to only show it there.
Existing view:
New view:
https://github.com/TerryCavanagh/VVVVVV/assets/44736680/bf976cb9-1391-4fc0-a3f9-be417fee5e83
=> Change editor unsupported message to only appear when editor is selected

desktop_version/src/Script.cpp
Closes #925.
My fix here is to delay the font change until all fading-out textboxes have disappeared. See it as adding a sort of `untilbars` or `untilfade` for text box fadeout, into setfont.
Before:
https://github.com/TerryCavanagh/VVVVVV/assets/44736680/30ed2d7c-4292-41b5-af86-382ae2df0ec1
After:
https://github.com/TerryCavanagh/VVVVVV/assets/44736680/ca5ca402-899a-49cb-9292-4a2225d4ad9b
This doesn't prevent every possible way to change the font of an existing textbox, but you would need to use internal scripting to still do it (and basically be doing it on purpose) - the problem in simplified scripting when you simply do textbox-setfont-textbox is gone.
Also, #1000! …
=> Fix `setfont()` changing font of fading out text boxes

desktop_version/src/Editor.cpp
For some reason, their horizontal draw position depended on where the gravity line started (from the left).
Now they're always on the side of the screen.
=> Fix gravity line edgeguides

desktop_version/src/Script.cpp
This commit fixes an obscure bug with `destroy(moving)` and `destroy(disappear)` where, when looping through entities, the code doesn't actually check what the entity is before trying to destroy the block underneath it.
To fix this, we just put the block-destroying code *inside* of the check, instead of being outside of it.
I also fixed the code style because it was horrible.
=> Fix bug with `destroy(moving)`/`destroy(disappear)`

README.md
The link to Family Jules in the readme links to a dead / parked site, I just updated it to the homepage link from their twitter so that they are easier to find and maybe get that SEO boost :)
- tho you don't need to do this.
=> Update link to FamilyJules' site

desktop_version/src/Editor.cpp
The line that checked if the current menu is the font menu ended up below the code that returned a menu, so this was an easy fix.
Closes #1017.
=> Fix double return when pressing Esc in editor font menu

desktop_version/lang/pl/strings.xml
`strings.xml` in Polish didn't yet contain the Steam Deck strings, and a few limits changes.
Also, "Font: " was translated as "Czcionka:", missing the space. This is fixed now.
=> Language patch - Sync Polish strings.xml, fix small space issue

desktop_version/lang/ca/strings.xml, desktop_version/lang/cy/strings.xml, desktop_version/lang/de/strings.xml, desktop_version/lang/en/strings.xml, desktop_version/lang/eo/strings.xml, desktop_version/lang/es/strings.xml, desktop_version/lang/fr/strings.xml, desktop_version/lang/ga/strings.xml, desktop_version/lang/it/strings.xml, desktop_version/lang/nl/strings.xml, desktop_version/lang/pt_BR/strings.xml, desktop_version/lang/pt_PT/strings.xml, desktop_version/lang/ru/strings.xml, desktop_version/lang/tr/strings.xml, desktop_version/lang/uk/strings.xml, desktop_version/lang/zh/strings.xml, desktop_version/src/BlockV.cpp, desktop_version/src/BlockV.h, desktop_version/src/Entity.cpp, desktop_version/src/FileSystemUtils.cpp, desktop_version/src/FileSystemUtils.h, desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/Input.cpp, desktop_version/src/Localization.cpp, desktop_version/src/Localization.h, desktop_version/src/Logic.cpp, desktop_version/src/Render.cpp, desktop_version/src/main.cpp
This PR fixes several bugs and makes some improvements (described in more detail in the commit messages):
- Fixed getting sent to the title screen if you have no language files and have never had, and open the language screen while in-game
- Added warning messages for missing fonts/lang folders in the bottom left of the main menu
- Fixed activity zone prompt language not getting updated when switching languages while in-game
- Prevent changing language if a script is running (to prevent the hard-to-fix language and font mixups in dialogues)
=> Fix some bugs related to switching languages

desktop_version/lang/ja/strings.xml
Got the translation for "Can not change the language while a textbox is displayed in-game."
=> Language patch - Add missing string in Japanese

desktop_version/src/Render.cpp
Since VVVVVV 2.3, time trial best times are stored not just with the number of seconds, but also the number of frames. However, there was no room to display it with the old design of the time trials screen. Now there is, so it can easily be displayed now with a small change!
Unset frames are stored as -1, which fits perfectly into the frames argument of help.format_time(), because in that case the amount of centiseconds is not shown.
It should be noted that opening VVVVVV 2.2 will instantly wipe your frames records, as described by #1030. But many people will likely never open 2.2 anymore.
=> Show centiseconds for best time trial times (if available)

desktop_version/src/Vlogging.c
Right now, Windows assumes all our console output is code page ????. That means our UTF-8 output appears mangled. (I ran into this while testing IME text input by outputting strings to the console)
For a moment I was scared we'd need to do UTF-16 conversions and call Windows-specific print functions like WriteConsoleW() in our vlog functions, but fortunately SetConsoleOutputCP(CP_UTF8) works just fine.
Example of `vlog_warn(loc::gettext("return"))` in German (just to make sure the encoding of the source file is not a factor) before this change:
After:
=> Allow UTF-8 console output on Windows (for -console)

desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/Input.cpp, desktop_version/src/Map.cpp, desktop_version/src/Map.h, desktop_version/src/Render.cpp, desktop_version/src/Script.cpp
`<summary>` in the save files is a string like "Space Station, 10:30:59" which is displayed in the SAVE tab in the map menu. This poses a problem if a save is made in one language and then that save is viewed in another language, since the new font may not display the old language properly.
This PR overhauls the entire save summary system in order to fix that bug, and fixes some quirks and improves the system in the process. The `<summary>` tag is now no longer read from, only still written to for older versions of the game.
That is only a summary of the changes (seriously), the commit messages go into much more detail.
=> Translate summary at display time instead of at time of saving, and improve summary system

desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/Graphics.cpp, desktop_version/src/Graphics.h, desktop_version/src/Script.cpp, desktop_version/src/Script.h, desktop_version/src/Textbox.cpp, desktop_version/src/Textbox.h
This commit adds a system for displaying sprites in textboxes, which replaces the hardcoded system in the main game.
This also adds a couple new commands to go along with it.
- `textsprite(x,y,sprite,color)` adds sprites to the textbox you're currently constructing. The coordinates are relative to the textbox.
- `textimage(levelcomplete/gamecomplete)` displays `levelcomplete.png` or `gamecomplete.png` and their flip mode variants (or text due to translation)
=> Sprite textboxes

desktop_version/src/Game.cpp, desktop_version/src/Game.h
As described in #1016, there used to be a bug that inflated `levelstats.vvv` in 2.3, which was fixed in 2.4, but there was no way for inflated files to get smaller yet.
This commit changes the storage of levelstats from a std::vector of structs to a std::map, so that uniqueness is guaranteed and thus the stats can be optimized automatically. And it also simplifies *and* optimizes the code that handles the levelstats - no more big loops that iterated over every element to find the matching level. (Farewell to the "life optimisation and all that" comment, too)
I tested this with both my own levelstats.vvv, as well as some inflated ones (including Balneor's 93 MB one) and saw this code correctly reduce the filesize and speed up the levels list.
Fixes #1016.
By submitting this pull request, I …
=> Change levelstats data type from vector to map (to fix inflated files)

desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/Script.cpp
The hardest room used to be stored as a room name in whatever language it was in when you last died enough times to break the record (before localization, that was always English). Even after localization became a thing we could get away with this since we only had a single font, but now we might have actual question marks appearing when the new font doesn't support characters from the old language.
Therefore, this commit adds more info about the hardest room to save files - everything that is needed to know in order to do the translation at display time. These are hardestroom_x and hardestroom_y for the room coordinates, as well as hardestroom_specialname to mark special names, in addition to changing the stored room name back to English. I've also added hardestroom_finalstretch in case …
=> Translate hardest room at display time instead of at time of death

desktop_version/CMakeLists.txt, desktop_version/lang/en/strings.xml, desktop_version/src/Game.cpp, desktop_version/src/Input.cpp, desktop_version/src/LevelDebugger.cpp, desktop_version/src/LevelDebugger.h, desktop_version/src/Logic.cpp, desktop_version/src/Render.cpp, desktop_version/src/main.cpp
This PR adds a level debugger. By pressing `Y` in playtesting mode (or in play mode if you pass in the flag `-leveldebugger`), the debug overlay appears which tells you information about the current game's state, and hovering over entities shows their information as well.
Holding `U` while in this state will show the flags and their current values.
=> Level debugger

desktop_version/lang/ja/cutscenes.xml
These are to make the textboxes not overlap with the header, by making them wrap to less lines.
Screenshots:
=> Apply changes to two terminal textboxes in Japanese

desktop_version/lang/fr/strings.xml
This string is used both in time trials (alongside "MORTS :" and "BLINGS :") as well as outside time trials if you enable the in-game timer. In English, this looks like "TIME:1:23.45". Since French adds a space before the colon, it will look like "TEMPS :1:23.45" instead. Therefore, I've added a space after the colon as well.
=> French: Add spaces at the end of "TEMPS :" string (and MORTS and BLINGS)

desktop_version/src/Music.cpp
Fixes #1057.
Based on Ethan's hunch, I simply removed the format comparison that decides whether to halt and restart, or reuse the voice. Voices are now always restarted when playing a new track.
This also simplifies the code somewhat: `MusicTrack::musicVoiceFormat` was now no longer used, and an `if (!IsHalted())` was no longer necessary because `Halt()` already does that. So those are now removed as well.
=> Fix remaining audio speedup/slowdown bug

desktop_version/src/Graphics.cpp
Textsprites and textimages no longer wait for the opacity value in order to display within transparent textboxes, so they now display at the same time as the text itself. Text sprites in normal opaque textboxes are not affected by this change.
This video shows the change in action (before the cut is current behaviour, after is with the change):
https://github.com/TerryCavanagh/VVVVVV/assets/44736084/a6e3f953-766c-4506-ae67-6fd2344c6e09
With this change, opportunities to use textsprites for e.g. animation and on-screen graphics display are made more convenient and easier to persue.
=> Change timing of textsprites in transparent textboxes

desktop_version/lang/it/strings.xml, desktop_version/lang/ja/strings.xml
Japanese: Apply change from 凄い to すごい
Italian: Fix in-game timer ON/OFF being reversed (see https://github.com/TerryCavanagh/VVVVVV/issues/1060#issuecomment-1830923642)
=> Minor language fixes for Japanese and Italian

desktop_version/fonts/font.fontmeta
Some characters were duplicated in fontmeta, causing e.g. the wrong icons to be displayed on the minimap. This fixes it by regenerating the font from git.txt.
=> Fixed duplicated/shifted characters in font

desktop_version/lang/de/strings.xml
It's a menu option, so it should be uncapitalized, like all other menu options.
=> Correct one letter's capitalization in German

desktop_version/lang/es/strings.xml
Fixes this (found by toni57 on Discord):
=> Fix ACCIÓN having changed to ACTION in Spanish

desktop_version/src/Game.cpp
Textboxes created with `graphics.createtextboxflipme()` use `PR_FONT_LEVEL` by default, but can be overridden with `graphics.textboxprintflags()` to, for example, set `PR_FONT_INTERFACE`. This happens for the textboxes on the Game Complete screen, which use interface text. The textboxes are centered by setting the X position to -1 though, which means they're solely centered based on the width of the first line, in the level font (because the font hasn't been changed to the interface font yet).
Normally, this isn't a problem, because in the main game (where the Game Complete screen usually appears), the level font is always equal to the interface font. However, in custom levels you can still get it (by calling gamestate 3500) and in that case some of the text may be misaligned. This change …
=> Fix centering of game complete texts if level font != interface font

desktop_version/src/Editor.cpp, desktop_version/src/Editor.h
This makes outside background tiles ignore solid walls. This was the behavior in the old autotiling system, so this brings that behavior back.
Also, it seems like I made a mistake while originally writing the "make autotiling base" code. This commit fixes the warp background turning into solid tiles when you switch to a different tileset.
=> A few more autotiling fixes

desktop_version/src/Game.cpp
Or well, lock yourself out if you don't have (easy) access to a keyboard, like on Steam Deck.
In 2.3, this problem used to be much worse, since you could bind any button to "menu" - which is actually also "return" in menus - and that button could then no longer be bound to any other action, because exiting the bindings menu had priority over assigning a different binding. The result would be that people could have all their buttons bound to "escape" with no way of undoing it or using their controllers at all other than manually going into their config file to change it.
In 2.4, the most important bugs in the bindings menu are fixed, but it's still possible to remove all your bindings from the "flip" (confirm) action, meaning you can't navigate the menus anymore with a controller to fix …
=> Fix binding menu allowing you to lock yourself out of the game

desktop_version/lang/README-programmers.txt, desktop_version/lang/README-translators.txt, desktop_version/src/LocalizationMaint.cpp, desktop_version/src/LocalizationStorage.cpp
Two translators thus far have tried to populate initial language files by creating a blank folder and then using the in-game sync option. For example, see #1078.
That is not how the sync option was intended to be used, but it's really close to getting everything, so I decided to just complete the support by making sure `numbers.xml` is copied from English, and making sure `meta.xml` is filled in with English text and not text from an arbitrary language. Also, minor detail on plural form 1 being set to 1 by default if reset, so `strings_plural.xml` is fully consistent too.
The top of lang/README-programmers.txt now also says that you need the translators readme to translate the game into a new language.
section of the credits for all of …
=> Make language sync support creating blank language files; clarify lang/README-programmers.txt

desktop_version/lang/ca/strings.xml, desktop_version/lang/cy/strings.xml, desktop_version/lang/de/strings.xml, desktop_version/lang/en/strings.xml, desktop_version/lang/eo/strings.xml, desktop_version/lang/es/strings.xml, desktop_version/lang/fr/strings.xml, desktop_version/lang/ga/strings.xml, desktop_version/lang/it/strings.xml, desktop_version/lang/ja/strings.xml, desktop_version/lang/ko/strings.xml, desktop_version/lang/nl/strings.xml, desktop_version/lang/pl/strings.xml, desktop_version/lang/pt_BR/strings.xml, desktop_version/lang/pt_PT/strings.xml, desktop_version/lang/ru/strings.xml, desktop_version/lang/szl/strings.xml, desktop_version/lang/tr/strings.xml, desktop_version/lang/uk/strings.xml, desktop_version/lang/zh/strings.xml, desktop_version/lang/zh_TW/strings.xml, desktop_version/src/Input.cpp, desktop_version/src/Render.cpp
- Fixed translator credits headers being forced to 8x8 font:
- Fixed current_credits_list_index not always being reset - explained further in the commit message
- Try to prevent some lines in rolling credits going offscreen - fixed version for Italian for example:
- Added limits (like `max="40"`) to the translator credits strings
- Minor indentation style fix in Render.cpp
=> Some fixes to the translator credits

desktop_version/src/Editor.cpp
I just discovered this: whereas 2.3 and older versions make gravity and warp lines - when placed in the editor - stick out one tile offscreen, the latest version stops the lines at the room border.
In this situation, all the gravity lines should be 4 tiles long:
This change restores the old behavior, and it's a simple fix: the refactored code was written to let tiles outside the room block gravity/warp lines. Instead of all offscreen tiles blocking lines, now there's a 1-tile padding around the room that will let them through.
=> Restore gravity/warp lines sticking out a tile offscreen

desktop_version/lang/de/strings.xml, desktop_version/lang/tr/strings.xml
When ACTION is filled in, the closing ] will go offscreen in Turkish.
To fix it, I simply removed the square brackets.
Edit: see below for German
=> Fix minor [Press ACTION to save your game] overflow in Turkish and German

desktop_version/lang/eo/roomnames.xml
This replaces the translated roomname for "It's Not Easy Being Green" (previously "La verdita generacio") with "Verda reaperis!", a different [cultural reference](https://en.wikipedia.org/wiki/Gerda_malaperis!) with a much better pun.
=> Change Warp Zone roomname in Esperanto translation

desktop_version/src/main.cpp
For some reason, the default behavior of SDL and/or Windows(?) (I only tested this on Windows) seems to result in the fact that if any SDL app doesn't account for it, there is no way for Japanese and Chinese speakers to know what they're typing in.
How IMEs are supposed to work is that you can type words as sort of WIP versions, and then select out of a list of candidates what the final result should be. The app may display the WIP text and tell the IME where the text field is so that the IME's menu can be displayed around it. But if the app doesn't say where the text field is, then the candidate list can also be displayed at the corner of the screen, which is done in Minecraft.
By default, however, SDL apps don't get a candidate list at all, which means you're basically flying blind as …
=> Enable SDL_HINT_IME_SHOW_UI to make typing CJK not guesswork

desktop_version/src/CWrappers.cpp, desktop_version/src/CWrappers.h, desktop_version/src/Localization.cpp, desktop_version/src/Localization.h, desktop_version/src/LocalizationStorage.cpp, desktop_version/src/LocalizationStorage.h, desktop_version/src/UtilityClass.cpp, desktop_version/src/UtilityClass.h, desktop_version/src/VFormat.c
Some languages have different spellings of wordy numbers based on the gender of the things they're counting (uno crewmate versus una trinket) or what a number's role is in the sentence (e.g. twenta out of twentu). We've always had the idea we couldn't support such complex differences though, because the game can't be adapted to know what gender each object will have and what word classes might exist in other languages, so translators would in those cases just have to forgo the wordy numbers and just let the game use "20 out of 20".
A solution we came up semi-recently though (after all translations were finished except for Arabic), was to allow the translator to define however many classes of wordy numbers they need, and fill them all out. This would not need the game to be *adapted* for …
=> Add a system for selecting between wordy/wordy2

.github/workflows/android.yml, .github/workflows/ci.yml
This makes it so that the main CI workflow will only trigger if a change is made to a code file in `desktop_version/` (as the CI is only for `desktop_version/`), or if the CI file itself is changed.
The CI workflow for Android will only trigger if Android-specific code _could have_ changed. This includes all code that is definitely Android-specific (e.g. Java files), but also C/C++ files that have `__ANDROID__` ifdefs.
Unfortunately, it's [not possible to reuse the same list of paths across two different event trigger types](https://github.com/orgs/community/discussions/37645). So we have to copy-paste here.
=> Only trigger CI workflows for code or CI changes

desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/Render.cpp, desktop_version/src/RenderFixed.cpp, desktop_version/src/Script.cpp
If you load in to gameplay with invincibility mode, glitchrunner mode, Flip Mode, or slowdown enabled, then there will be text displayed on screen for a few seconds that says so.
This is to serve as a useful reminder. A common pitfall with using  invincibility is forgetting to turn it off when you don't want it anymore. What usually happens is that players forget that they have it on until they encounter a hazard. Now, they can realize it as soon as they load in.
~~The only reason this is a draft pull request is because there is an issue with the Japanese translation where some menu option strings I would like to reuse, e.g. "Glitchrunner mode is {version}", can't be reused on account of them being genericized in Japanese (i.e. they say "Mode: OFF" and that gets reused across multiple …
=> Indicate modes when loading in to gameplay

desktop_version/lang/README-translators.txt
These things hadn't been added to the documentation yet:
- `<font>` in a language's meta.xml
- `<gamepad_hint>`
- `<rtl>`
- `wordy2`/`translation2`
=> Update README-translators.txt for some recent additions

desktop_version/src/Editor.cpp, desktop_version/src/Graphics.cpp, desktop_version/src/Graphics.h, desktop_version/src/Map.cpp, desktop_version/src/Map.h, desktop_version/src/Render.cpp
This is mostly so people making levels in an RTL language have a more pleasant and logical experience. If roomtext is placed in a level set to RTL, it will get p1=1, which makes that roomtext right-aligned. Because, imagine for English you click to place roomtext, and the text runs left of where you clicked, which wouldn't be logical.
Since it's an entity-bound property, switching RTL on and off either in the editor or via a script does not affect existing entities.
=> Add support for right-aligned roomtext

desktop_version/CMakeLists.txt, desktop_version/src/CWrappers.cpp, desktop_version/src/CWrappers.h, desktop_version/src/FileSystemUtils.cpp, desktop_version/src/FileSystemUtils.h, desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/Graphics.cpp, desktop_version/src/Graphics.h, desktop_version/src/GraphicsResources.cpp, desktop_version/src/GraphicsUtil.cpp, desktop_version/src/GraphicsUtil.h, desktop_version/src/KeyPoll.cpp, desktop_version/src/SteamNetwork.c
This adds a screenshot keybind (F6) and hooks Steam's screenshot function to send our own screenshots. This is so that people can easily grab screenshots of pixel perfect internal resolution (320x240) without needing to downscale it themselves.
Issues:
* ~~We need to change the existing F12 keybind, which is currently bound to reloading language files in translator mode. This conflicts with Steam's default screenshot keybind. In this draft, I've just disabled it instead.~~
* ~~Still need to add timestamps to filenames for F6 screenshots.~~
* ~~Flip Mode needs to be manually corrected but it doesn't work as of now.~~
=> Add screenshot functions

desktop_version/lang/nl/numbers.xml, desktop_version/lang/nl/strings.xml, desktop_version/lang/nl/strings_plural.xml
The number "one" in Dutch is "één" (silly, I know :P). Capital letters can have accents, but there's an exception where for this specific word, the first accent is much more often left off than not. So I'm now using wordy2 as the uppercase variants of all the numbers, and using that instead of the |upper flag.
=> Use wordy2 in Dutch to capitalize één as Eén

desktop_version/src/Editor.cpp
This reverts commit a806b072bd8635e40c0a30bd0ceab4f75218a06f.
It causes an instant segfault if there's no entities or if you're not editing terminals/script boxes or something, whatever it's not crucial as a last-minute fix.
=> Revert "Disable typing pipes in script names"

desktop_version/src/Graphics.cpp
While a7b22919ae379c96001c8dcdb9f73c36d298f967 makes text sprites modulate their RGB values, text images continued using alpha, despite alpha blending not even being enabled, so the initial commit didn't work right either.
=> Fix text images not fading

desktop_version/src/Editor.cpp
13d6b2d64c1d3a78c8bf049161f1446820765e99 adds a check where you can't type a pipe in script/terminal input fields anymore. It does this completely incorrectly, checking if certain variables are set instead of checking what's actually trying to be done.
This PR fixes that, simplifying the check a lot in the process.
=> Fix typing pipes in save/load prompts in editor

desktop_version/src/Graphics.cpp
This fixes warnings about narrowing and missing a component of the struct.
=> Fix warnings when calculating image color

desktop_version/lang/ru/cutscenes.xml, desktop_version/lang/ru/strings.xml
This PR fixes an issue with the Russian translation, where the "Map Music" menu in the Level Editor showed the string for Pushing Onwards as "1: Pushing Onwards (Потенциал для всего)" ("1: Pushing Onwards (Potential for Anything)"), and also adds Russian translations for song names when previewing their names in the "NEXT UNLOCK" dialogue with the Jukebox.
=> Minor Russian translation fixes

desktop_version/lang/uk/strings.xml
The Ukrainian strings.xml turns out to have two en-dashes which are not in the font. This commit replaces them with standard dashes.
=> Replace U+2013 (–) by standard dash in Ukrainian

desktop_version/src/Font.cpp
This fixes a segmentation fault caused by an out-of-bounds indexing caused by an attempt to unwordwrap a string that starts with two newlines.
The problem here is that in the branch of the function `string_unwordwrap()` where `consecutive_newlines == 1`, the function does not check that the string `result` isn't empty before attempting to index `result.size()-1`. If `result` is empty, then `result.size()` is 0, and `result.size()-1` becomes -1, and indexing a string at position -1 is always undefined behavior.
Funnily enough, a similar indexing happens just a few lines down, but this time, there is a check to make sure that the string isn't empty first. I'm unsure of how @Daaaav forgot that check a few lines earlier.
This situation can happen in practice, with custom level localizations. …
=> Fix segfault from attempting to unwordwrap a string that starts with two newlines

desktop_version/README.md
We recently had a user come in the VVVVVV Discord not knowing that, after running CMake, you then need to compile the game in a separate step. This clarifies the instructions.
=> README: Add step for compiling

desktop_version/src/GraphicsResources.cpp
LodePNG always loads PNG in big-endian RGBA format. For this reason, when loading PNG files VVVVVV was specifying the format as ABGR and the conversion would then be performed by SDL. However, then running on big-endian machines, this conversion should not be performed at all, and the surface format should then be set to RGBA.
=> Fix loading of PNG resources on big-endian machines

desktop_version/lang/cy/cutscenes.xml, desktop_version/lang/cy/strings.xml, desktop_version/lang/eo/cutscenes.xml, desktop_version/lang/ga/strings.xml, desktop_version/lang/nl/strings.xml
- Esperanto: Fixed Violet cutscene saying `[button?]` instead of the map button
- Welsh: Added newlines to "Congratulations!" and jukebox dialog boxes
- Irish: Added newlines to "Congratulations!" dialog boxes
- Dutch: Changed capitalization of no death mode to be consistent with the capitalization of the number "one"
=> Minor language fixes to Esperanto, Welsh, Irish and Dutch

desktop_version/src/Font.cpp, desktop_version/src/Font.h, desktop_version/src/Script.cpp
There used to be a problem with the `setfont()` and `setrtl()` script commands. Namely, if you used them in between text boxes naïvely, without any careful thought, then the fading out text box would suddenly gain the font of the new one. A kludge solution to this was implemented by simply blocking the script until the existing text box faded out before switching the font or RTL, and shipped for 2.4.0.
However, a better solution is to simply bake the font flags in to the text box, so that way, if the level font switches, then the text box keeps its font.
This is only for custom levels, because in the main game, the font in a text box needs to be able to change depending on language. But it seems like custom level translations weren't much on the roadmap, and so even the existing hack …
=> Properly fix using `setfont()`/`setrtl()` script commands in between text boxes

desktop_version/src/Game.cpp, desktop_version/src/Graphics.cpp, desktop_version/src/Graphics.h, desktop_version/src/Script.cpp, desktop_version/src/Textbox.cpp, desktop_version/src/Textbox.h
This change adds a one pixel gap between each line in textboxes, though only in the main game for now. It addresses this issue: https://github.com/TerryCavanagh/VVVVVV/issues/1051
A few screenshots of how it looks:
So! There was a lot of discussion about whether or not this change was a good idea on the discord, which is very fair - it does change the look of the game pretty noticeably, and it breaks the C64 8x8 grid. I found myself going back and forth on it a little bit - so I figured the best thing to do was just to try it, and make it a bit less hypothetical. I'll distribute a compiled version on the discord for easy testing.
Now that I've done it, I really like it! I actually find it quite jarring to go back to the zero gap textboxes in custom levels:
What do you think?
By submitting …
=> Add a one pixel gap between each line in textboxes

desktop_version/lang/cy/strings.xml, desktop_version/lang/es_419/cutscenes.xml, desktop_version/lang/es_419/meta.xml, desktop_version/lang/es_419/strings.xml, desktop_version/lang/es_AR/cutscenes.xml, desktop_version/lang/es_AR/meta.xml, desktop_version/lang/es_AR/strings.xml, desktop_version/lang/nl/strings.xml
- Sync Spanish LATAM and Spanish ARG language files
They were missing the latest strings and also still had strings that had been deleted.
(Whoever commits the upcoming delivery should also sync that version)
- Translate the current 4 proxy strings into Dutch
These are the 3 variants of Spanish and "Editing and LQA".
- Add missing spaces to script editor title in Welsh
=> Minor language file maintenance: sync Spanish LATAM&ARG, translate proxy strings into Dutch, add missing spaces in Welsh

desktop_version/src/Graphics.cpp, desktop_version/src/Graphics.h, desktop_version/src/KeyPoll.cpp, desktop_version/src/Screen.cpp, desktop_version/src/Screen.h
For future PRs, it'll be very nice to have full control over how VVVVVV gets drawn to the window. This means we can use the entire window size for things like touch input, drawing borders, or anything we want.
=> Implement scaling modes manually

desktop_version/lang/ar/strings_plural.xml, desktop_version/lang/es_419/cutscenes.xml, desktop_version/lang/es_419/meta.xml, desktop_version/lang/es_AR/cutscenes.xml
- Fix placeholders in Arabic strings_plural
For some reason all of us overlooked that all of them were {n_crew}, even those which required a different placeholder key... https://steamcommunity.com/sharedfiles/filedetails/?id=3154670529
- Change LATAM Spanish meta.xml Oprime to Pulsa
All of them were changed except for the one in meta.xml. I think it's safe to assume this is correct, because everywhere else, the same "Oprime {button} para" pattern always became "Pulsa {button} para" too.
- Align dimensional stability generator in Spanish LATAM and Spanish AR
=> Some small fixes to Arabic, Spanish LATAM and Spanish AR

desktop_version/lang/eo/strings.xml
New strings have been added into the Esperanto translation. This includes the Spanish variant names, "Editing and LQA", the "mode enabled" bug text, and the debug mode freeze prompts.
=> Translated missing strings into Esperanto

desktop_version/src/Input.cpp, desktop_version/src/Localization.cpp, desktop_version/src/Localization.h, desktop_version/src/main.cpp
Now that two new variants of Spanish have been added, it would be a shame that many players from Latin-America/Argentina may stay on Castilian or English because they don't realize the new versions were added for them. So now, if you've set your language in 2.4.0, the language screen will show up once more in 2.4.1. This is done by simply incrementing the lang_set flag to 2 - so that if it's 0 or 1, your language setting is considered to be possibly outdated.
This shouldn't inconvenience players who don't need to select a new language - their existing language will still be pre-selected, so they can just hit ACTION once.
Terry confirms he did the same thing with Dicey Dungeons and says it's a good idea (and that nobody minds).
section of …
=> Make language screen show up once more

desktop_version/src/Script.cpp
This is just a small visual fix to an inconsistency with textbox colors in simplified scripting. The `reply` command is meant to be used for the player, and always correctly positions it above the player, while the `say` command may be used to generate a cyan textbox that's positioned above a cyan non-player crewmate. However, the color for both textboxes is always `cyan`, so the `reply` command doesn't use the (normally identical) `player` color even though all its other behavior (squeak, position) does. Now that customized textbox colors were added in 2.4 (#910), it's a shame that this distinction isn't made between `cyan` and `player`, so this change addresses that (before we're stuck with levels that change `cyan` but not `player`).
As discussed with @InfoTeddy, this should be fine to …
=> Change `reply` scripting command to `player` color

desktop_version/src/Render.cpp
For localization, the "Thanks for playing!" text was split into two lines, when it was originally one line. Unfortunately, it was not updated to account for Flip Mode, so in Flip Mode, it looked like "playing! Thanks for".
This has been fixed.
=> Fix "Thanks for playing!" reversed in Flip Mode

desktop_version/src/Input.cpp
This fixes a bug report from Elomavi that you could still softlock from warping to ship and incrementing the gamestate by pressing ACTION, which is diverging behavior from how it was in 2.3. Warping to ship and incrementing by pressing ACTION is useful behavior for a couple niche speedrun categories.
I had already fixed this earlier by ignoring state locking if glitchrunner 2.2 or 2.0 was enabled, but softlocks could still happen because having glitchrunner mode off still enabled you to increment the gamestate when otherwise unintended. Softlocks shouldn't happen.
But without removing state locking entirely, I've chosen a middle ground where it will only be disabled if you press ACTION. That signifies intent that you still want to perform state incrementing glitches even with glitchrunner …
=> Disable state locking if incrementing state with ACTION

desktop_version/src/Editor.cpp
This fixes a regression from 2.4 where the foreground wouldn't update after using the G keybind to go to a room, requiring the user to touch a tile to update the rendering.
=> Fix regression: Foreground redraw after G keybind

desktop_version/src/Vlogging.c, desktop_version/src/main.cpp
The intention of the `-console` argument was to enable seeing console output on Windows without having to use workarounds. However, this didn't actually work for arguments like `-addresses` and `-version`, because the program would exit first before it could get the chance to create the console.
The other issue is that the console closes too quickly before output can be read by the user. So to fix that, we must hold it open and let the user close it when they want to.
=> Fix informational command-line arguments not working with `-console`

desktop_version/src/CustomLevels.cpp
This fixes a minor issue where if you had a zip in the levels list, but then removed it, it would still show up in the levels list after reloading it (if you also had a `.vvvvvv` file named the same as in the zip) even though it shouldn't.
Thankfully, this didn't lead to a memory leak or duplicate zip mounts or anything like that, because PhysFS ignores mounting a zip if it's already mounted.
This also didn't result in a level entry from a zip persisting after removal after reloading the levels list, because the entry would be gone due to the `.vvvvvv` file not being found.
=> Unload zips before loading zips

desktop_version/src/Entity.cpp
Commit 4f881b9e26131b2cd259337bf81c89104b349c46 fixed a duplication bug where enemy movement types 10 and 12 would keep duplicating itself on every frame if it was spawned outside of the rooms they were supposed to be used in the main game. The downside was that this was an overzealous fix and unintentionally broke some cases that were working before.
As brought to my attention by Ally, you can no longer place an edentity with a `p1` of 10 or 12 (translating to movement type 10 or 12) in the proper rooms and have it spawn perfectly working entities (that don't clone on themselves every frame), whereas you could in 2.2. This is considered a regression from 2.3.
So the problem here is that the reason the two emitter entities were so dangerous outside their respective rooms is because the …
=> Fix regression: Overzealous emitter dupe fix

desktop_version/src/Entity.cpp
Commit 53d725f78a3550b750d652a62ffe9d8b51dd0e18, intended to fix an overzealous commit, was itself overzealous. This is because it applied to all entities when it should only apply to entity-emitting entities. To fix this, `entityclonefix` needs to no-op if the entity is not an entity emitter.
Fixes #1176.
=> Fix regression: Entities not moving

desktop_version/lang/README-programmers.txt
`lang/README-programmers.txt` accidentally lists the name of the `font::print` function twice, when the second one should've been `font::print_wrap` instead. Oops.
[skip ci]
=> Fix font::print_wrap() name in lang/README-programmers.txt

desktop_version/CMakeLists.txt
`/EHsc` does not actually disable exceptions on MSVC, it only makes the compiler assume that `extern "C"` functions never throw C++ exceptions.
We had a discussion on Discord about actually disabling exceptions, and from research, that requires defining `_HAS_EXCEPTIONS=0`, but it's unsupported and undocumented so we deemed the benefits not worth it. Thus, we will stay with `/EHsc`. But the comment still has to be updated.
[skip ci]
=> Fix wrong comment on disabling MSVC exceptions

desktop_version/src/FileSystemUtils.cpp
A minor gripe, but one thing I didn't notice with commit b4579d88d3631c36d3c6457e85ca0996c65941ca is that it now results in two dialogs if data.zip is missing: The first being the "`data.zip` is missing" dialog, and the second is the generic "Unable to initialize filesystem" dialog.
So just bail early if `data.zip` can't be found, it's going to take the error path in `main()` and also bail regardless.
=> Fix double error dialog if `data.zip` is missing

desktop_version/CMakeLists.txt
Due to a confluence of weird factors, it turns out that PhysFS is compiling with implicit function definitions due to function definitions that get hidden with `-std=c99`, but not with `-std=gnu99` (or the default GCC value of `-std=gnu17`).
Also, due to a recent GCC update (GCC 14), implicit function declarations are actually prohibited with `-std=c99` as the C99 standard proscribes.
This meant that people started getting build errors in PhysFS code on default settings, which wasn't ideal.
To fix this, we will make our `-std=` flags apply only to VVVVVV source files. In CMake 2.8.12, this can be done with `set_source_files_properties`. Additionally the flags to disable exceptions and RTTI are scoped down too.
Thanks to leo60228 for helping debug and solve this issue.
Fixes #1167.
By …
=> CMake: Scope C99/C++98 flags to VVVVVV only

desktop_version/CMakeLists.txt, desktop_version/version.cmake
Previously, the interim version indicators (commit, date, and branch) would go away on development builds if git didn't exist. And if it did exist but provided blank output for whatever reason, that was almost exactly the same as not having them at all (save for the window title saying "VVVVVV []" which can be easy to overlook). This was bad because it complicates troubleshooting when you potentially have an unofficial or in-development build since those get distributed around or compiled by some people frequently.
Now, there will always be an interim version indicators unless the game is compiled with `-DOFFICIAL_BUILD=ON`. And if the indicators are blank for any reason, they will just be replaced with placeholder defaults so they will still show up.
By submitting this pull request, I …
=> Always have interim version indicators

desktop_version/src/Music.cpp
There seems to be a lot of confusion between user volume and game's master volume. As a result, a bug was introduced when the user volume setting was added in which for a single frame the music of these jingles was set to the VVV_MAX_VOLUME which may be much louder than the user's volume setting. This was especially noticeable for Path Complete, but could be heard in Plenary too (even with its baked-in fade). It might be a good idea to generally clean up the audio code because the different volume variables between user and master are peppered throughout the audio functions instead of being localized and processed in one place. Either way, this PR fixes the bug with the jingles (tracks 0 and 7). 
section of the credits for all of said …
=> Fix played jingles (Path Complete and Plenary) briefly not respecting user volume

desktop_version/src/main.cpp
This fixes a bug where fast-forward wouldn't work in 30-FPS-only mode.
This is because the 30-FPS-only code has a hardcoded check for the number 34, as in 34 milliseconds must pass before the next frame can advance. This is why slowdown still worked, because slowdown means you're waiting longer than 34 ms anyways, but fast-forward tries to wait for only 1 ms, which wouldn't work if the 34 limit was still enforced.
So instead, swap out the 34 with `game.get_timestep()` and this will be fixed.
Fixes #1185.
=> Use variable timestep for `SDL_Delay`

desktop_version/src/Logic.cpp
This fixes a regression from 2.3. Consider the following diagram:
CC
X  CC
<<<<
"C" indicates one tile of a checkpoint entity, "X" indicates a spike tile, and "<" indicates one tile of a conveyor entity that has the default speed (4 pixels per frame) going leftwards.
Now consider if the player were to touch the checkpoint and die. In 2.2, they would be able to escape from the spike by holding right. But in 2.3, they would not be able to, and would die from the spike continuously with no escape.
This happens because in 2.2, the player would spawn a couple pixels off the surface, and this gained them an extra frame of movement to move away from the conveyor. 2.3 places the player directly on the ground, moving them one frame earlier and thus forcing them to their doom.
Now consider the …
=> Fix regression: Escape from conveyor spikes

desktop_version/CMakeLists.txt, desktop_version/src/Graphics.cpp, desktop_version/src/IMERender.cpp, desktop_version/src/IMERender.h, desktop_version/src/KeyPoll.cpp, desktop_version/src/KeyPoll.h, desktop_version/src/main.cpp
As a followup to #1041 and the discussion inside it, this PR now shows the current candidate text (the uncommitted text being edited in the IME) in a box in the bottom left corner. This visualizes the data from `SDL_TEXTEDITING[_EXT]` events and makes it easier to input CJK text.
So at first (before #1041) you couldn't see what you were doing at all, after #1041 you could at least see the candidate list making it much clearer what was going on but you couldn't see the uncommitted text, and now you can also see the uncommitted text.
Not much more to explain about it except for a demo video:
https://github.com/user-attachments/assets/596c3519-c588-4a00-b9a3-04d818e46d0c …
=> Render uncommitted IME text in bottom left corner

desktop_version/src/IMERender.cpp
Just extending the selection background left by one pixel so there's not one pixel of black background to the left of a selection that starts at the beginning of the text, and so some characters being selected show up better (particularly where there's a long vertical bar at the first pixel). We shouldn't be overlapping any part of the previous character, since every character normally has a pixel of spacing on the right.
=> Tweak IME selection background left bound

desktop_version/lang/ar/strings.xml, desktop_version/lang/ca/strings.xml, desktop_version/lang/cy/strings.xml, desktop_version/lang/de/strings.xml, desktop_version/lang/en/strings.xml, desktop_version/lang/eo/strings.xml, desktop_version/lang/es/strings.xml, desktop_version/lang/es_419/strings.xml, desktop_version/lang/es_AR/strings.xml, desktop_version/lang/fr/strings.xml, desktop_version/lang/ga/strings.xml, desktop_version/lang/it/strings.xml, desktop_version/lang/ja/strings.xml, desktop_version/lang/ko/strings.xml, desktop_version/lang/nl/strings.xml, desktop_version/lang/pl/strings.xml, desktop_version/lang/pt_BR/strings.xml, desktop_version/lang/pt_PT/strings.xml, desktop_version/lang/ru/strings.xml, desktop_version/lang/szl/strings.xml, desktop_version/lang/tr/strings.xml, desktop_version/lang/uk/strings.xml, desktop_version/lang/zh/strings.xml, desktop_version/lang/zh_TW/strings.xml, desktop_version/src/CustomLevels.cpp, desktop_version/src/CustomLevels.h, desktop_version/src/Editor.cpp, desktop_version/src/Map.cpp
Currently, you can change platform speed, but not enemy speed, which is always hardcoded to be 4. This commit fixes that, by adding the `enemyv` property, which is an offset to the speed of 4. Since it defaults to 0, older levels are not broken by this change.
=> Add enemy speed as a room property

desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/Logic.cpp, desktop_version/src/Script.cpp
This makes it so that it is possible to obtain the Master of the Universe trophy/achievement, usually unlocked by beating No Death Mode, outside of NDM.
There are several conditions that need to be met:
1. The game needs to be started from a new game and cannot be from loading a save.
2. Accessibility modes (invincibility and slowdown) must never be enabled.
If either condition is violated, then the boolean that keeps track of NDM eligibility will be set to false.
=> Give Master of the Universe trophy in normal mode, meeting certain conditions

desktop_version/src/Game.cpp
Some discussion on the Discord server resulted in this change. It's a quality-of-life improvement where, if the game is in slowdown mode, it will return to 100% speed for the duration of the death animation.
The reasoning is obvious. There is nothing to do during the death animation, so making it take longer during slowdown is just an annoyance to the player, almost a penalty for them using an accessibility option. This is the same reason why slowdown no longer applies in menus, etc.
=> Remove slowdown during death animation

desktop_version/lang/ar/strings.xml, desktop_version/lang/ca/strings.xml, desktop_version/lang/cy/strings.xml, desktop_version/lang/de/strings.xml, desktop_version/lang/en/strings.xml, desktop_version/lang/eo/strings.xml, desktop_version/lang/es/strings.xml, desktop_version/lang/es_419/strings.xml, desktop_version/lang/es_AR/strings.xml, desktop_version/lang/fr/strings.xml, desktop_version/lang/ga/strings.xml, desktop_version/lang/it/strings.xml, desktop_version/lang/ja/strings.xml, desktop_version/lang/ko/strings.xml, desktop_version/lang/nl/strings.xml, desktop_version/lang/pl/strings.xml, desktop_version/lang/pt_BR/strings.xml, desktop_version/lang/pt_PT/strings.xml, desktop_version/lang/ru/strings.xml, desktop_version/lang/szl/strings.xml, desktop_version/lang/tr/strings.xml, desktop_version/lang/uk/strings.xml, desktop_version/lang/zh/strings.xml, desktop_version/lang/zh_TW/strings.xml, desktop_version/src/Entity.cpp, desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/Input.cpp, desktop_version/src/Render.cpp, desktop_version/src/Script.cpp
This is a small PR that adds mobile VVVVVV's behavior of saving on checkpoints. It quicksaves whenever your checkpoint gets set, either by touching a checkpoint or `setcheckpoint()`. On by default on Android, off otherwise. Can be manually overridden through `settings.vvv`.
=> Checkpoint autosaving

desktop_version/src/Game.cpp, desktop_version/src/Map.cpp, desktop_version/src/Map.h, desktop_version/src/Script.cpp
This pull request adds the commands `mapexplored(x)` and `mapreveal(x)`, which give level creators more control over revealing and hiding rooms on the minimap.
`mapexplored(x)`'s argument is either `all`, which shows every room on the minimap, or `none`, which hides all rooms on the minimap.
`mapreveal(x)` can be toggled either `on` or `off`, which enables or disables to automatic revealing of rooms on the minimap.
Here's a demonstration video:
https://user-images.githubusercontent.com/19874772/198907911-1398fa93-fb43-4274-9b50-2ccfe5625c23.mp4
Forwards compatibility should not be an issue, as this only affects how the map visually displays and won't affect gameplay (besides the player's ability to navigate, maybe) …
=> Add mapexplored(), mapreveal() commands

desktop_version/src/Game.cpp
Checkpoint saving no longer happens if:
- You're in `custommode`, but not `custommodeforreal` (editor playtesting)
- You're in `cliplaytest` (playtest mode, but it DOES work if you just pass the play flag without a save)
Fixes #1198.
=> Add more checks for checkpoint saving

desktop_version/CMakeLists.txt
Only `/GR-`/`-fno-rtti` were actually being applied.
=> Correctly set VVV_CXX_SRC flags (set_source_files_properties isn't cumulative)

.github/workflows/ci.yml
This isn't a _huge_ change, but it does bump the glibc requirement to 2.31, so this shouldn't be backported to 2.4-updates. The main benefit is that it gives us a container with access to new SDL APIs while also giving Misa one less thing to maintain locally.
Fixes #1205
=> CI: Migrate to SLR Sniper SDK for Linux builds

desktop_version/src/CustomLevels.cpp, desktop_version/src/Game.cpp, desktop_version/src/Graphics.cpp, desktop_version/src/Graphics.h, desktop_version/src/GraphicsResources.cpp, desktop_version/src/Map.cpp, desktop_version/src/Map.h, desktop_version/src/Render.cpp, desktop_version/src/Script.cpp
This PR adds a map region system. Regions allow the minimap to display only part of a level even if the level has larger bounds (for example, a 5x5 region in a 20x16 level). Regions can also have custom images. If region`id`.png is present in /graphics, then the minimap will display that image when the current region is `id`. The default region is `0`, and in region `0` the map will display minimap.png (instead of region0.png) if it is present, in order to maintain forwards compatibility. There are a maximum of 401 regions, from `0` to `400`.
It adds three commands to manage them:
`setregion(id,x,y,x2,y2)` - sets region `id` from `x,y` to `x2,y2`.
`changeregion(id)` - sets the current region to `id`. If region `id` doesn't exist, then it will act as if you aren't in any region at all. …
=> Region system

desktop_version/src/Graphics.cpp, desktop_version/src/Graphics.h, desktop_version/src/Script.cpp, desktop_version/src/Script.h, desktop_version/src/Textbox.cpp, desktop_version/src/Textbox.h
The `force` argument in `position`  forces the textbox position, meaning it won't be moved to be inside of the bounds of the screen (nor have the 10 pixel padding on each side.)
`textoutline(on/off/default)` is a new scripting command for textbox visual control, where you're able to force the transparent textbox's outline on or off. This does NOT affect roomtext.
These changes are both solely visual.
=> Add `position(force)` and `textoutline(on/off/default)`

desktop_version/lang/eo/strings.xml
"Rekordo" (record) flows better than "altpoentaro", which is a literal translation of "high score".
=> Tweak one word in the Esperanto localisation

desktop_version/src/Graphics.cpp
0-length gravity lines used to be invisible, but it "broke" some time in 2.4. This PR makes them invisible again.
=> Make 0-length gravity lines invisible again

desktop_version/src/Music.cpp, desktop_version/src/Music.h, desktop_version/src/Render.cpp
This cleans up the audio code as mentioned in #1183 to disambiguate `VVV_MAX_VOLUME` and `USER_VOLUME_MAX`. It introduces the `musicclass::set_music_volume()` and `musicclass::set_sound_volume()` methods - these handle adjusting the volume based on the user controlled volume setting and are called in place of `MusicTrack::SetVolume()` and `SoundTrack::SetVolume()` so modulating the user volume is not calculated in multiple disparate places.
It also changes `musicVolume` to `controlVolume`, as it's the variable used internally by the game to control the volume at any given time using a fade, which is then referenced by `musicclass::updatemutestate()` method.
for …
=> Clean up audio code

desktop_version/src/Input.cpp
If you push a button to set a controller binding, you may either hear one Viridian squeak, two Viridian squeaks (a louder one), or Viridian doesn't stop squeaking until you let go of the button. While you hear the continuous squeaking, your save file is also repeatedly saved.
(Don't forget to unmute the video:)
https://github.com/user-attachments/assets/1fdf2063-fbba-4823-a2e9-0761280d01bd
There are two small bugs at play here:
- the squeak is actually played in two different places at the same time (both in `titleinput()` whenever a button is pressed, and in `updatebuttonmappings()` when a mapping is succesfully changed)
- `titleinput()` doesn't register that a button is held down and applies the button (and saves to file) every frame for as long as the button is held
This PR fixes both …
=> Fix squeak and save spam in gamepad menu

desktop_version/lang/szl/meta.xml
Our Silesian translator asked for "Ślonsko godka" to be changed to "Ślōnsko". (This would probably also be nice as a backport to 2.4-updates since it's a really minor change)
=> Change name of Silesian option by request of translator

desktop_version/lang/szl/meta.xml
Turns out there was a little miscommunication with the translator - they said the option needed to say "Ślōnsko" but were only talking about correcting the first word, where I thought the whole thing needed to be replaced.
So for confirmation:
(Previous PR: #1220)
=> Change name of Silesian option (part 2)

desktop_version/src/Ent.cpp, desktop_version/src/Entity.cpp, desktop_version/src/Graphics.cpp, desktop_version/src/Graphics.h
This merges the colors from other palettes into the general entity palette function. Meaning, particles and "hue tiles" (aka coins) now use the main palette instead of having two extra palette functions.
=> Remove extra unnecessary palettes

desktop_version/src/Graphics.cpp, desktop_version/src/Render.cpp
Currently, if a custom level has zero crewmates, the "CREW" screen will look like this:
However, many, many custom levels don't actually use rescueable crewmates, so seeing "Zero crewmates remain" for a level without any is rather odd. This commit modifies the crew (and stats) screens in custom levels to be more flexible.
If a level has no rescueable crewmates, that line will no longer display and the description will be moved down, like so:
Additionally, if a level has no trinkets, the lines about how many trinkets you have are now removed from the "STATS" screen:
(this accounts for language, of course)
I've also increased the amount of space around the player head sprite that displays next to the author name to be more friendly to custom graphics. Instead of only rendering in a 10x10 …
=> Crew screen tweaks for custom levels

desktop_version/src/CustomLevels.cpp, desktop_version/src/CustomLevels.h, desktop_version/src/Editor.cpp, desktop_version/src/Script.cpp
This PR adds a new XML property for the player's colour. It is 0 by default, but you can change it to any colour ID. For example, making the player use the trinket color is `<PlayerColour>3</PlayerColour>`.
This is mostly a quality-of-life addition, as the player's colour is always 0 unless changed by scripts. A lot of levels which use different player colours use an intro script which both changes the player's colour and sets their respawn colour, which works great for finished, completed levels, but makes playtesting a little more annoying as they will spawn in as the wrong colour. Adding a level property for the default player colour fixes this annoyance.
Additionally, this changes the behavior of `restoreplayercolour`. This command used to set the player's colour to 0 (ignoring the …
=> Add player colour as a level property

desktop_version/src/Ent.cpp, desktop_version/src/Ent.h, desktop_version/src/Entity.cpp, desktop_version/src/Entity.h, desktop_version/src/Game.cpp, desktop_version/src/Graphics.cpp, desktop_version/src/Graphics.h, desktop_version/src/Input.cpp, desktop_version/src/Map.cpp, desktop_version/src/Otherlevel.cpp, desktop_version/src/Script.cpp
Entity colors are just integers. Their colour ID gets passed through a big switch, returning different RGB values depending on the colour ID (and can also get affected by randomness or other game state.)
But because of this, there's a bunch of random numbers floating around, with no actual description on what they are other than comments which, while most of the time are accurate, only exist in the switch.
To fix this, this commit adds a new enum which labels every colour. While we can't use it as a type (as we need to allow colours outside of what are defined, in case people want a "pure white", and scripting can set any colour ID they want), colours have to stay as `int`.
Additionally, there seemed to be an old enum for specifically colors which get used for crewmates...? Which has now …
=> Replace colour IDs with an enum

desktop_version/src/Entity.cpp
There's a problem in #1224 where it breaks spawning custom activity zones. After a bit of confusion after this was reported, I realized that I removed the fallback from `getcrewman` and changed the return value to `-1` if the entity isn't found, to avoid returning the wrong entity (entity 0, aka probably the player).
Unfortunately, it seems like a ton of levels (including my older ones) rely on this behavior.
Creating custom activity zones is a long process which uses a bunch of unintended behaviour, which includes targeting a crewmate with color
35. With the change I mentioned earlier, the `getcrewman` function would return `-1` instead, which was out of bounds of the entity array, so the game avoided spawning the activity zone at all. The prior behaviour of falling back to entity 0 …
=> Fix "invalid" activity zones not spawning

desktop_version/src/Render.cpp
PR #1226 tweaks both the crew and the stats screens. When there's no trinkets in the level, it removes the trinket count from the STATS screen in the menu. This, however, is missing a `custommode` check, meaning that the main game is ALSO missing the trinket count.
This PR fixes that oversight.
=> Fix the campaign trinket count missing from stats

desktop_version/src/GraphicsUtil.cpp
When `SDL_RenderReadPixels` fails for some reason, the game tries to free the temporary source surface it creates. Unfortunately, it never sets it to `NULL` after, so the next time the game tries to render the filter, it'll try to work with a memory region that was already freed.
To fix this, I just replaced `SDL_FreeSurface(*src);` with `VVV_freefunc(SDL_FreeSurface, *src);` which is a helper macro which sets the pointer to NULL after freeing.
Now, there's a new issue -- since the temporary buffer is now NULL, next frame we'll try to remake it! So I've introduced a static bool which disables the filter entirely if `SDL_RenderReadPixels` fails. Without this, it'd create and destroy a surface every frame, which could lead to slowdown. (Not as slow as the filter when it DOES work, but …
=> Fix #1223 (analogue mode segfault)

desktop_version/src/Graphics.cpp
Every now and then, the game crashes for me because of a division by zero, due to the rect returned by `Graphics::get_stretch_info`. I don't fully know how the width and height get set to 0, but this should protect against it.
As I always use integer scaling, my guess is that
`Screen::GetScreenSize` (which later calls `SDL_GetRendererOutputSize`) returns 0 sometimes, and the code trusts that -- but I know that windows and things can be finicky, so the clamp is probably a good idea.
=> Fix uncommon division-by-zero

desktop_version/lang/ar/strings.xml, desktop_version/lang/ca/strings.xml, desktop_version/lang/cy/strings.xml, desktop_version/lang/de/strings.xml, desktop_version/lang/en/strings.xml, desktop_version/lang/eo/strings.xml, desktop_version/lang/es/strings.xml, desktop_version/lang/es_419/strings.xml, desktop_version/lang/es_AR/strings.xml, desktop_version/lang/fr/strings.xml, desktop_version/lang/ga/strings.xml, desktop_version/lang/it/strings.xml, desktop_version/lang/ja/strings.xml, desktop_version/lang/ko/strings.xml, desktop_version/lang/nl/strings.xml, desktop_version/lang/pl/strings.xml, desktop_version/lang/pt_BR/strings.xml, desktop_version/lang/pt_PT/strings.xml, desktop_version/lang/ru/strings.xml, desktop_version/lang/szl/strings.xml, desktop_version/lang/tr/strings.xml, desktop_version/lang/uk/strings.xml, desktop_version/lang/zh/strings.xml, desktop_version/lang/zh_TW/strings.xml, desktop_version/src/ButtonGlyphs.cpp, desktop_version/src/ButtonGlyphs.h, desktop_version/src/Game.cpp, desktop_version/src/Game.h, desktop_version/src/Input.cpp, desktop_version/src/Render.cpp
This makes the following improvements to the gamepad bindings menu:
- The menu now shows a hint that you can press a button while any of the bind options are selected (or that you can navigate away from those options)
- Instead of button presses immediately setting a binding, they now ask for confirmation: press the same button a second time to confirm
- You can now remove a binding, the same way you add it (this has the same type of confirmation)
- This menu used to be inconsistent with pretty much every other menu in the game by showing a permanent title and description for the menu itself ("Game Pad", "Change controller options.") rather than showing a title and description for the currently selected option. This inconsistency is now fixed.
Demo video: …
=> Add confirmation and removal to bindings menu

.github/workflows/ci.yml, desktop_version/src/KeyPoll.cpp
When writing the initial stretch mode code, the existence of HiDPI displays completely slipped my mind -- or at least I didn't realize that they'd be a problem.
We implement scaling modes ourselves, so transforming the mouse coordinates to our 320x240 viewport is done manually. Unfortunately, that code did not take into account HiDPI scaling whatsoever, meaning that all of the math which assumes the window size and the renderer size is wrong.
To fix this, we use `SDL_GetWindowSizeInPixels` and `SDL_GetWindow` to find the scaling factor, and then apply that to the mouse coordinates to get the mouse coordinates in the pixel-space instead, and then we do all of our normal logic after.
Small code style thing: C-style casts without a following space (`(int)var`) was done intentionally here -- …
=> Fix mouse coordinates being wrong on HiDPI displays

desktop_version/src/FontBidi.cpp
This fixes our problem with Valgrind reporting a jump based on an uninitialized value; see https://github.com/Tehreer/SheenBidi/issues/19
Just to be sure nothing unexpected happens, I tested that this doesn't cause any changes in behavior by outputting bidi-transformed versions of all strings in strings.xml to a file for both our Arabic and Persian localizations before and after the update, and confirming that the files are the same.
This might be suitable for a 2.4 backport, but I'll leave that up to Ethan.
=> Update SheenBidi to 2.9.0

desktop_version/src/Graphics.cpp
Fixes #1242.
Turns out it was a really simple fix - the X positions were good, but the Y positions were always at the top of the screen regardless of the height of the textbox. Now they're vertically centered respective to the speaker.
(Requesting a 2.4 backport since it's a minor fix to what's technically a 2.4 regression)
=> Fix vertical position of Comms Relay textbox

desktop_version/src/ButtonGlyphs.cpp, desktop_version/src/FileSystemUtils.cpp, desktop_version/src/Game.cpp, desktop_version/src/Screen.cpp, desktop_version/src/Vlogging.c
SDL will define this variable to 0 on non-iOS targets. I'm not sure how this didn't cause any issues until I was working on some macOS changes just now?
=> Fix TARGET_OS_IPHONE checks
